-- ============================================================
-- 007_padron_seed.sql
--
-- Setter inn hele Padrón-katalogen (helt nytt merke i databasen).
-- Hierarki: manufacturer -> brand -> series -> vitola.
-- Kilde: padron.com (offisielle vitola-lister, ring gauge/lengde,
-- aldring og Cigar Aficionado "Cigar of the Year"-historikk).
--
-- Serier:
--   1) Padron Series      (15 vitolas — grunnlinjen fra 1964)
--   2) Damaso              (6 vitolas — mildeste linje, Ecuador Connecticut)
--   3) 1926 Serie          (10 vitolas — boxpresset, 5 års aldring)
--   4) 1964 Anniversary    (16 vitolas — boxpresset, 4 års aldring)
--   5) Family Reserve      (7 vitolas — 10 års aldring, toppserie)
--
-- Totalt 54 nye rader. Ingen eksisterende rader berøres.
-- ============================================================

-- ----------------------------------------------------------------
-- 1) Padron Series
-- ----------------------------------------------------------------
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description) values
('Padron','Padron','Padron Series','Ambassador','Lonsdale',42,6.875,'Parejo',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',4,null,'Padróns grunnlinje fra 1964 — femten sigarer fra Cortico til Magnum, middels til full styrke. Eldet minst 2,5 år, håndlaget av solgrodd nicaraguansk tobakk (puro). Tilgjengelig i natural og maduro.'),
('Padron','Padron','Padron Series','Churchill','Churchill',46,6.875,'Parejo',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',4,null,'Padróns grunnlinje fra 1964 — femten sigarer fra Cortico til Magnum, middels til full styrke. Eldet minst 2,5 år, håndlaget av solgrodd nicaraguansk tobakk (puro). Tilgjengelig i natural og maduro.'),
('Padron','Padron','Padron Series','Corticos','Petit Corona',35,4.25,'Parejo',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',4,null,'Padróns grunnlinje fra 1964 — femten sigarer fra Cortico til Magnum, middels til full styrke. Eldet minst 2,5 år, håndlaget av solgrodd nicaraguansk tobakk (puro). Tilgjengelig i natural og maduro.'),
('Padron','Padron','Padron Series','Delicias','Robusto',46,4.875,'Parejo',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',4,null,'Padróns grunnlinje fra 1964 — femten sigarer fra Cortico til Magnum, middels til full styrke. Eldet minst 2,5 år, håndlaget av solgrodd nicaraguansk tobakk (puro). Tilgjengelig i natural og maduro.'),
('Padron','Padron','Padron Series','Executive','Double Corona',50,7.5,'Parejo',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',4,null,'Padróns grunnlinje fra 1964 — femten sigarer fra Cortico til Magnum, middels til full styrke. Eldet minst 2,5 år, håndlaget av solgrodd nicaraguansk tobakk (puro). Tilgjengelig i natural og maduro.'),
('Padron','Padron','Padron Series','Londres','Corona',42,5.5,'Parejo',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',4,null,'Padróns grunnlinje fra 1964 — femten sigarer fra Cortico til Magnum, middels til full styrke. Eldet minst 2,5 år, håndlaget av solgrodd nicaraguansk tobakk (puro). Tilgjengelig i natural og maduro.'),
('Padron','Padron','Padron Series','Magnum','Gran Corona',50,9.0,'Parejo',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',4,null,'Padróns grunnlinje fra 1964 — femten sigarer fra Cortico til Magnum, middels til full styrke. Eldet minst 2,5 år, håndlaget av solgrodd nicaraguansk tobakk (puro). Tilgjengelig i natural og maduro.'),
('Padron','Padron','Padron Series','Palmas','Corona',42,6.3125,'Parejo',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',4,null,'Padróns grunnlinje fra 1964 — femten sigarer fra Cortico til Magnum, middels til full styrke. Eldet minst 2,5 år, håndlaget av solgrodd nicaraguansk tobakk (puro). Tilgjengelig i natural og maduro.'),
('Padron','Padron','Padron Series','Panetela','Panetela',36,6.875,'Parejo',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',4,null,'Padróns grunnlinje fra 1964 — femten sigarer fra Cortico til Magnum, middels til full styrke. Eldet minst 2,5 år, håndlaget av solgrodd nicaraguansk tobakk (puro). Tilgjengelig i natural og maduro.'),
('Padron','Padron','Padron Series','2000','Robusto',50,5.0,'Parejo',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',4,null,'Padróns grunnlinje fra 1964 — femten sigarer fra Cortico til Magnum, middels til full styrke. Eldet minst 2,5 år, håndlaget av solgrodd nicaraguansk tobakk (puro). Tilgjengelig i natural og maduro.'),
('Padron','Padron','Padron Series','3000','Robusto',52,5.5,'Parejo',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',4,null,'Padróns grunnlinje fra 1964 — femten sigarer fra Cortico til Magnum, middels til full styrke. Eldet minst 2,5 år, håndlaget av solgrodd nicaraguansk tobakk (puro). Tilgjengelig i natural og maduro.'),
('Padron','Padron','Padron Series','4000','Toro',54,6.5,'Parejo',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',4,null,'Padróns grunnlinje fra 1964 — femten sigarer fra Cortico til Magnum, middels til full styrke. Eldet minst 2,5 år, håndlaget av solgrodd nicaraguansk tobakk (puro). Tilgjengelig i natural og maduro.'),
('Padron','Padron','Padron Series','5000','Gordo',56,5.5,'Parejo',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',4,null,'Padróns grunnlinje fra 1964 — femten sigarer fra Cortico til Magnum, middels til full styrke. Eldet minst 2,5 år, håndlaget av solgrodd nicaraguansk tobakk (puro). Tilgjengelig i natural og maduro.'),
('Padron','Padron','Padron Series','6000','Robusto',52,5.5,'Parejo',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',4,null,'Padróns grunnlinje fra 1964 — femten sigarer fra Cortico til Magnum, middels til full styrke. Eldet minst 2,5 år, håndlaget av solgrodd nicaraguansk tobakk (puro). Tilgjengelig i natural og maduro.'),
('Padron','Padron','Padron Series','7000','Gordo',60,6.25,'Parejo',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',4,null,'Padróns grunnlinje fra 1964 — femten sigarer fra Cortico til Magnum, middels til full styrke. Eldet minst 2,5 år, håndlaget av solgrodd nicaraguansk tobakk (puro). Tilgjengelig i natural og maduro.');

-- ----------------------------------------------------------------
-- 2) Damaso Series
-- ----------------------------------------------------------------
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description) values
('Padron','Padron','Damaso','No 8','Robusto',46,5.5,'Parejo',null,null,null,'Ecuador','Ecuador Connecticut','Nicaraguan',array['Nicaragua'],'Nicaragua',2,null,'Padróns mildeste linje, oppkalt etter familiens grunnlegger Dámaso Padrón. Rund, mild til middels styrke, med Ecuador Connecticut-dekkblad. «Red Label»-variantene (No. 32 og No. 34) er kraftigere.'),
('Padron','Padron','Damaso','No 12','Robusto',50,5.0,'Parejo',null,null,null,'Ecuador','Ecuador Connecticut','Nicaraguan',array['Nicaragua'],'Nicaragua',2,null,'Padróns mildeste linje, oppkalt etter familiens grunnlegger Dámaso Padrón. Rund, mild til middels styrke, med Ecuador Connecticut-dekkblad. «Red Label»-variantene (No. 32 og No. 34) er kraftigere.'),
('Padron','Padron','Damaso','No 15','Toro',52,6.0,'Parejo',null,null,null,'Ecuador','Ecuador Connecticut','Nicaraguan',array['Nicaragua'],'Nicaragua',2,null,'Padróns mildeste linje, oppkalt etter familiens grunnlegger Dámaso Padrón. Rund, mild til middels styrke, med Ecuador Connecticut-dekkblad. «Red Label»-variantene (No. 32 og No. 34) er kraftigere.'),
('Padron','Padron','Damaso','No 17','Toro Grande',54,7.0,'Parejo',null,null,null,'Ecuador','Ecuador Connecticut','Nicaraguan',array['Nicaragua'],'Nicaragua',2,null,'Padróns mildeste linje, oppkalt etter familiens grunnlegger Dámaso Padrón. Rund, mild til middels styrke, med Ecuador Connecticut-dekkblad. «Red Label»-variantene (No. 32 og No. 34) er kraftigere.'),
('Padron','Padron','Damaso','No 32 Red Label','Robusto',52,5.25,'Parejo',null,null,null,'Ecuador','Ecuador Connecticut','Nicaraguan',array['Nicaragua'],'Nicaragua',3,null,'Padróns mildeste linje, oppkalt etter familiens grunnlegger Dámaso Padrón. Rund, mild til middels styrke, med Ecuador Connecticut-dekkblad. «Red Label»-variantene (No. 32 og No. 34) er kraftigere.'),
('Padron','Padron','Damaso','No 34 Red Label','Toro',52,6.0,'Parejo',null,null,null,'Ecuador','Ecuador Connecticut','Nicaraguan',array['Nicaragua'],'Nicaragua',3,null,'Padróns mildeste linje, oppkalt etter familiens grunnlegger Dámaso Padrón. Rund, mild til middels styrke, med Ecuador Connecticut-dekkblad. «Red Label»-variantene (No. 32 og No. 34) er kraftigere.');

-- ----------------------------------------------------------------
-- 3) 1926 Serie
-- ----------------------------------------------------------------
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description) values
('Padron','Padron','1926 Serie','No 1','Toro Grande',54,6.75,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 2002 for å feire José O. Padróns 75-årsdag. Boxpresset, individuelt håndlaget av tobakk eldet i 5 år — fullkroppet og balansert. Flere vitolas er kåret til Cigar Aficionados «Cigar of the Year» (No. 40 i 2004, No. 9 i 2007, No. 80 nr. 2 i 2008, No. 90 nr. 5 i 2016).'),
('Padron','Padron','1926 Serie','No 2','Robusto',52,5.5,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 2002 for å feire José O. Padróns 75-årsdag. Boxpresset, individuelt håndlaget av tobakk eldet i 5 år — fullkroppet og balansert. Flere vitolas er kåret til Cigar Aficionados «Cigar of the Year» (No. 40 i 2004, No. 9 i 2007, No. 80 nr. 2 i 2008, No. 90 nr. 5 i 2016).'),
('Padron','Padron','1926 Serie','No 6','Petit Robusto',50,4.75,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 2002 for å feire José O. Padróns 75-årsdag. Boxpresset, individuelt håndlaget av tobakk eldet i 5 år — fullkroppet og balansert. Flere vitolas er kåret til Cigar Aficionados «Cigar of the Year» (No. 40 i 2004, No. 9 i 2007, No. 80 nr. 2 i 2008, No. 90 nr. 5 i 2016).'),
('Padron','Padron','1926 Serie','No 9','Gordo',56,5.25,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 2002 for å feire José O. Padróns 75-årsdag. Boxpresset, individuelt håndlaget av tobakk eldet i 5 år — fullkroppet og balansert. Flere vitolas er kåret til Cigar Aficionados «Cigar of the Year» (No. 40 i 2004, No. 9 i 2007, No. 80 nr. 2 i 2008, No. 90 nr. 5 i 2016).'),
('Padron','Padron','1926 Serie','No 35','Petit Corona',48,4.0,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 2002 for å feire José O. Padróns 75-årsdag. Boxpresset, individuelt håndlaget av tobakk eldet i 5 år — fullkroppet og balansert. Flere vitolas er kåret til Cigar Aficionados «Cigar of the Year» (No. 40 i 2004, No. 9 i 2007, No. 80 nr. 2 i 2008, No. 90 nr. 5 i 2016).'),
('Padron','Padron','1926 Serie','No 40','Torpedo',54,6.5,'Figurado','Torpedo','Pointed','Closed','Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 2002 for å feire José O. Padróns 75-årsdag. Boxpresset, individuelt håndlaget av tobakk eldet i 5 år — fullkroppet og balansert. Flere vitolas er kåret til Cigar Aficionados «Cigar of the Year» (No. 40 i 2004, No. 9 i 2007, No. 80 nr. 2 i 2008, No. 90 nr. 5 i 2016).'),
('Padron','Padron','1926 Serie','No 47','Robusto',50,5.5,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 2002 for å feire José O. Padróns 75-årsdag. Boxpresset, individuelt håndlaget av tobakk eldet i 5 år — fullkroppet og balansert. Flere vitolas er kåret til Cigar Aficionados «Cigar of the Year» (No. 40 i 2004, No. 9 i 2007, No. 80 nr. 2 i 2008, No. 90 nr. 5 i 2016).'),
('Padron','Padron','1926 Serie','No 48','Gordo',60,5.5,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 2002 for å feire José O. Padróns 75-årsdag. Boxpresset, individuelt håndlaget av tobakk eldet i 5 år — fullkroppet og balansert. Flere vitolas er kåret til Cigar Aficionados «Cigar of the Year» (No. 40 i 2004, No. 9 i 2007, No. 80 nr. 2 i 2008, No. 90 nr. 5 i 2016).'),
('Padron','Padron','1926 Serie','No 80','Toro Grande',54,6.75,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 2002 for å feire José O. Padróns 75-årsdag. Boxpresset, individuelt håndlaget av tobakk eldet i 5 år — fullkroppet og balansert. Flere vitolas er kåret til Cigar Aficionados «Cigar of the Year» (No. 40 i 2004, No. 9 i 2007, No. 80 nr. 2 i 2008, No. 90 nr. 5 i 2016).'),
('Padron','Padron','1926 Serie','No 90','Robusto',52,5.5,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 2002 for å feire José O. Padróns 75-årsdag. Boxpresset, individuelt håndlaget av tobakk eldet i 5 år — fullkroppet og balansert. Flere vitolas er kåret til Cigar Aficionados «Cigar of the Year» (No. 40 i 2004, No. 9 i 2007, No. 80 nr. 2 i 2008, No. 90 nr. 5 i 2016).');

-- ----------------------------------------------------------------
-- 4) 1964 Anniversary Series
-- ----------------------------------------------------------------
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description) values
('Padron','Padron','1964 Anniversary Series','A','Gran Corona',50,8.25,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 1994 for å feire Padróns 30-årsjubileum. Boxpresset, eldet i 4 år, full styrke. Regnes som ett av verdens mest anerkjente sigarmerker — Torpedo ble kåret til Cigar Aficionados «Cigar of the Year» i 2021.'),
('Padron','Padron','1964 Anniversary Series','Diplomatico','Churchill',50,7.0,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 1994 for å feire Padróns 30-årsjubileum. Boxpresset, eldet i 4 år, full styrke. Regnes som ett av verdens mest anerkjente sigarmerker — Torpedo ble kåret til Cigar Aficionados «Cigar of the Year» i 2021.'),
('Padron','Padron','1964 Anniversary Series','Piramide','Torpedo',52,6.875,'Figurado','Piramide','Pointed','Closed','Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 1994 for å feire Padróns 30-årsjubileum. Boxpresset, eldet i 4 år, full styrke. Regnes som ett av verdens mest anerkjente sigarmerker — Torpedo ble kåret til Cigar Aficionados «Cigar of the Year» i 2021.'),
('Padron','Padron','1964 Anniversary Series','Monarca','Corona',46,6.5,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 1994 for å feire Padróns 30-årsjubileum. Boxpresset, eldet i 4 år, full styrke. Regnes som ett av verdens mest anerkjente sigarmerker — Torpedo ble kåret til Cigar Aficionados «Cigar of the Year» i 2021.'),
('Padron','Padron','1964 Anniversary Series','Superior','Corona',42,6.5,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 1994 for å feire Padróns 30-årsjubileum. Boxpresset, eldet i 4 år, full styrke. Regnes som ett av verdens mest anerkjente sigarmerker — Torpedo ble kåret til Cigar Aficionados «Cigar of the Year» i 2021.'),
('Padron','Padron','1964 Anniversary Series','No 4','Gordo',60,6.5,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 1994 for å feire Padróns 30-årsjubileum. Boxpresset, eldet i 4 år, full styrke. Regnes som ett av verdens mest anerkjente sigarmerker — Torpedo ble kåret til Cigar Aficionados «Cigar of the Year» i 2021.'),
('Padron','Padron','1964 Anniversary Series','Torpedo','Torpedo',52,6.0,'Figurado','Torpedo','Pointed','Closed','Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 1994 for å feire Padróns 30-årsjubileum. Boxpresset, eldet i 4 år, full styrke. Regnes som ett av verdens mest anerkjente sigarmerker — Torpedo ble kåret til Cigar Aficionados «Cigar of the Year» i 2021.'),
('Padron','Padron','1964 Anniversary Series','Imperial','Toro',54,6.0,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 1994 for å feire Padróns 30-årsjubileum. Boxpresset, eldet i 4 år, full styrke. Regnes som ett av verdens mest anerkjente sigarmerker — Torpedo ble kåret til Cigar Aficionados «Cigar of the Year» i 2021.'),
('Padron','Padron','1964 Anniversary Series','Corona','Corona',42,6.0,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 1994 for å feire Padróns 30-årsjubileum. Boxpresset, eldet i 4 år, full styrke. Regnes som ett av verdens mest anerkjente sigarmerker — Torpedo ble kåret til Cigar Aficionados «Cigar of the Year» i 2021.'),
('Padron','Padron','1964 Anniversary Series','Presidente','Toro',50,6.0,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 1994 for å feire Padróns 30-årsjubileum. Boxpresset, eldet i 4 år, full styrke. Regnes som ett av verdens mest anerkjente sigarmerker — Torpedo ble kåret til Cigar Aficionados «Cigar of the Year» i 2021.'),
('Padron','Padron','1964 Anniversary Series','Exclusivo','Robusto',50,5.5,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 1994 for å feire Padróns 30-årsjubileum. Boxpresset, eldet i 4 år, full styrke. Regnes som ett av verdens mest anerkjente sigarmerker — Torpedo ble kåret til Cigar Aficionados «Cigar of the Year» i 2021.'),
('Padron','Padron','1964 Anniversary Series','Belicoso','Belicoso',52,5.0,'Figurado','Belicoso','Pointed','Closed','Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 1994 for å feire Padróns 30-årsjubileum. Boxpresset, eldet i 4 år, full styrke. Regnes som ett av verdens mest anerkjente sigarmerker — Torpedo ble kåret til Cigar Aficionados «Cigar of the Year» i 2021.'),
('Padron','Padron','1964 Anniversary Series','Toro','Gordo',56,5.0,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 1994 for å feire Padróns 30-årsjubileum. Boxpresset, eldet i 4 år, full styrke. Regnes som ett av verdens mest anerkjente sigarmerker — Torpedo ble kåret til Cigar Aficionados «Cigar of the Year» i 2021.'),
('Padron','Padron','1964 Anniversary Series','Soberano','Robusto',52,5.0,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 1994 for å feire Padróns 30-årsjubileum. Boxpresset, eldet i 4 år, full styrke. Regnes som ett av verdens mest anerkjente sigarmerker — Torpedo ble kåret til Cigar Aficionados «Cigar of the Year» i 2021.'),
('Padron','Padron','1964 Anniversary Series','Principe','Petit Corona',46,4.5,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 1994 for å feire Padróns 30-årsjubileum. Boxpresset, eldet i 4 år, full styrke. Regnes som ett av verdens mest anerkjente sigarmerker — Torpedo ble kåret til Cigar Aficionados «Cigar of the Year» i 2021.'),
('Padron','Padron','1964 Anniversary Series','Hermoso','Rothschild',56,4.0,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Lansert i 1994 for å feire Padróns 30-årsjubileum. Boxpresset, eldet i 4 år, full styrke. Regnes som ett av verdens mest anerkjente sigarmerker — Torpedo ble kåret til Cigar Aficionados «Cigar of the Year» i 2021.');

-- ----------------------------------------------------------------
-- 5) Family Reserve
-- ----------------------------------------------------------------
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description) values
('Padron','Padron','Family Reserve','No 44','Torpedo',52,6.0,'Figurado','Torpedo','Pointed','Closed','Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Eksklusiv serie opprinnelig forbeholdt familiens jubileer. Hver sigar er individuelt håndlaget av tobakk eldet i 10 år — eksepsjonelt smidig, kompleks, balansert og fullkroppet. No. 45 ble kåret til Cigar Aficionados «Cigar of the Year» i 2009.'),
('Padron','Padron','Family Reserve','No 45','Toro',52,6.0,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Eksklusiv serie opprinnelig forbeholdt familiens jubileer. Hver sigar er individuelt håndlaget av tobakk eldet i 10 år — eksepsjonelt smidig, kompleks, balansert og fullkroppet. No. 45 ble kåret til Cigar Aficionados «Cigar of the Year» i 2009.'),
('Padron','Padron','Family Reserve','No 46','Gordo',56,5.5,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Eksklusiv serie opprinnelig forbeholdt familiens jubileer. Hver sigar er individuelt håndlaget av tobakk eldet i 10 år — eksepsjonelt smidig, kompleks, balansert og fullkroppet. No. 45 ble kåret til Cigar Aficionados «Cigar of the Year» i 2009.'),
('Padron','Padron','Family Reserve','No 50','Robusto',54,5.0,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Eksklusiv serie opprinnelig forbeholdt familiens jubileer. Hver sigar er individuelt håndlaget av tobakk eldet i 10 år — eksepsjonelt smidig, kompleks, balansert og fullkroppet. No. 45 ble kåret til Cigar Aficionados «Cigar of the Year» i 2009.'),
('Padron','Padron','Family Reserve','No 85','Robusto',50,5.25,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Eksklusiv serie opprinnelig forbeholdt familiens jubileer. Hver sigar er individuelt håndlaget av tobakk eldet i 10 år — eksepsjonelt smidig, kompleks, balansert og fullkroppet. No. 45 ble kåret til Cigar Aficionados «Cigar of the Year» i 2009.'),
('Padron','Padron','Family Reserve','No 95','Gordo',60,4.75,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Eksklusiv serie opprinnelig forbeholdt familiens jubileer. Hver sigar er individuelt håndlaget av tobakk eldet i 10 år — eksepsjonelt smidig, kompleks, balansert og fullkroppet. No. 45 ble kåret til Cigar Aficionados «Cigar of the Year» i 2009.'),
('Padron','Padron','Family Reserve','No 96','Toro',52,5.75,'Box-Pressed',null,null,null,'Nicaragua','Sun Grown Nicaraguan','Nicaraguan',array['Nicaragua'],'Nicaragua',5,null,'Eksklusiv serie opprinnelig forbeholdt familiens jubileer. Hver sigar er individuelt håndlaget av tobakk eldet i 10 år — eksepsjonelt smidig, kompleks, balansert og fullkroppet. No. 45 ble kåret til Cigar Aficionados «Cigar of the Year» i 2009.');

-- ----------------------------------------------------------------
-- 6) ALIAS — vanlige skrivemåter/forkortelser for OCR/søk-treff
-- ----------------------------------------------------------------
insert into cigar_aliases (alias, manufacturer, brand, series) values
('Padrón', 'Padron', 'Padron', null),
('Padron Cigars', 'Padron', 'Padron', null),
('Dámaso', 'Padron', 'Padron', 'Damaso'),
('Damaso Series', 'Padron', 'Padron', 'Damaso'),
('1964', 'Padron', 'Padron', '1964 Anniversary Series'),
('Padron 1964', 'Padron', 'Padron', '1964 Anniversary Series'),
('1926', 'Padron', 'Padron', '1926 Serie'),
('Padron 1926', 'Padron', 'Padron', '1926 Serie'),
('Family Reserve', 'Padron', 'Padron', 'Family Reserve'),
('Padron Family Reserve', 'Padron', 'Padron', 'Family Reserve');

-- ----------------------------------------------------------------
-- 7) Sanity check — skal være nøyaktig 54 nye Padron-rader
-- ----------------------------------------------------------------
do $$
declare
  cnt int;
begin
  select count(*) into cnt from cigars where manufacturer = 'Padron';
  if cnt <> 54 then
    raise exception 'Forventet 54 Padron-rader, fant %', cnt;
  end if;
end $$;
