-- Migrasjon 023: Oppfølging etter full gjennomgang av Holt's "All Cigar Brands"-katalog
-- DEL A: To manglende serier under merker vi allerede har (Crowned Heads, AJ Fernandez)
-- DEL B: Ni nye merker identifisert i gap-analysen: Man O' War, El Rey del Mundo, Quorum,
--        Saint Luis Rey, Don Diego, Licenciados, Vega Fina, Ave Maria, Bauza

-- ===================== DEL A: Nye serier under eksisterende merker =====================

-- Crowned Heads / Four Kicks (flaggskip-serien, manglet helt)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('Crowned Heads', 'Crowned Heads', 'Four Kicks', 'Corona Gorda', 'Corona Gorda', 46, 5.625, 'Parejo', null, null, null, 'Ecuador', 'Habano', 'Nicaragua', array['Nicaragua'], 'Nicaragua', 3, '$7-9', 'Crowned Heads sitt mest kjente merke, lansert i 2011. Balansert medium styrke med en oljeaktig Ecuador Habano-dekkblad.', array['cedar','black pepper','cocoa','toasted nuts']),
('Crowned Heads', 'Crowned Heads', 'Four Kicks', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Ecuador', 'Habano', 'Nicaragua', array['Nicaragua'], 'Nicaragua', 3, '$7-9', 'Robusto-formatet i Four Kicks-serien, samme balanserte profil med krydder og kakao.', array['cedar','black pepper','cocoa','espresso']),
('Crowned Heads', 'Crowned Heads', 'Four Kicks', 'Sublime', 'Toro', 54, 6.0, 'Parejo', null, null, null, 'Ecuador', 'Habano', 'Nicaragua', array['Nicaragua'], 'Nicaragua', 3, '$8-10', 'Det største formatet i Four Kicks-serien, gir lenger røyketid med samme medium styrke.', array['cedar','black pepper','cocoa','caramel']);

-- AJ Fernandez / San Lotano Oval
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('AJ Fernandez', 'AJ Fernandez', 'San Lotano Oval', 'Robusto', 'Robusto', 52, 5.0, 'Parejo', null, null, null, 'Ecuador', 'Habano', 'Honduras', array['Nicaragua','Honduras'], 'Nicaragua', 4, '$8-11', 'San Lotano Oval har en lett boxpress-form for ekstra komfort i munnen, med fyldig styrke fra AJ Fernandez.', array['leather','dark chocolate','black pepper','coffee']),
('AJ Fernandez', 'AJ Fernandez', 'San Lotano Oval', 'Toro', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'Ecuador', 'Habano', 'Honduras', array['Nicaragua','Honduras'], 'Nicaragua', 4, '$9-12', 'Toro-formatet i San Lotano Oval-serien, full-kroppet med Ecuador Habano-dekkblad.', array['leather','dark chocolate','black pepper','cedar']),
('AJ Fernandez', 'AJ Fernandez', 'San Lotano Oval', 'Gran Toro', 'Gordo', 60, 6.0, 'Parejo', null, null, null, 'Ecuador', 'Habano', 'Honduras', array['Nicaragua','Honduras'], 'Nicaragua', 4, '$9-12', 'Det største formatet i San Lotano Oval, samme fyldige og balanserte profil.', array['leather','dark chocolate','black pepper','toasted nuts']);

-- AJ Fernandez / San Lotano Requiem Maduro
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('AJ Fernandez', 'AJ Fernandez', 'San Lotano Requiem Maduro', 'Robusto', 'Robusto', 52, 5.0, 'Parejo', null, null, null, 'Brazil', 'Habano Maduro', 'Honduras', array['Nicaragua','Dominican Republic','Honduras'], 'Nicaragua', 5, '$9-13', 'Requiem Maduro bruker et sjeldent brasiliansk Habano-dekkblad og leverer full styrke fra start.', array['dark chocolate','espresso','black pepper','dried fruit']),
('AJ Fernandez', 'AJ Fernandez', 'San Lotano Requiem Maduro', 'Toro', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'Brazil', 'Habano Maduro', 'Honduras', array['Nicaragua','Dominican Republic','Honduras'], 'Nicaragua', 5, '$10-14', 'Toro-formatet i Requiem Maduro, kraftig og full-kroppet med søtt avtrekk.', array['dark chocolate','espresso','black pepper','molasses']),
('AJ Fernandez', 'AJ Fernandez', 'San Lotano Requiem Maduro', 'Torpedo', 'Torpedo', 52, 6.5, 'Figurado', null, null, null, 'Brazil', 'Habano Maduro', 'Honduras', array['Nicaragua','Dominican Republic','Honduras'], 'Nicaragua', 5, '$10-14', 'Torpedo-formatet i Requiem Maduro-serien, spisset fot gir konsentrert fyldig smak.', array['dark chocolate','espresso','black pepper','dried fruit']);

-- ===================== DEL B: Ni nye merker =====================

-- Man O' War (blandet av AJ Fernandez i Estelí, Nicaragua)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('AJ Fernandez', 'Man O'' War', 'Original', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Nicaragua', 'Habano', 'Nicaragua', array['Nicaragua','Honduras'], 'Nicaragua', 4, '$6-8', 'Man O'' War Original er full-kroppet med kubansk-frø ligero-tobakk fra Nicaragua og Honduras.', array['leather','black pepper','cedar','earth']),
('AJ Fernandez', 'Man O'' War', 'Ruination', 'Robusto', 'Robusto', 52, 5.0, 'Parejo', null, null, null, 'United States', 'Connecticut Broadleaf', 'Nicaragua', array['Nicaragua'], 'Nicaragua', 5, '$6-8', 'Ruination bruker et mørkt Connecticut Broadleaf-dekkblad og er den kraftigste i Man O'' War-familien.', array['dark chocolate','espresso','black pepper','char']),
('AJ Fernandez', 'Man O'' War', 'Virtue', 'Toro', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'Ecuador', 'Connecticut', 'Nicaragua', array['Nicaragua'], 'Nicaragua', 2, '$6-8', 'Virtue balanserer linjen med et silkeglatt Connecticut-dekkblad og mild til medium styrke.', array['cream','cedar','hay','sweet spice']);

-- El Rey del Mundo (Honduras)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('General Cigar Co.', 'El Rey del Mundo', 'Reserva Especial', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Nicaragua', 'Habano', 'Honduras', array['Honduras','Nicaragua','Peru'], 'Honduras', 4, '$5-7', 'Reserva Especial bruker aldret Honduras-, Nicaragua- og Peru-tobakk for en full-kroppet profil.', array['coffee','sweet spice','black pepper','dark chocolate']),
('General Cigar Co.', 'El Rey del Mundo', 'Serie G', 'Gordo', 'Gordo', 60, 6.0, 'Parejo', null, null, null, 'Nicaragua', 'Habano', 'Honduras', array['Honduras','Nicaragua'], 'Honduras', 4, '$5-7', 'Serie G ("Gigante") er en linje med store ringmål og full-kroppet styrke.', array['coffee','black pepper','cedar','earth']),
('General Cigar Co.', 'El Rey del Mundo', 'Natural Broadleaf', 'Toro', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'United States', 'Connecticut Broadleaf', 'Honduras', array['Honduras'], 'Honduras', 3, '$5-7', 'Natural Broadleaf har et gyllenbrunt Connecticut Broadleaf-dekkblad med notater av pepper og kakao.', array['black pepper','dark chocolate','earth','wood']);

-- Quorum (J.C. Newman, Nicaragua)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('J.C. Newman Cigar Co.', 'Quorum', 'Classic', 'Toro', 'Toro', 50, 6.0, 'Parejo', null, null, null, 'Indonesia', 'Sumatra', 'Nicaragua', array['Nicaragua'], 'Nicaragua', 3, '$3-5', 'Quorum Classic er et populært verdimerke med Sumatra-dekkblad og balansert medium styrke.', array['cedar','nuts','earth','black pepper']),
('J.C. Newman Cigar Co.', 'Quorum', 'Maduro', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Indonesia', 'Sumatra Maduro', 'United States', array['Nicaragua'], 'Nicaragua', 4, '$3-5', 'Quorum Maduro er den mørkeste i linjen, med et solgrodd Sumatra Maduro-dekkblad og fyldig smak.', array['dark chocolate','coffee','black pepper','molasses']),
('J.C. Newman Cigar Co.', 'Quorum', 'Shade', 'Toro', 'Toro', 50, 6.0, 'Parejo', null, null, null, 'Ecuador', 'Connecticut', 'Nicaragua', array['Nicaragua'], 'Nicaragua', 2, '$3-5', 'Quorum Shade er mild og kremet med et Ecuador Connecticut-dekkblad.', array['cream','cedar','hay','sweet spice']);

-- Saint Luis Rey (Honduras)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('General Cigar Co.', 'Saint Luis Rey', 'Reserva Especial', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Nicaragua', 'Habano', 'Nicaragua', array['Honduras','Nicaragua','Peru'], 'Honduras', 4, '$6-8', 'Reserva Especial er full-kroppet med aldret Honduras-, Nicaragua- og Peru-fyll.', array['coffee','sweet spice','black pepper','dark chocolate']),
('General Cigar Co.', 'Saint Luis Rey', 'Serie G', 'Gordo', 'Gordo', 60, 6.0, 'Parejo', null, null, null, 'Nicaragua', 'Habano', 'Honduras', array['Honduras'], 'Honduras', 4, '$6-8', 'Serie G ("Gigante") tilbyr store ringmål med full-kroppet styrke.', array['coffee','black pepper','cedar','earth']),
('General Cigar Co.', 'Saint Luis Rey', 'Carenas', 'Toro', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'Nicaragua', 'Habano', 'Honduras', array['Honduras'], 'Honduras', 3, '$6-8', 'Carenas har en Honduras-kjerne og et nicaraguansk dekkblad for en mer raffinert medium-kroppet smak.', array['cedar','toasted nuts','black pepper','cream']);

-- Don Diego (Dominikansk republikk, General Cigar)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('General Cigar Co.', 'Don Diego', 'Classic', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'United States', 'Connecticut Shade', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 1, '$4-6', 'Don Diego Classic er en mild, kremet klassiker med silkeglatt Connecticut Shade-dekkblad.', array['cream','cedar','roasted nuts','toasted bread']),
('General Cigar Co.', 'Don Diego', 'Aniversario', 'Toro', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'United States', 'Connecticut Shade', 'Dominican Republic', array['Dominican Republic','Brazil'], 'Dominican Republic', 3, '$5-7', 'Aniversario-linjen er medium til full-kroppet, en kraftigere variant av den klassiske Don Diego-profilen.', array['cedar','coffee','black pepper','cocoa']),
('General Cigar Co.', 'Don Diego', 'Fuerte', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Nicaragua', 'Habano', 'Dominican Republic', array['Dominican Republic','Nicaragua'], 'Dominican Republic', 4, '$5-7', 'Fuerte bruker et mørkt nicaraguansk dekkblad og gir Don Diego-familien sin kraftigste opplevelse.', array['black pepper','dark chocolate','earth','leather']);

-- Licenciados (Dominikansk republikk)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('General Cigar Co.', 'Licenciados', 'Classic', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'United States', 'Connecticut Shade', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 2, '$3-5', 'Licenciados er en mild til medium hverdagssigar med Connecticut Shade-dekkblad, lansert i 1989.', array['coffee','cedar','roasted nuts','cream']),
('General Cigar Co.', 'Licenciados', 'Classic', 'Toro', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'United States', 'Connecticut Shade', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 2, '$3-5', 'Toro-formatet av den samme kremede og nøtteaktige Licenciados-profilen.', array['coffee','cedar','roasted nuts','cream']),
('General Cigar Co.', 'Licenciados', 'Maduro', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'United States', 'Connecticut Broadleaf', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 3, '$3-5', 'Maduro-varianten gir mer kraft og søtere notater av brent brunt sukker og kakao.', array['brown sugar','cocoa','roasted peanuts','dark chocolate']);

-- Vega Fina (Dominikansk republikk, Altadis)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('Altadis U.S.A.', 'Vega Fina', 'Classic', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Ecuador', 'Connecticut', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 2, '$4-6', 'Vega Fina Classic er mild til medium med et silkeglatt Ecuador Connecticut-dekkblad.', array['cream','cedar','nuts','sweet spice']),
('Altadis U.S.A.', 'Vega Fina', 'Nicaragua', 'Toro', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'Nicaragua', 'Habano', 'Nicaragua', array['Nicaragua'], 'Dominican Republic', 3, '$4-6', 'Vega Fina Nicaragua bruker nicaraguansk tobakk gjennomgående for mer krydder og dybde.', array['black pepper','cedar','earth','dark chocolate']),
('Altadis U.S.A.', 'Vega Fina', 'Fortaleza 2', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Nicaragua', 'Maduro', 'Nicaragua', array['Nicaragua'], 'Dominican Republic', 5, '$4-6', 'Fortaleza 2 er den kraftigste linjen fra Vega Fina, full-kroppet og intens.', array['espresso','black pepper','dark chocolate','leather']);

-- Ave Maria (søstermerke til Asylum, blandet av AJ Fernandez)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('AJ Fernandez', 'Ave Maria', 'Ave Maria', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Ecuador', 'Habano', 'Nicaragua', array['Nicaragua','Honduras'], 'Nicaragua', 3, '$6-8', 'Ave Maria er medium til full-kroppet med sjokoladebrunt Ecuador Habano-dekkblad, blandet av AJ Fernandez.', array['dark chocolate','black pepper','cedar','earth']),
('AJ Fernandez', 'Ave Maria', 'Ave Maria', 'Toro', 'Toro', 54, 6.0, 'Parejo', null, null, null, 'Ecuador', 'Habano', 'Nicaragua', array['Nicaragua','Honduras'], 'Nicaragua', 3, '$6-8', 'Toro-formatet av Ave Maria, samme fyldige og krydrede profil.', array['dark chocolate','black pepper','cedar','coffee']),
('AJ Fernandez', 'Ave Maria', 'Ave Maria', 'Gordo', 'Gordo', 60, 6.0, 'Parejo', null, null, null, 'Ecuador', 'Habano', 'Nicaragua', array['Nicaragua','Honduras'], 'Nicaragua', 3, '$6-8', 'Det største formatet i Ave Maria-linjen, lang røyketid med samme balanserte styrke.', array['dark chocolate','black pepper','cedar','earth']);

-- Bauza (laget på Arturo Fuente-fabrikken i Dominikanske republikk)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('Tabacalera A. Fuente', 'Bauza', 'Classic', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Ecuador', 'Sumatra', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 3, '$4-6', 'Bauza håndlages av de samme torcedorene som lager Arturo Fuente, med et Ecuador Sumatra-dekkblad.', array['cedar','toasted nuts','leather','sweet spice']),
('Tabacalera A. Fuente', 'Bauza', 'Classic', 'Churchill', 'Churchill', 48, 7.0, 'Parejo', null, null, null, 'Ecuador', 'Sumatra', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 3, '$4-6', 'Churchill-formatet av Bauza, medium til full-kroppet med notater av sedertre og lær.', array['cedar','leather','toasted nuts','cocoa']),
('Tabacalera A. Fuente', 'Bauza', 'Casa Grande', 'Robusto', 'Robusto', 54, 5.5, 'Parejo', null, null, null, 'Ecuador', 'Sumatra', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 3, '$5-7', 'Casa Grande er en større, eksklusiv vitola i Bauza-familien med samme klassiske dominikanske profil.', array['cedar','toasted nuts','leather','cream']);
