-- Migrasjon 024: 7 nye merker funnet i full gjennomgang av Holt's komplette A-Å-katalog
-- Excalibur, Henry Clay, The Griffin's, Cuesta Rey, God of Fire, Charter Oak, Don Tomas

-- Excalibur (Hoyo de Monterrey-familien, produsert av Scandinavian Tobacco Group i Danlí, Honduras)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('Scandinavian Tobacco Group', 'Excalibur', 'Excalibur', 'No. I', 'Churchill', 54, 7.25, 'Parejo', null, null, null, 'United States', 'Connecticut Shade', 'United States', array['Honduras','Nicaragua','Dominican Republic'], 'Honduras', 2, '$5-7', 'Excalibur er en mild til medium klassiker fra Hoyo de Monterrey-familien, kjent for sin silkeglatte Connecticut Shade-dekkblad.', array['cedar','earth','espresso','mocha']),
('Scandinavian Tobacco Group', 'Excalibur', 'Excalibur', 'No. III', 'Toro', 50, 6.125, 'Parejo', null, null, null, 'United States', 'Connecticut Shade', 'United States', array['Honduras','Nicaragua','Dominican Republic'], 'Honduras', 2, '$5-7', 'Toro-formatet i Excalibur-serien, samme balanserte og kremete profil som resten av linjen.', array['cedar','earth','cream','mocha']),
('Scandinavian Tobacco Group', 'Excalibur', 'Excalibur Maduro', 'Epicure', 'Robusto', 50, 5.25, 'Parejo', null, null, null, 'United States', 'Connecticut Broadleaf Maduro', 'United States', array['Honduras','Nicaragua','Dominican Republic'], 'Honduras', 3, '$5-7', 'Maduro-varianten av Excalibur gir mer søtt og kraft enn originalen, med et mørkt Connecticut Broadleaf-dekkblad.', array['dark chocolate','espresso','black pepper','molasses']);

-- Henry Clay (Altadis U.S.A., historisk amerikansk merke)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('Altadis U.S.A.', 'Henry Clay', 'Original', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'United States', 'Connecticut Broadleaf Maduro', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 3, '$5-7', 'Den originale Henry Clay er en historisk klassiker med aldret dominikansk fyll og et mørkt Connecticut Broadleaf-dekkblad.', array['dark chocolate','coffee','cedar','sweet spice']),
('Altadis U.S.A.', 'Henry Clay', 'War Hawk', 'Toro', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'Ecuador', 'Connecticut Shade', 'United States', array['Honduras'], 'Dominican Republic', 3, '$5-7', 'War Hawk har et lyst Ecuador Connecticut Shade-dekkblad over en Connecticut Broadleaf-binder, medium styrke.', array['cream','cedar','toasted nuts','sweet spice']),
('Altadis U.S.A.', 'Henry Clay', 'Stalk Cut', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'United States', 'Connecticut Broadleaf (Stalk Cut)', 'Dominican Republic', array['Dominican Republic','Nicaragua'], 'Dominican Republic', 3, '$5-7', 'Stalk Cut-utgaven bruker stilkskåret Connecticut Broadleaf og dominikansk/nicaraguansk fyll for ekstra dybde.', array['dark chocolate','earth','black pepper','cedar']);

-- The Griffin's (Davidoff sitt verdimerke, laget på Occidental-fabrikken i Santiago)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('Davidoff', 'The Griffin''s', 'The Griffin''s', 'No. 300', 'Lonsdale', 44, 6.25, 'Parejo', null, null, null, 'Ecuador', 'Connecticut Shade', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 2, '$6-8', 'The Griffin''s er Davidoffs mildere verdilinje, med et gyllent Ecuador Connecticut Shade-dekkblad og delikat dominikansk fyll.', array['cream','hay','cedar','toasted almond']),
('Davidoff', 'The Griffin''s', 'The Griffin''s', 'No. 500', 'Robusto', 42, 5.06, 'Parejo', null, null, null, 'Ecuador', 'Connecticut Shade', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 2, '$6-8', 'Robusto-formatet av The Griffin''s, samme silkeglatte og milde profil i et kortere format.', array['cream','hay','cedar','vanilla']),
('Davidoff', 'The Griffin''s', 'The Griffin''s', 'Toro', 'Toro', 50, 6.0, 'Parejo', null, null, null, 'Ecuador', 'Connecticut Shade', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 2, '$6-8', 'Toro-formatet gir lenger røyketid med samme elegante, mild-til-medium Griffin''s-profil.', array['cream','hay','cedar','toasted almond']);

-- Cuesta Rey (J.C. Newman Cigar Co., håndlaget på Tabacalera A. Fuente-fabrikken)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('J.C. Newman Cigar Co.', 'Cuesta Rey', 'Centenario', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'United States', 'Connecticut Shade', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 3, '$6-9', 'Centenario er Cuesta Reys klassiske linje, med kubansk-frø fyll aldret i sedertre i opptil fem år.', array['cedar','toasted nuts','cream','sweet spice']),
('J.C. Newman Cigar Co.', 'Cuesta Rey', 'Centenario Maduro', 'Toro', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'United States', 'Connecticut Broadleaf Maduro', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 4, '$6-9', 'Maduro-varianten av Centenario gir mer kraft og søtere notater enn den klassiske Connecticut-utgaven.', array['dark chocolate','espresso','black pepper','molasses']),
('J.C. Newman Cigar Co.', 'Cuesta Rey', 'Centro Fino Sungrown', 'Toro', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'Ecuador', 'Sumatra Sungrown', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 4, '$6-9', 'Centro Fino Sungrown bruker solgrodd Ecuador Sumatra-dekkblad og aldret dominikansk ligero for en kraftigere smak.', array['leather','black pepper','earth','dark chocolate']);

-- God of Fire (ultra-premium, laget av Arturo Fuente for Prometheus)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('Tabacalera A. Fuente', 'God of Fire', 'Serie Aniversario', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Ecuador', 'Habano', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 4, '$15-20', 'God of Fire er en sjelden og svært eksklusiv linje laget av Arturo Fuente for Prometheus, lansert i 2004.', array['leather','dark chocolate','black pepper','dried fruit']),
('Tabacalera A. Fuente', 'God of Fire', 'By Don Carlos', 'Toro', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'Ecuador', 'Habano', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 4, '$15-20', 'By Don Carlos-linjen hyller Arturo Fuentes patriark med et raffinert Ecuador-dekkblad og kompleks smak.', array['cedar','espresso','dark chocolate','spice']),
('Tabacalera A. Fuente', 'God of Fire', 'Serie B', 'Robusto', 'Robusto', 54, 5.0, 'Parejo', null, null, null, 'United States', 'Connecticut Broadleaf Maduro', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 5, '$15-20', 'Serie B er den kraftigste i God of Fire-familien, med et mørkt Connecticut Broadleaf-dekkblad og intens smak.', array['dark chocolate','espresso','black pepper','molasses']);

-- Charter Oak (Foundation Cigar Co. sin verdilinje, blandet av Nick Melillo)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('Foundation Cigar Co.', 'Charter Oak', 'Connecticut Shade', 'Toro', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'United States', 'Connecticut Shade', 'Indonesia', array['Nicaragua'], 'Nicaragua', 2, '$4-6', 'Charter Oak Connecticut Shade er mild til medium, balansert med en Sumatra-binder og nicaraguansk fyll.', array['cream','cedar','hay','sweet spice']),
('Foundation Cigar Co.', 'Charter Oak', 'Connecticut Broadleaf', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'United States', 'Connecticut Broadleaf Maduro', 'Indonesia', array['Nicaragua'], 'Nicaragua', 3, '$4-6', 'Broadleaf-varianten av Charter Oak er mørkere og kraftigere, med rike og søte notater.', array['dark chocolate','espresso','black pepper','earth']),
('Foundation Cigar Co.', 'Charter Oak', 'Habano', 'Toro', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'Nicaragua', 'Habano', 'Nicaragua', array['Nicaragua'], 'Nicaragua', 3, '$4-6', 'Charter Oak Habano ble lagt til i 2020 og lages på AJ Fernandez-fabrikken i Estelí, medium styrke.', array['leather','black pepper','cedar','earth']);

-- Don Tomas (en av de eldste honduranske merkene, fra HATSA-fabrikken i Danlí)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('General Cigar Co.', 'Don Tomas', 'Clasico', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Honduras', 'Honduras', 'Honduras', array['Honduras','Nicaragua'], 'Honduras', 3, '$3-5', 'Don Tomas Clasico er en av de eldste honduranske merkene, med jordnær og balansert medium styrke.', array['earth','cedar','black pepper','toasted nuts']),
('General Cigar Co.', 'Don Tomas', 'Sun Grown', 'Toro', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'Honduras', 'Jamastran Sun Grown', 'Honduras', array['Honduras'], 'Honduras', 3, '$3-5', 'Sun Grown-varianten har et rødbrunt Jamastran-dekkblad og rik, aromatisk smak.', array['leather','cedar','sweet spice','earth']),
('General Cigar Co.', 'Don Tomas', 'Allegro', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Honduras', 'Habano', 'Honduras', array['Honduras','Nicaragua'], 'Honduras', 4, '$3-5', 'Allegro bruker et kraftigere Habano-dekkblad fra Honduras og gir medium til full styrke.', array['black pepper','dark chocolate','leather','earth']);
