-- Migrasjon 025: 7 nye merker funnet i gjennomgang av Wikipedias "List of cigar brands"
-- Bolivar, Cabaiguan, La Palina, Paul Garmirian, Por Larranaga, Sancho Panza, Zino Platinum

-- Bolivar (kubansk arvemerke, ikke-kubansk versjon laget av General Cigar Co. i Dominican Republic)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('General Cigar Co.', 'Bolivar', 'Cofradia', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'United States', 'Connecticut Broadleaf Oscuro', 'Honduras', array['Honduras','Nicaragua'], 'Dominican Republic', 4, '$8-11', 'Bolivar Cofradia er en kraftig hyllest til det kubanske arvemerket, med et oljeglinsende Connecticut Broadleaf Oscuro-dekkblad.', array['dark chocolate','espresso','black pepper','leather']),
('General Cigar Co.', 'Bolivar', 'Cofradia', 'Toro', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'United States', 'Connecticut Broadleaf Oscuro', 'Honduras', array['Honduras','Nicaragua'], 'Dominican Republic', 4, '$8-11', 'Toro-formatet av Cofradia gir lenger røyketid med samme mørke, søtlige og kraftfulle profil.', array['dark chocolate','molasses','black pepper','cedar']),
('General Cigar Co.', 'Bolivar', 'Heritage', 'Belicoso', 'Belicoso', 52, 5.5, 'Parejo', null, null, null, 'United States', 'Habano-seed Connecticut', 'Dominican Republic', array['Dominican Republic','Nicaragua'], 'Dominican Republic', 3, '$7-10', 'Bolivar Heritage er en mildere variant med et rødlig Habano-seed Connecticut-dekkblad og balansert dominikansk/nicaraguansk fyll.', array['cedar','toasted nuts','sweet spice','cream']);

-- Cabaiguan (samarbeid mellom Pete Johnson/Tatuaje og Don Pepin Garcia, rullet i Miami)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('EO Brands', 'Cabaiguan', 'Cabaiguan', 'Imperiales', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'Ecuador', 'Connecticut Shade', 'Nicaragua', array['Nicaragua'], 'United States', 2, '$8-11', 'Cabaiguan er et samarbeid mellom Pete Johnson (Tatuaje) og Don Pepin Garcia, oppkalt etter Pepins hjemby på Cuba.', array['cream','cedar','hay','black pepper']),
('EO Brands', 'Cabaiguan', 'Cabaiguan', 'Guapos', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Ecuador', 'Connecticut Shade', 'Nicaragua', array['Nicaragua'], 'United States', 2, '$8-11', 'Guapos-formatet gir samme milde til medium Pepin-signatur i et kortere robusto-format.', array['cream','toasted almond','cedar','sweet spice']),
('EO Brands', 'Cabaiguan', 'Cabaiguan Sungrown', 'Belicoso', 'Belicoso', 52, 5.5, 'Parejo', null, null, null, 'Ecuador', 'Sumatra Sungrown', 'Nicaragua', array['Nicaragua'], 'United States', 3, '$8-11', 'Sungrown-varianten bruker et mørkere, solgrodd Ecuador Sumatra-dekkblad for litt mer kraft og krydder.', array['leather','black pepper','earth','cedar']);

-- La Palina (moderne amerikansk premium-merke, Family Series Miami rullet i Miami)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('La Palina Cigars', 'La Palina', 'Family Series Miami', 'Babe', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Ecuador', 'Corojo ''98', 'Ecuador', array['Nicaragua'], 'United States', 3, '$9-12', 'Family Series Miami er rullet i Miami med et krydret Ecuador Corojo ''98-dekkblad og nicaraguansk fyll.', array['black pepper','cedar','sweet spice','leather']),
('La Palina Cigars', 'La Palina', 'Family Series Miami', 'Pasha', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'Ecuador', 'Corojo ''98', 'Ecuador', array['Nicaragua'], 'United States', 3, '$9-12', 'Pasha-formatet gir lenger røyketid med samme kraftfulle og krydrede Corojo-profil.', array['black pepper','espresso','cedar','dried fruit']),
('La Palina Cigars', 'La Palina', 'Family Series Miami', 'Alison', 'Corona', 44, 5.5, 'Parejo', null, null, null, 'Ecuador', 'Corojo ''98', 'Ecuador', array['Nicaragua'], 'United States', 3, '$9-12', 'Alison er det slankeste formatet i Family Series Miami, med konsentrert krydder og søtlig avslutning.', array['sweet spice','cedar','black pepper','cream']);

-- Paul Garmirian (PG, anerkjent håndlaget premium-merke fra Dominican Republic)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('Paul Garmirian Inc.', 'Paul Garmirian', 'Gourmet Series', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Ecuador', 'Connecticut Shade (Colorado)', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 2, '$10-14', 'PG Gourmet Series er et raffinert og komplekst merke, rullet i Santiago med aldret dominikansk fyll og et silkeglatt Connecticut-dekkblad.', array['cream','cedar','toasted nuts','honey']),
('Paul Garmirian Inc.', 'Paul Garmirian', 'Gourmet Series', 'Belicoso', 'Belicoso', 52, 6.0, 'Parejo', null, null, null, 'Ecuador', 'Connecticut Shade (Colorado)', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 2, '$10-14', 'Belicoso-formatet av Gourmet Series gir en spisset avslutning og samme elegante, krydrede profil.', array['cream','sweet spice','cedar','vanilla']),
('Paul Garmirian Inc.', 'Paul Garmirian', 'PG Maduro', 'Lonsdale', 'Lonsdale', 44, 6.5, 'Parejo', null, null, null, 'United States', 'Connecticut Broadleaf Maduro', 'Indonesia', array['Dominican Republic','Brazil'], 'Dominican Republic', 3, '$10-14', 'PG Maduro bruker et mørkt Connecticut Broadleaf-dekkblad med dominikansk og brasiliansk fyll for ekstra søtlig dybde.', array['dark chocolate','espresso','molasses','earth']);

-- Por Larranaga (et av de eldste kubanske arvemerkene, ikke-kubansk versjon via Altadis U.S.A.)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('Altadis U.S.A.', 'Por Larranaga', 'Por Larranaga', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Ecuador', 'Connecticut', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 3, '$6-9', 'Por Larranaga er et av de eldste kubanske arvemerkene, nå laget i Dominican Republic med Ecuador Connecticut-dekkblad og dominikansk Piloto/Olor-fyll.', array['cedar','toasted nuts','cream','sweet spice']),
('Altadis U.S.A.', 'Por Larranaga', 'Por Larranaga', 'Toro', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'Ecuador', 'Connecticut', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 3, '$6-9', 'Toro-formatet gir samme medium-bodied Por Larranaga-profil i et lengre format.', array['cedar','cream','hay','sweet spice']),
('Altadis U.S.A.', 'Por Larranaga', 'Por Larranaga', 'Churchill', 'Churchill', 48, 7.0, 'Parejo', null, null, null, 'Ecuador', 'Connecticut', 'Dominican Republic', array['Dominican Republic'], 'Dominican Republic', 3, '$6-9', 'Churchill-formatet er klassisk for merket, rullet på Tabacalera de Garcia med samme balanserte profil.', array['cedar','toasted nuts','cream','black pepper']);

-- Sancho Panza (kubansk arvemerke, ikke-kubansk versjon laget av General Cigar Co. i Honduras)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('General Cigar Co.', 'Sancho Panza', 'Original', 'Toro', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'Honduras', 'Connecticut-seed', 'Mexico', array['Brazil','Dominican Republic','Nicaragua'], 'Honduras', 3, '$5-7', 'Sancho Panza Original ble fornyet av General Cigars Matt Booth på STG-fabrikken i Danli, med honduransk Connecticut-frø-dekkblad og meksikansk San Andres-binder.', array['cedar','earth','toasted nuts','sweet spice']),
('General Cigar Co.', 'Sancho Panza', 'Double Maduro', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Ecuador', 'Sumatra Sungrown', 'Nicaragua', array['Dominican Republic','Nicaragua'], 'Honduras', 4, '$5-7', 'Double Maduro bruker et solgrodd Ecuador Sumatra-dekkblad og nicaraguansk Esteli-binder for mer kraft og søtlighet.', array['dark chocolate','espresso','black pepper','molasses']),
('General Cigar Co.', 'Sancho Panza', 'Extra Fuerte', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Ecuador', 'Sumatra', 'United States', array['Dominican Republic','Nicaragua'], 'Honduras', 5, '$5-7', 'Extra Fuerte er den kraftigste i Sancho Panza-familien, med Connecticut Broadleaf-binder og intens, fyldig smak.', array['black pepper','dark chocolate','leather','earth']);

-- Zino Platinum (Davidoffs eget merke, oppkalt etter grunnlegger Zino Davidoff)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('Davidoff', 'Zino Platinum', 'Crown Series', 'Toro', 'Toro', 54, 6.0, 'Parejo', null, null, null, 'Ecuador', 'Connecticut Shade', 'United States', array['Dominican Republic','Peru'], 'Dominican Republic', 3, '$12-16', 'Zino Platinum Crown Series er oppkalt etter grunnlegger Zino Davidoff, med et silkeglatt Ecuador Connecticut Shade-dekkblad og peruansk/dominikansk fyll.', array['cream','cedar','toasted almond','honey']),
('Davidoff', 'Zino Platinum', 'Scepter Series', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Ecuador', 'Connecticut Shade', 'United States', array['Dominican Republic','Peru'], 'Dominican Republic', 3, '$12-16', 'Scepter Series gir samme raffinerte og kremede profil i et kortere robusto-format.', array['cream','vanilla','cedar','sweet spice']),
('Davidoff', 'Zino Platinum', 'Exclusive Series', 'Belicoso', 'Belicoso', 52, 6.0, 'Parejo', null, null, null, 'Ecuador', 'Connecticut Shade', 'United States', array['Dominican Republic','Peru'], 'Dominican Republic', 3, '$12-16', 'Exclusive Series har en spisset avslutning og samme elegante Zino Platinum-signatur.', array['cream','cedar','honey','toasted nuts']);
