-- Migrasjon 026: 7 nye merker funnet i gjennomgang av Cigar Aficionados "All Cigar Brands"-liste
-- Bellas Artes, Casa Fernandez, Cuaba, L'Atelier, Leon Jimenes, Matilde, The Edge

-- Bellas Artes (A.J. Fernandez sitt hybrid-merke med "Rojita"-dekkblad)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('A.J. Fernandez Cigar Co.', 'Bellas Artes', 'Nicaraguan Hybrid', 'Robusto Extra', 'Robusto', 52, 5.0, 'Parejo', null, null, null, 'Nicaragua', 'Hybrid Rojita (Connecticut/Corojo 99/Havana 2000)', 'Nicaragua', array['Nicaragua','Honduras','Brazil'], 'Nicaragua', 3, '$9-12', 'Bellas Artes bruker A.J. Fernandez sitt proprietære "Rojita"-dekkblad, en hybrid av Connecticut Shade, Corojo 99 og Havana 2000.', array['cedar','black pepper','cocoa','citrus']),
('A.J. Fernandez Cigar Co.', 'Bellas Artes', 'Nicaraguan Hybrid', 'Toro', 'Toro', 54, 6.0, 'Parejo', null, null, null, 'Nicaragua', 'Hybrid Rojita (Connecticut/Corojo 99/Havana 2000)', 'Nicaragua', array['Nicaragua','Honduras','Brazil'], 'Nicaragua', 3, '$9-12', 'Toro-formatet gir lenger røyketid med samme balanserte og krydrede Rojita-profil.', array['cedar','cocoa','sweet spice','black pepper']),
('A.J. Fernandez Cigar Co.', 'Bellas Artes', 'Nicaraguan Hybrid', 'Short Churchill', 'Churchill', 48, 6.0, 'Parejo', null, null, null, 'Nicaragua', 'Hybrid Rojita (Connecticut/Corojo 99/Havana 2000)', 'Nicaragua', array['Nicaragua','Honduras','Brazil'], 'Nicaragua', 3, '$9-12', 'Short Churchill var en av de fire opprinnelige vitolaene da Bellas Artes ble lansert i 2016.', array['citrus','cedar','black pepper','cream']);

-- Casa Fernandez (Aganorsa Leafs eget merke, kjent for ren nicaraguansk tobakk)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('Aganorsa Leaf', 'Casa Fernandez', 'Aganorsa Leaf Maduro', 'Illustre', 'Corona Gorda', 48, 5.0, 'Parejo', null, null, null, 'Mexico', 'San Andres Maduro', 'Nicaragua', array['Nicaragua'], 'Nicaragua', 4, '$8-11', 'Casa Fernandez Aganorsa Leaf Maduro bruker et mørkt meksikansk San Andres-dekkblad over 100% nicaraguansk fyll fra Aganorsas egne gårder.', array['dark chocolate','espresso','black pepper','earth']),
('Aganorsa Leaf', 'Casa Fernandez', 'Aganorsa Leaf Maduro', 'El Supremo', 'Gordo', 58, 6.0, 'Parejo', null, null, null, 'Mexico', 'San Andres Maduro', 'Nicaragua', array['Nicaragua'], 'Nicaragua', 4, '$8-11', 'El Supremo er det største formatet i Maduro-linjen, med rikere og søtere røykutvikling.', array['dark chocolate','molasses','leather','black pepper']),
('Aganorsa Leaf', 'Casa Fernandez', 'Aganorsa Leaf TABSA', 'Bodhi No. 1', 'Robusto', 50, 5.25, 'Parejo', null, null, null, 'Nicaragua', 'Corojo', 'Nicaragua', array['Nicaragua'], 'Nicaragua', 3, '$8-11', 'TABSA-linjen er en hyllest til Aganorsas fabrikk i Nicaragua, med Corojo-dekkblad og ren nicaraguansk fyll.', array['cedar','toasted nuts','sweet spice','cream']);

-- Cuaba (kubansk arvemerke fra Habanos S.A., kjent for "double figurado"-formen)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('Habanos S.A.', 'Cuaba', null, 'Divinos', 'Perfecto', 43, 4.0, 'Perfecto', null, null, null, 'Cuba', 'Habano (Vuelta Abajo)', 'Cuba', array['Cuba'], 'Cuba', 4, '$25-35', 'Cuaba ble lansert i 1996 og er kjent for sin distinkte "double figurado"-form, en hyllest til kubanske sigarformer fra slutten av 1800-tallet.', array['earth','leather','black pepper','dried fruit']),
('Habanos S.A.', 'Cuaba', null, 'Exquisitos', 'Perfecto', 46, 5.7, 'Perfecto', null, null, null, 'Cuba', 'Habano (Vuelta Abajo)', 'Cuba', array['Cuba'], 'Cuba', 4, '$28-38', 'Exquisitos er det største formatet i Cuabas opprinnelige fire vitolaer fra 1996.', array['cedar','earth','espresso','black pepper']),
('Habanos S.A.', 'Cuaba', null, 'Tradicionales', 'Perfecto', 42, 4.7, 'Perfecto', null, null, null, 'Cuba', 'Habano (Vuelta Abajo)', 'Cuba', array['Cuba'], 'Cuba', 4, '$25-35', 'Tradicionales gir samme karakteristiske figurado-form i et mer kompakt format.', array['leather','earth','dried fruit','black pepper']);

-- L'Atelier (Pete Johnsons (Tatuaje) samarbeid med Garcia-familien, rullet hos My Father)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('My Father Cigars', 'L''Atelier', null, 'LAT52', 'Robusto', 52, 4.75, 'Parejo', null, null, null, 'Ecuador', 'Sancti Spiritus (Criollo/Pelo de Oro hybrid)', 'Nicaragua', array['Nicaragua'], 'Nicaragua', 4, '$11-14', 'L''Atelier ble lansert i 2012 av Pete Johnson (Tatuaje) med et sjeldent Sancti Spiritus-dekkblad og pigtail-topp inspirert av Cohiba Behike.', array['black pepper','espresso','leather','sweet spice']),
('My Father Cigars', 'L''Atelier', null, 'LAT54', 'Toro', 54, 5.625, 'Parejo', null, null, null, 'Ecuador', 'Sancti Spiritus (Criollo/Pelo de Oro hybrid)', 'Nicaragua', array['Nicaragua'], 'Nicaragua', 4, '$11-14', 'LAT54 gir samme kraftfulle og krydrede profil i et litt lengre format.', array['black pepper','dark chocolate','cedar','leather']),
('My Father Cigars', 'L''Atelier', null, 'LAT56', 'Gordo', 56, 6.5, 'Parejo', null, null, null, 'Ecuador', 'Sancti Spiritus (Criollo/Pelo de Oro hybrid)', 'Nicaragua', array['Nicaragua'], 'Nicaragua', 4, '$11-14', 'LAT56 er det største formatet, med lengre røyketid og samme signatur pigtail-topp.', array['espresso','black pepper','earth','sweet spice']);

-- Leon Jimenes (La Auroras hyllest til grunnleggerne Eduardo og Herminio Leon Jimenes)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('La Aurora', 'Leon Jimenes', 'Connecticut', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Ecuador', 'Connecticut', 'Dominican Republic', array['Dominican Republic','Nicaragua'], 'Dominican Republic', 2, '$6-9', 'Leon Jimenes Connecticut hyller La Auroras grunnleggere med et silkeglatt Ecuador Connecticut-dekkblad over dominikansk/nicaraguansk fyll.', array['cream','cedar','toasted nuts','honey']),
('La Aurora', 'Leon Jimenes', 'Connecticut', 'Toro', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'Ecuador', 'Connecticut', 'Dominican Republic', array['Dominican Republic','Nicaragua'], 'Dominican Republic', 2, '$6-9', 'Toro-formatet gir samme milde og kremede profil med lenger røyketid.', array['cream','vanilla','cedar','sweet spice']),
('La Aurora', 'Leon Jimenes', 'Prestige', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Ecuador', 'Connecticut Shade', 'Ecuador', array['Dominican Republic','Peru','Nicaragua'], 'Dominican Republic', 2, '$7-10', 'Prestige-linjen bruker et lyst Ecuador Connecticut Shade-dekkblad og en mer kompleks fyll med peruansk tobakk.', array['cream','toasted almond','cedar','honey']);

-- Matilde (boutique-merke av Jose Seijas, tidligere sjef for Tabacalera de Garcia)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('Seijas Cigars', 'Matilde', 'Renacer', 'Robusto', 'Robusto', 50, 5.25, 'Parejo', null, null, null, 'Ecuador', 'Habano', 'Dominican Republic', array['Dominican Republic','Nicaragua'], 'Dominican Republic', 3, '$9-12', 'Matilde Renacer var Jose Seijas sin debutlinje i 2014, med Ecuador Habano-dekkblad og dominikansk/nicaraguansk fyll.', array['cedar','black pepper','toasted nuts','sweet spice']),
('Seijas Cigars', 'Matilde', 'Renacer', 'Toro Bravo', 'Toro', 54, 6.5, 'Parejo', null, null, null, 'Ecuador', 'Habano', 'Dominican Republic', array['Dominican Republic','Nicaragua'], 'Dominican Republic', 3, '$9-12', 'Toro Bravo gir samme balanserte Renacer-profil i et lengre format.', array['cedar','sweet spice','black pepper','cream']),
('Seijas Cigars', 'Matilde', 'Quadrata', 'Robusto', 'Robusto', 50, 5.25, 'Parejo', null, null, null, 'Ecuador', 'Habano', 'Dominican Republic', array['Nicaragua','Dominican Republic'], 'Dominican Republic', 3, '$9-12', 'Quadrata er kjent for sin firkantede boks-presse-form og krydrede, balanserte profil.', array['black pepper','cedar','earth','toasted nuts']);

-- The Edge (Rocky Patels kjente verdimerke, opprinnelig lansert som $5-sigar)
insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('Rocky Patel Premium Cigars', 'The Edge', 'Maduro', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Honduras', 'Cuban-seed Maduro', 'Honduras', array['Honduras','Nicaragua'], 'Honduras', 4, '$5-7', 'The Edge Maduro bruker et honduransk Cuban-seed Maduro-dekkblad over fyll som er aldret i over fem år.', array['dark chocolate','espresso','black pepper','earth']),
('Rocky Patel Premium Cigars', 'The Edge', 'Corojo', 'Toro', 'Toro', 52, 6.0, 'Parejo', null, null, null, 'Honduras', 'Corojo', 'Nicaragua', array['Honduras'], 'Honduras', 3, '$5-7', 'The Edge Corojo kombinerer et klassisk honduransk Corojo-dekkblad med kraftig honduransk ligero-fyll.', array['black pepper','cedar','sweet spice','leather']),
('Rocky Patel Premium Cigars', 'The Edge', 'Connecticut', 'Robusto', 'Robusto', 50, 5.0, 'Parejo', null, null, null, 'Ecuador', 'Connecticut Shade', 'Nicaragua', array['Honduras','Nicaragua'], 'Honduras', 2, '$5-7', 'The Edge Connecticut er den mildeste varianten, med et lyst Ecuador Connecticut Shade-dekkblad.', array['cream','cedar','toasted nuts','sweet spice']);
