-- Migration 039: Cavalier Genève – full lineup
-- Swiss-founded (Sebastien Decoppet, 2015), made at Fábrica Centroamericana de Tabaco S.A., Danlí, Honduras

INSERT INTO cigars (
    brand, series, vitola,
    wrapper_country, wrapper_leaf, binder, filler,
    strength, country_origin,
    ring_gauge, length_inches,
    shape, common_format,
    body_type, head_type, foot_type,
    manufacturer,
    flavor_notes, description
) VALUES

-- ── WHITE SERIES (The Origin) ──────────────────────────────────────────────
-- Ecuadorian Connecticut wrapper; first line released 2015
('Cavalier Genève', 'White Series', 'Short Robusto',
 'Ecuador', 'Connecticut', 'Honduran', 'Honduran',
 'Medium', 'Honduras',
 52, 4.5,
 'parejo', 'Short Robusto',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Cream, cedar, almond, mild spice',
 'Cavalier Genève debut line; smooth Ecuadorian Connecticut wrapper over an all-Honduran blend.'),

('Cavalier Genève', 'White Series', 'Robusto',
 'Ecuador', 'Connecticut', 'Honduran', 'Honduran',
 'Medium', 'Honduras',
 52, 5.0,
 'parejo', 'Robusto',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Cream, cedar, almond, mild spice',
 'Cavalier Genève debut line; smooth Ecuadorian Connecticut wrapper over an all-Honduran blend.'),

('Cavalier Genève', 'White Series', 'Toro',
 'Ecuador', 'Connecticut', 'Honduran', 'Honduran',
 'Medium', 'Honduras',
 52, 6.0,
 'parejo', 'Toro',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Cream, cedar, almond, mild spice',
 'Cavalier Genève debut line; smooth Ecuadorian Connecticut wrapper over an all-Honduran blend.'),

('Cavalier Genève', 'White Series', 'Churchill',
 'Ecuador', 'Connecticut', 'Honduran', 'Honduran',
 'Medium', 'Honduras',
 48, 7.0,
 'parejo', 'Churchill',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Cream, cedar, almond, mild spice',
 'Cavalier Genève debut line; smooth Ecuadorian Connecticut wrapper over an all-Honduran blend.'),

('Cavalier Genève', 'White Series', 'Gordo',
 'Ecuador', 'Connecticut', 'Honduran', 'Honduran',
 'Medium', 'Honduras',
 60, 6.0,
 'parejo', 'Gordo',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Cream, cedar, almond, mild spice',
 'Cavalier Genève debut line; smooth Ecuadorian Connecticut wrapper over an all-Honduran blend.'),

-- ── INNER CIRCLE (The Homage) ──────────────────────────────────────────────
-- Honduran Corojo natural wrapper; fuller than White Series
('Cavalier Genève', 'Inner Circle', 'Short Robusto',
 'Honduras', 'Corojo', 'Honduran', 'Honduran',
 'Medium-Full', 'Honduras',
 52, 4.5,
 'parejo', 'Short Robusto',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Cedar, leather, dark chocolate, black pepper',
 'Core natural-wrapper blend with Honduran Corojo; richer and fuller than White Series.'),

('Cavalier Genève', 'Inner Circle', 'Robusto',
 'Honduras', 'Corojo', 'Honduran', 'Honduran',
 'Medium-Full', 'Honduras',
 52, 5.0,
 'parejo', 'Robusto',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Cedar, leather, dark chocolate, black pepper',
 'Core natural-wrapper blend with Honduran Corojo; richer and fuller than White Series.'),

('Cavalier Genève', 'Inner Circle', 'Toro',
 'Honduras', 'Corojo', 'Honduran', 'Honduran',
 'Medium-Full', 'Honduras',
 52, 6.0,
 'parejo', 'Toro',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Cedar, leather, dark chocolate, black pepper',
 'Core natural-wrapper blend with Honduran Corojo; richer and fuller than White Series.'),

('Cavalier Genève', 'Inner Circle', 'Churchill',
 'Honduras', 'Corojo', 'Honduran', 'Honduran',
 'Medium-Full', 'Honduras',
 48, 7.0,
 'parejo', 'Churchill',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Cedar, leather, dark chocolate, black pepper',
 'Core natural-wrapper blend with Honduran Corojo; richer and fuller than White Series.'),

('Cavalier Genève', 'Inner Circle', 'Gordo',
 'Honduras', 'Corojo', 'Honduran', 'Honduran',
 'Medium-Full', 'Honduras',
 60, 6.0,
 'parejo', 'Gordo',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Cedar, leather, dark chocolate, black pepper',
 'Core natural-wrapper blend with Honduran Corojo; richer and fuller than White Series.'),

-- ── BLACK II (The Old School) ──────────────────────────────────────────────
-- Honduran Maduro wrapper; bold and full-bodied
('Cavalier Genève', 'Black II', 'Short Robusto',
 'Honduras', 'Maduro', 'Honduran', 'Honduran',
 'Full', 'Honduras',
 52, 4.5,
 'parejo', 'Short Robusto',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Dark chocolate, espresso, earth, black pepper',
 'Bold Honduran maduro; deeply complex with roasted and peppery notes.'),

('Cavalier Genève', 'Black II', 'Robusto',
 'Honduras', 'Maduro', 'Honduran', 'Honduran',
 'Full', 'Honduras',
 52, 5.0,
 'parejo', 'Robusto',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Dark chocolate, espresso, earth, black pepper',
 'Bold Honduran maduro; deeply complex with roasted and peppery notes.'),

('Cavalier Genève', 'Black II', 'Toro',
 'Honduras', 'Maduro', 'Honduran', 'Honduran',
 'Full', 'Honduras',
 52, 6.0,
 'parejo', 'Toro',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Dark chocolate, espresso, earth, black pepper',
 'Bold Honduran maduro; deeply complex with roasted and peppery notes.'),

('Cavalier Genève', 'Black II', 'Gordo',
 'Honduras', 'Maduro', 'Honduran', 'Honduran',
 'Full', 'Honduras',
 60, 6.0,
 'parejo', 'Gordo',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Dark chocolate, espresso, earth, black pepper',
 'Bold Honduran maduro; deeply complex with roasted and peppery notes.'),

-- ── BII VISO JALAPA (The New School) ──────────────────────────────────────
-- Black II base with Viso Jalapa natural wrapper
('Cavalier Genève', 'BII Viso Jalapa', 'Robusto',
 'Honduras', 'Viso Jalapa', 'Honduran', 'Honduran',
 'Full', 'Honduras',
 52, 5.0,
 'parejo', 'Robusto',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Dark fruit, espresso, leather, white pepper',
 'Black II blend with a natural Viso Jalapa wrapper; complex, full, and refined.'),

('Cavalier Genève', 'BII Viso Jalapa', 'Toro',
 'Honduras', 'Viso Jalapa', 'Honduran', 'Honduran',
 'Full', 'Honduras',
 52, 6.0,
 'parejo', 'Toro',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Dark fruit, espresso, leather, white pepper',
 'Black II blend with a natural Viso Jalapa wrapper; complex, full, and refined.'),

('Cavalier Genève', 'BII Viso Jalapa', 'Gordo',
 'Honduras', 'Viso Jalapa', 'Honduran', 'Honduran',
 'Full', 'Honduras',
 60, 6.0,
 'parejo', 'Gordo',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Dark fruit, espresso, leather, white pepper',
 'Black II blend with a natural Viso Jalapa wrapper; complex, full, and refined.'),

-- ── PROSPEKTOR (Doble Capa) ────────────────────────────────────────────────
-- Unique double-wrapper (capa) construction
('Cavalier Genève', 'Prospektor', 'No. 1',
 'Honduras', 'Doble Capa', 'Honduran', 'Honduran',
 'Medium-Full', 'Honduras',
 46, 6.0,
 'parejo', 'Corona Gorda',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Toasted nuts, cedar, black pepper, leather',
 'Double-capa construction with two wrapper leaves; unique texture and complex flavour.'),

('Cavalier Genève', 'Prospektor', 'Robusto',
 'Honduras', 'Doble Capa', 'Honduran', 'Honduran',
 'Medium-Full', 'Honduras',
 52, 5.0,
 'parejo', 'Robusto',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Toasted nuts, cedar, black pepper, leather',
 'Double-capa construction with two wrapper leaves; unique texture and complex flavour.'),

('Cavalier Genève', 'Prospektor', 'Toro',
 'Honduras', 'Doble Capa', 'Honduran', 'Honduran',
 'Medium-Full', 'Honduras',
 52, 6.0,
 'parejo', 'Toro',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Toasted nuts, cedar, black pepper, leather',
 'Double-capa construction with two wrapper leaves; unique texture and complex flavour.'),

('Cavalier Genève', 'Prospektor', 'Gordo',
 'Honduras', 'Doble Capa', 'Honduran', 'Honduran',
 'Medium-Full', 'Honduras',
 60, 6.0,
 'parejo', 'Gordo',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Toasted nuts, cedar, black pepper, leather',
 'Double-capa construction with two wrapper leaves; unique texture and complex flavour.'),

-- ── TRES DELINCUENTES (Out of Control) ────────────────────────────────────
-- Large ring gauge; bold and complex
('Cavalier Genève', 'Tres Delincuentes', 'Robusto',
 'Honduras', 'Corojo', 'Honduran', 'Honduran',
 'Full', 'Honduras',
 54, 5.0,
 'parejo', 'Robusto',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Black pepper, leather, dark wood, cocoa',
 'Large ring-gauge blend; bold and complex with a Honduran Corojo wrapper.'),

('Cavalier Genève', 'Tres Delincuentes', 'Toro',
 'Honduras', 'Corojo', 'Honduran', 'Honduran',
 'Full', 'Honduras',
 54, 6.0,
 'parejo', 'Toro',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Black pepper, leather, dark wood, cocoa',
 'Large ring-gauge blend; bold and complex with a Honduran Corojo wrapper.'),

-- ── PROJECT BROADLEAF (Connecticut Broadleaf) ──────────────────────────────
-- Connecticut Broadleaf maduro wrapper
('Cavalier Genève', 'Project Broadleaf', 'Cowrider',
 'USA', 'Connecticut Broadleaf', 'Honduran', 'Honduran',
 'Full', 'Honduras',
 54, 4.75,
 'parejo', 'Robusto',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Dark chocolate, coffee, earth, molasses',
 'Connecticut Broadleaf maduro wrapper; rich, sweet, and full-bodied.'),

('Cavalier Genève', 'Project Broadleaf', 'Wayfinders No. 1',
 'USA', 'Connecticut Broadleaf', 'Honduran', 'Honduran',
 'Full', 'Honduras',
 52, 5.875,
 'parejo', 'Toro',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Dark chocolate, coffee, earth, molasses',
 'Connecticut Broadleaf maduro; rated 90 pts by Cigar Aficionado.'),

('Cavalier Genève', 'Project Broadleaf', 'Wayfinders No. 2',
 'USA', 'Connecticut Broadleaf', 'Honduran', 'Honduran',
 'Full', 'Honduras',
 48, 9.0,
 'parejo', 'Double Corona',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Dark chocolate, coffee, earth, molasses',
 'Connecticut Broadleaf maduro in a massive double-corona format; rated 92 pts by Cigar Aficionado.'),

-- ── DOMAINE ROUGE (The New Classic) ───────────────────────────────────────
-- Natural wrapper; elegant and refined
('Cavalier Genève', 'Domaine Rouge', 'Robusto',
 'Honduras', 'Natural', 'Honduran', 'Honduran',
 'Medium-Full', 'Honduras',
 52, 5.0,
 'parejo', 'Robusto',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Red fruit, dried cherry, cedar, cream, spice',
 'Elegant natural-wrapper blend; wine-inspired name, complex and refined character.'),

('Cavalier Genève', 'Domaine Rouge', 'Toro',
 'Honduras', 'Natural', 'Honduran', 'Honduran',
 'Medium-Full', 'Honduras',
 52, 6.0,
 'parejo', 'Toro',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Red fruit, dried cherry, cedar, cream, spice',
 'Elegant natural-wrapper blend; wine-inspired name, complex and refined character.'),

('Cavalier Genève', 'Domaine Rouge', 'Gordo',
 'Honduras', 'Natural', 'Honduran', 'Honduran',
 'Medium-Full', 'Honduras',
 60, 6.0,
 'parejo', 'Gordo',
 'straight', 'rounded', 'open',
 'Fábrica Centroamericana de Tabaco S.A.',
 'Red fruit, dried cherry, cedar, cream, spice',
 'Elegant natural-wrapper blend; wine-inspired name, complex and refined character.');
