-- Migration 040: 21 manglende merker fra M Sørensen-gap-analyse
-- 18 cubanske: Romeo y Julieta, Punch, Trinidad, Ramon Allones, Diplomaticos,
--   Vegas Robaina, San Cristobal de la Habana, Por Larranaga, Sancho Panza,
--   Rafael Gonzalez, Juan Lopez, Quai d''Orsay, Saint Luis Rey, La Flor de Cano,
--   Vegueros, Quintero, Guantanamera, Jose L. Piedra, Fonseca (Cuban)
-- New World: Aganorsa Leaf (Nicaragua), Vegafina (Dominican Republic)

INSERT INTO cigars (
    brand, series, vitola,
    wrapper_country, wrapper_leaf, binder, filler,
    strength, country_origin,
    ring_gauge, length_inches,
    shape, common_format,
    body_type, head_type, foot_type,
    manufacturer,
    flavor_notes, description
) VALUES

-- ── ROMEO Y JULIETA ────────────────────────────────────────────────────────
('Romeo y Julieta', 'Romeo y Julieta', 'Churchill',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 47, 7.0,
 'parejo', 'Churchill', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['floral', 'cedar', 'cream', 'light spice'],
 'The flagship Romeo y Julieta; refined and elegant Cuban Churchill, one of the world''s most recognised cigars.'),

('Romeo y Julieta', 'Romeo y Julieta', 'No. 1',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 42, 6.7,
 'parejo', 'Lonsdale', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['floral', 'cedar', 'cream', 'light spice'],
 'Classic lonsdale; smooth and complex with signature Romeo y Julieta elegance.'),

('Romeo y Julieta', 'Romeo y Julieta', 'Short Churchill',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 50, 4.8,
 'parejo', 'Robusto', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['floral', 'cedar', 'cream', 'light spice'],
 'Compact robusto; same elegant blend as the Churchill in a shorter format.'),

('Romeo y Julieta', 'Romeo y Julieta', 'Wide Churchill',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 55, 5.0,
 'parejo', 'Gordo', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['floral', 'cedar', 'cream', 'light spice'],
 'Wide ring-gauge Romeo; amplified creaminess and body without losing elegance.'),

-- ── PUNCH ────────────────────────────────────────────────────────────────
('Punch', 'Punch', 'Churchill',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 47, 7.0,
 'parejo', 'Churchill', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'leather', 'dark fruit', 'mild spice'],
 'Punch Churchill; classic Cuban medium-bodied smoke with excellent construction and consistent quality.'),

('Punch', 'Punch', 'Double Corona',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 49, 7.6,
 'parejo', 'Double Corona', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'leather', 'dark fruit', 'mild spice'],
 'Punch''s longest vitola; slow-burning and complex with cedar and leather notes.'),

('Punch', 'Punch', 'Punch',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 45, 5.3,
 'parejo', 'Corona', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'leather', 'dark fruit', 'mild spice'],
 'The eponymous vitola; classic corona format, medium and balanced.'),

('Punch', 'Punch', 'Short de Punch',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 52, 4.3,
 'parejo', 'Petit Robusto', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'leather', 'dark fruit', 'mild spice'],
 'Compact petit robusto; concentrated Punch flavour in a shorter smoke.'),

-- ── TRINIDAD ─────────────────────────────────────────────────────────────
('Trinidad', 'Trinidad', 'Fundadores',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 40, 7.5,
 'parejo', 'Laguito No. 1', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['floral', 'cream', 'cedar', 'white pepper'],
 'Originally made exclusively as diplomatic gifts by El Laguito; refined, elegant, and exceptionally complex.'),

('Trinidad', 'Trinidad', 'Robusto T',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 50, 4.8,
 'parejo', 'Robusto', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['floral', 'cream', 'cedar', 'white pepper'],
 'Trinidad in robusto format; elegant and refined with typical Trinidad creaminess.'),

('Trinidad', 'Trinidad', 'Coloniales',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 44, 5.1,
 'parejo', 'Petit Corona', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['floral', 'cream', 'cedar', 'white pepper'],
 'Most accessible Trinidad size; light and creamy with an excellent draw.'),

-- ── RAMON ALLONES ─────────────────────────────────────────────────────────
('Ramon Allones', 'Ramon Allones', 'Specially Selected',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 4, 'Cuba', 50, 4.8,
 'parejo', 'Robusto', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'leather', 'dark spice', 'cocoa', 'earth'],
 'Ramon Allones'' signature robusto; full-flavoured, spicy, and complex – a favourite among Cuban enthusiasts.'),

('Ramon Allones', 'Ramon Allones', 'Grand Corona',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 4, 'Cuba', 46, 5.6,
 'parejo', 'Grand Corona', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'leather', 'dark spice', 'cocoa', 'earth'],
 'Grand corona format; builds complexity nicely across its length.'),

('Ramon Allones', 'Ramon Allones', 'Small Club Coronas',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 4, 'Cuba', 42, 4.3,
 'parejo', 'Petit Corona', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'leather', 'dark spice', 'cocoa', 'earth'],
 'Compact size; packs full Ramon Allones character into a quick smoke.'),

-- ── DIPLOMATICOS ──────────────────────────────────────────────────────────
('Diplomaticos', 'Diplomaticos', 'No. 2',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 52, 6.0,
 'figurado', 'Piramide', 'straight', 'tapered', 'open',
 'Habanos S.A.',
 ARRAY['floral', 'cream', 'cedar', 'mild spice'],
 'Diplomaticos'' piramide; elegant Cuban figurado with classic medium body and complex tapering draw.'),

('Diplomaticos', 'Diplomaticos', 'No. 3',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 42, 5.4,
 'parejo', 'Corona', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['floral', 'cream', 'cedar', 'mild spice'],
 'Classic corona-sized Diplomaticos; smooth and medium-bodied.'),

('Diplomaticos', 'Diplomaticos', 'No. 4',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 42, 5.0,
 'parejo', 'Petit Corona', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['floral', 'cream', 'cedar', 'mild spice'],
 'Petit corona; one of the most accessible Diplomaticos vitolas.'),

-- ── VEGAS ROBAINA ─────────────────────────────────────────────────────────
('Vegas Robaina', 'Vegas Robaina', 'Famosos',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 4, 'Cuba', 48, 4.8,
 'parejo', 'Robusto', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'leather', 'earth', 'dark spice', 'coffee'],
 'Named for Alejandro Robaina, Cuba''s most revered tobacco farmer; full-flavoured robusto from premium Vuelta Abajo tobacco.'),

('Vegas Robaina', 'Vegas Robaina', 'Unicos',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 4, 'Cuba', 52, 5.6,
 'figurado', 'Piramide', 'straight', 'tapered', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'leather', 'earth', 'dark spice', 'coffee'],
 'Piramide vitola; builds intensity and complexity as the ring gauge narrows.'),

('Vegas Robaina', 'Vegas Robaina', 'Clasicos',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 4, 'Cuba', 42, 6.7,
 'parejo', 'Lonsdale', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'leather', 'earth', 'dark spice', 'coffee'],
 'Lonsdale format; full-bodied with long development of earthy, spicy flavour.'),

-- ── SAN CRISTOBAL DE LA HABANA ────────────────────────────────────────────
('San Cristobal de la Habana', 'San Cristobal', 'El Morro',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 52, 5.5,
 'parejo', 'Robusto Extra', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'cream', 'dried fruit', 'light spice'],
 'The largest standard San Cristobal vitola; medium-bodied with layered complexity.'),

('San Cristobal de la Habana', 'San Cristobal', 'El Príncipe',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 48, 4.3,
 'parejo', 'Petit Robusto', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'cream', 'dried fruit', 'light spice'],
 'Compact San Cristobal; approachable medium smoke for shorter sessions.'),

('San Cristobal de la Habana', 'San Cristobal', 'La Fuerza',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 50, 5.6,
 'parejo', 'Robusto', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'cream', 'dried fruit', 'light spice'],
 'Core robusto size; medium-bodied and elegant.'),

-- ── POR LARRANAGA ─────────────────────────────────────────────────────────
('Por Larranaga', 'Por Larranaga', 'Picadores',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 2, 'Cuba', 40, 4.8,
 'parejo', 'Petit Corona', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cream', 'hay', 'cedar', 'floral'],
 'One of Cuba''s oldest brands (founded 1834); mild, smooth, and highly accessible.'),

('Por Larranaga', 'Por Larranaga', 'Montecarlos',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 2, 'Cuba', 42, 5.6,
 'parejo', 'Corona', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cream', 'hay', 'cedar', 'floral'],
 'Classic corona format; mild and creamy, excellent for new smokers or mild-preference enthusiasts.'),

-- ── SANCHO PANZA ──────────────────────────────────────────────────────────
('Sancho Panza', 'Sancho Panza', 'Double Corona',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 2, 'Cuba', 49, 7.6,
 'parejo', 'Double Corona', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cream', 'hay', 'cedar', 'honey', 'mild spice'],
 'One of Cuba''s mildest double coronas; smooth, elegant, and incredibly smooth-burning.'),

('Sancho Panza', 'Sancho Panza', 'Belicosos',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 2, 'Cuba', 52, 5.5,
 'figurado', 'Belicoso', 'straight', 'tapered', 'open',
 'Habanos S.A.',
 ARRAY['cream', 'hay', 'cedar', 'honey', 'mild spice'],
 'Figurado vitola; the tapered head concentrates light, floral flavours beautifully.'),

('Sancho Panza', 'Sancho Panza', 'Non Plus',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 2, 'Cuba', 42, 5.1,
 'parejo', 'Petit Corona', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cream', 'hay', 'cedar', 'honey', 'mild spice'],
 'Accessible petit corona; mild, creamy, and elegant.'),

-- ── RAFAEL GONZALEZ ───────────────────────────────────────────────────────
('Rafael Gonzalez', 'Rafael Gonzalez', 'Lonsdale',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 2, 'Cuba', 42, 6.5,
 'parejo', 'Lonsdale', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cream', 'cedar', 'hay', 'mild spice'],
 'The classic Rafael Gonzalez lonsdale; one of Cuba''s finest mild, refined cigars – underrated gem.'),

('Rafael Gonzalez', 'Rafael Gonzalez', 'Corona Extra',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 2, 'Cuba', 46, 5.6,
 'parejo', 'Grand Corona', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cream', 'cedar', 'hay', 'mild spice'],
 'Grand corona format; slightly wider ring adds body while remaining mild and smooth.'),

-- ── JUAN LOPEZ ────────────────────────────────────────────────────────────
('Juan Lopez', 'Juan Lopez', 'Seleccion No. 1',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 42, 6.5,
 'parejo', 'Lonsdale', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'cream', 'earth', 'mild spice'],
 'Juan Lopez flagship lonsdale; medium-bodied with balanced complexity and good value.'),

('Juan Lopez', 'Juan Lopez', 'Seleccion No. 2',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 50, 4.8,
 'parejo', 'Robusto', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'cream', 'earth', 'mild spice'],
 'Robusto format; medium-bodied and smooth with reliable Cuban construction.'),

-- ── QUAI D'ORSAY ──────────────────────────────────────────────────────────
('Quai d''Orsay', 'Quai d''Orsay', 'No. 50',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 2, 'Cuba', 50, 6.0,
 'parejo', 'Robusto Extra', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cream', 'floral', 'cedar', 'honey'],
 'Made exclusively for the French market; among the mildest Cuban cigars – creamy, floral, and refined.'),

('Quai d''Orsay', 'Quai d''Orsay', 'Coronas Claro',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 2, 'Cuba', 42, 5.6,
 'parejo', 'Corona', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cream', 'floral', 'cedar', 'honey'],
 'Classic corona; claro-shade wrapper enhances the light, elegant character.'),

-- ── SAINT LUIS REY ────────────────────────────────────────────────────────
('Saint Luis Rey', 'Saint Luis Rey', 'Double Corona',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 4, 'Cuba', 49, 7.6,
 'parejo', 'Double Corona', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'leather', 'dark spice', 'earth', 'coffee'],
 'Saint Luis Rey''s most celebrated vitola; full-flavoured, powerful double corona – a cult Cuban favourite.'),

('Saint Luis Rey', 'Saint Luis Rey', 'Series A',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 4, 'Cuba', 50, 6.0,
 'parejo', 'Robusto Extra', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'leather', 'dark spice', 'earth', 'coffee'],
 'Robusto extra; full and complex with earthy, spicy character.'),

('Saint Luis Rey', 'Saint Luis Rey', 'Regios',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 4, 'Cuba', 48, 5.1,
 'parejo', 'Robusto', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'leather', 'dark spice', 'earth', 'coffee'],
 'Standard robusto; full-bodied with great consistency and value.'),

-- ── LA FLOR DE CANO ───────────────────────────────────────────────────────
('La Flor de Cano', 'La Flor de Cano', 'Short Churchill',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 50, 4.8,
 'parejo', 'Robusto', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'cream', 'earth', 'hay'],
 'La Flor de Cano robusto; medium-bodied, underrated Cuban brand with consistent quality and great value.'),

('La Flor de Cano', 'La Flor de Cano', 'Gran Corona',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 46, 5.8,
 'parejo', 'Grand Corona', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'cream', 'earth', 'hay'],
 'Grand corona; balanced medium complexity with reliable construction.'),

-- ── VEGUEROS ──────────────────────────────────────────────────────────────
('Vegueros', 'Vegueros', 'Tapados',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 52, 4.5,
 'parejo', 'Short Robusto', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'earth', 'hay', 'light spice'],
 'Vegueros short robusto; focused on Vuelta Abajo terroir – earthy, medium-bodied, and excellent value.'),

('Vegueros', 'Vegueros', 'Marevas',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 42, 5.1,
 'parejo', 'Petit Corona', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'earth', 'hay', 'light spice'],
 'The most popular Vegueros size; approachable, well-balanced, and affordable Cuban.'),

-- ── QUINTERO ─────────────────────────────────────────────────────────────
('Quintero', 'Quintero', 'Churchill',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 2, 'Cuba', 47, 7.0,
 'parejo', 'Churchill', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cream', 'hay', 'cedar', 'mild spice'],
 'Quintero Churchill; budget-friendly Cuban with mild, smooth character – excellent value.'),

('Quintero', 'Quintero', 'Coronas',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 2, 'Cuba', 42, 5.6,
 'parejo', 'Corona', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cream', 'hay', 'cedar', 'mild spice'],
 'Standard corona; mild and smooth, among Cuba''s most accessible budget smokes.'),

-- ── GUANTANAMERA ─────────────────────────────────────────────────────────
('Guantanamera', 'Guantanamera', 'Decimos',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 2, 'Cuba', 42, 5.6,
 'parejo', 'Corona', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cream', 'hay', 'cedar'],
 'Guantanamera''s most popular size; accessible entry-level Cuban, mild, smooth, and affordable.'),

('Guantanamera', 'Guantanamera', 'Cristales',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 2, 'Cuba', 32, 5.6,
 'parejo', 'Panetela', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cream', 'hay', 'cedar'],
 'Thin panetela format; light and quick, popular as a casual daytime Cuban.'),

-- ── JOSE L. PIEDRA ────────────────────────────────────────────────────────
('Jose L. Piedra', 'Jose L. Piedra', 'Brevas',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 44, 5.9,
 'parejo', 'Corona Grande', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'earth', 'leather', 'dark spice'],
 'Jose L. Piedra Brevas; budget Cuban with strong, rustic character – among Cuba''s best value smokes.'),

('Jose L. Piedra', 'Jose L. Piedra', 'Cazadores',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 3, 'Cuba', 43, 6.8,
 'parejo', 'Lonsdale', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cedar', 'earth', 'leather', 'dark spice'],
 'Lonsdale format; rustic and earthy with a long, satisfying smoke – exceptional value.'),

-- ── FONSECA (CUBAN) ───────────────────────────────────────────────────────
-- NB: Different from "Fonseca by My Father" (Dominican) already in DB
('Fonseca', 'Fonseca', 'No. 1',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 2, 'Cuba', 40, 6.8,
 'parejo', 'Lonsdale', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cream', 'hay', 'cedar', 'floral'],
 'Cuban Fonseca (distinct from Dominican Fonseca by My Father); mild, elegant lonsdale with a tissue-paper wrapper sleeve.'),

('Fonseca', 'Fonseca', 'Cosacos',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 2, 'Cuba', 42, 5.6,
 'parejo', 'Corona', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cream', 'hay', 'cedar', 'floral'],
 'Corona-sized Fonseca; smooth, mild, and creamy – a classic underrated Cuban.'),

('Fonseca', 'Fonseca', 'No. 5',
 'Cuba', 'Habano', 'Cuban', ARRAY['Cuba'],
 2, 'Cuba', 40, 4.3,
 'parejo', 'Petit Corona', 'straight', 'rounded', 'open',
 'Habanos S.A.',
 ARRAY['cream', 'hay', 'cedar', 'floral'],
 'Petit corona; smallest standard Fonseca vitola – light and accessible.'),

-- ── AGANORSA LEAF ─────────────────────────────────────────────────────────
('Aganorsa Leaf', 'Supreme Leaf', 'Robusto',
 'Nicaragua', 'Corojo 99', 'Nicaraguan', ARRAY['Nicaragua'],
 4, 'Nicaragua', 52, 5.0,
 'parejo', 'Robusto', 'straight', 'rounded', 'open',
 'NACSA (Nicaragua American Cigars S.A.)',
 ARRAY['cedar', 'dark spice', 'leather', 'coffee', 'black pepper'],
 'Grown on Aganorsa''s own farms in Jalapa and Estelí; powerful proprietary Corojo 99 wrapper drives bold complexity.'),

('Aganorsa Leaf', 'Supreme Leaf', 'Toro',
 'Nicaragua', 'Corojo 99', 'Nicaraguan', ARRAY['Nicaragua'],
 4, 'Nicaragua', 54, 6.0,
 'parejo', 'Toro', 'straight', 'rounded', 'open',
 'NACSA (Nicaragua American Cigars S.A.)',
 ARRAY['cedar', 'dark spice', 'leather', 'coffee', 'black pepper'],
 'Signature toro; medium-full to full with excellent balance from Aganorsa''s Corojo 99 leaf.'),

('Aganorsa Leaf', 'Supreme Leaf', 'Churchill',
 'Nicaragua', 'Corojo 99', 'Nicaraguan', ARRAY['Nicaragua'],
 4, 'Nicaragua', 48, 7.0,
 'parejo', 'Churchill', 'straight', 'rounded', 'open',
 'NACSA (Nicaragua American Cigars S.A.)',
 ARRAY['cedar', 'dark spice', 'leather', 'coffee', 'black pepper'],
 'Long-format Supreme Leaf; complex spice and wood development across a satisfying smoke time.'),

-- ── VEGAFINA ──────────────────────────────────────────────────────────────
('Vegafina', 'Vegafina', '1998',
 'Dominican Republic', 'Ecuadorian Connecticut', 'Dominican', ARRAY['Dominican Republic'],
 2, 'Dominican Republic', 50, 5.0,
 'parejo', 'Robusto', 'straight', 'rounded', 'open',
 'Tabacalera de García / Altadis',
 ARRAY['cream', 'cedar', 'floral', 'hay', 'mild spice'],
 'Vegafina''s flagship robusto; mild-medium Dominican smoke with smooth Ecuadorian Connecticut wrapper.'),

('Vegafina', 'Vegafina', 'Coronas',
 'Dominican Republic', 'Ecuadorian Connecticut', 'Dominican', ARRAY['Dominican Republic'],
 2, 'Dominican Republic', 42, 5.6,
 'parejo', 'Corona', 'straight', 'rounded', 'open',
 'Tabacalera de García / Altadis',
 ARRAY['cream', 'cedar', 'floral', 'hay', 'mild spice'],
 'Classic corona format; gentle and approachable, excellent entry-level Dominican cigar.'),

('Vegafina', 'Vegafina', 'Churchill',
 'Dominican Republic', 'Ecuadorian Connecticut', 'Dominican', ARRAY['Dominican Republic'],
 2, 'Dominican Republic', 48, 7.0,
 'parejo', 'Churchill', 'straight', 'rounded', 'open',
 'Tabacalera de García / Altadis',
 ARRAY['cream', 'cedar', 'floral', 'hay', 'mild spice'],
 'Mild and smooth Dominican Churchill; excellent value and consistent construction.');
