-- Migration 043: Add missing Marca Fina Ecuador vitolas (Coronita, Doble Corona, Colosales)

INSERT INTO cigars (brand, series, vitola, wrapper_country, wrapper_leaf, binder, filler, strength, country_origin, flavor_notes, description, price_range, ring_gauge, length_inches, shape, manufacturer, common_format, body_type, head_type, foot_type)
VALUES
  (
    'Marca Fina',
    'Ecuador',
    'Coronita',
    'Ecuador',
    'Ecuador Connecticut Shade',
    'Ecuador',
    ARRAY['Ecuador'],
    1,
    'Ecuador',
    ARRAY['grass', 'cream', 'cedar', 'mild spice'],
    'A petite 4x40 Coronita in the all-Ecuadorian Marca Fina lineup. Light and approachable with characteristic Connecticut Shade creaminess.',
    '$',
    40,
    4.0,
    'Petit Corona',
    'Tabacos de García',
    'Petit Corona',
    'claro',
    'rounded',
    'open'
  ),
  (
    'Marca Fina',
    'Ecuador',
    'Doble Corona',
    'Ecuador',
    'Ecuador Connecticut Shade',
    'Ecuador',
    ARRAY['Ecuador'],
    2,
    'Ecuador',
    ARRAY['cream', 'cedar', 'floral', 'light earth'],
    'A generous 7x50 Doble Corona offering a long, leisurely smoke. The Ecuadorian Connecticut Shade wrapper gives a smooth and elegant experience.',
    '$',
    50,
    7.0,
    'Double Corona',
    'Tabacos de García',
    'Double Corona',
    'claro',
    'rounded',
    'open'
  ),
  (
    'Marca Fina',
    'Ecuador',
    'Colosales',
    'Ecuador',
    'Ecuador Connecticut Shade',
    'Ecuador',
    ARRAY['Ecuador'],
    2,
    'Ecuador',
    ARRAY['cream', 'cedar', 'hay', 'light spice'],
    'An impressive 7x60 Gran Corona — one of the largest in the Marca Fina Ecuador line. The thick ring gauge slows the burn for a cooler, milder smoke.',
    '$',
    60,
    7.0,
    'Gran Corona',
    'Tabacos de García',
    'Gran Corona',
    'claro',
    'rounded',
    'open'
  );
