-- Migration 044: Add 13 missing premium brands
-- San Lotano, Casa Turrent, HVC, Onyx, La Estrella Cubana, Protocol,
-- Luciano, Hooten Young, Tabacalera La Alianza, Maya Selva, Aksum, Cusano, Stolen Throne

INSERT INTO cigars (brand, series, vitola, wrapper_country, wrapper_leaf, binder, filler, strength, country_origin, flavor_notes, description, price_range, ring_gauge, length_inches, shape, manufacturer, common_format, body_type, head_type, foot_type) VALUES

-- SAN LOTANO (AJ Fernandez, Nicaragua)
('San Lotano', 'Oval', 'Robusto', 'Nicaragua', 'Habano', 'Nicaragua', ARRAY['Nicaragua'], 3, 'Nicaragua', ARRAY['leather', 'earth', 'pepper', 'cedar', 'dark fruit'], 'The flagship San Lotano line features an oval box-press and Habano wrapper from Nicaragua. Full-bodied and complex with leather, dark fruit, and spice.', '$$', 52, 5.0, 'Robusto', 'AJ Fernandez', 'Robusto', 'colorado', 'rounded', 'open'),
('San Lotano', 'Oval', 'Toro', 'Nicaragua', 'Habano', 'Nicaragua', ARRAY['Nicaragua'], 3, 'Nicaragua', ARRAY['leather', 'earth', 'pepper', 'cedar', 'dark fruit'], 'San Lotano Oval Toro — same complex Habano-wrapped blend in a longer, cooler-smoking toro format.', '$$', 54, 6.0, 'Toro', 'AJ Fernandez', 'Toro', 'colorado', 'rounded', 'open'),
('San Lotano', 'Connecticut', 'Robusto', 'Ecuador', 'Ecuador Connecticut Shade', 'Nicaragua', ARRAY['Nicaragua'], 2, 'Nicaragua', ARRAY['cream', 'cedar', 'almond', 'light spice'], 'A milder expression from San Lotano with an Ecuadorian Connecticut Shade wrapper. Creamy and accessible with subtle complexity.', '$$', 52, 5.0, 'Robusto', 'AJ Fernandez', 'Robusto', 'claro', 'rounded', 'open'),
('San Lotano', 'Maduro', 'Robusto', 'USA', 'Connecticut Broadleaf Maduro', 'Nicaragua', ARRAY['Nicaragua'], 3, 'Nicaragua', ARRAY['dark chocolate', 'espresso', 'leather', 'sweet earth'], 'San Lotano Maduro wraps AJ Fernandez Nicaraguan filler in a rich Connecticut Broadleaf Maduro. Dark, sweet, and earthy.', '$$', 52, 5.0, 'Robusto', 'AJ Fernandez', 'Robusto', 'oscuro', 'rounded', 'open'),
('San Lotano', 'Habano', 'Toro', 'Nicaragua', 'Habano', 'Nicaragua', ARRAY['Nicaragua'], 3, 'Nicaragua', ARRAY['pepper', 'leather', 'cedar', 'earth', 'coffee'], 'San Lotano Habano delivers full-bodied Nicaraguan character with a rich Habano wrapper. A bold smoke with layers of pepper and cedar.', '$$', 54, 6.0, 'Toro', 'AJ Fernandez', 'Toro', 'colorado', 'rounded', 'open'),

-- CASA TURRENT (Mexico, San Andrés)
('Casa Turrent', '1901', 'Robusto', 'Mexico', 'San Andrés Maduro', 'Mexico', ARRAY['Mexico', 'Nicaragua'], 3, 'Mexico', ARRAY['dark chocolate', 'coffee', 'earth', 'leather', 'sweet spice'], 'Casa Turrent''s flagship 1901 line celebrates over a century of Mexican tobacco farming. The San Andrés Maduro wrapper delivers rich cocoa, earth, and leather.', '$$', 52, 5.0, 'Robusto', 'Casa Turrent', 'Robusto', 'oscuro', 'rounded', 'open'),
('Casa Turrent', '1901', 'Toro', 'Mexico', 'San Andrés Maduro', 'Mexico', ARRAY['Mexico', 'Nicaragua'], 3, 'Mexico', ARRAY['dark chocolate', 'coffee', 'earth', 'leather', 'sweet spice'], 'The 1901 Toro expands the signature San Andrés Maduro blend into a classic 6x52. Rich and full-bodied throughout.', '$$', 52, 6.0, 'Toro', 'Casa Turrent', 'Toro', 'oscuro', 'rounded', 'open'),
('Casa Turrent', '1942', 'Robusto', 'Mexico', 'San Andrés Colorado Claro', 'Mexico', ARRAY['Mexico'], 3, 'Mexico', 'Mexico', ARRAY['cedar', 'spice', 'leather', 'earth', 'cocoa'], 'The 1942 is a puro Mexicano wrapped in a San Andrés Colorado Claro. Medium-full with earthy complexity and a long finish.', '$$', 52, 5.0, 'Robusto', 'Casa Turrent', 'Robusto', 'colorado', 'rounded', 'open'),
('Casa Turrent', 'Origins', 'Nicaragua', 'Nicaragua', 'Habano', 'Nicaragua', ARRAY['Nicaragua'], 3, 'Mexico', ARRAY['pepper', 'cedar', 'leather', 'dark fruit'], 'Casa Turrent Origins explores premium Nicaraguan leaf with a Habano wrapper. A bold, spicy departure from the brand''s Mexican roots.', '$$', 52, 6.0, 'Toro', 'Casa Turrent', 'Toro', 'colorado', 'rounded', 'open'),

-- HVC — HAVANA V CIGARS (Nicaragua/AGANORSA)
('HVC', '50 Años', 'Robusto', 'Nicaragua', 'Corojo 99', 'Nicaragua', ARRAY['Nicaragua'], 3, 'Nicaragua', ARRAY['pepper', 'cedar', 'leather', 'cream', 'dark spice'], 'HVC 50 Años commemorates 50 years of Cuban heritage with a Corojo 99 wrapper from AGANORSA. Full and complex with old-world character.', '$$$', 50, 5.0, 'Robusto', 'AGANORSA Leaf', 'Robusto', 'colorado', 'rounded', 'open'),
('HVC', '50 Años', 'Toro', 'Nicaragua', 'Corojo 99', 'Nicaragua', ARRAY['Nicaragua'], 3, 'Nicaragua', ARRAY['pepper', 'cedar', 'leather', 'cream', 'dark spice'], 'The HVC 50 Años Toro gives more time to develop its Corojo 99 complexity. Pepper-forward with creamy retrohale.', '$$$', 52, 6.0, 'Toro', 'AGANORSA Leaf', 'Toro', 'colorado', 'rounded', 'open'),
('HVC', 'Capa de Oro', 'Robusto', 'Nicaragua', 'AGANORSA Criollo 98', 'Nicaragua', ARRAY['Nicaragua'], 3, 'Nicaragua', ARRAY['earth', 'leather', 'pepper', 'cedar', 'espresso'], 'HVC Capa de Oro uses AGANORSA''s prized Criollo 98 wrapper for a robust, earthy Nicaraguan puro with excellent construction.', '$$', 50, 5.0, 'Robusto', 'AGANORSA Leaf', 'Robusto', 'colorado', 'rounded', 'open'),
('HVC', 'For Him', 'Robusto', 'Nicaragua', 'Habano', 'Nicaragua', ARRAY['Nicaragua'], 3, 'Nicaragua', ARRAY['pepper', 'leather', 'coffee', 'cedar'], 'HVC For Him is a full-flavored Nicaraguan puro with Habano wrapper. Strength and complexity balanced for the seasoned smoker.', '$$', 52, 5.0, 'Robusto', 'AGANORSA Leaf', 'Robusto', 'colorado', 'rounded', 'open'),

-- ONYX (General Cigar, Honduras)
('Onyx', 'Reserve', 'Robusto', 'Honduras', 'Sumatra', 'Honduras', ARRAY['Honduras', 'Nicaragua', 'Dominican Republic'], 3, 'Honduras', ARRAY['cedar', 'leather', 'earth', 'spice', 'coffee'], 'Onyx Reserve is crafted at General Cigar''s Honduran factory with an oily Sumatra wrapper. Full-bodied and consistent with rich cedar and leather.', '$$', 52, 5.0, 'Robusto', 'General Cigar Co.', 'Robusto', 'colorado', 'rounded', 'open'),
('Onyx', 'Reserve', 'Toro', 'Honduras', 'Sumatra', 'Honduras', ARRAY['Honduras', 'Nicaragua', 'Dominican Republic'], 3, 'Honduras', ARRAY['cedar', 'leather', 'earth', 'spice', 'coffee'], 'Onyx Reserve Toro — the workhorse format for this Sumatra-wrapped Honduran blend. Consistent, full-bodied, and great value.', '$$', 52, 6.0, 'Toro', 'General Cigar Co.', 'Toro', 'colorado', 'rounded', 'open'),
('Onyx', 'Reserve', 'Churchill', 'Honduras', 'Sumatra', 'Honduras', ARRAY['Honduras', 'Nicaragua', 'Dominican Republic'], 3, 'Honduras', ARRAY['cedar', 'leather', 'earth', 'spice', 'coffee'], 'A long, satisfying smoke in the Onyx Reserve lineup. The Churchill format lets the Sumatra wrapper''s complexity fully develop.', '$$', 48, 7.0, 'Churchill', 'General Cigar Co.', 'Churchill', 'colorado', 'rounded', 'open'),

-- LA ESTRELLA CUBANA (AJ Fernandez, Nicaragua/DR)
('La Estrella Cubana', 'Maduro', 'Robusto', 'USA', 'Connecticut Broadleaf Maduro', 'Nicaragua', ARRAY['Nicaragua', 'Dominican Republic'], 3, 'Nicaragua', ARRAY['dark chocolate', 'espresso', 'cedar', 'sweet earth', 'leather'], 'La Estrella Cubana Maduro pairs AJ Fernandez''s Nicaraguan and Dominican filler with a lush Connecticut Broadleaf Maduro wrapper. Rich and sweet.', '$$', 52, 5.0, 'Robusto', 'AJ Fernandez', 'Robusto', 'oscuro', 'rounded', 'open'),
('La Estrella Cubana', 'Maduro', 'Toro', 'USA', 'Connecticut Broadleaf Maduro', 'Nicaragua', ARRAY['Nicaragua', 'Dominican Republic'], 3, 'Nicaragua', ARRAY['dark chocolate', 'espresso', 'cedar', 'sweet earth', 'leather'], 'La Estrella Cubana Maduro Toro — dark, sweet, and full-bodied. A great value from AJ Fernandez''s accessible lineup.', '$$', 54, 6.0, 'Toro', 'AJ Fernandez', 'Toro', 'oscuro', 'rounded', 'open'),
('La Estrella Cubana', 'Habano', 'Robusto', 'Nicaragua', 'Habano', 'Nicaragua', ARRAY['Nicaragua', 'Dominican Republic'], 3, 'Nicaragua', ARRAY['pepper', 'leather', 'cedar', 'earth', 'spice'], 'La Estrella Cubana Habano brings AJ Fernandez''s signature Nicaraguan/Dominican blend under a oily Habano wrapper. Spicy and earthy.', '$$', 52, 5.0, 'Robusto', 'AJ Fernandez', 'Robusto', 'colorado', 'rounded', 'open'),
('La Estrella Cubana', 'Connecticut', 'Robusto', 'Ecuador', 'Ecuador Connecticut Shade', 'Nicaragua', ARRAY['Nicaragua', 'Dominican Republic'], 2, 'Nicaragua', ARRAY['cream', 'cedar', 'almond', 'hay', 'light spice'], 'La Estrella Cubana Connecticut is a smooth, creamy introduction to the brand. Ecuador Connecticut Shade wrapper over AJ Fernandez Nicaraguan/DR filler.', '$$', 52, 5.0, 'Robusto', 'AJ Fernandez', 'Robusto', 'claro', 'rounded', 'open'),

-- PROTOCOL (Cubariquet / General Cigar)
('Protocol', 'Silver', 'Robusto', 'Ecuador', 'Ecuador Connecticut Shade', 'Nicaragua', ARRAY['Nicaragua'], 2, 'Nicaragua', ARRAY['cream', 'cedar', 'grass', 'almond', 'white pepper'], 'Protocol Silver is the approachable entry to the law-enforcement themed Protocol line. Smooth Ecuadorian Connecticut Shade over Nicaraguan filler.', '$$', 52, 5.0, 'Robusto', 'Cubariquet', 'Robusto', 'claro', 'rounded', 'open'),
('Protocol', 'Officer''s Reserve', 'Robusto', 'Nicaragua', 'Habano', 'Nicaragua', ARRAY['Nicaragua'], 3, 'Nicaragua', ARRAY['pepper', 'cedar', 'leather', 'earth', 'coffee'], 'Protocol Officer''s Reserve steps up to a Nicaraguan Habano wrapper for medium-full flavor. Consistent 90+ ratings make this a boutique standout.', '$$', 52, 5.0, 'Robusto', 'Cubariquet', 'Robusto', 'colorado', 'rounded', 'open'),
('Protocol', 'Officer''s Reserve', 'Toro', 'Nicaragua', 'Habano', 'Nicaragua', ARRAY['Nicaragua'], 3, 'Nicaragua', ARRAY['pepper', 'cedar', 'leather', 'earth', 'coffee'], 'Protocol Officer''s Reserve Toro gives extra time to develop its spicy Habano character. Excellent construction at a boutique price.', '$$', 54, 6.0, 'Toro', 'Cubariquet', 'Toro', 'colorado', 'rounded', 'open'),
('Protocol', 'Themis', 'Robusto', 'Ecuador', 'Ecuador Habano Sun-Grown', 'Nicaragua', ARRAY['Nicaragua'], 3, 'Nicaragua', ARRAY['cedar', 'spice', 'dark fruit', 'leather', 'cream'], 'Protocol Themis features an Ecuadorian Habano sun-grown wrapper for extra complexity. Named for the goddess of law, it''s precise and well-crafted.', '$$$', 52, 5.0, 'Robusto', 'Cubariquet', 'Robusto', 'colorado', 'rounded', 'open'),

-- LUCIANO (Ace Prime, Nicaragua)
('Luciano', 'The Luciano', 'Robusto', 'Ecuador', 'Ecuador Sun-Grown', 'Nicaragua', ARRAY['Nicaragua'], 3, 'Nicaragua', ARRAY['cedar', 'leather', 'spice', 'dark fruit', 'cream'], 'The flagship Luciano by Ace Prime showcases Luciano Meirelles'' mastery with an Ecuadorian sun-grown wrapper over premium Nicaraguan tobaccos. Ultra-premium construction and complexity.', '$$$', 52, 4.5, 'Robusto', 'Ace Prime', 'Robusto', 'colorado', 'rounded', 'open'),
('Luciano', 'The Luciano', 'Toro', 'Ecuador', 'Ecuador Sun-Grown', 'Nicaragua', ARRAY['Nicaragua'], 3, 'Nicaragua', ARRAY['cedar', 'leather', 'spice', 'dark fruit', 'cream'], 'Luciano Toro — the extended format of this ultra-premium boutique blend. Complex and refined from first third to nub.', '$$$', 54, 5.6, 'Toro', 'Ace Prime', 'Toro', 'colorado', 'rounded', 'open'),
('Luciano', 'Cigare Volant', 'Toro', 'Nicaragua', 'Habano', 'Nicaragua', ARRAY['Nicaragua'], 4, 'Nicaragua', ARRAY['pepper', 'dark earth', 'leather', 'espresso', 'spice'], 'Luciano''s Cigare Volant ("flying cigar") is a full-strength, torpedo-inspired box-press. Intense Nicaraguan Habano with outstanding construction.', '$$$', 54, 6.0, 'Toro', 'Ace Prime', 'Toro', 'colorado', 'rounded', 'open'),

-- HOOTEN YOUNG (Jonathan Drew, Nicaragua)
('Hooten Young', 'Robusto Real', 'Robusto', 'Nicaragua', 'Corojo', 'Nicaragua', ARRAY['Nicaragua'], 4, 'Nicaragua', ARRAY['pepper', 'cedar', 'dark earth', 'leather', 'coffee'], 'Hooten Young Robusto Real from Jonathan Drew is a powerhouse Nicaraguan Corojo. Full-strength and bold with exceptional construction from the Drew Estate mastermind.', '$$$', 52, 5.0, 'Robusto', 'Jonathan Drew', 'Robusto', 'colorado', 'rounded', 'open'),
('Hooten Young', 'Connecticut', 'Robusto', 'Ecuador', 'Ecuador Connecticut Shade', 'Nicaragua', ARRAY['Nicaragua'], 2, 'Nicaragua', ARRAY['cream', 'cedar', 'almond', 'light pepper', 'grass'], 'The milder side of Hooten Young — Connecticut Shade wrapper over Nicaraguan leaf. Smooth and nuanced from the Drew Estate legend.', '$$$', 52, 5.0, 'Robusto', 'Jonathan Drew', 'Robusto', 'claro', 'rounded', 'open'),
('Hooten Young', 'Robusto Real', 'Churchill', 'Nicaragua', 'Corojo', 'Nicaragua', ARRAY['Nicaragua'], 4, 'Nicaragua', ARRAY['pepper', 'cedar', 'dark earth', 'leather', 'coffee'], 'Hooten Young Churchill — a long, powerful smoke for those who want the Corojo at its fullest. Full-strength and complex.', '$$$', 48, 7.0, 'Churchill', 'Jonathan Drew', 'Churchill', 'colorado', 'rounded', 'open'),

-- TABACALERA LA ALIANZA (Erik Espinosa, Dominican Republic)
('Tabacalera La Alianza', 'TAA', 'Robusto', 'Ecuador', 'Ecuador Habano Sun-Grown', 'Dominican Republic', ARRAY['Dominican Republic', 'Nicaragua'], 3, 'Dominican Republic', ARRAY['cedar', 'spice', 'leather', 'earth', 'cocoa'], 'Tabacalera La Alianza produces premium Dominican cigars at Erik Espinosa''s La Alianza factory. The TAA Robusto is a well-constructed medium-full blend.', '$$', 50, 5.0, 'Robusto', 'La Alianza', 'Robusto', 'colorado', 'rounded', 'open'),
('Tabacalera La Alianza', 'TAA', 'Toro', 'Ecuador', 'Ecuador Habano Sun-Grown', 'Dominican Republic', ARRAY['Dominican Republic', 'Nicaragua'], 3, 'Dominican Republic', ARRAY['cedar', 'spice', 'leather', 'earth', 'cocoa'], 'La Alianza TAA Toro — excellent construction from the Espinosa factory in Santiago. Medium-full with Ecuadorian sun-grown character.', '$$', 52, 6.0, 'Toro', 'La Alianza', 'Toro', 'colorado', 'rounded', 'open'),
('Tabacalera La Alianza', 'TAA', 'Churchill', 'Ecuador', 'Ecuador Habano Sun-Grown', 'Dominican Republic', ARRAY['Dominican Republic', 'Nicaragua'], 3, 'Dominican Republic', ARRAY['cedar', 'spice', 'leather', 'earth', 'cocoa'], 'The TAA Churchill from La Alianza allows the Dominican/Nicaraguan blend to fully express itself over a long, satisfying smoke.', '$$', 48, 7.0, 'Churchill', 'La Alianza', 'Churchill', 'colorado', 'rounded', 'open'),

-- MAYA SELVA (France/Honduras)
('Maya Selva', 'Cuesta del Viento', 'Robusto', 'Honduras', 'Honduras Habano', 'Honduras', ARRAY['Honduras', 'Nicaragua'], 3, 'Honduras', ARRAY['cedar', 'leather', 'earth', 'black pepper', 'dark fruit'], 'Maya Selva''s flagship Cuesta del Viento is a full-flavored Honduran blend beloved in Europe. The Habano wrapper delivers pepper, earth, and dark fruit complexity.', '$$', 52, 5.0, 'Robusto', 'Maya Selva', 'Robusto', 'colorado', 'rounded', 'open'),
('Maya Selva', 'Cuesta del Viento', 'Toro', 'Honduras', 'Honduras Habano', 'Honduras', ARRAY['Honduras', 'Nicaragua'], 3, 'Honduras', ARRAY['cedar', 'leather', 'earth', 'black pepper', 'dark fruit'], 'Cuesta del Viento Toro — more time to develop the Honduran Habano''s complexity. A crowd favourite at European cigar lounges.', '$$', 54, 6.0, 'Toro', 'Maya Selva', 'Toro', 'colorado', 'rounded', 'open'),
('Maya Selva', 'Flora Rosa', 'Robusto', 'Honduras', 'Honduras Colorado', 'Honduras', ARRAY['Honduras'], 2, 'Honduras', ARRAY['floral', 'cedar', 'cream', 'light spice', 'hay'], 'Flora Rosa is Maya Selva''s medium-strength offering with a lighter Colorado wrapper. Floral and elegant — a distinctive take on Honduran tobacco.', '$$', 50, 5.0, 'Robusto', 'Maya Selva', 'Robusto', 'colorado claro', 'rounded', 'open'),
('Maya Selva', 'Flor de Selva', 'Robusto', 'Honduras', 'Honduras Colorado', 'Honduras', ARRAY['Honduras'], 3, 'Honduras', ARRAY['cedar', 'spice', 'leather', 'earth', 'toasted wood'], 'Maya Selva Flor de Selva is a traditional Honduran blend with Colorado wrapper. Medium-full and approachable, showcasing Honduras''s finest leaf.', '$$', 52, 5.0, 'Robusto', 'Maya Selva', 'Robusto', 'colorado', 'rounded', 'open'),

-- AKSUM (Ethiopian-themed, Dominican Republic)
('Aksum', 'Claro', 'Robusto', 'Ecuador', 'Ecuador Connecticut Shade', 'Dominican Republic', ARRAY['Dominican Republic', 'Nicaragua'], 2, 'Dominican Republic', ARRAY['cream', 'cedar', 'almond', 'light spice', 'honey'], 'Aksum Claro celebrates the ancient Ethiopian empire with an Ecuadorian Connecticut Shade wrapper over premium Dominican/Nicaraguan filler. Smooth and approachable.', '$$', 50, 5.0, 'Robusto', 'Aksum', 'Robusto', 'claro', 'rounded', 'open'),
('Aksum', 'Maduro', 'Robusto', 'USA', 'Connecticut Broadleaf Maduro', 'Dominican Republic', ARRAY['Dominican Republic', 'Nicaragua'], 3, 'Dominican Republic', ARRAY['dark chocolate', 'coffee', 'cedar', 'sweet earth', 'spice'], 'Aksum Maduro wraps its Dominican/Nicaraguan blend in a Connecticut Broadleaf Maduro. Rich, dark, and balanced with sweet earth and chocolate notes.', '$$', 50, 5.0, 'Robusto', 'Aksum', 'Robusto', 'oscuro', 'rounded', 'open'),
('Aksum', 'Claro', 'Toro', 'Ecuador', 'Ecuador Connecticut Shade', 'Dominican Republic', ARRAY['Dominican Republic', 'Nicaragua'], 2, 'Dominican Republic', ARRAY['cream', 'cedar', 'almond', 'light spice', 'honey'], 'The Aksum Claro Toro gives more smoke time to develop its creamy Connecticut Shade character. A well-crafted boutique cigar at a reasonable price.', '$$', 52, 6.0, 'Toro', 'Aksum', 'Toro', 'claro', 'rounded', 'open'),

-- CUSANO (M. Cusano International, Dominican Republic)
('Cusano', '18', 'Robusto', 'Ecuador', 'Ecuador Connecticut Shade', 'Dominican Republic', ARRAY['Dominican Republic', 'Brazil'], 2, 'Dominican Republic', ARRAY['cream', 'cedar', 'almond', 'floral', 'light earth'], 'Cusano 18 is aged for 18 months after rolling, delivering extra smoothness. The Connecticut Shade wrapper over Dominican/Brazilian filler is classic and refined.', '$$', 52, 5.0, 'Robusto', 'M. Cusano International', 'Robusto', 'claro', 'rounded', 'open'),
('Cusano', 'Corojo', 'Robusto', 'Honduras', 'Honduras Corojo', 'Dominican Republic', ARRAY['Dominican Republic', 'Nicaragua'], 3, 'Dominican Republic', ARRAY['pepper', 'leather', 'cedar', 'spice', 'earth'], 'Cusano Corojo uses a Honduran Corojo wrapper over Dominican/Nicaraguan filler for a medium-full smoke with classic Corojo spice and leather notes.', '$$', 52, 5.0, 'Robusto', 'M. Cusano International', 'Robusto', 'colorado', 'rounded', 'open'),
('Cusano', 'Connecticut', 'Toro', 'Ecuador', 'Ecuador Connecticut Shade', 'Dominican Republic', ARRAY['Dominican Republic'], 1, 'Dominican Republic', ARRAY['cream', 'cedar', 'grass', 'honey', 'light floral'], 'Cusano Connecticut is a mild, smooth smoke with Ecuadorian shade wrapper over Dominican filler. A refined choice for milder cigar lovers.', '$$', 52, 6.0, 'Toro', 'M. Cusano International', 'Toro', 'claro', 'rounded', 'open'),

-- STOLEN THRONE (Honduras)
('Stolen Throne', 'Deposed', 'Robusto', 'Honduras', 'Honduras Habano', 'Honduras', ARRAY['Honduras', 'Nicaragua'], 3, 'Honduras', ARRAY['leather', 'earth', 'pepper', 'cedar', 'dark fruit'], 'Stolen Throne Deposed is a bold Honduran boutique cigar with Habano wrapper. Medium-full with leather, pepper, and dark fruit that develops toward the finish.', '$$', 52, 5.0, 'Robusto', 'Stolen Throne', 'Robusto', 'colorado', 'rounded', 'open'),
('Stolen Throne', 'Deposed', 'Toro', 'Honduras', 'Honduras Habano', 'Honduras', ARRAY['Honduras', 'Nicaragua'], 3, 'Honduras', ARRAY['leather', 'earth', 'pepper', 'cedar', 'dark fruit'], 'Stolen Throne Deposed Toro — the flagship boutique blend in a longer, cooler-smoking format. Honduran Habano wrapper with Nicaraguan accents.', '$$', 54, 6.0, 'Toro', 'Stolen Throne', 'Toro', 'colorado', 'rounded', 'open'),
('Stolen Throne', 'Deposed', 'Churchill', 'Honduras', 'Honduras Habano', 'Honduras', ARRAY['Honduras', 'Nicaragua'], 3, 'Honduras', ARRAY['leather', 'earth', 'pepper', 'cedar', 'dark fruit'], 'The longest format in the Stolen Throne lineup — a generous Churchill that allows the Honduran blend to fully mature and reveal its complexity.', '$$', 48, 7.0, 'Churchill', 'Stolen Throne', 'Churchill', 'colorado', 'rounded', 'open');
