-- 074_lca_cigar_buddha_seed.sql
-- Tre LCA-eksklusive (Limited Cigar Association) sigarer som fantes hos
-- The Cigar Buddha, men manglet i vår katalog. Spess hentet fra produktsidene.
-- Merk: dette er begrensede LCA-slipp — reelle merker vi allerede fører
-- brand-messig (Cavalier Genève, Asylum, Aganorsa Leaf), men disse linjene manglet.

insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('Cavalier Genève','Cavalier Genève','Paca','Toro','Toro',50,5.0,'Parejo',null,null,null,null,'Habano','Connecticut',array['Nicaragua','Peru'],'Honduras',3,'$12-14','LCA-eksklusiv gjenutgivelse av Cavalier Genèves «Paca». En forseglet allokering med tre års lagring ble funnet i fabrikkjelleren; bandet bærer en stripe ekte paca-tekstil fra burlappen bladene hvilte på. Plasencia-tobakk i kjernen, honduransk håndverk og den karakteristiske gullfolie-diamanten. Habano-dekkblad, Connecticut-omslag, nicaraguansk og peruansk fyll. Medium, med sedertre, graham-søthet, lær og espresso.',array['cedar','graham cracker','leather','dried cherry','espresso','cocoa']),
('Christian Eiroa','Asylum','Straight Jacket Revival','Toro','Toro',52,6.0,'Parejo',null,null,null,'Honduras','Corojo (Cuban Seed)','Honduran',array['Honduras'],'Honduras',5,'$12','Legendariske Asylum Straight Jacket er tilbake som LCA-eksklusiv (2024) etter at linja ble lagt ned i 2022. En honduransk puro bygget på en ny avling av original Eiroa cubansk-frø Corojo — hentet fra Cuba før mugg tvang fram hybridfrø. Fullkroppet kraftpakke fra Eiroa-familien i ny 6×52 toro med revidert band. Pepper, lær, jord og sedertre.',array['black pepper','leather','earth','cedar','espresso']),
('Aganorsa Leaf','Aganorsa Leaf','Golden Locket','Toro','Toro',52,6.0,'Parejo',null,null,null,'Nicaragua','Corojo 99','Criollo',array['Nicaragua'],'Nicaragua',4,'$12-13','LCA-eksklusiv 6×52 toro, to års lagring, 100% nicaraguansk tobakk fra Aganorsas egne gårder. Corojo 99-dekkblad, Criollo-omslag og fyll fra Condega, Jalapa og Estelí. Blandingen inkluderer et nyutviklet «golden»-blad kjent for rik, gyllen smak. Medium til fullkroppet med sedertre, muskat, kremet sødme og krydder.',array['cedar','nutmeg','cream','earth','sweet spice']);
