-- 076_nordic_cigars_illusione_romacraft_lagalera_fratello.sql
-- Kjente boutique-merker fra Nordic Cigars som manglet: illusione, RoMa Craft, La Galera, Fratello.
-- Flaggskip-linjer med verifiserte specs (kilde: kjente blandinger + Nordic Cigars produktsider).

insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('Illusione Cigars','Illusione','Original Documents','888','Churchill',48,6.5,'Parejo',null,null,null,'Nicaragua','Corojo ''99','Nicaragua',array['Nicaragua'],'Nicaragua',4,null,'illusione ~OD (Original Documents) er husets kjerne — nicaraguansk puro produsert på TABSA. Corojo ''99-dekkblad, middels til fullkroppet med sedertre, hvit pepper og en tørr, urteaktig kompleksitet. «888» er den populære Churchill-vitolaen.',array['cedar','white pepper','cocoa','earth','hay']),
('Illusione Cigars','Illusione','Rothchildes','Robusto','Robusto',50,4.5,'Parejo',null,null,null,'Mexico','San Andrés Maduro','Nicaragua',array['Nicaragua'],'Nicaragua',3,null,'Rothchildes er en rimelig, kort robusto med meksikansk San Andrés-dekkblad over nicaraguansk innmat. Middels med kakao, kaffe og søt krydder — en populær hverdagsrøyk.',array['cocoa','coffee','sweet spice','earth']),
('Illusione Cigars','Illusione','Rothchildes Connecticut','Robusto','Robusto',50,4.5,'Parejo',null,null,null,'Ecuador','Connecticut','Nicaragua',array['Nicaragua'],'Nicaragua',2,null,'Connecticut-utgaven av Rothchildes: ecuadoriansk Connecticut-dekkblad over nicaraguansk innmat. Mild til middels, kremet med sedertre og muskat.',array['cream','cedar','nutmeg','hay']),
('Illusione Cigars','Illusione','Epernay','Le Grand','Toro',48,6.0,'Parejo',null,null,null,'Nicaragua','Corojo ''99','Nicaragua',array['Nicaragua'],'Nicaragua',3,null,'Epernay er illusiones elegante, balanserte linje — nicaraguansk puro med Corojo ''99-dekkblad. Kremet og forfinet med sedertre, mandel og et floralt preg.',array['cedar','cream','almond','floral','white pepper']),
('Illusione Cigars','Illusione','Fume d''Amour','Clementes','Churchill',48,6.5,'Parejo',null,null,null,'Nicaragua','Corojo','Nicaragua',array['Nicaragua'],'Nicaragua',4,null,'Fumé d''Amour bruker eldet nicaraguansk tobakk (puro) for en rund, moden profil med sedertre, lær, kaffe og søt krydder.',array['cedar','leather','coffee','sweet spice']),
('Illusione Cigars','Illusione','Maduro','888','Churchill',48,6.5,'Parejo',null,null,null,'Mexico','San Andrés Maduro','Nicaragua',array['Nicaragua'],'Nicaragua',4,null,'Maduro-versjonen av illusione med mørkt meksikansk San Andrés-dekkblad over nicaraguansk innmat. Fyldig med mørk sjokolade, espresso og svart pepper.',array['dark chocolate','espresso','black pepper','earth']),
('RoMa Craft Tobac','CroMagnon','CroMagnon','EMH','Corona Gorda',46,5.5,'Parejo',null,null,null,'Cameroon','Cameroon','Connecticut Broadleaf',array['Nicaragua','Dominican Republic','USA'],'Nicaragua',5,null,'CroMagnon er RoMa Crafts flaggskip — cameroun-dekkblad, Connecticut Broadleaf-omslag og en fyldig blanding av nicaraguansk, dominikansk og Pennsylvania-tobakk. Kraftig med jord, lær, mørk sjokolade og pepper.',array['earth','leather','dark chocolate','black pepper','coffee']),
('RoMa Craft Tobac','CroMagnon','Aquitaine','Mode 5','Robusto',50,5.0,'Parejo',null,null,null,'Ecuador','Habano H-2000','Connecticut Broadleaf',array['Nicaragua','Dominican Republic','USA'],'Nicaragua',5,null,'Aquitaine deler CroMagnons innmat, men med et ecuadoriansk Habano-dekkblad (H-2000). Kraftig og krydret med pepper, sedertre og espresso.',array['black pepper','cedar','earth','cocoa','espresso']),
('RoMa Craft Tobac','Intemperance','Intemperance BA XXI','Whiskey Rebellion','Corona',46,5.5,'Parejo',null,null,null,'Ecuador','Habano','Nicaragua',array['Nicaragua'],'Nicaragua',3,null,'Intemperance BA XXI er en middels, tilgjengelig blanding med ecuadoriansk Habano-dekkblad over nicaraguansk innmat. Sedertre, søt krydder og nøtter.',array['cedar','sweet spice','nuts','cream']),
('RoMa Craft Tobac','Intemperance','Intemperance EC XVIII','Virtue','Corona',46,5.5,'Parejo',null,null,null,'Ecuador','Connecticut','Nicaragua',array['Nicaragua'],'Nicaragua',2,null,'EC XVIII er den mildere Connecticut-varianten av Intemperance — kremet og myk med sedertre, høy og mandel.',array['cream','cedar','hay','almond']),
('RoMa Craft Tobac','Neanderthal','Neanderthal','HN','Petit Robusto',52,4.75,'Parejo',null,null,null,null,null,'Connecticut Broadleaf',array['Nicaragua','USA'],'Nicaragua',5,null,'Neanderthal er beryktet ekstremt fullkroppet, med rikelig Pennsylvania-ligero i innmaten. Kraftig jord, lær, svart pepper og mørk sjokolade — kun for erfarne røykere.',array['black pepper','earth','leather','dark chocolate']),
('Tabacalera Palma','La Galera','Habano','Coloso','Gordo',60,8.0,'Parejo',null,null,null,'Ecuador','Habano','Dominican',array['Dominican Republic'],'Dominican Republic',3,null,'La Galera Habano fra Tabacalera Palma (Jochy Blanco) i Den dominikanske republikk — ecuadoriansk Habano-dekkblad over dominikansk innmat. Middels med sedertre, kaffe og søt krydder.',array['cedar','coffee','sweet spice','earth','nuts']),
('Tabacalera Palma','La Galera','Maduro','Coloso','Gordo',60,8.0,'Parejo',null,null,null,'USA','Connecticut Broadleaf','Dominican',array['Dominican Republic'],'Dominican Republic',4,null,'La Galera Maduro bruker et mørkt Connecticut Broadleaf-dekkblad over dominikansk innmat. Middels til fullkroppet med kakao, espresso og pepper.',array['cocoa','espresso','black pepper','earth']),
('Tabacalera Palma','La Galera','Habano','Half Corona','Petit Corona',46,3.5,'Parejo',null,null,null,'Ecuador','Habano','Dominican',array['Dominican Republic'],'Dominican Republic',3,null,'En kort halv corona av La Galera Habano — samme balanserte dominikanske blanding i et raskt format.',array['cedar','coffee','sweet spice','nuts']),
('Fratello Cigars','Fratello','Fratello','Toro','Toro',54,6.0,'Parejo',null,null,null,'Ecuador','Habano','Cameroon',array['Nicaragua','Peru'],'Nicaragua',4,null,'Fratello (Omar de Frias) — ecuadoriansk Habano-dekkblad, cameroun-omslag og nicaraguansk/peruansk innmat. Middels til fullkroppet med sedertre, kaffe, pepper og lær.',array['cedar','coffee','black pepper','leather','cocoa']),
('Fratello Cigars','Fratello','Navetta','Robusto','Robusto',52,5.0,'Parejo',null,null,null,'Ecuador','Habano Oscuro','Nicaragua',array['Nicaragua','Peru'],'Nicaragua',5,null,'Navetta er Fratellos fyldigste linje — mørkt ecuadoriansk Habano Oscuro-dekkblad. Kraftig med espresso, mørk sjokolade, svart pepper og jord.',array['espresso','dark chocolate','black pepper','earth']),
('Fratello Cigars','Fratello','Bianco','Robusto','Robusto',50,5.0,'Parejo',null,null,null,'Ecuador','Connecticut','Ecuador',array['Nicaragua','Peru'],'Nicaragua',2,null,'Bianco er den milde Connecticut-linjen fra Fratello — kremet og myk med sedertre, muskat og høy.',array['cream','cedar','nutmeg','hay']);
