-- 078_nordic_sinistro_elartista_principle_eladiodiaz.sql
-- Flere kjente Nordic Cigars-merker: El Artista (Big Papi), Principle, Sinistro, Eladio Diaz.
-- Specs fyllt der de er kjente; tomme felt der blandingen ikke er offentlig bekreftet.

insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('Tabacalera El Artista','El Artista','Big Papi','Slugger Robusto','Robusto',50,5.0,'Parejo',null,null,null,'Ecuador','Habano','Dominican',array['Dominican Republic','Nicaragua'],'Dominican Republic',4,null,'Big Papi av El Artista (oppkalt etter David Ortiz) lages av Tabacalera El Artista i Den dominikanske republikk. Ecuadoriansk Habano-dekkblad over dominikansk og nicaraguansk innmat. Middels til fullkroppet.',array['cedar','coffee','black pepper','cocoa']),
('Tabacalera El Artista','El Artista','Big Papi','Toro','Toro',54,6.0,'Parejo',null,null,null,'Ecuador','Habano','Dominican',array['Dominican Republic','Nicaragua'],'Dominican Republic',4,null,'Big Papi i Toro-format — ecuadoriansk Habano-dekkblad, dominikansk/nicaraguansk innmat. Middels til fullkroppet med sedertre, kaffe og pepper.',array['cedar','coffee','black pepper','cocoa']),
('Tabacalera El Artista','El Artista','Big Papi Maduro','Slugger','Gordo',60,7.0,'Parejo',null,null,null,'Mexico','San Andrés Maduro','Dominican',array['Dominican Republic','Nicaragua'],'Dominican Republic',4,null,'Maduro-utgaven av Big Papi med mørkt meksikansk San Andrés-dekkblad. Fyldig med mørk sjokolade, espresso og pepper.',array['dark chocolate','espresso','black pepper','earth']),
('Principle Cigars','Principle','Aviator Series','Toro','Toro',52,6.0,'Parejo',null,null,null,null,null,null,array['Dominican Republic'],'Dominican Republic',4,null,'Aviator er Principles flaggskip — nominert til beste boutique-merke i Den dominikanske republikk. Middels til fullkroppet, balansert og forfinet.',array['cedar','leather','coffee','sweet spice']),
('Principle Cigars','Principle','Accomplice Classic','Toro','Toro',52,6.0,'Parejo',null,null,null,'Ecuador','Habano',null,array['Dominican Republic'],'Dominican Republic',3,null,'Accomplice Classic med ecuadoriansk Habano-dekkblad — middels, kremet og balansert med sedertre og nøtter.',array['cedar','cream','nuts','coffee']),
('Principle Cigars','Principle','Accomplice Maduro','Robusto','Robusto',50,5.0,'Parejo',null,null,null,'Mexico','San Andrés Maduro',null,array['Dominican Republic'],'Dominican Republic',4,null,'Accomplice Maduro med meksikansk San Andrés-dekkblad — fyldigere med kakao, espresso og pepper.',array['cocoa','espresso','black pepper','earth']),
('Principle Cigars','Principle','Frothy Monkey','Signature','Petit Corona',40,5.0,'Parejo',null,null,null,null,null,null,array['Dominican Republic'],'Dominican Republic',3,null,'Frothy Monkey er en liten, kaffevennlig sigar fra Principle — mild til middels.',array['coffee','cream','cedar','sweet spice']),
('Sinistro Cigars','Sinistro','Mr. White','Robusto','Robusto',50,5.0,'Parejo',null,null,null,'Ecuador','Habano',null,null,'Costa Rica',3,null,'Sinistro Mr. White — ecuadoriansk dekkblad, middels og tilgjengelig. Sedertre, kremet og krydder.',array['cedar','cream','sweet spice','nuts']),
('Sinistro Cigars','Sinistro','Mr. Black','Robusto','Robusto',50,5.0,'Parejo',null,null,null,null,null,null,null,'Costa Rica',4,null,'Sinistro Mr. Black — mørkere og fyldigere enn Mr. White, med lær, kaffe og pepper.',array['leather','coffee','black pepper','earth']),
('Sinistro Cigars','Sinistro','Mr. Red','Robusto','Robusto',50,5.0,'Parejo',null,null,null,null,'Maduro',null,null,'Costa Rica',4,null,'Sinistro Mr. Red — maduro-dekkblad, fyldig med mørk sjokolade, espresso og søt krydder.',array['dark chocolate','espresso','sweet spice','earth']),
('Sinistro Cigars','Sinistro','Mr. Sinistro','Toro','Toro',56,6.5,'Parejo',null,null,null,null,null,null,null,'Costa Rica',4,null,'Mr. Sinistro er husets signatur i et fyldig 56x6,5-format — fullkroppet med lær, jord og pepper.',array['leather','earth','black pepper','cocoa']),
('La Aurora','Eladio Diaz','La Diana','Robusto','Robusto',52,5.0,'Parejo',null,null,null,null,null,null,array['Dominican Republic'],'Dominican Republic',4,null,'Eladio Diaz er La Auroras legendariske mesterblander; La Diana er hans personlige blanding laget hos La Aurora i Den dominikanske republikk. Middels til fullkroppet og balansert.',array['cedar','coffee','leather','sweet spice']);
