-- 079_artista.sql
-- Tabacalera Artista (Ram Rodriguez) fra Nordic Cigars.

insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values
('Tabacalera Artista','Artista','Exactus Maduro','Robusto','Robusto',54,5.0,'Parejo',null,null,null,null,'Maduro',null,null,null,4,null,'Artista Exactus (Ram Rodriguez) — inspirert av bestefaren Don Pulitas kreasjoner fra 50-tallet, med et moderne, silkemykt preg. Maduro-utgaven er fyldig med mørk sjokolade og kaffe.',array['dark chocolate','coffee','black pepper','earth']),
('Tabacalera Artista','Artista','Exactus Connecticut Shade','Robusto','Robusto',54,5.0,'Parejo',null,null,null,'Ecuador','Connecticut Shade',null,null,null,2,null,'Artista Exactus Clásico med Connecticut Shade-dekkblad — mild og kremet med sedertre og nøtter.',array['cream','cedar','nuts','hay']),
('Tabacalera Artista','Artista','Colorado','Wide Robusto','Robusto',54,5.0,'Parejo',null,null,null,null,'Colorado',null,null,null,3,null,'Artista Colorado Wide Robusto — medium styrke, smaksrik og balansert. Fabrikken oppgir ikke innmat utover at tobakken kommer fra flere land.',array['cedar','coffee','sweet spice','leather']),
('Tabacalera Artista','Artista','Limited 1.4','Toro Bokspress','Toro',50,6.0,'Parejo',null,null,null,null,null,null,null,null,4,null,'Artista Limited 1.4 — box-pressed toro, først lansert på PCA 2025 i en samplerboks sammen med Falu, Harvest og Midnight. Svært begrenset opplag.',array['cedar','leather','black pepper','cocoa']),
('Tabacalera Artista','Artista','Club Mini','Rustico','Cigarillo',27,4.0,'Parejo',null,null,null,null,null,null,null,null,3,null,'Artista Club Mini — små sigarillos for lomma (20 pk). Rustico er den mørkeste, fyldigste varianten.',array['cedar','coffee','earth']),
('Tabacalera Artista','Artista','Club Mini','Claro','Cigarillo',27,4.0,'Parejo',null,null,null,null,null,null,null,null,2,null,'Artista Club Mini Claro — lys, mild sigarillo for lomma (20 pk).',array['cedar','cream','hay']),
('Tabacalera Artista','Artista','Club Mini','Oscuro','Cigarillo',27,4.0,'Parejo',null,null,null,null,null,null,null,null,3,null,'Artista Club Mini Oscuro — mørk, fyldigere sigarillo for lomma (20 pk).',array['cocoa','coffee','earth']);
