-- 082_german_engineered_cigars.sql
-- German Engineered Cigars (GEC) — grunnlagt 2016 i Hamburg.
-- Blendes etter en «aromatisk reise» som designes først; tobakken velges etterpå.
-- Rulles i Den dominikanske republikk og Nicaragua. Kilde: cigarengineers.com
--
-- 5 blends × 16 vitolaer.
-- Idempotent: fjerner ev. eksisterende GEC-rader før innsett.

delete from cigars where brand = 'German Engineered Cigars';

insert into cigars (manufacturer, brand, series, vitola, common_format, ring_gauge, length_inches, shape, body_type, head_type, foot_type, wrapper_country, wrapper_leaf, binder, filler, country_origin, strength, price_range, description, flavor_notes) values

-- ── RVGN «Rauchvergnügen» — Dominikansk, medium ─────────────────────────────
('German Engineered Cigars','German Engineered Cigars','RVGN Rauchvergnügen','Panatela','Panatela',38,5.0,'Parejo',null,null,null,'Ecuador','Ecuador Hybrid Seed','Dominican Criollo 98',array['Dominican Republic','Nicaragua','United States'],'Dominican Republic',3,null,'RVGN Rauchvergnügen i slankt panatela-format. Den aromatiske reisen: full fart rundt Nürburgring i åpen racerbil en strålende morgen. Sedertre, alpeurter, mynte og fuktig skog med torv, kaffe og ingefær.',array['cedar','hay','coffee','spice','pepper','earth']),
('German Engineered Cigars','German Engineered Cigars','RVGN Rauchvergnügen','Robusto','Robusto',50,5.25,'Parejo',null,null,null,'Ecuador','Ecuador Hybrid Seed','Dominican Criollo 98',array['Dominican Republic','Nicaragua','United States'],'Dominican Republic',3,null,'RVGN Rauchvergnügen Robusto — merkets mest kjøpte format. Sjokoladeaktig dekkblad, kald trekk av høy og mynte, og en røyk av sedertre, alpeurter og fuktig skog med torv, kaffe og Szechuan-pepper.',array['cedar','hay','coffee','spice','pepper','earth']),
('German Engineered Cigars','German Engineered Cigars','RVGN Rauchvergnügen','Toro','Toro',52,6.25,'Parejo',null,null,null,'Ecuador','Ecuador Hybrid Seed','Dominican Criollo 98',array['Dominican Republic','Nicaragua','United States'],'Dominican Republic',3,null,'RVGN Rauchvergnügen Toro. Lengre brennetid gir blenden rom til å utfolde seg: sedertre, alpeurter, mynte, torv, kaffe og et snev av ingefær.',array['cedar','hay','coffee','spice','pepper','earth']),
('German Engineered Cigars','German Engineered Cigars','RVGN Rauchvergnügen','Gordo','Gordo',60,6.0,'Parejo',null,null,null,'Ecuador','Ecuador Hybrid Seed','Dominican Criollo 98',array['Dominican Republic','Nicaragua','United States'],'Dominican Republic',3,null,'RVGN Rauchvergnügen Gordo. Tykt format, kjølig trekk og fyldigere innmatsuttrykk — sedertre, urter, kaffe og pepper.',array['cedar','hay','coffee','spice','pepper','earth']),

-- ── RVGN Extrem — Dominikansk, medium (mørkere, mer intens) ─────────────────
('German Engineered Cigars','German Engineered Cigars','RVGN Extrem','Short Robusto','Robusto',50,4.0,'Parejo',null,null,null,'Mexico','Mexican Undisclosed Seed','Olor Dominicano Carbonel',array['Dominican Republic','Nicaragua'],'Dominican Republic',3,null,'RVGN Extrem Short Robusto. Den aromatiske reisen: å lede løpet på Nürburgring i regn. Achtung Nordschleife! Eik, alpeurter, vått lær, furuskog, espresso, mørk kakao, kirsebær og hvit pepper.',array['oak','leather','espresso','dark cocoa','fruit','white pepper']),
('German Engineered Cigars','German Engineered Cigars','RVGN Extrem','Toro','Toro',52,6.25,'Parejo',null,null,null,'Mexico','Mexican Undisclosed Seed','Olor Dominicano Carbonel',array['Dominican Republic','Nicaragua'],'Dominican Republic',3,null,'RVGN Extrem Toro. Dekkblad med friskhet, honning og mynte; kald trekk av lavendel og vått gress. Røyken gir eik, vått lær, furuskog, espresso, mørk kakao og hvit pepper.',array['oak','leather','espresso','dark cocoa','fruit','white pepper']),

-- ── Raumzeit — Nicaraguansk, mild til medium ────────────────────────────────
('German Engineered Cigars','German Engineered Cigars','Raumzeit','Panatela','Panatela',37,5.0,'Parejo',null,null,null,'Nicaragua','Nicaraguan Connecticut','Indonesian Sumatra',array['Nicaragua','Dominican Republic'],'Nicaragua',2,null,'Raumzeit Panatela. Den aromatiske reisen: reise i lysets hastighet forbi neste galakse, mens en vennlig android serverer kake. Nøtter, fløte, honning og malt med hvit pepper, mineraler og nellik.',array['nuts','cream','honey','white pepper','minerals','spice']),
('German Engineered Cigars','German Engineered Cigars','Raumzeit','Robusto','Robusto',50,5.25,'Parejo',null,null,null,'Nicaragua','Nicaraguan Connecticut','Indonesian Sumatra',array['Nicaragua','Dominican Republic'],'Nicaragua',2,null,'Raumzeit Robusto. Lyst, silkeaktig dekkblad med honning og fløte. Kald trekk av tørre blader, bjørkebark og valnøtt. Røyk av nøtter, fløte, honning, malt, hvit pepper, mineraler og muskat.',array['nuts','cream','honey','white pepper','minerals','spice']),
('German Engineered Cigars','German Engineered Cigars','Raumzeit','Torpedo','Torpedo',52,6.25,'Figurado','Torpedo','Pointed',null,'Nicaragua','Nicaraguan Connecticut','Indonesian Sumatra',array['Nicaragua','Dominican Republic'],'Nicaragua',2,null,'Raumzeit Torpedo. Spiss hode gir konsentrert trekk og mer dekkblad mot ganen. Nøtter, fløte, honning og malt med hvit pepper, mineraler og nellik.',array['nuts','cream','honey','white pepper','minerals','spice']),
('German Engineered Cigars','German Engineered Cigars','Raumzeit','Gordo','Gordo',60,6.0,'Parejo',null,null,null,'Nicaragua','Nicaraguan Connecticut','Indonesian Sumatra',array['Nicaragua','Dominican Republic'],'Nicaragua',2,null,'Raumzeit Gordo. Bredt format, kjølig og langsom brenning. Nøtter, fløte, honning og malt, med mineraler og et snev av muskat.',array['nuts','cream','honey','white pepper','minerals','spice']),

-- ── Weltschmerz — Nicaraguansk, medium ──────────────────────────────────────
('German Engineered Cigars','German Engineered Cigars','Weltschmerz','Panatela','Panatela',37,5.0,'Parejo',null,null,null,'Ecuador','Ecuador Habano Oscuro','Nicaraguan Jalapa',array['Nicaragua'],'Nicaragua',3,null,'Weltschmerz Panatela. Den aromatiske reisen: tilbake i barndommens landskap, ovnen fortsatt varm. Grønt gress, hasselnøtter, toast, mineraler og rå eik med vanilje og blåbær.',array['grass','nuts','toast','minerals','oak','vanilla','fruit','chocolate']),
('German Engineered Cigars','German Engineered Cigars','Weltschmerz','Robusto','Robusto',50,5.25,'Parejo',null,null,null,'Ecuador','Ecuador Habano Oscuro','Nicaraguan Jalapa',array['Nicaragua'],'Nicaragua',3,null,'Weltschmerz Robusto. Mahogni, stall og litt lavendel i dekkbladet; kald trekk av sjokolade, rosiner og kandisert appelsin. Røyk av gress, hasselnøtter, toast, mineraler, rå eik, vanilje og blåbær.',array['grass','nuts','toast','minerals','oak','vanilla','fruit','chocolate']),
('German Engineered Cigars','German Engineered Cigars','Weltschmerz','Perfecto','Perfecto',54,5.0,'Figurado','Perfecto','Pointed','Tapered','Ecuador','Ecuador Habano Oscuro','Nicaraguan Jalapa',array['Nicaragua'],'Nicaragua',3,null,'Weltschmerz Perfecto. Innsnevret i begge ender — smaksbildet endrer seg tydelig gjennom røyken. Hasselnøtter, toast, mineraler, rå eik, vanilje og blåbær.',array['grass','nuts','toast','minerals','oak','vanilla','fruit','chocolate']),
('German Engineered Cigars','German Engineered Cigars','Weltschmerz','Toro','Toro',52,6.25,'Parejo',null,null,null,'Ecuador','Ecuador Habano Oscuro','Nicaraguan Jalapa',array['Nicaragua'],'Nicaragua',3,null,'Weltschmerz Toro. Ecuadoriansk Habano Oscuro over nicaraguansk innmat fra Estelí og Jalapa. Gress, sandjord, hasselnøtter, toast, mineraler og rå eik med vanilje, blåbær og ristede valnøtter.',array['grass','nuts','toast','minerals','oak','vanilla','fruit','chocolate']),

-- ── Kraftwerk — Dominikansk, full ───────────────────────────────────────────
('German Engineered Cigars','German Engineered Cigars','Kraftwerk','Short Robusto','Robusto',50,4.0,'Parejo',null,null,null,'Mexico','Mexican San Andrés','Mexican San Andrés',array['Dominican Republic'],'Dominican Republic',5,null,'Kraftwerk Short Robusto. Den aromatiske reisen: inn i en gigantisk maskinhall, omgitt av brøl og enorm energi. Noen spiller techno med krydder. Mørkt tre, kull, sort pepper, espresso og mørk sjokolade.',array['wood','black pepper','espresso','dark chocolate','anise','nuts','vanilla','cardamom','dried fruit','earth']),
('German Engineered Cigars','German Engineered Cigars','Kraftwerk','Robusto','Robusto',50,5.25,'Parejo',null,null,null,'Mexico','Mexican San Andrés','Mexican San Andrés',array['Dominican Republic'],'Dominican Republic',5,null,'Kraftwerk Robusto — merkets fyldigste blend. Meksikansk San Andrés som dekkblad og omblad over dominikansk Piloto, Olor og Corojo. Mørkt tre, kull, sort pepper, espresso og mørk sjokolade med anis, valnøtt, vanilje, kardemomme, tørkede kirsebær og chili-varme.',array['wood','black pepper','espresso','dark chocolate','anise','nuts','vanilla','cardamom','dried fruit','earth']);
