-- 135: Topp-10 manglende premiummerker (batch 1) fra masterliste-kryssjekk 2026.
-- Blend fra produsentens egen side der publisert; størrelser fra produsent ELLER
-- presse/forhandler (da source_tier='retailer'). Tomme felt der produsenten ikke
-- oppgir data (f.eks. El Septimo publiserer ikke dekkblad) — tomt slår gjetning.
-- Opphavsland satt per linje der det avviker fra merket. Kun faste/kjerne-linjer.

-- Graycliff
INSERT INTO public.cigars
  (brand, series, vitola, wrapper_country, wrapper_leaf, binder, filler, strength,
   country_origin, manufacturer, shape, common_format, description, is_public,
   source_tier, source_url, verified_at, aliases)
VALUES
('Graycliff', 'Original', 'Robusto', 'Ecuador', 'Sumatra', 'Indonesian', ARRAY['Dominican','Nicaraguan','Brazilian','Honduran'], 3, 'Honduras', 'Graycliff Cigar Company', 'Parejo', 'Robusto', 'En balansert mellomsterk sigar med Sumatra-dekkblad og fyll fra flere land, med toner av lær, ristede nøtter og krydder.', true, 'retailer', 'https://www.holts.com/cigars/all-cigar-brands/graycliff-original.html', now(), ARRAY['Graycliff']),
('Graycliff', 'Original', 'Toro', 'Ecuador', 'Sumatra', 'Indonesian', ARRAY['Dominican','Nicaraguan','Brazilian','Honduran'], 3, 'Honduras', 'Graycliff Cigar Company', 'Parejo', 'Toro', 'En balansert mellomsterk sigar med Sumatra-dekkblad og fyll fra flere land, med toner av lær, ristede nøtter og krydder.', true, 'retailer', 'https://www.holts.com/cigars/all-cigar-brands/graycliff-original.html', now(), ARRAY['Graycliff']),
('Graycliff', 'Original', 'Torpedo', 'Ecuador', 'Sumatra', 'Indonesian', ARRAY['Dominican','Nicaraguan','Brazilian','Honduran'], 3, 'Honduras', 'Graycliff Cigar Company', 'Figurado', 'Torpedo', 'En balansert mellomsterk sigar med Sumatra-dekkblad og fyll fra flere land, med toner av lær, ristede nøtter og krydder.', true, 'retailer', 'https://www.holts.com/cigars/all-cigar-brands/graycliff-original.html', now(), ARRAY['Graycliff']),
('Graycliff', 'Original', 'Presidente', 'Ecuador', 'Sumatra', 'Indonesian', ARRAY['Dominican','Nicaraguan','Brazilian','Honduran'], 3, 'Honduras', 'Graycliff Cigar Company', 'Parejo', 'Presidente', 'En balansert mellomsterk sigar med Sumatra-dekkblad og fyll fra flere land, med toner av lær, ristede nøtter og krydder.', true, 'retailer', 'https://www.holts.com/cigars/all-cigar-brands/graycliff-original.html', now(), ARRAY['Graycliff']),
('Graycliff', 'Profesionale', 'Robusto', 'Ecuador', 'Sumatra', 'Sumatra', ARRAY['Brazilian','Dominican','Honduran','Nicaraguan'], 3, 'Honduras', 'Graycliff Cigar Company', 'Parejo', 'Robusto', 'En mellomsterk sigar med ecuadoriansk Sumatra-dekkblad og fyll fra fire land — Graycliffs mest tilgjengelige serie.', true, 'retailer', 'https://www.cigar.com/product/graycliff-profesionale-series/G1B-PM.html', now(), ARRAY['Graycliff']),
('Graycliff', 'Profesionale', 'Toro', 'Ecuador', 'Sumatra', 'Sumatra', ARRAY['Brazilian','Dominican','Honduran','Nicaraguan'], 3, 'Honduras', 'Graycliff Cigar Company', 'Parejo', 'Toro', 'En mellomsterk sigar med ecuadoriansk Sumatra-dekkblad og fyll fra fire land — Graycliffs mest tilgjengelige serie.', true, 'retailer', 'https://www.cigar.com/product/graycliff-profesionale-series/G1B-PM.html', now(), ARRAY['Graycliff']),
('Graycliff', 'Profesionale', 'Torpedo', 'Ecuador', 'Sumatra', 'Sumatra', ARRAY['Brazilian','Dominican','Honduran','Nicaraguan'], 3, 'Honduras', 'Graycliff Cigar Company', 'Figurado', 'Torpedo', 'En mellomsterk sigar med ecuadoriansk Sumatra-dekkblad og fyll fra fire land — Graycliffs mest tilgjengelige serie.', true, 'retailer', 'https://www.cigar.com/product/graycliff-profesionale-series/G1B-PM.html', now(), ARRAY['Graycliff']),
('Graycliff', 'Profesionale', 'Presidente', 'Ecuador', 'Sumatra', 'Sumatra', ARRAY['Brazilian','Dominican','Honduran','Nicaraguan'], 3, 'Honduras', 'Graycliff Cigar Company', 'Parejo', 'Presidente', 'En mellomsterk sigar med ecuadoriansk Sumatra-dekkblad og fyll fra fire land — Graycliffs mest tilgjengelige serie.', true, 'retailer', 'https://www.cigar.com/product/graycliff-profesionale-series/G1B-PM.html', now(), ARRAY['Graycliff']),
('Graycliff', 'Crystal', 'Taco', 'Ecuador', 'Habano', 'Greek', ARRAY['Nicaraguan','Honduran'], 2, 'Bahamas', 'Graycliff Cigar Company', 'Parejo', 'Taco', 'En mild til mellomsterk sigar med ecuadoriansk Habano-dekkblad og lagret tobakk som gir en myk profil med lær, honning og vanilje.', true, 'retailer', 'https://www.cigarsdirect.com/blogs/cigar-aficionado/cigar-spotlight-graycliff-crystal', now(), ARRAY['Graycliff']),
('Graycliff', 'Crystal', 'Robusto', 'Ecuador', 'Habano', 'Greek', ARRAY['Nicaraguan','Honduran'], 2, 'Bahamas', 'Graycliff Cigar Company', 'Parejo', 'Robusto', 'En mild til mellomsterk sigar med ecuadoriansk Habano-dekkblad og lagret tobakk som gir en myk profil med lær, honning og vanilje.', true, 'retailer', 'https://www.cigarsdirect.com/blogs/cigar-aficionado/cigar-spotlight-graycliff-crystal', now(), ARRAY['Graycliff']),
('Graycliff', 'Crystal', 'Toro', 'Ecuador', 'Habano', 'Greek', ARRAY['Nicaraguan','Honduran'], 2, 'Bahamas', 'Graycliff Cigar Company', 'Parejo', 'Toro', 'En mild til mellomsterk sigar med ecuadoriansk Habano-dekkblad og lagret tobakk som gir en myk profil med lær, honning og vanilje.', true, 'retailer', 'https://www.cigarsdirect.com/blogs/cigar-aficionado/cigar-spotlight-graycliff-crystal', now(), ARRAY['Graycliff']),
('Graycliff', 'Crystal', 'Torpedo', 'Ecuador', 'Habano', 'Greek', ARRAY['Nicaraguan','Honduran'], 2, 'Bahamas', 'Graycliff Cigar Company', 'Figurado', 'Torpedo', 'En mild til mellomsterk sigar med ecuadoriansk Habano-dekkblad og lagret tobakk som gir en myk profil med lær, honning og vanilje.', true, 'retailer', 'https://www.cigarsdirect.com/blogs/cigar-aficionado/cigar-spotlight-graycliff-crystal', now(), ARRAY['Graycliff']),
('Graycliff', 'Crystal', 'Presidente', 'Ecuador', 'Habano', 'Greek', ARRAY['Nicaraguan','Honduran'], 2, 'Bahamas', 'Graycliff Cigar Company', 'Parejo', 'Presidente', 'En mild til mellomsterk sigar med ecuadoriansk Habano-dekkblad og lagret tobakk som gir en myk profil med lær, honning og vanilje.', true, 'retailer', 'https://www.cigarsdirect.com/blogs/cigar-aficionado/cigar-spotlight-graycliff-crystal', now(), ARRAY['Graycliff']),
('Graycliff', 'Espresso', 'Toro', 'Costa Rica', 'Maduro', NULL, ARRAY['Brazilian','Costa Rican','Nicaraguan'], 5, 'Bahamas', 'Graycliff Cigar Company', 'Parejo', 'Toro', 'En fyldig, kaffeinspirert sigar med Costa Rica-maduro-dekkblad og noter av sjokolade, kaffe og pepper.', true, 'retailer', 'https://www.bestcigarprices.com/cigar-directory/graycliff-espresso-cigars/graycliff-espresso-toro-249325/', now(), ARRAY['Graycliff']),
('Graycliff', 'Chateau Grand Cru', 'Toro', 'Costa Rica', 'Habano', 'Ecuadorian', ARRAY['Costa Rican','Honduran','Nicaraguan'], 3, 'Bahamas', 'Graycliff Cigar Company', 'Parejo', 'Toro', 'En elegant mellomsterk sigar med Costa Rica Habano-dekkblad og smaksnoter av fløte, vanilje og ristede nøtter.', true, 'retailer', 'https://www.bestcigarprices.com/cigar-directory/graycliff-chateau-grand-cru-cigars/graycliff-chateau-grand-cru-toro-248282/', now(), ARRAY['Graycliff']),
('Graycliff', 'G2 Habano', 'Robusto', 'Ecuador', 'Habano', 'Nicaraguan', ARRAY['Dominican','Nicaraguan'], 4, 'Nicaragua', 'Graycliff Cigar Company', 'Parejo', 'Robusto', 'En kraftig mellom-til-fyldig sigar med ecuadoriansk Habano-dekkblad og nicaraguansk fyll, med krydder, pepper og jord.', true, 'retailer', 'https://www.cigar.com/product/graycliff-g2-habano/G2H-PM.html', now(), ARRAY['Graycliff']),
('Graycliff', 'G2 Habano', 'Toro', 'Ecuador', 'Habano', 'Nicaraguan', ARRAY['Dominican','Nicaraguan'], 4, 'Nicaragua', 'Graycliff Cigar Company', 'Parejo', 'Toro', 'En kraftig mellom-til-fyldig sigar med ecuadoriansk Habano-dekkblad og nicaraguansk fyll, med krydder, pepper og jord.', true, 'retailer', 'https://www.cigar.com/product/graycliff-g2-habano/G2H-PM.html', now(), ARRAY['Graycliff']),
('Graycliff', 'G2 Habano', 'Gordo', 'Ecuador', 'Habano', 'Nicaraguan', ARRAY['Dominican','Nicaraguan'], 4, 'Nicaragua', 'Graycliff Cigar Company', 'Parejo', 'Gordo', 'En kraftig mellom-til-fyldig sigar med ecuadoriansk Habano-dekkblad og nicaraguansk fyll, med krydder, pepper og jord.', true, 'retailer', 'https://www.cigar.com/product/graycliff-g2-habano/G2H-PM.html', now(), ARRAY['Graycliff']),
('Graycliff', 'G2 Habano', 'Torpedo', 'Ecuador', 'Habano', 'Nicaraguan', ARRAY['Dominican','Nicaraguan'], 4, 'Nicaragua', 'Graycliff Cigar Company', 'Figurado', 'Torpedo', 'En kraftig mellom-til-fyldig sigar med ecuadoriansk Habano-dekkblad og nicaraguansk fyll, med krydder, pepper og jord.', true, 'retailer', 'https://www.cigar.com/product/graycliff-g2-habano/G2H-PM.html', now(), ARRAY['Graycliff']),
('Graycliff', 'G2 Habano', 'Presidente', 'Ecuador', 'Habano', 'Nicaraguan', ARRAY['Dominican','Nicaraguan'], 4, 'Nicaragua', 'Graycliff Cigar Company', 'Parejo', 'Presidente', 'En kraftig mellom-til-fyldig sigar med ecuadoriansk Habano-dekkblad og nicaraguansk fyll, med krydder, pepper og jord.', true, 'retailer', 'https://www.cigar.com/product/graycliff-g2-habano/G2H-PM.html', now(), ARRAY['Graycliff']);

-- El Septimo
INSERT INTO public.cigars
  (brand, series, vitola, wrapper_country, wrapper_leaf, binder, filler, strength,
   country_origin, manufacturer, shape, common_format, description, is_public,
   source_tier, source_url, verified_at, aliases)
VALUES
('El Septimo', 'Zaya', '20th Anniversary Doble Gran Reserva', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Honduras','Costa Rica'], NULL, 'Costa Rica', 'El Septimo Geneva', 'Parejo', '20th Anniversary Doble Gran Reserva', 'En luksuriøs premiumkolleksjon med lagret tobakk i et bredt spekter av fargekodede vitolaer.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/zaya-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Zaya', 'Bomba Orange', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Honduras','Costa Rica'], NULL, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Bomba Orange', 'En luksuriøs premiumkolleksjon med lagret tobakk i et bredt spekter av fargekodede vitolaer.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/zaya-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Zaya', 'Kolosso Amethyst', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Honduras','Costa Rica'], NULL, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Kolosso Amethyst', 'En luksuriøs premiumkolleksjon med lagret tobakk i et bredt spekter av fargekodede vitolaer.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/zaya-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Zaya', 'Mirifico Sapphire', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Honduras','Costa Rica'], NULL, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Mirifico Sapphire', 'En luksuriøs premiumkolleksjon med lagret tobakk i et bredt spekter av fargekodede vitolaer.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/zaya-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Zaya', 'Fabuloso Dark Ruby', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Honduras','Costa Rica'], NULL, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Fabuloso Dark Ruby', 'En luksuriøs premiumkolleksjon med lagret tobakk i et bredt spekter av fargekodede vitolaer.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/zaya-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Zaya', 'Excepcion Esmeralda', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Honduras','Costa Rica'], NULL, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Excepcion Esmeralda', 'En luksuriøs premiumkolleksjon med lagret tobakk i et bredt spekter av fargekodede vitolaer.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/zaya-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Zaya', 'Double Shot White', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Honduras','Costa Rica'], NULL, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Double Shot White', 'En luksuriøs premiumkolleksjon med lagret tobakk i et bredt spekter av fargekodede vitolaer.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/zaya-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Zaya', 'Short Dream Topaz', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Honduras','Costa Rica'], NULL, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Short Dream Topaz', 'En luksuriøs premiumkolleksjon med lagret tobakk i et bredt spekter av fargekodede vitolaer.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/zaya-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Zaya', 'Bullet Black', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Honduras','Costa Rica'], NULL, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Bullet Black', 'En luksuriøs premiumkolleksjon med lagret tobakk i et bredt spekter av fargekodede vitolaer.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/zaya-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Luxus', 'Precioso Pink', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Honduras','Costa Rica'], 2, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Precioso Pink', 'Håndrullede sigarer laget med ti år lagret tobakk, hovedsakelig i mildere og mindre formater.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/luxus-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Luxus', 'Small Impact Green', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Honduras','Costa Rica'], 2, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Small Impact Green', 'Håndrullede sigarer laget med ti år lagret tobakk, hovedsakelig i mildere og mindre formater.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/luxus-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Luxus', 'Bullet Blue', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Honduras','Costa Rica'], 2, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Bullet Blue', 'Håndrullede sigarer laget med ti år lagret tobakk, hovedsakelig i mildere og mindre formater.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/luxus-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Luxus', 'Excepcion White', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Honduras','Costa Rica'], 2, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Excepcion White', 'Håndrullede sigarer laget med ti år lagret tobakk, hovedsakelig i mildere og mindre formater.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/luxus-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Luxus', 'Long Shot Black', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Honduras','Costa Rica'], 2, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Long Shot Black', 'Håndrullede sigarer laget med ti år lagret tobakk, hovedsakelig i mildere og mindre formater.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/luxus-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Luxus', 'Rebelde Blue', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Honduras','Costa Rica'], 2, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Rebelde Blue', 'Håndrullede sigarer laget med ti år lagret tobakk, hovedsakelig i mildere og mindre formater.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/luxus-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Luxus', 'Short Dream Amarillo', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Honduras','Costa Rica'], 2, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Short Dream Amarillo', 'Håndrullede sigarer laget med ti år lagret tobakk, hovedsakelig i mildere og mindre formater.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/luxus-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Luxus', 'Small Sabor Blue', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Honduras','Costa Rica'], 2, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Small Sabor Blue', 'Håndrullede sigarer laget med ti år lagret tobakk, hovedsakelig i mildere og mindre formater.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/luxus-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Luxus', 'Flamingo Amarillo', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Honduras','Costa Rica'], 2, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Flamingo Amarillo', 'Håndrullede sigarer laget med ti år lagret tobakk, hovedsakelig i mildere og mindre formater.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/luxus-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Emperor', 'Empress Sheba Toro', NULL, NULL, NULL, NULL, NULL, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Empress Sheba Toro', 'En bred kolleksjon med både milde Connecticut-blandinger og kraftigere maduro-blandinger.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/emperor-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Emperor', 'King Sargon Maduro Robusto', NULL, NULL, NULL, NULL, NULL, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'King Sargon Maduro Robusto', 'En bred kolleksjon med både milde Connecticut-blandinger og kraftigere maduro-blandinger.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/emperor-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Emperor', 'King Sargon Maduro Churchill', NULL, NULL, NULL, NULL, NULL, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'King Sargon Maduro Churchill', 'En bred kolleksjon med både milde Connecticut-blandinger og kraftigere maduro-blandinger.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/emperor-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Emperor', 'King Sargon Connecticut Robusto', NULL, NULL, NULL, NULL, NULL, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'King Sargon Connecticut Robusto', 'En bred kolleksjon med både milde Connecticut-blandinger og kraftigere maduro-blandinger.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/emperor-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Emperor', 'King Sargon Connecticut Churchill', NULL, NULL, NULL, NULL, NULL, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'King Sargon Connecticut Churchill', 'En bred kolleksjon med både milde Connecticut-blandinger og kraftigere maduro-blandinger.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/emperor-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Emperor', 'Yao Maduro', NULL, NULL, NULL, NULL, NULL, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Yao Maduro', 'En bred kolleksjon med både milde Connecticut-blandinger og kraftigere maduro-blandinger.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/emperor-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Emperor', 'Vartan The Dragon', NULL, NULL, NULL, NULL, NULL, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Vartan The Dragon', 'En bred kolleksjon med både milde Connecticut-blandinger og kraftigere maduro-blandinger.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/emperor-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Emperor', 'Empress Sheba', NULL, NULL, NULL, NULL, NULL, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Empress Sheba', 'En bred kolleksjon med både milde Connecticut-blandinger og kraftigere maduro-blandinger.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/emperor-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Emperor', 'Yao Connecticut', NULL, NULL, NULL, NULL, NULL, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Yao Connecticut', 'En bred kolleksjon med både milde Connecticut-blandinger og kraftigere maduro-blandinger.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/emperor-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Emperor', 'Napoleon Maduro', NULL, NULL, NULL, NULL, NULL, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Napoleon Maduro', 'En bred kolleksjon med både milde Connecticut-blandinger og kraftigere maduro-blandinger.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/emperor-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Emperor', 'Napoleon Connecticut', NULL, NULL, NULL, NULL, NULL, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Napoleon Connecticut', 'En bred kolleksjon med både milde Connecticut-blandinger og kraftigere maduro-blandinger.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/emperor-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Emperor', 'Augustus Connecticut', NULL, NULL, NULL, NULL, NULL, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Augustus Connecticut', 'En bred kolleksjon med både milde Connecticut-blandinger og kraftigere maduro-blandinger.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/emperor-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Sacred Arts', 'Botticelli', NULL, NULL, 'Ecuadorian Habano', ARRAY['Dominican Republic','Ecuador','Nicaragua'], 3, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Botticelli', 'En kunstnerinspirert kolleksjon oppkalt etter renessansens mestere, med sigarer av middels styrke.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/sacred-arts-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Sacred Arts', 'Da Vinci', NULL, NULL, 'Ecuadorian Habano', ARRAY['Dominican Republic','Ecuador','Nicaragua'], 3, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Da Vinci', 'En kunstnerinspirert kolleksjon oppkalt etter renessansens mestere, med sigarer av middels styrke.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/sacred-arts-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Sacred Arts', 'Michelangelo', NULL, NULL, 'Ecuadorian Habano', ARRAY['Dominican Republic','Ecuador','Nicaragua'], 3, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Michelangelo', 'En kunstnerinspirert kolleksjon oppkalt etter renessansens mestere, med sigarer av middels styrke.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/sacred-arts-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Sacred Arts', 'Rembrandt', NULL, NULL, 'Ecuadorian Habano', ARRAY['Dominican Republic','Ecuador','Nicaragua'], 3, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Rembrandt', 'En kunstnerinspirert kolleksjon oppkalt etter renessansens mestere, med sigarer av middels styrke.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/sacred-arts-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Sacred Arts', 'Salvador Dali', NULL, NULL, 'Ecuadorian Habano', ARRAY['Dominican Republic','Ecuador','Nicaragua'], 3, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Salvador Dali', 'En kunstnerinspirert kolleksjon oppkalt etter renessansens mestere, med sigarer av middels styrke.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/sacred-arts-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Sacred Arts', 'Van Gogh', NULL, NULL, 'Ecuadorian Habano', ARRAY['Dominican Republic','Ecuador','Nicaragua'], 3, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Van Gogh', 'En kunstnerinspirert kolleksjon oppkalt etter renessansens mestere, med sigarer av middels styrke.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/sacred-arts-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Sacred Arts', 'Raphael', NULL, NULL, 'Ecuadorian Habano', ARRAY['Dominican Republic','Ecuador','Nicaragua'], 3, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Raphael', 'En kunstnerinspirert kolleksjon oppkalt etter renessansens mestere, med sigarer av middels styrke.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/sacred-arts-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Alexandra', 'Coco Robusto', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Ecuador'], 3, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Coco Robusto', 'En kremet og mild portefølje skapt for den kvinnelige sigarkjenneren.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/alexandra-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Alexandra', 'Marilyn', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Ecuador'], 3, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Marilyn', 'En kremet og mild portefølje skapt for den kvinnelige sigarkjenneren.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/alexandra-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Gilgamesh', 'King Sargon', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Ecuador'], 4, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'King Sargon', 'Kraftige smaker i overraskende små ringmål, oppkalt etter mesopotamiske skikkelser.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/gilgamesh-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Gilgamesh', 'Sable Shamash', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Ecuador'], 4, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Sable Shamash', 'Kraftige smaker i overraskende små ringmål, oppkalt etter mesopotamiske skikkelser.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/gilgamesh-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Gilgamesh', 'Aqua Anu', NULL, NULL, 'Dominican Republic', ARRAY['Dominican Republic','Nicaragua','Ecuador'], 4, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Aqua Anu', 'Kraftige smaker i overraskende små ringmål, oppkalt etter mesopotamiske skikkelser.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/gilgamesh-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Culinary Art', 'Spain Rioja', NULL, NULL, NULL, NULL, 2, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Spain Rioja', 'El Septimos rimeligere premiumserie inspirert av verdens matkulturer, blandet med fem år lagret tobakk.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/culinary-art-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Culinary Art', 'Italy Toscana', NULL, NULL, NULL, NULL, 2, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Italy Toscana', 'El Septimos rimeligere premiumserie inspirert av verdens matkulturer, blandet med fem år lagret tobakk.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/culinary-art-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Culinary Art', 'Japan Nigori', NULL, NULL, NULL, NULL, 2, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'Japan Nigori', 'El Septimos rimeligere premiumserie inspirert av verdens matkulturer, blandet med fem år lagret tobakk.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/culinary-art-collection/', now(), ARRAY['El Septimo','Septimo']),
('El Septimo', 'Culinary Art', 'France Bordeaux', NULL, NULL, NULL, NULL, 2, 'Costa Rica', 'El Septimo Geneva', 'Parejo', 'France Bordeaux', 'El Septimos rimeligere premiumserie inspirert av verdens matkulturer, blandet med fem år lagret tobakk.', true, 'manufacturer', 'https://el-septimo.com/collection/cigars/culinary-art-collection/', now(), ARRAY['El Septimo','Septimo']);

-- Sindicato
INSERT INTO public.cigars
  (brand, series, vitola, wrapper_country, wrapper_leaf, binder, filler, strength,
   country_origin, manufacturer, shape, common_format, description, is_public,
   source_tier, source_url, verified_at, aliases)
VALUES
('Sindicato', 'Natural', 'Robusto', 'Nicaragua', 'Corojo', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Robusto', 'En firkantpresset nikaraguansk puro med skyggedyrket Corojo-dekkblad fra Jalapa som gir en balansert, mellomkraftig røyk.', true, 'retailer', 'https://cigar-coop.com/2014/11/cigar-review-sindicato-maduro-toro.html', now(), ARRAY['Sindicato']),
('Sindicato', 'Natural', 'Toro', 'Nicaragua', 'Corojo', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Toro', 'En firkantpresset nikaraguansk puro med skyggedyrket Corojo-dekkblad fra Jalapa som gir en balansert, mellomkraftig røyk.', true, 'retailer', 'https://cigar-coop.com/2014/11/cigar-review-sindicato-maduro-toro.html', now(), ARRAY['Sindicato']),
('Sindicato', 'Natural', 'Churchill', 'Nicaragua', 'Corojo', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Churchill', 'En firkantpresset nikaraguansk puro med skyggedyrket Corojo-dekkblad fra Jalapa som gir en balansert, mellomkraftig røyk.', true, 'retailer', 'https://cigar-coop.com/2014/11/cigar-review-sindicato-maduro-toro.html', now(), ARRAY['Sindicato']),
('Sindicato', 'Natural', 'Magnum', 'Nicaragua', 'Corojo', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Magnum', 'En firkantpresset nikaraguansk puro med skyggedyrket Corojo-dekkblad fra Jalapa som gir en balansert, mellomkraftig røyk.', true, 'retailer', 'https://cigar-coop.com/2014/11/cigar-review-sindicato-maduro-toro.html', now(), ARRAY['Sindicato']),
('Sindicato', 'Maduro', 'Robusto', 'Mexico', 'San Andrés', 'Nicaraguan', ARRAY['Nicaragua'], 4, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Robusto', 'En firkantpresset sigar med mørkt meksikansk San Andrés-dekkblad og nicaraguansk fyll for en fyldig og kraftig røyk.', true, 'retailer', 'https://cigar-coop.com/2014/11/cigar-review-sindicato-maduro-toro.html', now(), ARRAY['Sindicato']),
('Sindicato', 'Maduro', 'Toro', 'Mexico', 'San Andrés', 'Nicaraguan', ARRAY['Nicaragua'], 4, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Toro', 'En firkantpresset sigar med mørkt meksikansk San Andrés-dekkblad og nicaraguansk fyll for en fyldig og kraftig røyk.', true, 'retailer', 'https://cigar-coop.com/2014/11/cigar-review-sindicato-maduro-toro.html', now(), ARRAY['Sindicato']),
('Sindicato', 'Maduro', 'Churchill', 'Mexico', 'San Andrés', 'Nicaraguan', ARRAY['Nicaragua'], 4, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Churchill', 'En firkantpresset sigar med mørkt meksikansk San Andrés-dekkblad og nicaraguansk fyll for en fyldig og kraftig røyk.', true, 'retailer', 'https://cigar-coop.com/2014/11/cigar-review-sindicato-maduro-toro.html', now(), ARRAY['Sindicato']),
('Sindicato', 'Maduro', 'Magnum', 'Mexico', 'San Andrés', 'Nicaraguan', ARRAY['Nicaragua'], 4, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Magnum', 'En firkantpresset sigar med mørkt meksikansk San Andrés-dekkblad og nicaraguansk fyll for en fyldig og kraftig røyk.', true, 'retailer', 'https://cigar-coop.com/2014/11/cigar-review-sindicato-maduro-toro.html', now(), ARRAY['Sindicato']),
('Sindicato', 'Affinity', 'Corona', 'Ecuador', 'Connecticut', 'Nicaraguan', ARRAY['Nicaragua','Dominican Republic'], 2, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Corona', 'En mild til mellomkraftig sigar med silkemykt ecuadoriansk Connecticut-dekkblad, laget for smak og fylde uten for mye styrke.', true, 'retailer', 'https://halfwheel.com/sindicato-ships-affinity/43976/', now(), ARRAY['Sindicato']),
('Sindicato', 'Affinity', 'Robusto', 'Ecuador', 'Connecticut', 'Nicaraguan', ARRAY['Nicaragua','Dominican Republic'], 2, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Robusto', 'En mild til mellomkraftig sigar med silkemykt ecuadoriansk Connecticut-dekkblad, laget for smak og fylde uten for mye styrke.', true, 'retailer', 'https://halfwheel.com/sindicato-ships-affinity/43976/', now(), ARRAY['Sindicato']),
('Sindicato', 'Affinity', 'Toro', 'Ecuador', 'Connecticut', 'Nicaraguan', ARRAY['Nicaragua','Dominican Republic'], 2, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Toro', 'En mild til mellomkraftig sigar med silkemykt ecuadoriansk Connecticut-dekkblad, laget for smak og fylde uten for mye styrke.', true, 'retailer', 'https://halfwheel.com/sindicato-ships-affinity/43976/', now(), ARRAY['Sindicato']),
('Sindicato', 'Affinity', 'Gran Toro', 'Ecuador', 'Connecticut', 'Nicaraguan', ARRAY['Nicaragua','Dominican Republic'], 2, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Gran Toro', 'En mild til mellomkraftig sigar med silkemykt ecuadoriansk Connecticut-dekkblad, laget for smak og fylde uten for mye styrke.', true, 'retailer', 'https://halfwheel.com/sindicato-ships-affinity/43976/', now(), ARRAY['Sindicato']),
('Sindicato', 'Affinity', 'Belicoso', 'Ecuador', 'Connecticut', 'Nicaraguan', ARRAY['Nicaragua','Dominican Republic'], 2, 'Nicaragua', 'Sindicato Cigars', 'Figurado', 'Belicoso', 'En mild til mellomkraftig sigar med silkemykt ecuadoriansk Connecticut-dekkblad, laget for smak og fylde uten for mye styrke.', true, 'retailer', 'https://halfwheel.com/sindicato-ships-affinity/43976/', now(), ARRAY['Sindicato']),
('Sindicato', 'Affinity', 'Churchill', 'Ecuador', 'Connecticut', 'Nicaraguan', ARRAY['Nicaragua','Dominican Republic'], 2, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Churchill', 'En mild til mellomkraftig sigar med silkemykt ecuadoriansk Connecticut-dekkblad, laget for smak og fylde uten for mye styrke.', true, 'retailer', 'https://halfwheel.com/sindicato-ships-affinity/43976/', now(), ARRAY['Sindicato']),
('Sindicato', 'Affinity Maduro', 'Corona', 'United States', 'Connecticut Broadleaf', 'Nicaraguan', ARRAY['Nicaragua'], 4, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Corona', 'En kraftigere Affinity med mørkt Connecticut Broadleaf-dekkblad og nicaraguansk fyll for en mellom- til fyldig røyk.', true, 'retailer', 'https://www.coronacigar.com/brands/sindicato/affinity-maduro-by-sindicato/', now(), ARRAY['Sindicato']),
('Sindicato', 'Affinity Maduro', 'Robusto', 'United States', 'Connecticut Broadleaf', 'Nicaraguan', ARRAY['Nicaragua'], 4, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Robusto', 'En kraftigere Affinity med mørkt Connecticut Broadleaf-dekkblad og nicaraguansk fyll for en mellom- til fyldig røyk.', true, 'retailer', 'https://www.coronacigar.com/brands/sindicato/affinity-maduro-by-sindicato/', now(), ARRAY['Sindicato']),
('Sindicato', 'Affinity Maduro', 'Toro', 'United States', 'Connecticut Broadleaf', 'Nicaraguan', ARRAY['Nicaragua'], 4, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Toro', 'En kraftigere Affinity med mørkt Connecticut Broadleaf-dekkblad og nicaraguansk fyll for en mellom- til fyldig røyk.', true, 'retailer', 'https://www.coronacigar.com/brands/sindicato/affinity-maduro-by-sindicato/', now(), ARRAY['Sindicato']),
('Sindicato', 'Affinity Maduro', 'Gran Toro', 'United States', 'Connecticut Broadleaf', 'Nicaraguan', ARRAY['Nicaragua'], 4, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Gran Toro', 'En kraftigere Affinity med mørkt Connecticut Broadleaf-dekkblad og nicaraguansk fyll for en mellom- til fyldig røyk.', true, 'retailer', 'https://www.coronacigar.com/brands/sindicato/affinity-maduro-by-sindicato/', now(), ARRAY['Sindicato']),
('Sindicato', 'Affinity Maduro', 'Churchill', 'United States', 'Connecticut Broadleaf', 'Nicaraguan', ARRAY['Nicaragua'], 4, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Churchill', 'En kraftigere Affinity med mørkt Connecticut Broadleaf-dekkblad og nicaraguansk fyll for en mellom- til fyldig røyk.', true, 'retailer', 'https://www.coronacigar.com/brands/sindicato/affinity-maduro-by-sindicato/', now(), ARRAY['Sindicato']),
('Sindicato', 'Hex', 'Robusto', 'Ecuador', 'Habano', 'Nicaraguan', ARRAY['Nicaragua'], 4, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Robusto', 'En dristig og fyldig sigar av aldrede, sjeldne tobakker under et mørkt ecuadoriansk Habano-dekkblad.', true, 'retailer', 'https://halfwheel.com/review-sindicato-hex-perfecto/41240/', now(), ARRAY['Sindicato']),
('Sindicato', 'Hex', 'Figurado', 'Ecuador', 'Habano', 'Nicaraguan', ARRAY['Nicaragua'], 4, 'Nicaragua', 'Sindicato Cigars', 'Figurado', 'Figurado', 'En dristig og fyldig sigar av aldrede, sjeldne tobakker under et mørkt ecuadoriansk Habano-dekkblad.', true, 'retailer', 'https://halfwheel.com/review-sindicato-hex-perfecto/41240/', now(), ARRAY['Sindicato']),
('Sindicato', 'Hex', 'Toro', 'Ecuador', 'Habano', 'Nicaraguan', ARRAY['Nicaragua'], 4, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Toro', 'En dristig og fyldig sigar av aldrede, sjeldne tobakker under et mørkt ecuadoriansk Habano-dekkblad.', true, 'retailer', 'https://halfwheel.com/review-sindicato-hex-perfecto/41240/', now(), ARRAY['Sindicato']),
('Sindicato', 'Hex', 'Churchill', 'Ecuador', 'Habano', 'Nicaraguan', ARRAY['Nicaragua'], 4, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Churchill', 'En dristig og fyldig sigar av aldrede, sjeldne tobakker under et mørkt ecuadoriansk Habano-dekkblad.', true, 'retailer', 'https://halfwheel.com/review-sindicato-hex-perfecto/41240/', now(), ARRAY['Sindicato']),
('Sindicato', 'Hex', 'Perfecto', 'Ecuador', 'Habano', 'Nicaraguan', ARRAY['Nicaragua'], 4, 'Nicaragua', 'Sindicato Cigars', 'Figurado', 'Perfecto', 'En dristig og fyldig sigar av aldrede, sjeldne tobakker under et mørkt ecuadoriansk Habano-dekkblad.', true, 'retailer', 'https://halfwheel.com/review-sindicato-hex-perfecto/41240/', now(), ARRAY['Sindicato']),
('Sindicato', 'Casa Bella', 'Corona', 'Ecuador', 'Connecticut', 'Indonesian', ARRAY['Dominican Republic','Nicaragua'], 2, 'Dominican Republic', 'Sindicato Cigars', 'Parejo', 'Corona', 'En håndlaget sigar fra Den dominikanske republikk med ecuadoriansk Connecticut-dekkblad og en jevn, mild til mellomkraftig røyk.', true, 'retailer', 'https://cigar-coop.com/2013/07/cigar-preview-casa-bella-by-sindicato.html', now(), ARRAY['Sindicato']),
('Sindicato', 'Casa Bella', 'Robusto', 'Ecuador', 'Connecticut', 'Indonesian', ARRAY['Dominican Republic','Nicaragua'], 2, 'Dominican Republic', 'Sindicato Cigars', 'Parejo', 'Robusto', 'En håndlaget sigar fra Den dominikanske republikk med ecuadoriansk Connecticut-dekkblad og en jevn, mild til mellomkraftig røyk.', true, 'retailer', 'https://cigar-coop.com/2013/07/cigar-preview-casa-bella-by-sindicato.html', now(), ARRAY['Sindicato']),
('Sindicato', 'Casa Bella', 'Toro', 'Ecuador', 'Connecticut', 'Indonesian', ARRAY['Dominican Republic','Nicaragua'], 2, 'Dominican Republic', 'Sindicato Cigars', 'Parejo', 'Toro', 'En håndlaget sigar fra Den dominikanske republikk med ecuadoriansk Connecticut-dekkblad og en jevn, mild til mellomkraftig røyk.', true, 'retailer', 'https://cigar-coop.com/2013/07/cigar-preview-casa-bella-by-sindicato.html', now(), ARRAY['Sindicato']),
('Sindicato', 'Casa Bella', 'Churchill', 'Ecuador', 'Connecticut', 'Indonesian', ARRAY['Dominican Republic','Nicaragua'], 2, 'Dominican Republic', 'Sindicato Cigars', 'Parejo', 'Churchill', 'En håndlaget sigar fra Den dominikanske republikk med ecuadoriansk Connecticut-dekkblad og en jevn, mild til mellomkraftig røyk.', true, 'retailer', 'https://cigar-coop.com/2013/07/cigar-preview-casa-bella-by-sindicato.html', now(), ARRAY['Sindicato']),
('Sindicato', 'Casa Bella', 'Gran Toro', 'Ecuador', 'Connecticut', 'Indonesian', ARRAY['Dominican Republic','Nicaragua'], 2, 'Dominican Republic', 'Sindicato Cigars', 'Parejo', 'Gran Toro', 'En håndlaget sigar fra Den dominikanske republikk med ecuadoriansk Connecticut-dekkblad og en jevn, mild til mellomkraftig røyk.', true, 'retailer', 'https://cigar-coop.com/2013/07/cigar-preview-casa-bella-by-sindicato.html', now(), ARRAY['Sindicato']),
('Sindicato', 'Particulares', 'Deliciosos', 'Nicaragua', 'Corojo', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Deliciosos', 'En nikaraguansk puro laget ved TABSA — en gjenoppliving av det klassiske Particulares-merket med skyggedyrket Corojo-dekkblad.', true, 'retailer', 'https://cigar-coop.com/2016/09/cigar-news-sindicato-brings-back-particulares-brand-at-ipcpr.html', now(), ARRAY['Sindicato']),
('Sindicato', 'Particulares', 'Cesta', 'Nicaragua', 'Corojo', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Cesta', 'En nikaraguansk puro laget ved TABSA — en gjenoppliving av det klassiske Particulares-merket med skyggedyrket Corojo-dekkblad.', true, 'retailer', 'https://cigar-coop.com/2016/09/cigar-news-sindicato-brings-back-particulares-brand-at-ipcpr.html', now(), ARRAY['Sindicato']),
('Sindicato', 'Particulares', 'No. 1', 'Nicaragua', 'Corojo', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'No. 1', 'En nikaraguansk puro laget ved TABSA — en gjenoppliving av det klassiske Particulares-merket med skyggedyrket Corojo-dekkblad.', true, 'retailer', 'https://cigar-coop.com/2016/09/cigar-news-sindicato-brings-back-particulares-brand-at-ipcpr.html', now(), ARRAY['Sindicato']),
('Sindicato', 'Particulares', 'Belvederes', 'Nicaragua', 'Corojo', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Sindicato Cigars', 'Parejo', 'Belvederes', 'En nikaraguansk puro laget ved TABSA — en gjenoppliving av det klassiske Particulares-merket med skyggedyrket Corojo-dekkblad.', true, 'retailer', 'https://cigar-coop.com/2016/09/cigar-news-sindicato-brings-back-particulares-brand-at-ipcpr.html', now(), ARRAY['Sindicato']);

-- Serino
INSERT INTO public.cigars
  (brand, series, vitola, wrapper_country, wrapper_leaf, binder, filler, strength,
   country_origin, manufacturer, shape, common_format, description, is_public,
   source_tier, source_url, verified_at, aliases)
VALUES
('Serino', 'Royale Connecticut', 'Robusto', 'Ecuador', 'Connecticut Shade', 'Nicaraguan', ARRAY['Nicaragua'], 2, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Robusto', 'En kremet, mild-til-medium sigar med ecuadoriansk Connecticut-dekkblad og nicaraguansk innmat, med toner av vanilje, cashew, sitronskall og hvit pepper.', true, 'manufacturer', 'https://serinocigars.com/cigars/serino-royale-connecticut/', now(), ARRAY['Serino']),
('Serino', 'Royale Connecticut', 'Sublime', 'Ecuador', 'Connecticut Shade', 'Nicaraguan', ARRAY['Nicaragua'], 2, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Sublime', 'En kremet, mild-til-medium sigar med ecuadoriansk Connecticut-dekkblad og nicaraguansk innmat, med toner av vanilje, cashew, sitronskall og hvit pepper.', true, 'manufacturer', 'https://serinocigars.com/cigars/serino-royale-connecticut/', now(), ARRAY['Serino']),
('Serino', 'Royale Connecticut', 'Churchill', 'Ecuador', 'Connecticut Shade', 'Nicaraguan', ARRAY['Nicaragua'], 2, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Churchill', 'En kremet, mild-til-medium sigar med ecuadoriansk Connecticut-dekkblad og nicaraguansk innmat, med toner av vanilje, cashew, sitronskall og hvit pepper.', true, 'manufacturer', 'https://serinocigars.com/cigars/serino-royale-connecticut/', now(), ARRAY['Serino']),
('Serino', 'Royale Connecticut', 'Gordo', 'Ecuador', 'Connecticut Shade', 'Nicaraguan', ARRAY['Nicaragua'], 2, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Gordo', 'En kremet, mild-til-medium sigar med ecuadoriansk Connecticut-dekkblad og nicaraguansk innmat, med toner av vanilje, cashew, sitronskall og hvit pepper.', true, 'manufacturer', 'https://serinocigars.com/cigars/serino-royale-connecticut/', now(), ARRAY['Serino']),
('Serino', 'Royale Medio', 'Robusto Extra', 'Ecuador', 'Habano', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Robusto Extra', 'En mediumfyldig sigar med ecuadoriansk Habano-dekkblad og nicaraguansk innmat for en balansert, krydret profil.', true, 'manufacturer', 'https://serinocigars.com/cigars/serino-royale-medio/', now(), ARRAY['Serino']),
('Serino', 'Royale Medio', 'Sublime', 'Ecuador', 'Habano', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Sublime', 'En mediumfyldig sigar med ecuadoriansk Habano-dekkblad og nicaraguansk innmat for en balansert, krydret profil.', true, 'manufacturer', 'https://serinocigars.com/cigars/serino-royale-medio/', now(), ARRAY['Serino']),
('Serino', 'Royale Medio', 'Gordo', 'Ecuador', 'Habano', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Gordo', 'En mediumfyldig sigar med ecuadoriansk Habano-dekkblad og nicaraguansk innmat for en balansert, krydret profil.', true, 'manufacturer', 'https://serinocigars.com/cigars/serino-royale-medio/', now(), ARRAY['Serino']),
('Serino', 'Royale Maduro XX', 'Robusto Extra', 'Ecuador', 'Havana 2000 Oscuro', 'Nicaraguan', ARRAY['Nicaragua'], 4, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Robusto Extra', 'En fyldig, men balansert maduro med ecuadoriansk Havana 2000 Oscuro-dekkblad og nicaraguansk innmat.', true, 'manufacturer', 'https://serinocigars.com/cigars/serino-royale-maduro-xx/', now(), ARRAY['Serino']),
('Serino', 'Royale Maduro XX', 'Sublime', 'Ecuador', 'Havana 2000 Oscuro', 'Nicaraguan', ARRAY['Nicaragua'], 4, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Sublime', 'En fyldig, men balansert maduro med ecuadoriansk Havana 2000 Oscuro-dekkblad og nicaraguansk innmat.', true, 'manufacturer', 'https://serinocigars.com/cigars/serino-royale-maduro-xx/', now(), ARRAY['Serino']),
('Serino', 'Royale Maduro XX', 'Gordo', 'Ecuador', 'Havana 2000 Oscuro', 'Nicaraguan', ARRAY['Nicaragua'], 4, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Gordo', 'En fyldig, men balansert maduro med ecuadoriansk Havana 2000 Oscuro-dekkblad og nicaraguansk innmat.', true, 'manufacturer', 'https://serinocigars.com/cigars/serino-royale-maduro-xx/', now(), ARRAY['Serino']),
('Serino', 'Taino', 'Robusto', 'Ecuador', 'Habano', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Robusto', 'En mediumfyldig nicaraguansk sigar med ecuadoriansk Habano-dekkblad og en kompleks, krydret innmat.', true, 'manufacturer', 'https://serinocigars.com/cigars/taino/', now(), ARRAY['Serino']),
('Serino', 'Taino', 'Corona Gorda', 'Ecuador', 'Habano', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Corona Gorda', 'En mediumfyldig nicaraguansk sigar med ecuadoriansk Habano-dekkblad og en kompleks, krydret innmat.', true, 'manufacturer', 'https://serinocigars.com/cigars/taino/', now(), ARRAY['Serino']),
('Serino', 'Taino', 'Toro', 'Ecuador', 'Habano', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Toro', 'En mediumfyldig nicaraguansk sigar med ecuadoriansk Habano-dekkblad og en kompleks, krydret innmat.', true, 'manufacturer', 'https://serinocigars.com/cigars/taino/', now(), ARRAY['Serino']),
('Serino', 'Taino Heritage', 'Hamaca', 'Ecuador', 'Habano 2000', NULL, ARRAY['Dominican Republic'], NULL, 'Dominican Republic', 'Serino Cigar Co.', 'Parejo', 'Hamaca', 'En dominikansk sigar laget på Tabacalera Palma med ecuadoriansk Habano 2000-dekkblad og femårslagret innmat.', true, 'manufacturer', 'https://serinocigars.com/cigars/taino-heritage/', now(), ARRAY['Serino']),
('Serino', 'Taino Heritage', 'Yocahu', 'Ecuador', 'Habano 2000', NULL, ARRAY['Dominican Republic'], NULL, 'Dominican Republic', 'Serino Cigar Co.', 'Parejo', 'Yocahu', 'En dominikansk sigar laget på Tabacalera Palma med ecuadoriansk Habano 2000-dekkblad og femårslagret innmat.', true, 'manufacturer', 'https://serinocigars.com/cigars/taino-heritage/', now(), ARRAY['Serino']),
('Serino', 'Taino Heritage', 'Manicato', 'Ecuador', 'Habano 2000', NULL, ARRAY['Dominican Republic'], NULL, 'Dominican Republic', 'Serino Cigar Co.', 'Parejo', 'Manicato', 'En dominikansk sigar laget på Tabacalera Palma med ecuadoriansk Habano 2000-dekkblad og femårslagret innmat.', true, 'manufacturer', 'https://serinocigars.com/cigars/taino-heritage/', now(), ARRAY['Serino']),
('Serino', 'Wayfarer', 'The 109', 'Ecuador', 'Corojo 99', 'Nicaraguan', ARRAY['Nicaragua'], NULL, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'The 109', 'En nicaraguansk sigar med ecuadoriansk Corojo 99-dekkblad, med toner av pekannøtt, lær, kanel og melkesjokolade.', true, 'manufacturer', 'https://serinocigars.com/cigars/wayfarer/', now(), ARRAY['Serino']),
('Serino', 'Wayfarer', 'Robusto', 'Ecuador', 'Corojo 99', 'Nicaraguan', ARRAY['Nicaragua'], NULL, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Robusto', 'En nicaraguansk sigar med ecuadoriansk Corojo 99-dekkblad, med toner av pekannøtt, lær, kanel og melkesjokolade.', true, 'manufacturer', 'https://serinocigars.com/cigars/wayfarer/', now(), ARRAY['Serino']),
('Serino', 'Wayfarer', 'Corona Gorda', 'Ecuador', 'Corojo 99', 'Nicaraguan', ARRAY['Nicaragua'], NULL, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Corona Gorda', 'En nicaraguansk sigar med ecuadoriansk Corojo 99-dekkblad, med toner av pekannøtt, lær, kanel og melkesjokolade.', true, 'manufacturer', 'https://serinocigars.com/cigars/wayfarer/', now(), ARRAY['Serino']),
('Serino', 'Wayfarer', 'Dalia', 'Ecuador', 'Corojo 99', 'Nicaraguan', ARRAY['Nicaragua'], NULL, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Dalia', 'En nicaraguansk sigar med ecuadoriansk Corojo 99-dekkblad, med toner av pekannøtt, lær, kanel og melkesjokolade.', true, 'manufacturer', 'https://serinocigars.com/cigars/wayfarer/', now(), ARRAY['Serino']),
('Serino', 'Wayfarer', 'Corona', 'Ecuador', 'Corojo 99', 'Nicaraguan', ARRAY['Nicaragua'], NULL, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Corona', 'En nicaraguansk sigar med ecuadoriansk Corojo 99-dekkblad, med toner av pekannøtt, lær, kanel og melkesjokolade.', true, 'manufacturer', 'https://serinocigars.com/cigars/wayfarer/', now(), ARRAY['Serino']),
('Serino', 'Elenor Rose', 'Lady 48', 'Ecuador', 'Rosado', 'Nicaraguan', ARRAY['Nicaragua','Peru','Pennsylvania'], NULL, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Lady 48', 'En elegant sigar med ecuadoriansk Rosado-dekkblad og innmat fra Nicaragua, Peru og Pennsylvania, med toner av honning, eik og kirsebær.', true, 'manufacturer', 'https://serinocigars.com/cigars/studio-serino-elenor-rose/', now(), ARRAY['Serino']),
('Serino', 'Elenor Rose', 'Eagle', 'Ecuador', 'Rosado', 'Nicaraguan', ARRAY['Nicaragua','Peru','Pennsylvania'], NULL, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Eagle', 'En elegant sigar med ecuadoriansk Rosado-dekkblad og innmat fra Nicaragua, Peru og Pennsylvania, med toner av honning, eik og kirsebær.', true, 'manufacturer', 'https://serinocigars.com/cigars/studio-serino-elenor-rose/', now(), ARRAY['Serino']),
('Serino', 'Elenor Rose', 'Revolver', 'Ecuador', 'Rosado', 'Nicaraguan', ARRAY['Nicaragua','Peru','Pennsylvania'], NULL, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Revolver', 'En elegant sigar med ecuadoriansk Rosado-dekkblad og innmat fra Nicaragua, Peru og Pennsylvania, med toner av honning, eik og kirsebær.', true, 'manufacturer', 'https://serinocigars.com/cigars/studio-serino-elenor-rose/', now(), ARRAY['Serino']),
('Serino', 'The Expat', 'Corona Gorda', 'Ecuador', 'Habano Oscuro', 'Nicaraguan', ARRAY['Nicaragua','Pennsylvania'], NULL, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Corona Gorda', 'En nicaraguansk verdisigar med ecuadoriansk Habano Oscuro-dekkblad og Pennsylvania broadleaf, med toner av kakao, rosiner, kaffe og kanel.', true, 'manufacturer', 'https://serinocigars.com/cigars/serino-cigar-co-the-expat/', now(), ARRAY['Serino']),
('Serino', 'The Expat', 'The Passport', 'Ecuador', 'Habano Oscuro', 'Nicaraguan', ARRAY['Nicaragua','Pennsylvania'], NULL, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'The Passport', 'En nicaraguansk verdisigar med ecuadoriansk Habano Oscuro-dekkblad og Pennsylvania broadleaf, med toner av kakao, rosiner, kaffe og kanel.', true, 'manufacturer', 'https://serinocigars.com/cigars/serino-cigar-co-the-expat/', now(), ARRAY['Serino']),
('Serino', 'The Expat', 'Sublime', 'Ecuador', 'Habano Oscuro', 'Nicaraguan', ARRAY['Nicaragua','Pennsylvania'], NULL, 'Nicaragua', 'Serino Cigar Co.', 'Parejo', 'Sublime', 'En nicaraguansk verdisigar med ecuadoriansk Habano Oscuro-dekkblad og Pennsylvania broadleaf, med toner av kakao, rosiner, kaffe og kanel.', true, 'manufacturer', 'https://serinocigars.com/cigars/serino-cigar-co-the-expat/', now(), ARRAY['Serino']);

-- Rojas
INSERT INTO public.cigars
  (brand, series, vitola, wrapper_country, wrapper_leaf, binder, filler, strength,
   country_origin, manufacturer, shape, common_format, description, is_public,
   source_tier, source_url, verified_at, aliases)
VALUES
('Rojas', 'Statement', 'Corona Gorda', 'Mexico', 'San Andrés', 'Nicaraguan', ARRAY['Nicaragua'], 4, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Corona Gorda', 'En medium til fyldig sigar med meksikansk San Andrés-dekkblad og nicaraguansk innmat, med jord, mørk sjokolade og pepper.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']),
('Rojas', 'Statement', 'Lancero', 'Mexico', 'San Andrés', 'Nicaraguan', ARRAY['Nicaragua'], 4, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Lancero', 'En medium til fyldig sigar med meksikansk San Andrés-dekkblad og nicaraguansk innmat, med jord, mørk sjokolade og pepper.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']),
('Rojas', 'Statement', 'Robusto', 'Mexico', 'San Andrés', 'Nicaraguan', ARRAY['Nicaragua'], 4, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Robusto', 'En medium til fyldig sigar med meksikansk San Andrés-dekkblad og nicaraguansk innmat, med jord, mørk sjokolade og pepper.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']),
('Rojas', 'Statement', 'Toro', 'Mexico', 'San Andrés', 'Nicaraguan', ARRAY['Nicaragua'], 4, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Toro', 'En medium til fyldig sigar med meksikansk San Andrés-dekkblad og nicaraguansk innmat, med jord, mørk sjokolade og pepper.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']),
('Rojas', 'Bluebonnets', 'Corona Gorda', 'Ecuador', 'Corojo', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Corona Gorda', 'En mellomsterk sigar med ecuadoriansk Corojo-dekkblad og nicaraguansk bind og innmat.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']),
('Rojas', 'Bluebonnets', 'Lancero', 'Ecuador', 'Corojo', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Lancero', 'En mellomsterk sigar med ecuadoriansk Corojo-dekkblad og nicaraguansk bind og innmat.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']),
('Rojas', 'Bluebonnets', 'Robusto', 'Ecuador', 'Corojo', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Robusto', 'En mellomsterk sigar med ecuadoriansk Corojo-dekkblad og nicaraguansk bind og innmat.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']),
('Rojas', 'Bluebonnets', 'Toro', 'Ecuador', 'Corojo', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Toro', 'En mellomsterk sigar med ecuadoriansk Corojo-dekkblad og nicaraguansk bind og innmat.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']),
('Rojas', 'Quiet Morning', 'Corona', 'Ecuador', 'Connecticut', 'Nicaraguan', ARRAY['Nicaragua'], 2, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Corona', 'En mild til medium sigar med ecuadoriansk Connecticut-dekkblad, ideell som morgenrøyk.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']),
('Rojas', 'Quiet Morning', 'Lancero', 'Ecuador', 'Connecticut', 'Nicaraguan', ARRAY['Nicaragua'], 2, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Lancero', 'En mild til medium sigar med ecuadoriansk Connecticut-dekkblad, ideell som morgenrøyk.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']),
('Rojas', 'Quiet Morning', 'Robusto', 'Ecuador', 'Connecticut', 'Nicaraguan', ARRAY['Nicaragua'], 2, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Robusto', 'En mild til medium sigar med ecuadoriansk Connecticut-dekkblad, ideell som morgenrøyk.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']),
('Rojas', 'Quiet Morning', 'Toro', 'Ecuador', 'Connecticut', 'Nicaraguan', ARRAY['Nicaragua'], 2, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Toro', 'En mild til medium sigar med ecuadoriansk Connecticut-dekkblad, ideell som morgenrøyk.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']),
('Rojas', 'Unfinished Business', 'Corona Gorda', 'Ecuador', 'Sumatra', 'Nicaraguan', ARRAY['Nicaragua','Mexico'], 3, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Corona Gorda', 'En medium, mykpresset sigar med lukket fot, ecuadoriansk Sumatra-dekkblad og innmat fra Nicaragua og Mexico.', true, 'retailer', 'https://www.famous-smoke.com/brand/rojas-unfinished-business-cigars', now(), ARRAY['Rojas']),
('Rojas', 'Unfinished Business', 'Robusto', 'Ecuador', 'Sumatra', 'Nicaraguan', ARRAY['Nicaragua','Mexico'], 3, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Robusto', 'En medium, mykpresset sigar med lukket fot, ecuadoriansk Sumatra-dekkblad og innmat fra Nicaragua og Mexico.', true, 'retailer', 'https://www.famous-smoke.com/brand/rojas-unfinished-business-cigars', now(), ARRAY['Rojas']),
('Rojas', 'Street Tacos Barbacoa', 'Short Corona', 'Ecuador', 'Sumatra', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Short Corona', 'En smakrik, jordaktig sigar med ecuadoriansk Sumatra-dekkblad og nicaraguansk bind og innmat.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']),
('Rojas', 'Street Tacos Barbacoa', 'Robusto', 'Ecuador', 'Sumatra', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Robusto', 'En smakrik, jordaktig sigar med ecuadoriansk Sumatra-dekkblad og nicaraguansk bind og innmat.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']),
('Rojas', 'Street Tacos Barbacoa', 'Toro', 'Ecuador', 'Sumatra', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Toro', 'En smakrik, jordaktig sigar med ecuadoriansk Sumatra-dekkblad og nicaraguansk bind og innmat.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']),
('Rojas', 'Street Tacos Carnitas', 'Short Corona', 'Ecuador', 'Connecticut', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Short Corona', 'Den mildeste sigaren i Street Tacos-serien, med ecuadoriansk Connecticut-dekkblad og nicaraguansk bind og innmat.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']),
('Rojas', 'Street Tacos Carnitas', 'Robusto', 'Ecuador', 'Connecticut', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Robusto', 'Den mildeste sigaren i Street Tacos-serien, med ecuadoriansk Connecticut-dekkblad og nicaraguansk bind og innmat.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']),
('Rojas', 'Street Tacos Carnitas', 'Toro', 'Ecuador', 'Connecticut', 'Nicaraguan', ARRAY['Nicaragua'], 3, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Toro', 'Den mildeste sigaren i Street Tacos-serien, med ecuadoriansk Connecticut-dekkblad og nicaraguansk bind og innmat.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']),
('Rojas', 'Street Tacos Al Pastor', 'Robusto', 'Ecuador', 'Habano', 'Mexican', ARRAY['Dominican Republic','Nicaragua'], 3, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Robusto', 'En medium sigar med ecuadoriansk Habano-dekkblad, meksikansk San Andrés-bind og innmat fra DR og Nicaragua.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']),
('Rojas', 'Street Tacos Al Pastor', 'Toro', 'Ecuador', 'Habano', 'Mexican', ARRAY['Dominican Republic','Nicaragua'], 3, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Toro', 'En medium sigar med ecuadoriansk Habano-dekkblad, meksikansk San Andrés-bind og innmat fra DR og Nicaragua.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']),
('Rojas', 'Street Tacos Al Pastor', 'Toro Grande', 'Ecuador', 'Habano', 'Mexican', ARRAY['Dominican Republic','Nicaragua'], 3, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Toro Grande', 'En medium sigar med ecuadoriansk Habano-dekkblad, meksikansk San Andrés-bind og innmat fra DR og Nicaragua.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']),
('Rojas', 'Street Tacos Al Pastor', 'Gordo', 'Ecuador', 'Habano', 'Mexican', ARRAY['Dominican Republic','Nicaragua'], 3, 'Nicaragua', 'Rojas Cigars', 'Parejo', 'Gordo', 'En medium sigar med ecuadoriansk Habano-dekkblad, meksikansk San Andrés-bind og innmat fra DR og Nicaragua.', true, 'retailer', 'https://www.smokingpipes.com/cigars/rojas/', now(), ARRAY['Rojas']);

-- Powstanie
INSERT INTO public.cigars
  (brand, series, vitola, wrapper_country, wrapper_leaf, binder, filler, strength,
   country_origin, manufacturer, shape, common_format, description, is_public,
   source_tier, source_url, verified_at, aliases)
VALUES
('Powstanie', 'Habano', 'Short Perfecto', 'Ecuador', 'Habano', 'Indonesian', ARRAY['Dominican','Nicaraguan'], 3, 'Nicaragua', 'Powstanie Cigars', 'Figurado', 'Short Perfecto', 'En middels til fyldig, cubansk-inspirert blanding med ecuadoriansk Habano-dekkblad, laget hos NicaSueño.', true, 'retailer', 'https://www.smokingpipes.com/cigars/powstanie/', now(), ARRAY['Powstanie']),
('Powstanie', 'Habano', 'Corona Gorda', 'Ecuador', 'Habano', 'Indonesian', ARRAY['Dominican','Nicaraguan'], 3, 'Nicaragua', 'Powstanie Cigars', 'Parejo', 'Corona Gorda', 'En middels til fyldig, cubansk-inspirert blanding med ecuadoriansk Habano-dekkblad, laget hos NicaSueño.', true, 'retailer', 'https://www.smokingpipes.com/cigars/powstanie/', now(), ARRAY['Powstanie']),
('Powstanie', 'Habano', 'Belicoso', 'Ecuador', 'Habano', 'Indonesian', ARRAY['Dominican','Nicaraguan'], 3, 'Nicaragua', 'Powstanie Cigars', 'Figurado', 'Belicoso', 'En middels til fyldig, cubansk-inspirert blanding med ecuadoriansk Habano-dekkblad, laget hos NicaSueño.', true, 'retailer', 'https://www.smokingpipes.com/cigars/powstanie/', now(), ARRAY['Powstanie']),
('Powstanie', 'Habano', 'Toro', 'Ecuador', 'Habano', 'Indonesian', ARRAY['Dominican','Nicaraguan'], 3, 'Nicaragua', 'Powstanie Cigars', 'Parejo', 'Toro', 'En middels til fyldig, cubansk-inspirert blanding med ecuadoriansk Habano-dekkblad, laget hos NicaSueño.', true, 'retailer', 'https://www.smokingpipes.com/cigars/powstanie/', now(), ARRAY['Powstanie']),
('Powstanie', 'Broadleaf', 'Robusto', 'United States', 'Connecticut Broadleaf', 'Indonesian', ARRAY['Nicaraguan'], 4, 'Nicaragua', 'Powstanie Cigars', 'Parejo', 'Robusto', 'Et mørkt, oljete Connecticut Broadleaf maduro-dekkblad gir en fyldig, søtlig røyk.', true, 'retailer', 'https://www.jrcigars.com/cigars/handmade-cigars/powstanie-cigars/', now(), ARRAY['Powstanie']),
('Powstanie', 'Broadleaf', 'Short Perfecto', 'United States', 'Connecticut Broadleaf', 'Indonesian', ARRAY['Nicaraguan'], 4, 'Nicaragua', 'Powstanie Cigars', 'Figurado', 'Short Perfecto', 'Et mørkt, oljete Connecticut Broadleaf maduro-dekkblad gir en fyldig, søtlig røyk.', true, 'retailer', 'https://www.jrcigars.com/cigars/handmade-cigars/powstanie-cigars/', now(), ARRAY['Powstanie']),
('Powstanie', 'Broadleaf', 'Belicoso', 'United States', 'Connecticut Broadleaf', 'Indonesian', ARRAY['Nicaraguan'], 4, 'Nicaragua', 'Powstanie Cigars', 'Figurado', 'Belicoso', 'Et mørkt, oljete Connecticut Broadleaf maduro-dekkblad gir en fyldig, søtlig røyk.', true, 'retailer', 'https://www.jrcigars.com/cigars/handmade-cigars/powstanie-cigars/', now(), ARRAY['Powstanie']),
('Powstanie', 'Broadleaf', 'Toro', 'United States', 'Connecticut Broadleaf', 'Indonesian', ARRAY['Nicaraguan'], 4, 'Nicaragua', 'Powstanie Cigars', 'Parejo', 'Toro', 'Et mørkt, oljete Connecticut Broadleaf maduro-dekkblad gir en fyldig, søtlig røyk.', true, 'retailer', 'https://www.jrcigars.com/cigars/handmade-cigars/powstanie-cigars/', now(), ARRAY['Powstanie']),
('Powstanie', 'Connecticut', 'Short Perfecto', 'Ecuador', 'Connecticut Shade', 'Connecticut', ARRAY['Nicaraguan'], 2, 'Nicaragua', 'Powstanie Cigars', 'Figurado', 'Short Perfecto', 'En mildere sigar med ecuadoriansk Connecticut Shade-dekkblad og nicaraguansk innmat.', true, 'retailer', 'https://www.smokingpipes.com/cigars/powstanie/', now(), ARRAY['Powstanie']),
('Powstanie', 'Connecticut', 'Corona Gorda', 'Ecuador', 'Connecticut Shade', 'Connecticut', ARRAY['Nicaraguan'], 2, 'Nicaragua', 'Powstanie Cigars', 'Parejo', 'Corona Gorda', 'En mildere sigar med ecuadoriansk Connecticut Shade-dekkblad og nicaraguansk innmat.', true, 'retailer', 'https://www.smokingpipes.com/cigars/powstanie/', now(), ARRAY['Powstanie']),
('Powstanie', 'Connecticut', 'Belicoso', 'Ecuador', 'Connecticut Shade', 'Connecticut', ARRAY['Nicaraguan'], 2, 'Nicaragua', 'Powstanie Cigars', 'Figurado', 'Belicoso', 'En mildere sigar med ecuadoriansk Connecticut Shade-dekkblad og nicaraguansk innmat.', true, 'retailer', 'https://www.smokingpipes.com/cigars/powstanie/', now(), ARRAY['Powstanie']),
('Powstanie', 'Connecticut', 'Toro', 'Ecuador', 'Connecticut Shade', 'Connecticut', ARRAY['Nicaraguan'], 2, 'Nicaragua', 'Powstanie Cigars', 'Parejo', 'Toro', 'En mildere sigar med ecuadoriansk Connecticut Shade-dekkblad og nicaraguansk innmat.', true, 'retailer', 'https://www.smokingpipes.com/cigars/powstanie/', now(), ARRAY['Powstanie']),
('Powstanie', 'San Andrés', 'Robusto', 'Mexico', 'San Andrés', 'Ecuadorian Habano', ARRAY['Dominican','Nicaraguan'], 4, 'Nicaragua', 'Powstanie Cigars', 'Parejo', 'Robusto', 'Et meksikansk San Andrés-dekkblad gir en kraftig, dyp smaksprofil.', true, 'retailer', 'https://www.smokingpipes.com/cigars/powstanie/', now(), ARRAY['Powstanie']),
('Powstanie', 'San Andrés', 'Short Perfecto', 'Mexico', 'San Andrés', 'Ecuadorian Habano', ARRAY['Dominican','Nicaraguan'], 4, 'Nicaragua', 'Powstanie Cigars', 'Figurado', 'Short Perfecto', 'Et meksikansk San Andrés-dekkblad gir en kraftig, dyp smaksprofil.', true, 'retailer', 'https://www.smokingpipes.com/cigars/powstanie/', now(), ARRAY['Powstanie']),
('Powstanie', 'San Andrés', 'Corona Gorda', 'Mexico', 'San Andrés', 'Ecuadorian Habano', ARRAY['Dominican','Nicaraguan'], 4, 'Nicaragua', 'Powstanie Cigars', 'Parejo', 'Corona Gorda', 'Et meksikansk San Andrés-dekkblad gir en kraftig, dyp smaksprofil.', true, 'retailer', 'https://www.smokingpipes.com/cigars/powstanie/', now(), ARRAY['Powstanie']),
('Powstanie', 'San Andrés', 'Belicoso', 'Mexico', 'San Andrés', 'Ecuadorian Habano', ARRAY['Dominican','Nicaraguan'], 4, 'Nicaragua', 'Powstanie Cigars', 'Figurado', 'Belicoso', 'Et meksikansk San Andrés-dekkblad gir en kraftig, dyp smaksprofil.', true, 'retailer', 'https://www.smokingpipes.com/cigars/powstanie/', now(), ARRAY['Powstanie']),
('Powstanie', 'San Andrés', 'Toro', 'Mexico', 'San Andrés', 'Ecuadorian Habano', ARRAY['Dominican','Nicaraguan'], 4, 'Nicaragua', 'Powstanie Cigars', 'Parejo', 'Toro', 'Et meksikansk San Andrés-dekkblad gir en kraftig, dyp smaksprofil.', true, 'retailer', 'https://www.smokingpipes.com/cigars/powstanie/', now(), ARRAY['Powstanie']),
('Powstanie', 'Sumatra', 'Petite Robusto', 'Ecuador', 'Sumatra', 'Mexican & Pennsylvania', ARRAY['Dominican','Nicaraguan'], 3, 'Nicaragua', 'Powstanie Cigars', 'Parejo', 'Petite Robusto', 'En boks-presset serie med ecuadoriansk Sumatra-dekkblad og en middels fyldig smak.', true, 'retailer', 'https://www.smokingpipes.com/cigars/powstanie/', now(), ARRAY['Powstanie']),
('Powstanie', 'Sumatra', 'Gran Robusto', 'Ecuador', 'Sumatra', 'Mexican & Pennsylvania', ARRAY['Dominican','Nicaraguan'], 3, 'Nicaragua', 'Powstanie Cigars', 'Parejo', 'Gran Robusto', 'En boks-presset serie med ecuadoriansk Sumatra-dekkblad og en middels fyldig smak.', true, 'retailer', 'https://www.smokingpipes.com/cigars/powstanie/', now(), ARRAY['Powstanie']),
('Powstanie', 'Sumatra', 'Gran Toro', 'Ecuador', 'Sumatra', 'Mexican & Pennsylvania', ARRAY['Dominican','Nicaraguan'], 3, 'Nicaragua', 'Powstanie Cigars', 'Parejo', 'Gran Toro', 'En boks-presset serie med ecuadoriansk Sumatra-dekkblad og en middels fyldig smak.', true, 'retailer', 'https://www.smokingpipes.com/cigars/powstanie/', now(), ARRAY['Powstanie']),
('Powstanie', 'Sumatra', 'Churchill', 'Ecuador', 'Sumatra', 'Mexican & Pennsylvania', ARRAY['Dominican','Nicaraguan'], 3, 'Nicaragua', 'Powstanie Cigars', 'Parejo', 'Churchill', 'En boks-presset serie med ecuadoriansk Sumatra-dekkblad og en middels fyldig smak.', true, 'retailer', 'https://www.smokingpipes.com/cigars/powstanie/', now(), ARRAY['Powstanie']);

-- MBombay
INSERT INTO public.cigars
  (brand, series, vitola, wrapper_country, wrapper_leaf, binder, filler, strength,
   country_origin, manufacturer, shape, common_format, description, is_public,
   source_tier, source_url, verified_at, aliases)
VALUES
('MBombay', 'Classic', 'Corona', 'Ecuador', 'Connecticut Shade', 'Ecuador', ARRAY['Nicaragua','Dominican Republic','Peru'], 2, 'Costa Rica', 'Bombay Tobak', 'Parejo', 'Corona', 'En mild til medium sigar med ecuadoriansk Connecticut Shade-dekkblad, håndrullet i Costa Rica.', true, 'retailer', 'https://cigar-coop.com/2018/01/cigar-review-mbombay-classic-torpedo-by-bombay-tobak.html', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'Classic', 'Robusto', 'Ecuador', 'Connecticut Shade', 'Ecuador', ARRAY['Nicaragua','Dominican Republic','Peru'], 2, 'Costa Rica', 'Bombay Tobak', 'Parejo', 'Robusto', 'En mild til medium sigar med ecuadoriansk Connecticut Shade-dekkblad, håndrullet i Costa Rica.', true, 'retailer', 'https://cigar-coop.com/2018/01/cigar-review-mbombay-classic-torpedo-by-bombay-tobak.html', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'Classic', 'Belicoso', 'Ecuador', 'Connecticut Shade', 'Ecuador', ARRAY['Nicaragua','Dominican Republic','Peru'], 2, 'Costa Rica', 'Bombay Tobak', 'Figurado', 'Belicoso', 'En mild til medium sigar med ecuadoriansk Connecticut Shade-dekkblad, håndrullet i Costa Rica.', true, 'retailer', 'https://cigar-coop.com/2018/01/cigar-review-mbombay-classic-torpedo-by-bombay-tobak.html', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'Classic', 'Perfecto', 'Ecuador', 'Connecticut Shade', 'Ecuador', ARRAY['Nicaragua','Dominican Republic','Peru'], 2, 'Costa Rica', 'Bombay Tobak', 'Figurado', 'Perfecto', 'En mild til medium sigar med ecuadoriansk Connecticut Shade-dekkblad, håndrullet i Costa Rica.', true, 'retailer', 'https://cigar-coop.com/2018/01/cigar-review-mbombay-classic-torpedo-by-bombay-tobak.html', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'Classic', 'Torpedo', 'Ecuador', 'Connecticut Shade', 'Ecuador', ARRAY['Nicaragua','Dominican Republic','Peru'], 2, 'Costa Rica', 'Bombay Tobak', 'Figurado', 'Torpedo', 'En mild til medium sigar med ecuadoriansk Connecticut Shade-dekkblad, håndrullet i Costa Rica.', true, 'retailer', 'https://cigar-coop.com/2018/01/cigar-review-mbombay-classic-torpedo-by-bombay-tobak.html', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'Classic', 'Churchill', 'Ecuador', 'Connecticut Shade', 'Ecuador', ARRAY['Nicaragua','Dominican Republic','Peru'], 2, 'Costa Rica', 'Bombay Tobak', 'Parejo', 'Churchill', 'En mild til medium sigar med ecuadoriansk Connecticut Shade-dekkblad, håndrullet i Costa Rica.', true, 'retailer', 'https://cigar-coop.com/2018/01/cigar-review-mbombay-classic-torpedo-by-bombay-tobak.html', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'Corojo Oscuro', 'Robusto', 'Ecuador', 'Corojo Oscuro', 'Ecuador', ARRAY['Ecuador','Peru','Dominican Republic'], 3, 'Costa Rica', 'Bombay Tobak', 'Parejo', 'Robusto', 'En medium-kraftig sigar med mørkt ecuadoriansk Corojo Oscuro-dekkblad, produsert i Costa Rica.', true, 'retailer', 'https://cigar-coop.com/2017/05/cigar-review-mbombay-corojo-oscuro-gordo.html', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'Corojo Oscuro', 'Perfecto', 'Ecuador', 'Corojo Oscuro', 'Ecuador', ARRAY['Ecuador','Peru','Dominican Republic'], 3, 'Costa Rica', 'Bombay Tobak', 'Figurado', 'Perfecto', 'En medium-kraftig sigar med mørkt ecuadoriansk Corojo Oscuro-dekkblad, produsert i Costa Rica.', true, 'retailer', 'https://cigar-coop.com/2017/05/cigar-review-mbombay-corojo-oscuro-gordo.html', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'Corojo Oscuro', 'Gordo', 'Ecuador', 'Corojo Oscuro', 'Ecuador', ARRAY['Ecuador','Peru','Dominican Republic'], 3, 'Costa Rica', 'Bombay Tobak', 'Parejo', 'Gordo', 'En medium-kraftig sigar med mørkt ecuadoriansk Corojo Oscuro-dekkblad, produsert i Costa Rica.', true, 'retailer', 'https://cigar-coop.com/2017/05/cigar-review-mbombay-corojo-oscuro-gordo.html', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'Corojo Oscuro', 'Churchill', 'Ecuador', 'Corojo Oscuro', 'Ecuador', ARRAY['Ecuador','Peru','Dominican Republic'], 3, 'Costa Rica', 'Bombay Tobak', 'Parejo', 'Churchill', 'En medium-kraftig sigar med mørkt ecuadoriansk Corojo Oscuro-dekkblad, produsert i Costa Rica.', true, 'retailer', 'https://cigar-coop.com/2017/05/cigar-review-mbombay-corojo-oscuro-gordo.html', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'Corojo Oscuro', 'Double Corona', 'Ecuador', 'Corojo Oscuro', 'Ecuador', ARRAY['Ecuador','Peru','Dominican Republic'], 3, 'Costa Rica', 'Bombay Tobak', 'Parejo', 'Double Corona', 'En medium-kraftig sigar med mørkt ecuadoriansk Corojo Oscuro-dekkblad, produsert i Costa Rica.', true, 'retailer', 'https://cigar-coop.com/2017/05/cigar-review-mbombay-corojo-oscuro-gordo.html', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'Gaaja', 'Toro', 'Ecuador', 'Habano Hybrid', 'Ecuador', ARRAY['Dominican Republic','Ecuador','Peru','Paraguay'], NULL, 'Costa Rica', 'Bombay Tobak', 'Parejo', 'Toro', 'En boks-presset sigar med ecuadoriansk hybrid-dekkblad og kompleks fyll fra flere land.', true, 'retailer', 'https://halfwheel.com/mbombay-gaaja-maduro-torpedo/145611/', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'Gaaja Maduro', 'Toro', 'Brazil', 'Mata Fina', 'Ecuador', ARRAY['Dominican Republic','Ecuador','Paraguay','Peru'], NULL, 'Costa Rica', 'Bombay Tobak', 'Parejo', 'Toro', 'En boks-presset maduro med brasiliansk Mata Fina-dekkblad, produsert i Costa Rica.', true, 'retailer', 'https://halfwheel.com/mbombay-gaaja-maduro-torpedo/145611/', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'Gaaja Maduro', 'Torpedo', 'Brazil', 'Mata Fina', 'Ecuador', ARRAY['Dominican Republic','Ecuador','Paraguay','Peru'], NULL, 'Costa Rica', 'Bombay Tobak', 'Figurado', 'Torpedo', 'En boks-presset maduro med brasiliansk Mata Fina-dekkblad, produsert i Costa Rica.', true, 'retailer', 'https://halfwheel.com/mbombay-gaaja-maduro-torpedo/145611/', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'KeSara', 'Robusto Largo', 'Ecuador', 'Connecticut Desflorado', 'Ecuador', ARRAY['Dominican Republic','Peru'], NULL, 'Costa Rica', 'Bombay Tobak', 'Parejo', 'Robusto Largo', 'En sigar med ecuadoriansk Connecticut Desflorado-dekkblad og dominikansk og peruansk fyll.', true, 'retailer', 'https://cigar-coop.com/2016/04/cigar-review-mbombay-kesara-a.html', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'KeSara', 'No. 4', 'Ecuador', 'Connecticut Desflorado', 'Ecuador', ARRAY['Dominican Republic','Peru'], NULL, 'Costa Rica', 'Bombay Tobak', 'Parejo', 'No. 4', 'En sigar med ecuadoriansk Connecticut Desflorado-dekkblad og dominikansk og peruansk fyll.', true, 'retailer', 'https://cigar-coop.com/2016/04/cigar-review-mbombay-kesara-a.html', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'KeSara', '585', 'Ecuador', 'Connecticut Desflorado', 'Ecuador', ARRAY['Dominican Republic','Peru'], NULL, 'Costa Rica', 'Bombay Tobak', 'Parejo', '585', 'En sigar med ecuadoriansk Connecticut Desflorado-dekkblad og dominikansk og peruansk fyll.', true, 'retailer', 'https://cigar-coop.com/2016/04/cigar-review-mbombay-kesara-a.html', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'KeSara', 'No. 2', 'Ecuador', 'Connecticut Desflorado', 'Ecuador', ARRAY['Dominican Republic','Peru'], NULL, 'Costa Rica', 'Bombay Tobak', 'Parejo', 'No. 2', 'En sigar med ecuadoriansk Connecticut Desflorado-dekkblad og dominikansk og peruansk fyll.', true, 'retailer', 'https://cigar-coop.com/2016/04/cigar-review-mbombay-kesara-a.html', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'KeSara', 'Salomon', 'Ecuador', 'Connecticut Desflorado', 'Ecuador', ARRAY['Dominican Republic','Peru'], NULL, 'Costa Rica', 'Bombay Tobak', 'Figurado', 'Salomon', 'En sigar med ecuadoriansk Connecticut Desflorado-dekkblad og dominikansk og peruansk fyll.', true, 'retailer', 'https://cigar-coop.com/2016/04/cigar-review-mbombay-kesara-a.html', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'KeSara', 'Toro', 'Ecuador', 'Connecticut Desflorado', 'Ecuador', ARRAY['Dominican Republic','Peru'], NULL, 'Costa Rica', 'Bombay Tobak', 'Parejo', 'Toro', 'En sigar med ecuadoriansk Connecticut Desflorado-dekkblad og dominikansk og peruansk fyll.', true, 'retailer', 'https://cigar-coop.com/2016/04/cigar-review-mbombay-kesara-a.html', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'KeSara', 'Pyramid', 'Ecuador', 'Connecticut Desflorado', 'Ecuador', ARRAY['Dominican Republic','Peru'], NULL, 'Costa Rica', 'Bombay Tobak', 'Figurado', 'Pyramid', 'En sigar med ecuadoriansk Connecticut Desflorado-dekkblad og dominikansk og peruansk fyll.', true, 'retailer', 'https://cigar-coop.com/2016/04/cigar-review-mbombay-kesara-a.html', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'KeSara', 'A', 'Ecuador', 'Connecticut Desflorado', 'Ecuador', ARRAY['Dominican Republic','Peru'], NULL, 'Costa Rica', 'Bombay Tobak', 'Parejo', 'A', 'En sigar med ecuadoriansk Connecticut Desflorado-dekkblad og dominikansk og peruansk fyll.', true, 'retailer', 'https://cigar-coop.com/2016/04/cigar-review-mbombay-kesara-a.html', now(), ARRAY['MBombay','Bombay','Bombay Tobak']),
('MBombay', 'Vintage Reserve', 'Lancero 1973', 'Ecuador', 'Desflorado', NULL, NULL, NULL, 'Costa Rica', 'Bombay Tobak', 'Parejo', 'Lancero 1973', 'En eksklusiv serie med ecuadoriansk Desflorado-dekkblad, produsert i Costa Rica.', true, 'retailer', 'https://cigarpress.com/bombay-tobak-mbombay-vintage-reserve/', now(), ARRAY['MBombay','Bombay','Bombay Tobak']);

-- Casa Cuevas
INSERT INTO public.cigars
  (brand, series, vitola, wrapper_country, wrapper_leaf, binder, filler, strength,
   country_origin, manufacturer, shape, common_format, description, is_public,
   source_tier, source_url, verified_at, aliases)
VALUES
('Casa Cuevas', 'Connecticut', 'Robusto', 'Ecuador', 'Connecticut', 'Nicaragua', ARRAY['Nicaragua','Dominican Republic'], 2, 'Dominican Republic', 'Tabacalera Las Lavas', 'Parejo', 'Robusto', 'En mild og tilgjengelig sigar med ecuadoriansk Connecticut-dekkblad, for alt fra nybegynnere til daglige nytere.', true, 'retailer', 'https://cigardojo.com/2018/04/casa-cuevas-connecticut-robusto/', now(), ARRAY['Casa Cuevas']),
('Casa Cuevas', 'Connecticut', 'Toro', 'Ecuador', 'Connecticut', 'Nicaragua', ARRAY['Nicaragua','Dominican Republic'], 2, 'Dominican Republic', 'Tabacalera Las Lavas', 'Parejo', 'Toro', 'En mild og tilgjengelig sigar med ecuadoriansk Connecticut-dekkblad, for alt fra nybegynnere til daglige nytere.', true, 'retailer', 'https://cigardojo.com/2018/04/casa-cuevas-connecticut-robusto/', now(), ARRAY['Casa Cuevas']),
('Casa Cuevas', 'Connecticut', 'Gordo', 'Ecuador', 'Connecticut', 'Nicaragua', ARRAY['Nicaragua','Dominican Republic'], 2, 'Dominican Republic', 'Tabacalera Las Lavas', 'Parejo', 'Gordo', 'En mild og tilgjengelig sigar med ecuadoriansk Connecticut-dekkblad, for alt fra nybegynnere til daglige nytere.', true, 'retailer', 'https://cigardojo.com/2018/04/casa-cuevas-connecticut-robusto/', now(), ARRAY['Casa Cuevas']),
('Casa Cuevas', 'Habano', 'Robusto', 'Ecuador', 'Habano', 'Nicaragua', ARRAY['Dominican Republic','Nicaragua'], 3, 'Dominican Republic', 'Tabacalera Las Lavas', 'Parejo', 'Robusto', 'En medium sigar med ecuadoriansk Habano-dekkblad som gir en balansert og krydret smaksprofil.', true, 'retailer', 'https://blindmanspuff.com/blind-cigar-review-casa-cuevas-habano-toro/', now(), ARRAY['Casa Cuevas']),
('Casa Cuevas', 'Habano', 'Toro', 'Ecuador', 'Habano', 'Nicaragua', ARRAY['Dominican Republic','Nicaragua'], 3, 'Dominican Republic', 'Tabacalera Las Lavas', 'Parejo', 'Toro', 'En medium sigar med ecuadoriansk Habano-dekkblad som gir en balansert og krydret smaksprofil.', true, 'retailer', 'https://blindmanspuff.com/blind-cigar-review-casa-cuevas-habano-toro/', now(), ARRAY['Casa Cuevas']),
('Casa Cuevas', 'Habano', 'Gordo', 'Ecuador', 'Habano', 'Nicaragua', ARRAY['Dominican Republic','Nicaragua'], 3, 'Dominican Republic', 'Tabacalera Las Lavas', 'Parejo', 'Gordo', 'En medium sigar med ecuadoriansk Habano-dekkblad som gir en balansert og krydret smaksprofil.', true, 'retailer', 'https://blindmanspuff.com/blind-cigar-review-casa-cuevas-habano-toro/', now(), ARRAY['Casa Cuevas']),
('Casa Cuevas', 'Maduro', 'Robusto', 'Mexico', 'San Andrés', 'Nicaragua', ARRAY['Colombia','Dominican Republic','Nicaragua','Pennsylvania'], 4, 'Dominican Republic', 'Tabacalera Las Lavas', 'Parejo', 'Robusto', 'En fyldig sigar med meksikansk San Andrés maduro-dekkblad og søte, mørke toner.', true, 'retailer', 'https://halfwheel.com/casa-cuevas-maduro-toro/152909/', now(), ARRAY['Casa Cuevas']),
('Casa Cuevas', 'Maduro', 'Toro', 'Mexico', 'San Andrés', 'Nicaragua', ARRAY['Colombia','Dominican Republic','Nicaragua','Pennsylvania'], 4, 'Dominican Republic', 'Tabacalera Las Lavas', 'Parejo', 'Toro', 'En fyldig sigar med meksikansk San Andrés maduro-dekkblad og søte, mørke toner.', true, 'retailer', 'https://halfwheel.com/casa-cuevas-maduro-toro/152909/', now(), ARRAY['Casa Cuevas']),
('Casa Cuevas', 'Maduro', 'Gordo', 'Mexico', 'San Andrés', 'Nicaragua', ARRAY['Colombia','Dominican Republic','Nicaragua','Pennsylvania'], 4, 'Dominican Republic', 'Tabacalera Las Lavas', 'Parejo', 'Gordo', 'En fyldig sigar med meksikansk San Andrés maduro-dekkblad og søte, mørke toner.', true, 'retailer', 'https://halfwheel.com/casa-cuevas-maduro-toro/152909/', now(), ARRAY['Casa Cuevas']),
('Casa Cuevas', 'Prensado Habano', 'Prensado', 'Ecuador', 'Habano', 'Nicaragua', ARRAY['Dominican Republic','Nicaragua'], 3, 'Dominican Republic', 'Tabacalera Las Lavas', 'Parejo', 'Prensado', 'En boks-presset sigar med ecuadoriansk Habano-dekkblad der presset fremhever dekkblad og bindeblad i smaken.', true, 'retailer', 'https://halfwheel.com/casa-cuevas-rebrands-prensado-line/400825/', now(), ARRAY['Casa Cuevas']),
('Casa Cuevas', 'Prensado Maduro', 'Prensado', 'Mexico', 'San Andrés', 'Nicaragua', ARRAY['Dominican Republic','Nicaragua'], 4, 'Dominican Republic', 'Tabacalera Las Lavas', 'Parejo', 'Prensado', 'En boks-presset maduro med meksikansk San Andrés-dekkblad og dype, mørke smaksnyanser.', true, 'retailer', 'https://halfwheel.com/casa-cuevas-rebrands-prensado-line/400825/', now(), ARRAY['Casa Cuevas']),
('Casa Cuevas', 'Patrimonio', 'Robusto Gordo', 'Honduras', 'Corojo', 'Ecuadorian Habano', ARRAY['Nicaragua','Peru','Dominican Republic'], 4, 'Dominican Republic', 'Tabacalera Las Lavas', 'Parejo', 'Robusto Gordo', 'En fyldig og kompleks sigar med honduransk Corojo-dekkblad, som en hyllest til familiens tobakksarv.', true, 'retailer', 'https://halfwheel.com/casa-cuevas-patrimonio-toro/401242/', now(), ARRAY['Casa Cuevas']),
('Casa Cuevas', 'Patrimonio', 'Toro', 'Honduras', 'Corojo', 'Ecuadorian Habano', ARRAY['Nicaragua','Peru','Dominican Republic'], 4, 'Dominican Republic', 'Tabacalera Las Lavas', 'Parejo', 'Toro', 'En fyldig og kompleks sigar med honduransk Corojo-dekkblad, som en hyllest til familiens tobakksarv.', true, 'retailer', 'https://halfwheel.com/casa-cuevas-patrimonio-toro/401242/', now(), ARRAY['Casa Cuevas']),
('Casa Cuevas', 'Patrimonio', 'Gordo', 'Honduras', 'Corojo', 'Ecuadorian Habano', ARRAY['Nicaragua','Peru','Dominican Republic'], 4, 'Dominican Republic', 'Tabacalera Las Lavas', 'Parejo', 'Gordo', 'En fyldig og kompleks sigar med honduransk Corojo-dekkblad, som en hyllest til familiens tobakksarv.', true, 'retailer', 'https://halfwheel.com/casa-cuevas-patrimonio-toro/401242/', now(), ARRAY['Casa Cuevas']),
('Casa Cuevas', 'Sangre Nueva', 'Robusto', 'Ecuador', 'Cameroon', 'Honduran Corojo', ARRAY['Dominican Republic','Nicaragua','Pennsylvania','Kentucky'], 4, 'Dominican Republic', 'Tabacalera Las Lavas', 'Parejo', 'Robusto', 'En fyldig sigar med ecuadoriansk Cameroon-frø-dekkblad og litt ild-tørket Kentucky-tobakk for ekstra dybde.', true, 'retailer', 'https://halfwheel.com/casa-cuevas-sangre-nueva-toro-2/434540/', now(), ARRAY['Casa Cuevas']),
('Casa Cuevas', 'Sangre Nueva', 'Toro', 'Ecuador', 'Cameroon', 'Honduran Corojo', ARRAY['Dominican Republic','Nicaragua','Pennsylvania','Kentucky'], 4, 'Dominican Republic', 'Tabacalera Las Lavas', 'Parejo', 'Toro', 'En fyldig sigar med ecuadoriansk Cameroon-frø-dekkblad og litt ild-tørket Kentucky-tobakk for ekstra dybde.', true, 'retailer', 'https://halfwheel.com/casa-cuevas-sangre-nueva-toro-2/434540/', now(), ARRAY['Casa Cuevas']),
('Casa Cuevas', 'Sangre Nueva', 'Double Perfecto', 'Ecuador', 'Cameroon', 'Honduran Corojo', ARRAY['Dominican Republic','Nicaragua','Pennsylvania','Kentucky'], 4, 'Dominican Republic', 'Tabacalera Las Lavas', 'Figurado', 'Double Perfecto', 'En fyldig sigar med ecuadoriansk Cameroon-frø-dekkblad og litt ild-tørket Kentucky-tobakk for ekstra dybde.', true, 'retailer', 'https://halfwheel.com/casa-cuevas-sangre-nueva-toro-2/434540/', now(), ARRAY['Casa Cuevas']),
('Casa Cuevas', 'Reserva Maduro', 'Robusto', 'Mexico', 'San Andrés', 'Dominican Piloto Cubano', ARRAY['Dominican Republic','Nicaragua'], 4, 'Dominican Republic', 'Tabacalera Las Lavas', 'Parejo', 'Robusto', 'En medium-fyldig maduro med meksikansk San Andrés-dekkblad over dominikansk Piloto Cubano-bindeblad.', true, 'retailer', 'https://halfwheel.com/casa-cuevas-reserva-maduro-toro/369107/', now(), ARRAY['Casa Cuevas']),
('Casa Cuevas', 'Reserva Maduro', 'Toro', 'Mexico', 'San Andrés', 'Dominican Piloto Cubano', ARRAY['Dominican Republic','Nicaragua'], 4, 'Dominican Republic', 'Tabacalera Las Lavas', 'Parejo', 'Toro', 'En medium-fyldig maduro med meksikansk San Andrés-dekkblad over dominikansk Piloto Cubano-bindeblad.', true, 'retailer', 'https://halfwheel.com/casa-cuevas-reserva-maduro-toro/369107/', now(), ARRAY['Casa Cuevas']),
('Casa Cuevas', 'Reserva Maduro', 'Torpedo', 'Mexico', 'San Andrés', 'Dominican Piloto Cubano', ARRAY['Dominican Republic','Nicaragua'], 4, 'Dominican Republic', 'Tabacalera Las Lavas', 'Figurado', 'Torpedo', 'En medium-fyldig maduro med meksikansk San Andrés-dekkblad over dominikansk Piloto Cubano-bindeblad.', true, 'retailer', 'https://halfwheel.com/casa-cuevas-reserva-maduro-toro/369107/', now(), ARRAY['Casa Cuevas']),
('Casa Cuevas', 'La Mandarria', 'Toro', 'Ecuador', 'Habano', 'Nicaragua', ARRAY['Colombia','Dominican Republic','Nicaragua'], 5, 'Dominican Republic', 'Tabacalera Las Lavas', 'Parejo', 'Toro', 'Den sterkeste og fyldigste sigaren i porteføljen, med ecuadoriansk Habano-dekkblad og en karakteristisk pigtail-topp.', true, 'retailer', 'https://halfwheel.com/casa-cuevas-makes-la-mandarria-regular-production-updates-bands/371825/', now(), ARRAY['Casa Cuevas']);

-- Casa 1910
INSERT INTO public.cigars
  (brand, series, vitola, wrapper_country, wrapper_leaf, binder, filler, strength,
   country_origin, manufacturer, shape, common_format, description, is_public,
   source_tier, source_url, verified_at, aliases)
VALUES
('Casa 1910', 'Cuchillo Parado', 'Corona', 'Mexico', 'Mexican Sumatra', 'Mexican San Andrés Negro', ARRAY['Mexico'], 3, 'Mexico', 'Casa 1910', 'Parejo', 'Corona', 'Casa 1910s flaggskip — en mellomsterk meksikansk puro med Sumatra-dekkblad rundt aldret San Andrés-tobakk fra Veracruz.', true, 'manufacturer', 'https://www.casa1910.com/en/products/cuchillo-parado', now(), ARRAY['Casa 1910','1910']),
('Casa 1910', 'Cuchillo Parado', 'Robusto', 'Mexico', 'Mexican Sumatra', 'Mexican San Andrés Negro', ARRAY['Mexico'], 3, 'Mexico', 'Casa 1910', 'Parejo', 'Robusto', 'Casa 1910s flaggskip — en mellomsterk meksikansk puro med Sumatra-dekkblad rundt aldret San Andrés-tobakk fra Veracruz.', true, 'manufacturer', 'https://www.casa1910.com/en/products/cuchillo-parado', now(), ARRAY['Casa 1910','1910']),
('Casa 1910', 'Cuchillo Parado', 'Toro', 'Mexico', 'Mexican Sumatra', 'Mexican San Andrés Negro', ARRAY['Mexico'], 3, 'Mexico', 'Casa 1910', 'Parejo', 'Toro', 'Casa 1910s flaggskip — en mellomsterk meksikansk puro med Sumatra-dekkblad rundt aldret San Andrés-tobakk fra Veracruz.', true, 'manufacturer', 'https://www.casa1910.com/en/products/cuchillo-parado', now(), ARRAY['Casa 1910','1910']),
('Casa 1910', 'Tierra Blanca', 'Corona', 'Mexico', 'San Andrés Negro Maduro', 'Mexican San Andrés Negro', ARRAY['Mexico'], 5, 'Mexico', 'Casa 1910', 'Parejo', 'Corona', 'En fyldig og kraftfull meksikansk San Andrés-puro med maduro-dekkblad, aldret fem år for dyp og intens smak.', true, 'manufacturer', 'https://www.casa1910.com/en/products/tierra-blanca', now(), ARRAY['Casa 1910','1910']),
('Casa 1910', 'Tierra Blanca', 'Robusto', 'Mexico', 'San Andrés Negro Maduro', 'Mexican San Andrés Negro', ARRAY['Mexico'], 5, 'Mexico', 'Casa 1910', 'Parejo', 'Robusto', 'En fyldig og kraftfull meksikansk San Andrés-puro med maduro-dekkblad, aldret fem år for dyp og intens smak.', true, 'manufacturer', 'https://www.casa1910.com/en/products/tierra-blanca', now(), ARRAY['Casa 1910','1910']),
('Casa 1910', 'Tierra Blanca', 'Toro', 'Mexico', 'San Andrés Negro Maduro', 'Mexican San Andrés Negro', ARRAY['Mexico'], 5, 'Mexico', 'Casa 1910', 'Parejo', 'Toro', 'En fyldig og kraftfull meksikansk San Andrés-puro med maduro-dekkblad, aldret fem år for dyp og intens smak.', true, 'manufacturer', 'https://www.casa1910.com/en/products/tierra-blanca', now(), ARRAY['Casa 1910','1910']),
('Casa 1910', 'El Ebano', 'Corona', 'Mexico', 'San Andrés Colorado Maduro', 'Mexican San Andrés Claro', ARRAY['Mexico'], 4, 'Mexico', 'Casa 1910', 'Parejo', 'Corona', 'En mellomsterk til fyldig meksikansk puro med Colorado Maduro San Andrés-dekkblad over en meksikansk blanding aldret fem år.', true, 'manufacturer', 'https://www.casa1910.com/en/products/el-ebano', now(), ARRAY['Casa 1910','1910']),
('Casa 1910', 'El Ebano', 'Robusto', 'Mexico', 'San Andrés Colorado Maduro', 'Mexican San Andrés Claro', ARRAY['Mexico'], 4, 'Mexico', 'Casa 1910', 'Parejo', 'Robusto', 'En mellomsterk til fyldig meksikansk puro med Colorado Maduro San Andrés-dekkblad over en meksikansk blanding aldret fem år.', true, 'manufacturer', 'https://www.casa1910.com/en/products/el-ebano', now(), ARRAY['Casa 1910','1910']),
('Casa 1910', 'El Ebano', 'Toro', 'Mexico', 'San Andrés Colorado Maduro', 'Mexican San Andrés Claro', ARRAY['Mexico'], 4, 'Mexico', 'Casa 1910', 'Parejo', 'Toro', 'En mellomsterk til fyldig meksikansk puro med Colorado Maduro San Andrés-dekkblad over en meksikansk blanding aldret fem år.', true, 'manufacturer', 'https://www.casa1910.com/en/products/el-ebano', now(), ARRAY['Casa 1910','1910']);

-- Regius
INSERT INTO public.cigars
  (brand, series, vitola, wrapper_country, wrapper_leaf, binder, filler, strength,
   country_origin, manufacturer, shape, common_format, description, is_public,
   source_tier, source_url, verified_at, aliases)
VALUES
('Regius', 'Original', 'Corona', 'Nicaragua', 'Nicaraguan', 'Nicaraguan', ARRAY['Nicaraguan'], 3, 'Nicaragua', 'Regius Cigars', 'Parejo', 'Corona', 'Regius'' opprinnelige helnikaraguanske blanding, håndrullet hos Plasencia i Estelí, med balansert medium styrke.', true, 'retailer', 'https://halfwheel.com/regius-robusto/21696/', now(), ARRAY['Regius']),
('Regius', 'Original', 'Robusto', 'Nicaragua', 'Nicaraguan', 'Nicaraguan', ARRAY['Nicaraguan'], 3, 'Nicaragua', 'Regius Cigars', 'Parejo', 'Robusto', 'Regius'' opprinnelige helnikaraguanske blanding, håndrullet hos Plasencia i Estelí, med balansert medium styrke.', true, 'retailer', 'https://halfwheel.com/regius-robusto/21696/', now(), ARRAY['Regius']),
('Regius', 'Original', 'Toro', 'Nicaragua', 'Nicaraguan', 'Nicaraguan', ARRAY['Nicaraguan'], 3, 'Nicaragua', 'Regius Cigars', 'Parejo', 'Toro', 'Regius'' opprinnelige helnikaraguanske blanding, håndrullet hos Plasencia i Estelí, med balansert medium styrke.', true, 'retailer', 'https://halfwheel.com/regius-robusto/21696/', now(), ARRAY['Regius']),
('Regius', 'Original', 'Grandido', 'Nicaragua', 'Nicaraguan', 'Nicaraguan', ARRAY['Nicaraguan'], 3, 'Nicaragua', 'Regius Cigars', 'Parejo', 'Grandido', 'Regius'' opprinnelige helnikaraguanske blanding, håndrullet hos Plasencia i Estelí, med balansert medium styrke.', true, 'retailer', 'https://halfwheel.com/regius-robusto/21696/', now(), ARRAY['Regius']),
('Regius', 'Original', 'Gran Toro', 'Nicaragua', 'Nicaraguan', 'Nicaraguan', ARRAY['Nicaraguan'], 3, 'Nicaragua', 'Regius Cigars', 'Parejo', 'Gran Toro', 'Regius'' opprinnelige helnikaraguanske blanding, håndrullet hos Plasencia i Estelí, med balansert medium styrke.', true, 'retailer', 'https://halfwheel.com/regius-robusto/21696/', now(), ARRAY['Regius']),
('Regius', 'Connecticut', 'Corona', 'Honduras', 'Connecticut Shade', 'Nicaraguan', ARRAY['Nicaraguan'], NULL, 'Nicaragua', 'Regius Cigars', 'Parejo', 'Corona', 'En mildere Regius med honduransk Connecticut Shade-dekkblad fra Talanga og nicaraguansk bind og innmat.', true, 'retailer', 'https://cigar-coop.com/2017/08/cigar-news-regius-connecticut-showcased-at-2017-ipcpr.html', now(), ARRAY['Regius']),
('Regius', 'Connecticut', 'Robusto', 'Honduras', 'Connecticut Shade', 'Nicaraguan', ARRAY['Nicaraguan'], NULL, 'Nicaragua', 'Regius Cigars', 'Parejo', 'Robusto', 'En mildere Regius med honduransk Connecticut Shade-dekkblad fra Talanga og nicaraguansk bind og innmat.', true, 'retailer', 'https://cigar-coop.com/2017/08/cigar-news-regius-connecticut-showcased-at-2017-ipcpr.html', now(), ARRAY['Regius']),
('Regius', 'Connecticut', 'Toro', 'Honduras', 'Connecticut Shade', 'Nicaraguan', ARRAY['Nicaraguan'], NULL, 'Nicaragua', 'Regius Cigars', 'Parejo', 'Toro', 'En mildere Regius med honduransk Connecticut Shade-dekkblad fra Talanga og nicaraguansk bind og innmat.', true, 'retailer', 'https://cigar-coop.com/2017/08/cigar-news-regius-connecticut-showcased-at-2017-ipcpr.html', now(), ARRAY['Regius']),
('Regius', 'Connecticut', 'Grandido', 'Honduras', 'Connecticut Shade', 'Nicaraguan', ARRAY['Nicaraguan'], NULL, 'Nicaragua', 'Regius Cigars', 'Parejo', 'Grandido', 'En mildere Regius med honduransk Connecticut Shade-dekkblad fra Talanga og nicaraguansk bind og innmat.', true, 'retailer', 'https://cigar-coop.com/2017/08/cigar-news-regius-connecticut-showcased-at-2017-ipcpr.html', now(), ARRAY['Regius']),
('Regius', 'Connecticut', 'Gran Toro', 'Honduras', 'Connecticut Shade', 'Nicaraguan', ARRAY['Nicaraguan'], NULL, 'Nicaragua', 'Regius Cigars', 'Parejo', 'Gran Toro', 'En mildere Regius med honduransk Connecticut Shade-dekkblad fra Talanga og nicaraguansk bind og innmat.', true, 'retailer', 'https://cigar-coop.com/2017/08/cigar-news-regius-connecticut-showcased-at-2017-ipcpr.html', now(), ARRAY['Regius']),
('Regius', 'Sun Grown', 'Corona', 'Nicaragua', 'Nicaraguan Sun Grown', 'Nicaraguan', ARRAY['Nicaraguan'], 4, 'Nicaragua', 'Regius Cigars', 'Parejo', 'Corona', 'Et mørkere, høyt-priming nikaraguansk soldyrket dekkblad over helnikaraguansk innmat gir en fyldigere medium-til-full profil.', true, 'retailer', 'https://cigar-coop.com/2019/05/cigar-review-regius-sun-grown-robusto.html', now(), ARRAY['Regius']),
('Regius', 'Sun Grown', 'Robusto', 'Nicaragua', 'Nicaraguan Sun Grown', 'Nicaraguan', ARRAY['Nicaraguan'], 4, 'Nicaragua', 'Regius Cigars', 'Parejo', 'Robusto', 'Et mørkere, høyt-priming nikaraguansk soldyrket dekkblad over helnikaraguansk innmat gir en fyldigere medium-til-full profil.', true, 'retailer', 'https://cigar-coop.com/2019/05/cigar-review-regius-sun-grown-robusto.html', now(), ARRAY['Regius']),
('Regius', 'Sun Grown', 'Toro', 'Nicaragua', 'Nicaraguan Sun Grown', 'Nicaraguan', ARRAY['Nicaraguan'], 4, 'Nicaragua', 'Regius Cigars', 'Parejo', 'Toro', 'Et mørkere, høyt-priming nikaraguansk soldyrket dekkblad over helnikaraguansk innmat gir en fyldigere medium-til-full profil.', true, 'retailer', 'https://cigar-coop.com/2019/05/cigar-review-regius-sun-grown-robusto.html', now(), ARRAY['Regius']),
('Regius', 'Sun Grown', 'Grandido', 'Nicaragua', 'Nicaraguan Sun Grown', 'Nicaraguan', ARRAY['Nicaraguan'], 4, 'Nicaragua', 'Regius Cigars', 'Parejo', 'Grandido', 'Et mørkere, høyt-priming nikaraguansk soldyrket dekkblad over helnikaraguansk innmat gir en fyldigere medium-til-full profil.', true, 'retailer', 'https://cigar-coop.com/2019/05/cigar-review-regius-sun-grown-robusto.html', now(), ARRAY['Regius']),
('Regius', 'Sun Grown', 'Gran Toro', 'Nicaragua', 'Nicaraguan Sun Grown', 'Nicaraguan', ARRAY['Nicaraguan'], 4, 'Nicaragua', 'Regius Cigars', 'Parejo', 'Gran Toro', 'Et mørkere, høyt-priming nikaraguansk soldyrket dekkblad over helnikaraguansk innmat gir en fyldigere medium-til-full profil.', true, 'retailer', 'https://cigar-coop.com/2019/05/cigar-review-regius-sun-grown-robusto.html', now(), ARRAY['Regius']),
('Regius', 'Maduro', 'Corona', NULL, 'Maduro', NULL, NULL, NULL, 'Nicaragua', 'Regius Cigars', 'Parejo', 'Corona', 'En mørk maduro-utgave av Regius produsert hos Plasencia i Nicaragua, med bladdetaljer som ikke er offentliggjort.', true, 'retailer', 'https://halfwheel.com/regius-maduro-corona/269995/', now(), ARRAY['Regius']),
('Regius', 'Maduro', 'Robusto', NULL, 'Maduro', NULL, NULL, NULL, 'Nicaragua', 'Regius Cigars', 'Parejo', 'Robusto', 'En mørk maduro-utgave av Regius produsert hos Plasencia i Nicaragua, med bladdetaljer som ikke er offentliggjort.', true, 'retailer', 'https://halfwheel.com/regius-maduro-corona/269995/', now(), ARRAY['Regius']),
('Regius', 'Maduro', 'Toro', NULL, 'Maduro', NULL, NULL, NULL, 'Nicaragua', 'Regius Cigars', 'Parejo', 'Toro', 'En mørk maduro-utgave av Regius produsert hos Plasencia i Nicaragua, med bladdetaljer som ikke er offentliggjort.', true, 'retailer', 'https://halfwheel.com/regius-maduro-corona/269995/', now(), ARRAY['Regius']),
('Regius', 'Maduro', 'Grandido', NULL, 'Maduro', NULL, NULL, NULL, 'Nicaragua', 'Regius Cigars', 'Parejo', 'Grandido', 'En mørk maduro-utgave av Regius produsert hos Plasencia i Nicaragua, med bladdetaljer som ikke er offentliggjort.', true, 'retailer', 'https://halfwheel.com/regius-maduro-corona/269995/', now(), ARRAY['Regius']),
('Regius', 'Maduro', 'Gran Toro', NULL, 'Maduro', NULL, NULL, NULL, 'Nicaragua', 'Regius Cigars', 'Parejo', 'Gran Toro', 'En mørk maduro-utgave av Regius produsert hos Plasencia i Nicaragua, med bladdetaljer som ikke er offentliggjort.', true, 'retailer', 'https://halfwheel.com/regius-maduro-corona/269995/', now(), ARRAY['Regius']);
