-- 141: Gjenopprett mål (ring_gauge/length_inches) for batch-2-merkene fra 136.
-- Bug i 136: v-CTE-en hadde len/ring, men INSERT-en tok dem aldri med, så alle
-- radene ble lagret uten mål. Her settes de eksakte, researchede tallene inn igjen,
-- matchet paa brand+series+vitola. Idempotent: setter kun der maal fortsatt mangler.
UPDATE public.cigars c
SET ring_gauge = d.ring, length_inches = d.len
FROM (VALUES
  ('Meerapfel','Richard','Robusto',4.875,50),
  ('Meerapfel','Richard','Corona Gorda',5.5,46),
  ('Meerapfel','Richard','Double Robusto',5.75,52),
  ('Meerapfel','Richard','Pyramide',6.125,52),
  ('Meerapfel','Richard','Lonsdale',6.75,43),
  ('Meerapfel','Richard','Churchill',7.0,47),
  ('Meerapfel','Richard','Lancero',7.5,40),
  ('Meerapfel','Meir','Robusto',4.875,50),
  ('Meerapfel','Meir','Corona Gorda',5.5,46),
  ('Meerapfel','Meir','Double Robusto',5.75,52),
  ('Meerapfel','Meir','Pyramid',6.125,52),
  ('Meerapfel','Meir','Lonsdale',6.75,43),
  ('Meerapfel','Meir','Churchill',7.0,47),
  ('Meerapfel','Ernest','Robusto',4.875,50),
  ('Meerapfel','Ernest','Corona Gorda',5.5,46),
  ('Meerapfel','Ernest','Double Robusto',5.75,52),
  ('Meerapfel','Ernest','Lonsdale',6.75,43),
  ('Meerapfel','Ernest','Lancero',7.5,40),
  ('Lost & Found','Instant Classic Habano','Robusto',5.0,50),
  ('Lost & Found','Instant Classic Habano','Toro',6.75,50),
  ('Lost & Found','Instant Classic San Andrés','Corona',6.0,46),
  ('Lost & Found','Instant Classic San Andrés','Torpedo',6.0,52),
  ('Lost & Found','22 Minutes to Midnight Habano','Toro',6.0,52),
  ('Lost & Found','22 Minutes to Midnight Criollo','Robusto',5.5,50),
  ('Dapper','El Borracho','Robusto',5.0,50),
  ('Dapper','El Borracho','Edmundo',5.5,52),
  ('Dapper','El Borracho','Toro',6.0,54),
  ('Dapper','El Borracho','Belicoso',6.25,52),
  ('Dapper','El Borracho Maduro','Robusto',5.0,50),
  ('Dapper','El Borracho Maduro','Edmundo',5.5,52),
  ('Dapper','El Borracho Maduro','Toro',6.0,54),
  ('Dapper','El Borracho Maduro','Belicoso',6.25,52),
  ('Dapper','La Madrina','Robusto',5.0,50),
  ('Dapper','La Madrina','Toro',6.125,52),
  ('Dapper','La Madrina','Belicoso',6.25,52),
  ('Dapper','La Madrina','Corona Gorda',5.625,46),
  ('Dapper','La Madrina Shade','Robusto',5.0,50),
  ('Dapper','La Madrina Shade','Toro',6.125,52),
  ('Dapper','La Madrina Shade','Belicoso',6.25,52),
  ('Dapper','La Madrina Shade','Corona Gorda',5.625,46),
  ('Dapper','Cubo Sumatra','Corona Gorda',5.625,46),
  ('Dapper','Cubo Sumatra','Robusto',5.0,50),
  ('Dapper','Cubo Sumatra','Toro',6.125,52),
  ('Dapper','Cubo Sumatra','Toro Grande',6.0,54),
  ('Dapper','Desvalido','Lonsdale',6.5,46),
  ('Dapper','Desvalido','Robusto',5.0,50),
  ('Dapper','Desvalido','Toro',6.125,52),
  ('Dapper','Desvalido','Corona Doble',6.75,54),
  ('Dapper','Siempre','Rothchilds',4.5,50),
  ('Dapper','Siempre','Robusto',5.0,50),
  ('Dapper','Siempre','Corona Gorda',5.625,46),
  ('Dapper','Siempre','Toro',6.125,52),
  ('Dapper','Siempre','Toro Grande',6.0,54),
  ('Dapper','Cubata Cru Shade','Bucko',6.0,44),
  ('Dapper','Cubata Cru Shade','Blunderbuss',5.0,54),
  ('Dapper','Cubata Cru Shade','Bumbo',6.125,52),
  ('Dapper','Union Break','Connecticut Shade',4.0,38),
  ('Dapper','Union Break','Connecticut Broadleaf',4.0,38),
  ('Dapper','Union Break','Barberpole',4.0,38),
  ('Black Works Studio','NBK','Corona Larga',6.0,46),
  ('Black Works Studio','NBK','Robusto',5.0,50),
  ('Black Works Studio','Green Hornet','Perfecto',5.0,60),
  ('Black Works Studio','Green Hornet','Lancero',7.25,42),
  ('Black Works Studio','Killer Bee','Perfecto',4.5,46),
  ('Black Works Studio','Hyena','Corona Gorda',5.0,46),
  ('Black Works Studio','Hyena','Lonsdale',6.5,42),
  ('Black Works Studio','Boondock Saint','Corona Larga',6.25,46),
  ('Black Works Studio','Boondock Saint','Robusto',5.25,50),
  ('Black Works Studio','Rorschach','Petit Lancero',5.0,38),
  ('K by Karen Berger','Connecticut','Robusto',5.0,52),
  ('K by Karen Berger','Connecticut','Toro',6.0,52),
  ('K by Karen Berger','Cameroon','Robusto',5.0,52),
  ('K by Karen Berger','Cameroon','Toro',6.0,52),
  ('K by Karen Berger','Habano','Robusto',5.0,52),
  ('K by Karen Berger','Habano','Toro',6.0,52),
  ('K by Karen Berger','Maduro','Robusto',5.0,52),
  ('K by Karen Berger','Maduro','Toro',6.0,52),
  ('Kafie 1901','Maduro','Robusto',5.0,50),
  ('Kafie 1901','Maduro','Toro',5.75,54),
  ('Kafie 1901','Maduro','Belicoso',6.25,52),
  ('Kafie 1901','Maduro','Churchill',7.0,47),
  ('Kafie 1901','Maduro','Gran Toro',6.0,58),
  ('Kafie 1901','Connecticut','Robusto',5.0,50),
  ('Kafie 1901','Connecticut','Toro',5.75,54),
  ('Kafie 1901','Connecticut','Belicoso',6.25,52),
  ('Kafie 1901','Connecticut','Churchill',7.0,47),
  ('Kafie 1901','Connecticut','Gran Toro',6.0,58),
  ('Kafie 1901','Sumatra','Robusto',5.0,50),
  ('Kafie 1901','Sumatra','Toro',5.75,54),
  ('Kafie 1901','Sumatra','Belicoso',6.25,52),
  ('Kafie 1901','Sumatra','Churchill',7.0,47),
  ('Kafie 1901','Sumatra','Gran Toro',6.0,58),
  ('Kafie 1901','San Andrés','Robusto',5.0,50),
  ('Kafie 1901','San Andrés','Toro',5.75,54),
  ('Kafie 1901','San Andrés','Belicoso',6.25,52),
  ('Kafie 1901','San Andrés','Churchill',7.0,47),
  ('Kafie 1901','San Andrés','Gran Toro',6.0,58),
  ('Kafie 1901','Serie L Natural','Robusto',5.0,50),
  ('Kafie 1901','Serie L Natural','Toro',5.75,54),
  ('Kafie 1901','Serie L Natural','Belicoso',6.25,52),
  ('Kafie 1901','Serie L Natural','Churchill',7.0,47),
  ('Kafie 1901','Serie L Natural','Gran Toro',6.0,58),
  ('Kafie 1901','Don Kiki Brown Label','Figurado',4.5,52),
  ('Kafie 1901','Don Kiki Brown Label','Toro',6.0,52),
  ('Kafie 1901','Don Kiki Brown Label','Torpedo',6.0,54),
  ('Kafie 1901','Don Kiki Green Label','Robusto',5.0,52),
  ('Kafie 1901','Don Kiki Green Label','Toro',6.0,52),
  ('Kafie 1901','Don Kiki Green Label','Churchill',7.0,52),
  ('Kafie 1901','Don Kiki Green Label','Torpedo',6.0,54),
  ('Kafie 1901','Don Kiki White Label','Toro',6.0,52),
  ('Kafie 1901','Don Kiki White Label','Churchill',7.0,52),
  ('Kafie 1901','Don Kiki White Label','Chairman',6.0,60),
  ('Debonaire','Habano','First Degree',4.0,44),
  ('Debonaire','Habano','Robusto',5.25,50),
  ('Debonaire','Habano','Toro',6.0,54),
  ('Debonaire','Habano','Belicoso',6.0,54),
  ('Debonaire','Maduro','First Degree',4.0,44),
  ('Debonaire','Maduro','Sagita',5.5,38),
  ('Debonaire','Maduro','Robusto',5.25,50),
  ('Debonaire','Maduro','Belicoso',6.0,54),
  ('Debonaire','Maduro','Toro',6.0,54),
  ('Debonaire','Daybreak','First Degree',4.0,44),
  ('Debonaire','Daybreak','Sagita',5.5,38),
  ('Debonaire','Daybreak','Corona',6.0,46),
  ('Debonaire','Daybreak','Robusto',5.0,50),
  ('Debonaire','Daybreak','Toro',6.0,50),
  ('Debonaire','Daybreak','Belicoso',6.0,54),
  ('Hiram & Solomon','Traveling Man','Robusto',5.5,50),
  ('Hiram & Solomon','Traveling Man','Toro',6.0,52),
  ('Hiram & Solomon','Traveling Man','Torpedo',6.0,54),
  ('Hiram & Solomon','Traveling Man','Gran Toro',6.0,60),
  ('Hiram & Solomon','Master Mason','Robusto',5.0,52),
  ('Hiram & Solomon','Master Mason','Toro',6.0,52),
  ('Hiram & Solomon','Master Mason','Gran Toro',6.0,60),
  ('Hiram & Solomon','Fellow Craft','Gavel',5.0,60),
  ('Hiram & Solomon','Fellow Craft','Robusto',5.5,50),
  ('Hiram & Solomon','Fellow Craft','Toro',6.0,52),
  ('Hiram & Solomon','Fellow Craft','Gran Toro',6.0,60),
  ('Hiram & Solomon','Shriner','Petit Corona',5.5,42),
  ('Hiram & Solomon','Shriner','Robusto',5.5,50),
  ('Hiram & Solomon','Shriner','Toro',6.0,52),
  ('Hiram & Solomon','Shriner','Gran Toro',6.0,60),
  ('Hiram & Solomon','Entered Apprentice','Gavel',5.0,60),
  ('Hiram & Solomon','Entered Apprentice','Robusto',5.5,50),
  ('Hiram & Solomon','Entered Apprentice','Toro',6.0,52),
  ('Hiram & Solomon','Entered Apprentice','Gran Toro',6.0,60),
  ('Hiram & Solomon','Grand Architect','Robusto',5.0,50),
  ('Hiram & Solomon','Grand Architect','Toro',6.0,52),
  ('Hiram & Solomon','Grand Architect','Gran Toro',6.0,60),
  ('Hiram & Solomon','Veiled Prophet','Monarch',6.0,54),
  ('Hiram & Solomon','Veiled Prophet','Grand Monarch',7.0,60),
  ('Hiram & Solomon','Veiled Prophet','Lancero',7.0,38),
  ('West Tampa Tobacco','Red','Robusto',5.0,50),
  ('West Tampa Tobacco','Red','Toro',6.0,52),
  ('West Tampa Tobacco','Red','Gigante',6.0,60),
  ('West Tampa Tobacco','Red','Lancero',7.0,40),
  ('West Tampa Tobacco','White','Robusto',5.0,50),
  ('West Tampa Tobacco','White','Toro',6.0,52),
  ('West Tampa Tobacco','White','Gigante',6.0,60),
  ('West Tampa Tobacco','White','Lancero',7.0,40),
  ('West Tampa Tobacco','Black','Robusto',5.0,50),
  ('West Tampa Tobacco','Black','Toro',6.0,52),
  ('West Tampa Tobacco','Black','Gigante',6.0,60),
  ('West Tampa Tobacco','Black','Lancero',7.0,40),
  ('Tabanero','Habano','Corona',5.0,42),
  ('Tabanero','Habano','Robusto',5.0,50),
  ('Tabanero','Habano','Toro',6.0,52),
  ('Tabanero','Habano','Churchill',7.0,50),
  ('Tabanero','Habano','Torpedo',6.5,54),
  ('Tabanero','Connecticut','Robusto',5.0,50),
  ('Tabanero','Connecticut','Toro',6.0,52),
  ('Tabanero','Connecticut','Churchill',7.0,50),
  ('Tabanero','Connecticut','Big Daddy',6.5,60),
  ('Tabanero','Momentum Maduro','Robusto',5.0,50),
  ('Tabanero','Momentum Maduro','Toro',6.0,52),
  ('Topper','Original Handmade','Breva',5.5,46),
  ('Topper','Original Handmade','Grande Corona',6.0,47),
  ('Topper','Original Handmade','Ebony',5.5,47),
  ('Topper','Original Handmade','Old Fashioned Perfecto',4.88,48),
  ('Topper','1894','Shorty',4.0,43),
  ('Topper','1894','Corona',6.0,44),
  ('Topper','1894','Robusto',5.0,50),
  ('Topper','1894','Toro',6.0,54),
  ('Topper','Danli','Robusto',5.0,50),
  ('Topper','Danli','Toro',6.0,50),
  ('Topper','Danli','Belicoso',6.0,54),
  ('Topper','Danli','Churchill',7.0,50),
  ('Falto','Edición Especial ELH Hato Viejo','Corona Gorda',6.0,47),
  ('Falto','Lonsdale','Lonsdale',6.5,42),
  ('Falto','Robusto','Robusto',5.0,50),
  ('Falto','Reserva Especial Tres Luises','Petit Belicoso',5.0,52),
  ('Falto','Prominente Gran Reserva Especial','Perfecto',4.5,47),
  ('Falto','Perla Reserva Especial','Petit Corona',4.0,40),
  ('Falto','Selección Especial','Corona Gorda',5.75,48),
  ('Falto','Legado','Corona Gorda',5.5,47),
  ('Falto','La Obra Azojuano','Corona Gorda',5.5,47),
  ('Falto','El Falto Los Menesteres','Corona Gorda',5.5,47),
  ('Falto','Terruño Hermanos','Robusto',5.0,50),
  ('Falto','Ballibo Edición Especial Abuelos','Corona',5.25,43),
  ('Falto','Dos Banderas','Lancero',6.875,40),
  ('Falto','Yagüez Arawaco','Perfecto',5.0,54),
  ('Falto','El Prócer Historias','Churchill',6.0,48),
  ('Falto','LJF Reserva del Fundador','Box Pressed',5.5,52),
  ('Falto','La Pureza','Lancero',6.875,40),
  ('Falto','El Surco Cosecheros','Corona Gorda',6.875,47),
  ('Micallef','Black','Robusto',5.0,52),
  ('Micallef','Black','Toro',6.0,52),
  ('Micallef','Blue','Robusto',5.0,52),
  ('Micallef','Blue','Toro',6.0,52),
  ('Micallef','Green','Robusto',5.0,52),
  ('Micallef','Green','Toro',6.0,52),
  ('Micallef','Purple','Robusto',5.0,52),
  ('Micallef','Purple','Toro',6.0,52),
  ('Micallef','Red','Robusto',5.0,52),
  ('Micallef','Red','Toro',6.0,52),
  ('Micallef','White','Robusto',5.0,52),
  ('Micallef','White','Toro',6.0,52),
  ('Micallef','Connecticut','Corona',5.0,40),
  ('Micallef','Connecticut','Robusto',5.0,52),
  ('Micallef','Experiencia La Crema','Corona',5.0,40),
  ('Micallef','Experiencia La Crema','Robusto Gordo',5.0,54),
  ('Micallef','Experiencia La Crema','Toro',6.0,52),
  ('Micallef','Experiencia La Crema','Churchill',7.0,52),
  ('Micallef','Herencia','Corona',5.0,40),
  ('Micallef','Herencia','Toro',6.0,52),
  ('Micallef','Herencia','Box-Pressed Torpedo',5.5,52),
  ('Micallef','Leyenda','Corona',5.0,40),
  ('Micallef','Leyenda','Robusto',5.0,52),
  ('Micallef','Leyenda','Toro',6.0,52),
  ('Micallef','Leyenda','Presidente',7.5,54),
  ('Micallef','A/a','Petit',4.0,46),
  ('Micallef','A/a','Toro Grande',6.75,54),
  ('Micallef','A/a','Gordo',6.0,60),
  ('Micallef','Migdalia','Corona',5.0,40),
  ('Micallef','Migdalia','Petit',4.0,46),
  ('Micallef','Migdalia','Corona Gorda',6.0,46),
  ('Micallef','Migdalia','Toro',6.0,52),
  ('Micallef','Reata','Corona',5.0,40),
  ('Micallef','Reata','Robusto',5.0,52),
  ('Micallef','Reata','Corona Gorda',6.0,46),
  ('Micallef','Reata','Toro',6.0,52),
  ('Micallef','Reserva','Corona',5.0,40),
  ('Micallef','Reserva','Toro',6.0,52),
  ('Micallef','Reserva','Churchill',7.0,52),
  ('Jake Wyatt','Fourth Dimension','Robusto',5.0,50),
  ('Jake Wyatt','Fourth Dimension','Toro',6.0,54),
  ('Jake Wyatt','Fourth Dimension','Belicoso',6.0,52),
  ('Jake Wyatt','Fourth Dimension','Gordo',6.0,60),
  ('Jake Wyatt','Herbert Spencer','Robusto',5.0,50),
  ('Jake Wyatt','Herbert Spencer','Toro',6.0,54),
  ('Jake Wyatt','Herbert Spencer','Belicoso',6.0,52),
  ('Jake Wyatt','Herbert Spencer','Gordo',6.0,60),
  ('Jake Wyatt','Appendix II','Robusto',5.0,50),
  ('Jake Wyatt','Appendix II','Toro',6.0,54),
  ('Jake Wyatt','Appendix II','Belicoso',6.0,52),
  ('Jake Wyatt','Appendix II','Gordo',6.0,60),
  ('Jake Wyatt','Lucid Interval','Robusto',5.0,50),
  ('Jake Wyatt','Lucid Interval','Toro',6.0,54),
  ('Jake Wyatt','Lucid Interval','Belicoso',6.0,52),
  ('Jake Wyatt','Lucid Interval','Gordo',6.0,60),
  ('Jake Wyatt','Lithium','Toro',6.0,50),
  ('Jake Wyatt','Icarus','Toro Extra',6.0,54),
  ('Jake Wyatt','J.W. Maverick','Robusto',5.0,50),
  ('Jake Wyatt','J.W. Maverick','Toro',6.0,54),
  ('Jake Wyatt','J.W. Maverick','Box-Pressed Gordo',6.0,60),
  ('Jake Wyatt','Titan Series','Robusto',5.0,50),
  ('Jake Wyatt','Titan Series','Toro',6.0,54),
  ('Nat Cicco','Aniversario 1965 Liga No. 4','Corona',5.5,46),
  ('Nat Cicco','Aniversario 1965 Liga No. 4','Robusto',5.0,52),
  ('Nat Cicco','Aniversario 1965 Liga No. 4','Robusto Grande',5.5,56),
  ('Nat Cicco','Aniversario 1965 Liga No. 4','Toro',6.0,52),
  ('Nat Cicco','Aniversario 1965 Liga No. 4','Torpedo',6.25,52),
  ('Nat Cicco','Aniversario 1965 Liga No. 4','Double Toro',6.5,60),
  ('Nat Cicco','Aniversario 1965 Liga No. 4','Churchill',7.0,52),
  ('Nat Cicco','Cuban Legends','No. 4',4.0,58),
  ('Nat Cicco','Cuban Legends','Robusto',5.0,54),
  ('Nat Cicco','Cuban Legends','Torpedo',6.0,54),
  ('Nat Cicco','Cuban Legends','Toro',6.0,56),
  ('Nat Cicco','Cuban Legends','Churchill',7.5,52),
  ('Nat Cicco','HHB Gold','Corona',5.25,50),
  ('Nat Cicco','HHB Gold','Corona Extra',6.25,50),
  ('Nat Cicco','HHB Gold','Robusto',5.25,56),
  ('Nat Cicco','HHB Gold','Toro',6.75,58),
  ('Nat Cicco','HHB Gold','Churchill',7.75,54),
  ('Nat Cicco','HHB Classic','Robusto',5.25,56),
  ('Nat Cicco','HHB Classic','Toro',6.75,58),
  ('Nat Cicco','Elephant Ears','Elephant Ears',8.5,60),
  ('Nat Cicco','Elephant Ears','Baby',7.5,54),
  ('Nat Cicco','Elephant Ears','Juniors',7.5,60),
  ('Nat Cicco','Elephant Ears','Baby Juniors',6.5,54),
  ('Nat Cicco','Elephant Ears','Jumbo',6.0,70),
  ('Nat Cicco','Elephant Ears','Jumbo Juniors',6.0,60),
  ('Nat Cicco','Nicaraguan Long Filler','Robusto',5.0,52),
  ('Nat Cicco','Nicaraguan Long Filler','Robusto Grande',5.5,56),
  ('Nat Cicco','Nicaraguan Long Filler','Toro',6.0,52),
  ('Nat Cicco','Nicaraguan Long Filler','Belicoso',6.25,52),
  ('Nat Cicco','Nicaraguan Long Filler','Magnum',6.25,60),
  ('Nat Cicco','Nicaraguan Long Filler','Churchill',7.0,56),
  ('Nat Cicco','Cuban Style','Corona Grande',6.0,42),
  ('Nat Cicco','Cuban Style','Robusto',5.75,49),
  ('Nat Cicco','Cuban Style','Churchill',7.5,46),
  ('Warfighter Tobacco','5.56 Field Connecticut Shade','Minutemen',4.0,44),
  ('Warfighter Tobacco','5.56 Field Connecticut Shade','Corona',5.5,46),
  ('Warfighter Tobacco','5.56 Field Connecticut Shade','Robusto',5.0,52),
  ('Warfighter Tobacco','5.56 Field Connecticut Shade','Toro',6.0,52),
  ('Warfighter Tobacco','5.56 Field Connecticut Shade','Gordo',6.0,60),
  ('Warfighter Tobacco','5.56 Field Connecticut Shade','Lancero',7.0,38),
  ('Warfighter Tobacco','7.62 Field Sumatra','Minutemen',4.0,44),
  ('Warfighter Tobacco','7.62 Field Sumatra','Corona',5.5,46),
  ('Warfighter Tobacco','7.62 Field Sumatra','Robusto',5.0,52),
  ('Warfighter Tobacco','7.62 Field Sumatra','Toro',6.0,52),
  ('Warfighter Tobacco','7.62 Field Sumatra','Gordo',6.0,60),
  ('Warfighter Tobacco','7.62 Field Sumatra','Lancero',7.0,38),
  ('Warfighter Tobacco','.50 Cal Field Maduro','Minutemen',4.0,44),
  ('Warfighter Tobacco','.50 Cal Field Maduro','Corona',5.5,46),
  ('Warfighter Tobacco','.50 Cal Field Maduro','Robusto',5.0,52),
  ('Warfighter Tobacco','.50 Cal Field Maduro','Toro',6.0,52),
  ('Warfighter Tobacco','.50 Cal Field Maduro','Gordo',6.0,60),
  ('Warfighter Tobacco','.50 Cal Field Maduro','Lancero',7.0,38),
  ('Warfighter Tobacco','Garrison Corojo','Minutemen',4.0,44),
  ('Warfighter Tobacco','Garrison Corojo','Corona',5.5,46),
  ('Warfighter Tobacco','Garrison Corojo','Robusto',5.0,52),
  ('Warfighter Tobacco','Garrison Corojo','Toro',6.0,52),
  ('Warfighter Tobacco','Garrison Corojo','Gordo',6.0,60),
  ('Warfighter Tobacco','Garrison Corojo','Lancero',7.0,38),
  ('Warfighter Tobacco','Garrison Rosado','Minutemen',4.0,44),
  ('Warfighter Tobacco','Garrison Rosado','Corona',5.5,46),
  ('Warfighter Tobacco','Garrison Rosado','Robusto',5.0,52),
  ('Warfighter Tobacco','Garrison Rosado','Toro',6.0,52),
  ('Warfighter Tobacco','Garrison Rosado','Rocco',6.0,60),
  ('Warfighter Tobacco','Garrison Rosado','Lancero',7.0,38),
  ('Warfighter Tobacco','Garrison Oscuro Maduro','Minutemen',4.0,44),
  ('Warfighter Tobacco','Garrison Oscuro Maduro','Corona',5.5,46),
  ('Warfighter Tobacco','Garrison Oscuro Maduro','Robusto',5.0,52),
  ('Warfighter Tobacco','Garrison Oscuro Maduro','Toro',6.0,52),
  ('Warfighter Tobacco','Garrison Oscuro Maduro','Rocco',6.0,60),
  ('Warfighter Tobacco','Garrison Oscuro Maduro','Lancero',7.0,38),
  ('Warfighter Tobacco','Night Shift','Toro',6.0,50),
  ('Warfighter Tobacco','10th Anniversary','Toro',6.0,52),
  ('Warfighter Tobacco','San Andres','Toro',6.0,52),
  ('La Sirena','Original','Sea Sprite',5.5,42),
  ('La Sirena','Original','The Prince',5.0,50),
  ('La Sirena','Original','Trident',7.0,50),
  ('La Sirena','Original','Divine',5.5,52),
  ('La Sirena','Original','King Poseidon',6.0,60),
  ('La Sirena','Original','Lancero',7.0,42),
  ('La Sirena','Merlion','Robusto',5.0,50),
  ('La Sirena','Merlion','Toro',5.5,54),
  ('La Sirena','Merlion','Gran Toro',6.0,58),
  ('La Sirena','Oceano','Southern',5.0,43),
  ('La Sirena','Oceano','Indian',5.5,50),
  ('La Sirena','Oceano','Atlantic',7.0,52),
  ('La Sirena','Oceano','Pacific',6.0,65),
  ('JRE Tobacco','Rancho Luna Habano','Robusto',5.0,50),
  ('JRE Tobacco','Rancho Luna Habano','Toro',6.0,50),
  ('JRE Tobacco','Rancho Luna Habano','Gordo',6.5,60),
  ('JRE Tobacco','Rancho Luna Habano','Grandes 64',7.0,64),
  ('JRE Tobacco','Rancho Luna Habano','Grandes 70',7.0,70),
  ('JRE Tobacco','Rancho Luna Maduro','Robusto',5.0,50),
  ('JRE Tobacco','Rancho Luna Maduro','Toro',6.0,50),
  ('JRE Tobacco','Rancho Luna Maduro','Gordo',6.5,60),
  ('JRE Tobacco','Tatascan Habano','Corona',5.0,44),
  ('JRE Tobacco','Tatascan Habano','Robusto',5.0,50),
  ('JRE Tobacco','Tatascan Habano','Toro',6.0,50),
  ('JRE Tobacco','Tatascan Habano','Gran Churchill',7.0,52),
  ('JRE Tobacco','Tatascan Habano','Gordo',6.5,60),
  ('JRE Tobacco','Tatascan Connecticut','Robusto',5.0,50),
  ('JRE Tobacco','Tatascan Connecticut','Toro',6.0,50),
  ('JRE Tobacco','Tatascan Connecticut','Gordo',6.5,60),
  ('JRE Tobacco','Tatascan Maduro','Robusto',5.0,50)
) AS d(brand,series,vitola,len,ring)
WHERE c.brand = d.brand AND c.series = d.series AND c.vitola = d.vitola
  AND (c.ring_gauge IS NULL OR c.length_inches IS NULL);
