-- 143: Gjenopprett mal (ring_gauge/length_inches) for de 10 merkene fra migrering 135.
-- Bug i 135: INSERT-en tok aldri med mal-kolonnene. Her settes de researchede tallene
-- inn igjen (produsent/anerkjent kilde per merke), matchet paa brand+series+vitola.
-- Idempotent: setter kun der mal fortsatt mangler.
UPDATE public.cigars c
SET ring_gauge = d.ring, length_inches = d.len
FROM (VALUES
  ('Graycliff','Chateau Grand Cru','Toro',6.0,54),
  ('Graycliff','Crystal','Presidente',7.0,48),
  ('Graycliff','Crystal','Robusto',5.25,50),
  ('Graycliff','Crystal','Taco',4.5,44),
  ('Graycliff','Crystal','Toro',6.0,54),
  ('Graycliff','Crystal','Torpedo',6.0,52),
  ('Graycliff','Espresso','Toro',6.0,54),
  ('Graycliff','G2 Habano','Gordo',6.0,60),
  ('Graycliff','G2 Habano','Presidente',7.0,48),
  ('Graycliff','G2 Habano','Robusto',5.2,50),
  ('Graycliff','G2 Habano','Toro',6.0,50),
  ('Graycliff','G2 Habano','Torpedo',6.0,52),
  ('Graycliff','Original','Presidente',7.0,48),
  ('Graycliff','Original','Robusto',5.25,50),
  ('Graycliff','Original','Toro',6.0,50),
  ('Graycliff','Original','Torpedo',6.0,52),
  ('Graycliff','Profesionale','Presidente',7.0,48),
  ('Graycliff','Profesionale','Robusto',5.2,50),
  ('Graycliff','Profesionale','Toro',6.0,50),
  ('Graycliff','Profesionale','Torpedo',6.0,52),
  ('El Septimo','Alexandra','Coco Robusto',5.25,52),
  ('El Septimo','Alexandra','Marilyn',5.0,58),
  ('El Septimo','Culinary Art','France Bordeaux',6.0,60),
  ('El Septimo','Culinary Art','Italy Toscana',6.0,52),
  ('El Septimo','Culinary Art','Japan Nigori',6.0,46),
  ('El Septimo','Culinary Art','Spain Rioja',5.0,54),
  ('El Septimo','Emperor','Augustus Connecticut',5.0,52),
  ('El Septimo','Emperor','Empress Sheba',6.0,60),
  ('El Septimo','Emperor','Empress Sheba Toro',6.0,54),
  ('El Septimo','Emperor','King Sargon Connecticut Churchill',7.25,50),
  ('El Septimo','Emperor','King Sargon Connecticut Robusto',4.25,54),
  ('El Septimo','Emperor','King Sargon Maduro Churchill',7.25,50),
  ('El Septimo','Emperor','King Sargon Maduro Robusto',4.25,54),
  ('El Septimo','Emperor','Napoleon Connecticut',9.0,55),
  ('El Septimo','Emperor','Napoleon Maduro',9.0,55),
  ('El Septimo','Emperor','Vartan The Dragon',6.75,58),
  ('El Septimo','Emperor','Yao Connecticut',6.5,60),
  ('El Septimo','Emperor','Yao Maduro',6.5,60),
  ('El Septimo','Gilgamesh','Aqua Anu',6.0,50),
  ('El Septimo','Gilgamesh','King Sargon',6.0,52),
  ('El Septimo','Gilgamesh','Sable Shamash',6.0,50),
  ('El Septimo','Luxus','Bullet Blue',3.25,56),
  ('El Septimo','Luxus','Excepcion White',5.0,60),
  ('El Septimo','Luxus','Flamingo Amarillo',4.5,52),
  ('El Septimo','Luxus','Long Shot Black',5.0,68),
  ('El Septimo','Luxus','Precioso Pink',4.25,34),
  ('El Septimo','Luxus','Rebelde Blue',5.5,54),
  ('El Septimo','Luxus','Short Dream Amarillo',4.0,60),
  ('El Septimo','Luxus','Small Impact Green',2.0,56),
  ('El Septimo','Luxus','Small Sabor Blue',3.5,54),
  ('El Septimo','Sacred Arts','Botticelli',7.5,58),
  ('El Septimo','Sacred Arts','Da Vinci',7.5,40),
  ('El Septimo','Sacred Arts','Michelangelo',5.5,50),
  ('El Septimo','Sacred Arts','Raphael',6.0,50),
  ('El Septimo','Sacred Arts','Rembrandt',7.0,54),
  ('El Septimo','Sacred Arts','Salvador Dali',6.5,54),
  ('El Septimo','Sacred Arts','Van Gogh',9.0,56),
  ('El Septimo','Zaya','20th Anniversary Doble Gran Reserva',6.0,52),
  ('El Septimo','Zaya','Bomba Orange',6.5,60),
  ('El Septimo','Zaya','Bullet Black',3.25,56),
  ('El Septimo','Zaya','Double Shot White',3.75,68),
  ('El Septimo','Zaya','Excepcion Esmeralda',5.0,60),
  ('El Septimo','Zaya','Fabuloso Dark Ruby',6.25,70),
  ('El Septimo','Zaya','Kolosso Amethyst',6.0,60),
  ('El Septimo','Zaya','Mirifico Sapphire',6.75,58),
  ('El Septimo','Zaya','Short Dream Topaz',4.0,60),
  ('Sindicato','Affinity','Belicoso',6.125,52),
  ('Sindicato','Affinity','Churchill',7.0,56),
  ('Sindicato','Affinity','Corona',5.5,46),
  ('Sindicato','Affinity','Gran Toro',6.0,60),
  ('Sindicato','Affinity','Robusto',5.0,52),
  ('Sindicato','Affinity','Toro',6.0,54),
  ('Sindicato','Affinity Maduro','Churchill',7.0,56),
  ('Sindicato','Affinity Maduro','Corona',5.5,46),
  ('Sindicato','Affinity Maduro','Gran Toro',6.0,60),
  ('Sindicato','Affinity Maduro','Robusto',5.0,52),
  ('Sindicato','Affinity Maduro','Toro',6.0,54),
  ('Sindicato','Casa Bella','Churchill',7.0,52),
  ('Sindicato','Casa Bella','Corona',5.5,44),
  ('Sindicato','Casa Bella','Gran Toro',6.0,60),
  ('Sindicato','Casa Bella','Robusto',5.0,52),
  ('Sindicato','Casa Bella','Toro',6.0,54),
  ('Sindicato','Hex','Churchill',7.0,54),
  ('Sindicato','Hex','Figurado',5.25,52),
  ('Sindicato','Hex','Perfecto',6.25,52),
  ('Sindicato','Hex','Robusto',5.0,52),
  ('Sindicato','Hex','Toro',6.0,54),
  ('Sindicato','Maduro','Churchill',7.0,52),
  ('Sindicato','Maduro','Magnum',6.0,60),
  ('Sindicato','Maduro','Robusto',5.0,54),
  ('Sindicato','Maduro','Toro',6.0,54),
  ('Sindicato','Natural','Churchill',7.0,52),
  ('Sindicato','Natural','Magnum',6.0,60),
  ('Sindicato','Natural','Robusto',5.0,54),
  ('Sindicato','Natural','Toro',6.0,54),
  ('Sindicato','Particulares','Belvederes',7.0,52),
  ('Sindicato','Particulares','Cesta',6.0,60),
  ('Sindicato','Particulares','Deliciosos',6.0,54),
  ('Sindicato','Particulares','No. 1',6.25,48),
  ('Serino','Elenor Rose','Eagle',5.625,50),
  ('Serino','Elenor Rose','Lady 48',5.75,48),
  ('Serino','Elenor Rose','Revolver',5.75,54),
  ('Serino','Royale Connecticut','Churchill',7.0,50),
  ('Serino','Royale Connecticut','Gordo',6.0,58),
  ('Serino','Royale Connecticut','Robusto',5.0,52),
  ('Serino','Royale Connecticut','Sublime',6.25,54),
  ('Serino','Royale Maduro XX','Gordo',6.0,58),
  ('Serino','Royale Maduro XX','Robusto Extra',5.5,50),
  ('Serino','Royale Maduro XX','Sublime',6.25,54),
  ('Serino','Royale Medio','Gordo',6.0,58),
  ('Serino','Royale Medio','Robusto Extra',5.5,50),
  ('Serino','Royale Medio','Sublime',6.25,54),
  ('Serino','Taino','Corona Gorda',6.0,46),
  ('Serino','Taino','Robusto',5.0,50),
  ('Serino','Taino','Toro',6.0,52),
  ('Serino','Taino Heritage','Hamaca',5.125,50),
  ('Serino','Taino Heritage','Manicato',6.25,54),
  ('Serino','Taino Heritage','Yocahu',6.0,47),
  ('Serino','The Expat','Corona Gorda',6.0,46),
  ('Serino','The Expat','Sublime',6.5,54),
  ('Serino','The Expat','The Passport',5.875,50),
  ('Serino','Wayfarer','Corona',5.125,44),
  ('Serino','Wayfarer','Corona Gorda',6.0,46),
  ('Serino','Wayfarer','Dalia',6.75,43),
  ('Serino','Wayfarer','Robusto',5.0,52),
  ('Serino','Wayfarer','The 109',6.25,50),
  ('MBombay','Classic','Belicoso',5.0,52),
  ('MBombay','Classic','Churchill',7.0,48),
  ('MBombay','Classic','Corona',5.0,43),
  ('MBombay','Classic','Perfecto',6.0,50),
  ('MBombay','Classic','Robusto',4.5,48),
  ('MBombay','Classic','Torpedo',6.0,52),
  ('MBombay','Corojo Oscuro','Churchill',7.0,48),
  ('MBombay','Corojo Oscuro','Double Corona',7.0,52),
  ('MBombay','Corojo Oscuro','Gordo',6.0,60),
  ('MBombay','Corojo Oscuro','Perfecto',5.5,50),
  ('MBombay','Corojo Oscuro','Robusto',4.5,50),
  ('MBombay','Gaaja','Toro',6.0,54),
  ('MBombay','Gaaja Maduro','Toro',6.0,54),
  ('MBombay','Gaaja Maduro','Torpedo',6.5,54),
  ('MBombay','KeSara','585',5.0,58),
  ('MBombay','KeSara','A',9.0,47),
  ('MBombay','KeSara','No. 2',6.0,52),
  ('MBombay','KeSara','No. 4',5.1,44),
  ('MBombay','KeSara','Pyramid',7.0,54),
  ('MBombay','KeSara','Robusto Largo',4.5,54),
  ('MBombay','KeSara','Salomon',7.0,58),
  ('MBombay','KeSara','Toro',6.0,52),
  ('MBombay','Vintage Reserve','Lancero 1973',8.5,38),
  ('Powstanie','Broadleaf','Belicoso',5.5,54),
  ('Powstanie','Broadleaf','Robusto',5.0,50),
  ('Powstanie','Broadleaf','Short Perfecto',5.0,50),
  ('Powstanie','Broadleaf','Toro',6.0,52),
  ('Powstanie','Connecticut','Belicoso',5.5,54),
  ('Powstanie','Connecticut','Corona Gorda',5.5,46),
  ('Powstanie','Connecticut','Short Perfecto',5.0,50),
  ('Powstanie','Connecticut','Toro',6.0,52),
  ('Powstanie','Habano','Belicoso',5.5,54),
  ('Powstanie','Habano','Corona Gorda',5.5,46),
  ('Powstanie','Habano','Short Perfecto',5.0,50),
  ('Powstanie','Habano','Toro',6.0,52),
  ('Powstanie','San Andrés','Belicoso',5.5,54),
  ('Powstanie','San Andrés','Corona Gorda',5.5,46),
  ('Powstanie','San Andrés','Robusto',5.0,50),
  ('Powstanie','San Andrés','Short Perfecto',5.0,50),
  ('Powstanie','San Andrés','Toro',6.0,52),
  ('Powstanie','Sumatra','Churchill',7.0,48),
  ('Powstanie','Sumatra','Gran Robusto',5.5,52),
  ('Powstanie','Sumatra','Gran Toro',6.25,52),
  ('Powstanie','Sumatra','Petite Robusto',4.75,50),
  ('Regius','Connecticut','Corona',5.125,42),
  ('Regius','Connecticut','Gran Toro',6.5,56),
  ('Regius','Connecticut','Grandido',7.0,47),
  ('Regius','Connecticut','Robusto',4.875,50),
  ('Regius','Connecticut','Toro',6.0,50),
  ('Regius','Maduro','Corona',5.125,42),
  ('Regius','Maduro','Gran Toro',6.5,56),
  ('Regius','Maduro','Grandido',7.0,47),
  ('Regius','Maduro','Robusto',4.875,50),
  ('Regius','Maduro','Toro',6.0,50),
  ('Regius','Original','Corona',5.125,42),
  ('Regius','Original','Gran Toro',6.5,56),
  ('Regius','Original','Grandido',7.0,47),
  ('Regius','Original','Robusto',4.875,50),
  ('Regius','Original','Toro',6.0,50),
  ('Regius','Sun Grown','Corona',5.125,42),
  ('Regius','Sun Grown','Gran Toro',6.5,56),
  ('Regius','Sun Grown','Grandido',7.0,47),
  ('Regius','Sun Grown','Robusto',4.875,50),
  ('Regius','Sun Grown','Toro',6.0,50),
  ('Rojas','Bluebonnets','Corona Gorda',6.0,46),
  ('Rojas','Bluebonnets','Lancero',7.0,38),
  ('Rojas','Bluebonnets','Robusto',5.0,50),
  ('Rojas','Bluebonnets','Toro',6.0,52),
  ('Rojas','Quiet Morning','Corona',6.0,46),
  ('Rojas','Quiet Morning','Lancero',7.0,40),
  ('Rojas','Quiet Morning','Robusto',5.0,50),
  ('Rojas','Quiet Morning','Toro',6.0,52),
  ('Rojas','Statement','Corona Gorda',6.0,46),
  ('Rojas','Statement','Lancero',7.0,38),
  ('Rojas','Statement','Robusto',5.0,50),
  ('Rojas','Statement','Toro',6.0,52),
  ('Rojas','Street Tacos Al Pastor','Gordo',6.0,60),
  ('Rojas','Street Tacos Al Pastor','Robusto',5.0,50),
  ('Rojas','Street Tacos Al Pastor','Toro',6.0,52),
  ('Rojas','Street Tacos Al Pastor','Toro Grande',6.5,56),
  ('Rojas','Street Tacos Barbacoa','Robusto',5.0,50),
  ('Rojas','Street Tacos Barbacoa','Short Corona',5.5,46),
  ('Rojas','Street Tacos Barbacoa','Toro',6.0,50),
  ('Rojas','Street Tacos Carnitas','Robusto',5.0,50),
  ('Rojas','Street Tacos Carnitas','Short Corona',5.5,46),
  ('Rojas','Street Tacos Carnitas','Toro',6.0,50),
  ('Rojas','Unfinished Business','Corona Gorda',6.0,46),
  ('Rojas','Unfinished Business','Robusto',5.0,50),
  ('Casa Cuevas','Connecticut','Gordo',6.0,60),
  ('Casa Cuevas','Connecticut','Robusto',5.0,52),
  ('Casa Cuevas','Connecticut','Toro',6.0,50),
  ('Casa Cuevas','Habano','Gordo',6.0,60),
  ('Casa Cuevas','Habano','Robusto',5.0,52),
  ('Casa Cuevas','Habano','Toro',6.0,50),
  ('Casa Cuevas','La Mandarria','Toro',6.0,52),
  ('Casa Cuevas','Maduro','Gordo',6.0,60),
  ('Casa Cuevas','Maduro','Robusto',5.0,52),
  ('Casa Cuevas','Maduro','Toro',6.0,50),
  ('Casa Cuevas','Patrimonio','Gordo',6.0,60),
  ('Casa Cuevas','Patrimonio','Robusto Gordo',5.0,54),
  ('Casa Cuevas','Patrimonio','Toro',6.0,52),
  ('Casa Cuevas','Prensado Habano','Prensado',6.0,48),
  ('Casa Cuevas','Prensado Maduro','Prensado',6.0,48),
  ('Casa Cuevas','Reserva Maduro','Robusto',5.0,52),
  ('Casa Cuevas','Reserva Maduro','Toro',6.0,50),
  ('Casa Cuevas','Reserva Maduro','Torpedo',6.25,52),
  ('Casa Cuevas','Sangre Nueva','Double Perfecto',6.0,58),
  ('Casa Cuevas','Sangre Nueva','Robusto',4.75,54),
  ('Casa Cuevas','Sangre Nueva','Toro',6.0,52),
  ('Casa 1910','Cuchillo Parado','Corona',5.5,42),
  ('Casa 1910','Cuchillo Parado','Robusto',5.0,50),
  ('Casa 1910','Cuchillo Parado','Toro',6.0,52),
  ('Casa 1910','El Ebano','Corona',5.5,42),
  ('Casa 1910','El Ebano','Robusto',5.0,50),
  ('Casa 1910','El Ebano','Toro',6.0,52),
  ('Casa 1910','Tierra Blanca','Corona',5.5,42),
  ('Casa 1910','Tierra Blanca','Robusto',5.0,50),
  ('Casa 1910','Tierra Blanca','Toro',6.0,52)
) AS d(brand,series,vitola,len,ring)
WHERE c.brand = d.brand AND c.series = d.series AND c.vitola = d.vitola
  AND (c.ring_gauge IS NULL OR c.length_inches IS NULL);
