-- 144: Smaksnoter for topp-7-merkene (CAO, Macanudo, Joya de Nicaragua, Ashton,
-- Dunbarton, Padron, Sinistro). Researchet per blanding (serie) fra Cigar Aficionado,
-- halfwheel og anmeldere; mappet til appens faste notevokabular. Settes paa alle
-- vitolaer i serien der smak fortsatt mangler. Idempotent. To serier uten publiserte
-- noter (Macanudo Ecuadorian Shade, Sinistro La Fabrica) er bevisst utelatt (tomt>gjetting).
UPDATE public.cigars c
SET flavor_notes = d.notes
FROM (VALUES
  ('Ashton','Aged Maduro',ARRAY['Leather','Earth','Oak','Cocoa','Espresso']::text[]),
  ('Ashton','Cabinet Selection',ARRAY['Cream','Almonds','Butter','Vanilla','Spice']::text[]),
  ('Ashton','Classic',ARRAY['Cedar','Cream','Almonds','Coffee','Honey']::text[]),
  ('Ashton','ESG',ARRAY['Almonds','Coffee','Cream','Leather','Pepper']::text[]),
  ('Ashton','Esquire',ARRAY['Almonds','Coffee','Cocoa','Cream','Cedar']::text[]),
  ('Ashton','Heritage Puro Sol',ARRAY['Nuts','Cinnamon','Leather','Earth','Caramel']::text[]),
  ('Ashton','Small Cigars Cameroon',ARRAY['Wood','Cocoa','Black Pepper','Nutmeg','Leather']::text[]),
  ('Ashton','Small Cigars Connecticut',ARRAY['Cream','Nuts','Cedar','Spice']::text[]),
  ('Ashton','Symmetry',ARRAY['Pepper','Leather','Coffee','Cedar','Cream']::text[]),
  ('Ashton','VSG',ARRAY['Espresso','Leather','Cedar','Pepper','Dark Fruit']::text[]),
  ('CAO','Amazon Basin',ARRAY['Pepper','Earth','Leather','Dark Fruit','Sweetness']::text[]),
  ('CAO','Amazon Basin Extra Añejo',ARRAY['Black Pepper','Wood','Earth','Cream','Sweetness']::text[]),
  ('CAO','America',ARRAY['Coffee','Leather','Pepper','Wood','Caramel']::text[]),
  ('CAO','America 250th Anniversary',ARRAY['Dark Chocolate','Earth','Leather','Black Pepper']::text[]),
  ('CAO','Bones',ARRAY['Cedar','Sweetness','Earth','Pepper','Coffee']::text[]),
  ('CAO','Brazilia',ARRAY['Earth','Toast','Black Pepper','Sweetness']::text[]),
  ('CAO','BX3',ARRAY['Earth','Black Pepper','Wood','Sweetness','Nuts']::text[]),
  ('CAO','Cameroon',ARRAY['Butter','Caramel','Cedar','Leather','White Pepper']::text[]),
  ('CAO','Colombia',ARRAY['Cedar','Citrus','Toast','Chocolate']::text[]),
  ('CAO','Consigliere',ARRAY['Earth','Baking Spice','Cedar','Espresso']::text[]),
  ('CAO','Eileen''s Dream',ARRAY['Chocolate','Cocoa','Vanilla','Cream','Nuts']::text[]),
  ('CAO','FASA Noche',ARRAY['Pepper','Earth','Herbal']::text[]),
  ('CAO','FASA Sol',ARRAY['Cedar','Earth','Coffee','Pepper','Baking Spice']::text[]),
  ('CAO','FASA Sombra',ARRAY['Butter','Hay','Cream','Almonds']::text[]),
  ('CAO','Firewalker',ARRAY['Earth','Leather','Dried Fruit','Pepper','Toast']::text[]),
  ('CAO','Flathead V21',ARRAY['Oak','Almonds','Black Pepper','Hay','Dark Chocolate']::text[]),
  ('CAO','Flathead V23',ARRAY['Earth','Nuts','Dried Fruit','Pepper','Leather']::text[]),
  ('CAO','Gold',ARRAY['Cedar','Tobacco','Nuts','Citrus']::text[]),
  ('CAO','Gold Maduro',ARRAY['Cinnamon','Malt','Earth','Coffee','Cream']::text[]),
  ('CAO','Italia',ARRAY['Earth','Molasses','Spice','Wood','Floral']::text[]),
  ('CAO','Maduro',ARRAY['Cocoa','Coffee','Pepper','Dark Chocolate','Molasses']::text[]),
  ('CAO','Moontrance',ARRAY['Caramel','Vanilla','Sweetness']::text[]),
  ('CAO','Mortal Coil',ARRAY['Earth','Black Pepper','Wood','Chocolate','Cream']::text[]),
  ('CAO','Nicaragua',ARRAY['Wood','Spice','Coffee','Chocolate','Sweetness']::text[]),
  ('CAO','Orellana',ARRAY['Earth','Caramel','Citrus','Pepper','Molasses']::text[]),
  ('CAO','OSA SOL',ARRAY['Wood','Sweetness','Herbal','Pepper','Nuts']::text[]),
  ('CAO','Pilón',ARRAY['Nuts','Cocoa','Spice']::text[]),
  ('CAO','Pilón Añejo',ARRAY['Leather','Earth','Cinnamon','Oak','Sweetness']::text[]),
  ('CAO','Session',ARRAY['Dark Fruit','Black Pepper','Earth','Cedar','Coffee']::text[]),
  ('CAO','Speed Shop',ARRAY['White Pepper','Leather','Earth','Spice','Espresso']::text[]),
  ('CAO','Steel Horse',ARRAY['Cedar','Oak','Sweetness','Cinnamon']::text[]),
  ('CAO','Stokk',ARRAY['Oak','Smoke','Earth','Black Pepper','Cream']::text[]),
  ('CAO','V19',ARRAY['Black Pepper','Earth','Cedar','Leather','Molasses']::text[]),
  ('CAO','Vision',ARRAY['Wood','Cocoa','Cedar','Floral','Sweetness']::text[]),
  ('CAO','Vision 2022',ARRAY['Cedar','Cinnamon','Nuts','Dark Fruit','Coffee']::text[]),
  ('CAO','Zócalo',ARRAY['Earth','Cedar','Coffee','Pepper','Chocolate']::text[]),
  ('Dunbarton Tobacco & Trust','Mi Querida',ARRAY['Chocolate','Pepper','Earth','Coffee','Wood']::text[]),
  ('Dunbarton Tobacco & Trust','Mi Querida Black',ARRAY['Cream','Pepper','Toast','Earth','Wood']::text[]),
  ('Dunbarton Tobacco & Trust','Mi Querida Triqui Traca',ARRAY['Black Pepper','Sweetness','Cedar','Earth','Dark Chocolate']::text[]),
  ('Dunbarton Tobacco & Trust','Muestra de Saka',ARRAY['Chocolate','Earth','Toasted Nuts','Cedar','Pepper']::text[]),
  ('Dunbarton Tobacco & Trust','Polpetta',ARRAY['Coffee','Chocolate','Pepper','Earth','Citrus']::text[]),
  ('Dunbarton Tobacco & Trust','Red Meat Lovers',ARRAY['Cocoa','Cedar','Oak','Coffee','Leather']::text[]),
  ('Dunbarton Tobacco & Trust','Sin Compromiso',ARRAY['Chocolate','Pepper','Earth','Sweetness','Coffee']::text[]),
  ('Dunbarton Tobacco & Trust','Sobremesa',ARRAY['Cinnamon','Chocolate','Cream','Malt','Earth']::text[]),
  ('Dunbarton Tobacco & Trust','Sobremesa Brûlée',ARRAY['Nuts','Cream','Sweetness','Caramel','Citrus']::text[]),
  ('Dunbarton Tobacco & Trust','Stillwell Star',ARRAY['Coffee','Smoke','Dark Chocolate','Pepper']::text[]),
  ('Dunbarton Tobacco & Trust','Todos Las Dias',ARRAY['Pepper','Earth','Tobacco','Cocoa','Wood']::text[]),
  ('Dunbarton Tobacco & Trust','Umbagog',ARRAY['Cedar','Earth','Black Pepper','Coffee','Baking Spice']::text[]),
  ('Dunbarton Tobacco & Trust','Unicorns',ARRAY['Earth','Coffee','Cedar','Pepper','Mocha']::text[]),
  ('Joya de Nicaragua','Antaño 1970',ARRAY['Leather','Toasted Nuts','Chocolate','Honey','Wood']::text[]),
  ('Joya de Nicaragua','Antaño CT',ARRAY['Leather','Cedar','White Pepper','Cream','Nuts']::text[]),
  ('Joya de Nicaragua','Antaño Dark Corojo',ARRAY['Pepper','Chocolate','Spice','Dark Fruit']::text[]),
  ('Joya de Nicaragua','Antaño Gran Reserva',ARRAY['Pepper','Chocolate','Earth','Coffee','Cream']::text[]),
  ('Joya de Nicaragua','Cinco de Cinco',ARRAY['Earth','Pepper','Chocolate','Cream']::text[]),
  ('Joya de Nicaragua','Cinco Décadas',ARRAY['Cedar','White Pepper','Earth','Black Pepper']::text[]),
  ('Joya de Nicaragua','Clásico Original',ARRAY['Cedar','Oak','White Pepper','Nuts','Butter']::text[]),
  ('Joya de Nicaragua','Cuatro Cinco',ARRAY['Almonds','Cedar','Cocoa','Leather','Cream']::text[]),
  ('Joya de Nicaragua','Joya Black',ARRAY['Spice','Cocoa','Wood','Pepper','Leather']::text[]),
  ('Joya de Nicaragua','Joya Cabinetta',ARRAY['Cedar','Cream','Pepper','Honey','Earth']::text[]),
  ('Joya de Nicaragua','Joya Red',ARRAY['Leather','Cocoa','Cherry','Cream','Black Pepper']::text[]),
  ('Joya de Nicaragua','Joya Silver',ARRAY['Tobacco','Cherry','Earth','Cedar','Pepper']::text[]),
  ('Joya de Nicaragua','Número Uno',ARRAY['Nuts','Leather','Cedar','Espresso','Caramel']::text[]),
  ('Joya de Nicaragua','Rosalones Reserva',ARRAY['Black Pepper','Earth','Honey','Dark Chocolate','Leather']::text[]),
  ('Macanudo','1968',ARRAY['Leather','Cocoa','Coffee','Spice','Cedar']::text[]),
  ('Macanudo','Café',ARRAY['Cream','Cedar','Nuts','Sweetness','Wood']::text[]),
  ('Macanudo','Cru Royale',ARRAY['Nuts','Cocoa','Spice','Earth','Dark Fruit']::text[]),
  ('Macanudo','Estate Reserve No. 1',ARRAY['Oak','Cinnamon','Vanilla','Cream','Cedar']::text[]),
  ('Macanudo','Estate Reserve No. 2',ARRAY['Vanilla','Cream','Almonds','Dark Fruit','Cedar']::text[]),
  ('Macanudo','Estate Reserve No. 3',ARRAY['Vanilla','Cherry','Cream','Wood','Pepper']::text[]),
  ('Macanudo','Gold Label',ARRAY['Cream','Sweetness','Almonds']::text[]),
  ('Macanudo','Inspirado Black',ARRAY['Mocha','Toasted Nuts','Chocolate','Spice','Black Pepper']::text[]),
  ('Macanudo','Inspirado Brazilian Shade',ARRAY['Hay','Cedar','Cream','Leather','Cocoa']::text[]),
  ('Macanudo','Inspirado Green',ARRAY['Coffee','White Pepper','Citrus','Earth','Cedar']::text[]),
  ('Macanudo','Inspirado Jamao',ARRAY['Wood','Cedar','Earth','Black Pepper','Citrus']::text[]),
  ('Macanudo','Inspirado Orange',ARRAY['Wood','Spice','Cedar','Earth','Black Pepper']::text[]),
  ('Macanudo','Inspirado Red',ARRAY['Dark Fruit','Black Pepper','Leather','Cedar','Coffee']::text[]),
  ('Macanudo','Inspirado Tercio Aged',ARRAY['Chocolate','Coffee','Pepper','Earth','Cedar']::text[]),
  ('Macanudo','Inspirado White',ARRAY['Cream','Spice','Cedar']::text[]),
  ('Macanudo','Maduro',ARRAY['Cinnamon','Chocolate','Coffee','Cedar']::text[]),
  ('Macanudo','Sumatra',ARRAY['Oak','Coffee','Cocoa','Dried Fruit','Spice']::text[]),
  ('Macanudo','Vintage 2010',ARRAY['Cedar','Cream','Vanilla']::text[]),
  ('Macanudo','Vintage Maduro 2013',ARRAY['Coffee','Dark Fruit','Spice','Earth']::text[]),
  ('Padrón','1926 Serie',ARRAY['Chocolate','Coffee','Nuts','Cherry','Pepper']::text[]),
  ('Padrón','1964 Anniversary Series',ARRAY['Nuts','Cocoa','Coffee','Wood','Chocolate']::text[]),
  ('Padrón','Dámaso Series',ARRAY['Cedar','Cream','White Pepper','Nuts','Leather']::text[]),
  ('Padrón','Family Reserve',ARRAY['Chocolate','Coffee','Nuts','Cocoa','Caramel']::text[]),
  ('Padrón','Padrón Series',ARRAY['Coffee','Cocoa','Leather','Cedar','Pepper']::text[]),
  ('Sinistro','El Burro Connecticut',ARRAY['Cream','Cedar','Nuts','White Pepper','Earth']::text[]),
  ('Sinistro','El Burro Corojo',ARRAY['Pepper','Toasted Nuts','Leather','Sweetness']::text[]),
  ('Sinistro','El Burro Maduro',ARRAY['Cocoa','Pepper','Leather','Earth','Coffee']::text[]),
  ('Sinistro','Last Cowboy Natural',ARRAY['Coffee','Vanilla','Earth']::text[]),
  ('Sinistro','Mr. Black',ARRAY['Toasted Nuts','Cocoa','Spice','Caramel','Cream']::text[]),
  ('Sinistro','Mr. Desflorado',ARRAY['Honey','Cream','Floral','Toasted Nuts','White Pepper']::text[]),
  ('Sinistro','Mr. Red',ARRAY['Coffee','Chocolate','Toasted Nuts','Cream','White Pepper']::text[]),
  ('Sinistro','NV',ARRAY['Cream','Black Pepper','Wood','Nuts','Earth']::text[]),
  ('Sinistro','The Last Barbarian',ARRAY['Tobacco','Cedar','Leather','Pepper','Oak']::text[]),
  ('Sinistro','Year of the Cowboy Maduro',ARRAY['Molasses','Coffee','Oak','Black Pepper','Earth']::text[]),
  ('Sinistro','Year of the Cowboy Natural',ARRAY['Cedar','Vanilla','Hay','Spice','Caramel']::text[])
) AS d(brand,series,notes)
WHERE c.brand = d.brand AND c.series = d.series
  AND coalesce(c.is_public,true) = true
  AND (c.flavor_notes IS NULL OR array_length(c.flavor_notes,1) IS NULL);
