-- 150: Legg inn batch-2 premiummerker fra Neptune-kryssjekk (10 merker, 192 sigarer).
-- Esteban Carreras, Bandolero, Blanco, Chillin Moose, Los Statos,
-- Freud Cigar Company, Titan de Bronze, Gellis Family Cigars, Latitude Zero, Ilegal.
-- Moose-familien og Los Statos har egne merker. Forged/FLVR utelatt (novelty, kun duplikater ellers).
-- Generert fra databasen etter innsetting; filen samsvarer 1:1 med public.cigars.

INSERT INTO public.cigars
  (brand,series,vitola,shape,common_format,wrapper_country,wrapper_leaf,binder,filler,strength,country_origin,manufacturer,length_inches,ring_gauge,flavor_notes,description,is_public,source_tier,source_url,verified_at,aliases)
VALUES
  ('Bandolero','Bandolero Premium','Ironicos','Parejo','Ironicos','Ecuador','Habano 2000','Nicaragua',ARRAY['Nicaragua','Peru']::text[],3,'Costa Rica','Selected Tobacco',4.5,50,ARRAY['Earth','Cedar','Tobacco','Cream','Pepper']::text[],'En mellomsterk costaricansk sigar med Habano 2000-dekkblad, med toner av jord, seder, tobakk og fløte.',true,'retailer','https://cigar-coop.com/2025/04/selected-tobacco-to-release-bandolero-premium-at-pca-2025-cigar-news.html',now(),ARRAY['Bandolero']::text[]),
  ('Bandolero','Bandolero Premium','Bravos','Parejo','Bravos','Ecuador','Habano 2000','Nicaragua',ARRAY['Nicaragua','Peru']::text[],3,'Costa Rica','Selected Tobacco',5.3,52,ARRAY['Earth','Cedar','Tobacco','Cream','Pepper']::text[],'En mellomsterk costaricansk sigar med Habano 2000-dekkblad, med toner av jord, seder, tobakk og fløte.',true,'retailer','https://cigar-coop.com/2025/04/selected-tobacco-to-release-bandolero-premium-at-pca-2025-cigar-news.html',now(),ARRAY['Bandolero']::text[]),
  ('Bandolero','Bandolero Premium','Magnificos','Parejo','Magnificos','Ecuador','Habano 2000','Nicaragua',ARRAY['Nicaragua','Peru']::text[],3,'Costa Rica','Selected Tobacco',6,55,ARRAY['Earth','Cedar','Tobacco','Cream','Pepper']::text[],'En mellomsterk costaricansk sigar med Habano 2000-dekkblad, med toner av jord, seder, tobakk og fløte.',true,'retailer','https://cigar-coop.com/2025/04/selected-tobacco-to-release-bandolero-premium-at-pca-2025-cigar-news.html',now(),ARRAY['Bandolero']::text[]),
  ('Bandolero','Firecracker','Short Robusto','Parejo','Short Robusto','Ecuador',NULL,'Ecuador',ARRAY['Dominican Republic','Nicaragua']::text[],3,'Costa Rica','Selected Tobacco',3.5,50,ARRAY['Earth','Dark Chocolate','Black Pepper','Wood','Cream']::text[],'En mellomsterk costaricansk sigar med Ecuador-dekkblad, med toner av jord, mørk sjokolade, svart pepper og tre.',true,'retailer','https://halfwheel.com/bandolero-firecracker/412769/',now(),ARRAY['Bandolero']::text[]),
  ('Bandolero','Serie A (Aventureros)','Osados','Parejo','Osados','Ecuador','Habano','Peru',ARRAY['Peru','Nicaragua']::text[],4,'Costa Rica','Selected Tobacco',5,42,ARRAY['Black Pepper','Oak','Leather','Espresso','Cocoa']::text[],'En mellomsterk til fyldig costaricansk sigar med Habano-dekkblad, med toner av svart pepper, eik, lær og espresso.',true,'retailer','https://unitedcigargroup.com/bandolero-aventureros/',now(),ARRAY['Bandolero']::text[]),
  ('Bandolero','Serie A (Aventureros)','Sagaces','Parejo','Sagaces','Ecuador','Habano','Peru',ARRAY['Peru','Nicaragua']::text[],4,'Costa Rica','Selected Tobacco',5.4,46,ARRAY['Black Pepper','Oak','Leather','Espresso','Cocoa']::text[],'En mellomsterk til fyldig costaricansk sigar med Habano-dekkblad, med toner av svart pepper, eik, lær og espresso.',true,'retailer','https://unitedcigargroup.com/bandolero-aventureros/',now(),ARRAY['Bandolero']::text[]),
  ('Bandolero','Serie A (Aventureros)','Salvajes','Parejo','Salvajes','Ecuador','Habano','Peru',ARRAY['Peru','Nicaragua']::text[],4,'Costa Rica','Selected Tobacco',4.1,50,ARRAY['Black Pepper','Oak','Leather','Espresso','Cocoa']::text[],'En mellomsterk til fyldig costaricansk sigar med Habano-dekkblad, med toner av svart pepper, eik, lær og espresso.',true,'retailer','https://unitedcigargroup.com/bandolero-aventureros/',now(),ARRAY['Bandolero']::text[]),
  ('Bandolero','Serie A (Aventureros)','Audaces','Parejo','Audaces','Ecuador','Habano','Peru',ARRAY['Peru','Nicaragua']::text[],4,'Costa Rica','Selected Tobacco',4.5,54,ARRAY['Black Pepper','Oak','Leather','Espresso','Cocoa']::text[],'En mellomsterk til fyldig costaricansk sigar med Habano-dekkblad, med toner av svart pepper, eik, lær og espresso.',true,'retailer','https://unitedcigargroup.com/bandolero-aventureros/',now(),ARRAY['Bandolero']::text[]),
  ('Bandolero','Serie C (Clandestinos)','Traviesos','Parejo','Traviesos','Ecuador',NULL,'Peru',ARRAY['Peru','Brazil','Dominican Republic']::text[],3,'Costa Rica','Selected Tobacco',5,50,ARRAY['Toasted Nuts','Oak','Baking Spice','Floral','Cedar']::text[],'En mellomsterk costaricansk sigar med Ecuador-dekkblad, med toner av ristede nøtter, eik, bakekrydder og blomster.',true,'retailer','https://unitedcigargroup.com/bandolero-clandestinos/',now(),ARRAY['Bandolero']::text[]),
  ('Bandolero','Serie C (Clandestinos)','Soberbios','Parejo','Soberbios','Ecuador',NULL,'Peru',ARRAY['Peru','Brazil','Dominican Republic']::text[],3,'Costa Rica','Selected Tobacco',5.5,50,ARRAY['Toasted Nuts','Oak','Baking Spice','Floral','Cedar']::text[],'En mellomsterk costaricansk sigar med Ecuador-dekkblad, med toner av ristede nøtter, eik, bakekrydder og blomster.',true,'retailer','https://unitedcigargroup.com/bandolero-clandestinos/',now(),ARRAY['Bandolero']::text[]),
  ('Bandolero','Serie C (Clandestinos)','Colosales','Parejo','Colosales','Ecuador',NULL,'Peru',ARRAY['Peru','Brazil','Dominican Republic']::text[],3,'Costa Rica','Selected Tobacco',6,54,ARRAY['Toasted Nuts','Oak','Baking Spice','Floral','Cedar']::text[],'En mellomsterk costaricansk sigar med Ecuador-dekkblad, med toner av ristede nøtter, eik, bakekrydder og blomster.',true,'retailer','https://unitedcigargroup.com/bandolero-clandestinos/',now(),ARRAY['Bandolero']::text[]),
  ('Bandolero','Serie C (Clandestinos)','Barbaros','Parejo','Barbaros','Ecuador',NULL,'Peru',ARRAY['Peru','Brazil','Dominican Republic']::text[],3,'Costa Rica','Selected Tobacco',4.5,60,ARRAY['Toasted Nuts','Oak','Baking Spice','Floral','Cedar']::text[],'En mellomsterk costaricansk sigar med Ecuador-dekkblad, med toner av ristede nøtter, eik, bakekrydder og blomster.',true,'retailer','https://unitedcigargroup.com/bandolero-clandestinos/',now(),ARRAY['Bandolero']::text[]),
  ('Bandolero','Serie T (Traficantes)','Tremendos','Parejo','Tremendos','Ecuador',NULL,'Peru',ARRAY['Peru','Brazil','Dominican Republic']::text[],4,'Costa Rica','Selected Tobacco',5,50,ARRAY['Citrus','Mocha','Black Pepper','Earth','Toasted Nuts']::text[],'En mellomsterk til fyldig costaricansk sigar med Ecuador-dekkblad, med toner av sitrus, mokka, svart pepper og jord.',true,'retailer','https://unitedcigargroup.com/bandolero-traficantes/',now(),ARRAY['Bandolero']::text[]),
  ('Bandolero','Serie T (Traficantes)','Picaros','Parejo','Picaros','Ecuador',NULL,'Peru',ARRAY['Peru','Brazil','Dominican Republic']::text[],4,'Costa Rica','Selected Tobacco',5.5,54,ARRAY['Citrus','Mocha','Black Pepper','Earth','Toasted Nuts']::text[],'En mellomsterk til fyldig costaricansk sigar med Ecuador-dekkblad, med toner av sitrus, mokka, svart pepper og jord.',true,'retailer','https://unitedcigargroup.com/bandolero-traficantes/',now(),ARRAY['Bandolero']::text[]),
  ('Bandolero','Serie T (Traficantes)','Vanidosos','Parejo','Vanidosos','Ecuador',NULL,'Peru',ARRAY['Peru','Brazil','Dominican Republic']::text[],4,'Costa Rica','Selected Tobacco',6,54,ARRAY['Citrus','Mocha','Black Pepper','Earth','Toasted Nuts']::text[],'En mellomsterk til fyldig costaricansk sigar med Ecuador-dekkblad, med toner av sitrus, mokka, svart pepper og jord.',true,'retailer','https://unitedcigargroup.com/bandolero-traficantes/',now(),ARRAY['Bandolero']::text[]),
  ('Bandolero','Serie T (Traficantes)','Pretenciosos','Parejo','Pretenciosos','Ecuador',NULL,'Peru',ARRAY['Peru','Brazil','Dominican Republic']::text[],4,'Costa Rica','Selected Tobacco',6.5,60,ARRAY['Citrus','Mocha','Black Pepper','Earth','Toasted Nuts']::text[],'En mellomsterk til fyldig costaricansk sigar med Ecuador-dekkblad, med toner av sitrus, mokka, svart pepper og jord.',true,'retailer','https://unitedcigargroup.com/bandolero-traficantes/',now(),ARRAY['Bandolero']::text[]);

INSERT INTO public.cigars
  (brand,series,vitola,shape,common_format,wrapper_country,wrapper_leaf,binder,filler,strength,country_origin,manufacturer,length_inches,ring_gauge,flavor_notes,description,is_public,source_tier,source_url,verified_at,aliases)
VALUES
  ('Blanco','Above and Beyond','Belicoso','Figurado','Belicoso','Nicaragua','Habano Rosado','Honduras',ARRAY['Nicaragua']::text[],3,'Nicaragua','Blanco Cigar Co.',5,54,ARRAY['Molasses','Nuts','Baking Spice','Floral','Butter']::text[],'En mellomsterk nicaraguansk sigar med Habano Rosado-dekkblad, med toner av melasse, nøtter, bakekrydder og blomster.',true,'retailer','https://cigarpublic.com/2023/03/27/above-and-beyond-unwilling-heroes/',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Above and Beyond','Churchill','Parejo','Churchill','Nicaragua','Habano Rosado','Honduras',ARRAY['Nicaragua']::text[],3,'Nicaragua','Blanco Cigar Co.',7,54,ARRAY['Molasses','Nuts','Baking Spice','Floral','Butter']::text[],'En mellomsterk nicaraguansk sigar med Habano Rosado-dekkblad, med toner av melasse, nøtter, bakekrydder og blomster.',true,'retailer','https://cigarpublic.com/2023/03/27/above-and-beyond-unwilling-heroes/',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Above and Beyond','Gordo','Parejo','Gordo','Nicaragua','Habano Rosado','Honduras',ARRAY['Nicaragua']::text[],3,'Nicaragua','Blanco Cigar Co.',6,60,ARRAY['Molasses','Nuts','Baking Spice','Floral','Butter']::text[],'En mellomsterk nicaraguansk sigar med Habano Rosado-dekkblad, med toner av melasse, nøtter, bakekrydder og blomster.',true,'retailer','https://cigarpublic.com/2023/03/27/above-and-beyond-unwilling-heroes/',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Cigar Obsession 1st Third','Lancero','Parejo','Lancero','Ecuador','Sumatra','Nicaragua & Honduras',ARRAY['Nicaragua','Honduras']::text[],4,'Nicaragua','Blanco Cigar Co.',7,38,ARRAY['Earth','Black Pepper','Chocolate','Cinnamon']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Sumatra-dekkblad, med toner av jord, svart pepper, sjokolade og kanel.',true,'retailer','https://cigarandpipes.com/product/cigar-obsession-cigars/',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Cigar Obsession 1st Third','Robusto','Parejo','Robusto','Ecuador','Sumatra','Nicaragua & Honduras',ARRAY['Nicaragua','Honduras']::text[],4,'Nicaragua','Blanco Cigar Co.',5,52,ARRAY['Earth','Black Pepper','Chocolate','Cinnamon']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Sumatra-dekkblad, med toner av jord, svart pepper, sjokolade og kanel.',true,'retailer','https://cigarandpipes.com/product/cigar-obsession-cigars/',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Cigar Obsession 1st Third','Toro','Parejo','Toro','Ecuador','Sumatra','Nicaragua & Honduras',ARRAY['Nicaragua','Honduras']::text[],4,'Nicaragua','Blanco Cigar Co.',6,52,ARRAY['Earth','Black Pepper','Chocolate','Cinnamon']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Sumatra-dekkblad, med toner av jord, svart pepper, sjokolade og kanel.',true,'retailer','https://cigarandpipes.com/product/cigar-obsession-cigars/',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Cigar Obsession 2nd Third','Robusto','Parejo','Robusto','Cameroon','Cameroon','Nicaragua',ARRAY['Nicaragua']::text[],3,'Nicaragua','Blanco Cigar Co.',5,52,ARRAY['Leather','Cedar','Spice','Cream','Sweetness']::text[],'En mellomsterk nicaraguansk sigar med Cameroon-dekkblad, med toner av lær, seder, krydder og fløte.',true,'retailer','https://cigarandpipes.com/product/cigar-obsession-cigars/',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Cigar Obsession 2nd Third','Toro','Parejo','Toro','Cameroon','Cameroon','Nicaragua',ARRAY['Nicaragua']::text[],3,'Nicaragua','Blanco Cigar Co.',6,52,ARRAY['Leather','Cedar','Spice','Cream','Sweetness']::text[],'En mellomsterk nicaraguansk sigar med Cameroon-dekkblad, med toner av lær, seder, krydder og fløte.',true,'retailer','https://cigarandpipes.com/product/cigar-obsession-cigars/',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Cigar Obsession 2nd Third','Salomon','Figurado','Salomon','Cameroon','Cameroon','Nicaragua',ARRAY['Nicaragua']::text[],3,'Nicaragua','Blanco Cigar Co.',6.1,52,ARRAY['Leather','Cedar','Spice','Cream','Sweetness']::text[],'En mellomsterk nicaraguansk sigar med Cameroon-dekkblad, med toner av lær, seder, krydder og fløte.',true,'retailer','https://cigarandpipes.com/product/cigar-obsession-cigars/',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Cigar Obsession BG Reserve','Short Lonsdale','Parejo','Short Lonsdale','Mexico','San Andres','Indonesia (Sumatra)',ARRAY['Nicaragua']::text[],4,'Nicaragua','Blanco Cigar Co.',5.5,46,ARRAY['Cocoa','Earth','Pepper','Coffee']::text[],'En mellomsterk til fyldig nicaraguansk sigar med San Andres-dekkblad, med toner av kakao, jord, pepper og kaffe.',true,'retailer','https://halfwheel.com/blanco-adding-bg-reserve-to-cigar-obsession-series/396596/',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Cigar Obsession BG Reserve','Robusto','Parejo','Robusto','Mexico','San Andres','Indonesia (Sumatra)',ARRAY['Nicaragua']::text[],4,'Nicaragua','Blanco Cigar Co.',5,52,ARRAY['Cocoa','Earth','Pepper','Coffee']::text[],'En mellomsterk til fyldig nicaraguansk sigar med San Andres-dekkblad, med toner av kakao, jord, pepper og kaffe.',true,'retailer','https://halfwheel.com/blanco-adding-bg-reserve-to-cigar-obsession-series/396596/',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Cigar Obsession BG Reserve','Toro Barber Pole','Parejo','Toro Barber Pole','Mexico','San Andres','Indonesia (Sumatra)',ARRAY['Nicaragua']::text[],4,'Nicaragua','Blanco Cigar Co.',6,52,ARRAY['Cocoa','Earth','Pepper','Coffee']::text[],'En mellomsterk til fyldig nicaraguansk sigar med San Andres-dekkblad, med toner av kakao, jord, pepper og kaffe.',true,'retailer','https://halfwheel.com/blanco-adding-bg-reserve-to-cigar-obsession-series/396596/',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Cigar Obsession BG Reserve','Figurado','Figurado','Figurado','Mexico','San Andres','Indonesia (Sumatra)',ARRAY['Nicaragua']::text[],4,'Nicaragua','Blanco Cigar Co.',5.4,60,ARRAY['Cocoa','Earth','Pepper','Coffee']::text[],'En mellomsterk til fyldig nicaraguansk sigar med San Andres-dekkblad, med toner av kakao, jord, pepper og kaffe.',true,'retailer','https://halfwheel.com/blanco-adding-bg-reserve-to-cigar-obsession-series/396596/',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Cigar Obsession Final Third','Lancero','Parejo','Lancero','Nicaragua','Habano Rosado','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Blanco Cigar Co.',7,38,ARRAY['Earth','Wood','Cocoa','Black Pepper','Cream']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Habano Rosado-dekkblad, med toner av jord, tre, kakao og svart pepper.',true,'retailer','https://cigarandpipes.com/product/cigar-obsession-cigars/',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Cigar Obsession Final Third','Robusto','Parejo','Robusto','Nicaragua','Habano Rosado','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Blanco Cigar Co.',5,54,ARRAY['Earth','Wood','Cocoa','Black Pepper','Cream']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Habano Rosado-dekkblad, med toner av jord, tre, kakao og svart pepper.',true,'retailer','https://cigarandpipes.com/product/cigar-obsession-cigars/',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Cigar Obsession Final Third','Toro','Parejo','Toro','Nicaragua','Habano Rosado','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Blanco Cigar Co.',6,54,ARRAY['Earth','Wood','Cocoa','Black Pepper','Cream']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Habano Rosado-dekkblad, med toner av jord, tre, kakao og svart pepper.',true,'retailer','https://cigarandpipes.com/product/cigar-obsession-cigars/',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Liga Exclusiva de Familia Connecticut','Robusto','Parejo','Robusto','USA','Connecticut Shade','Nicaragua',ARRAY['Nicaragua']::text[],3,'Nicaragua','Blanco Cigar Co.',5,54,ARRAY['Wood','Earth','Pepper','Cream']::text[],'En mellomsterk nicaraguansk sigar med Connecticut Shade-dekkblad, med toner av tre, jord, pepper og fløte.',true,'retailer','https://www.neptunecigar.com/cigars/blanco-liga-exclusiva-de-familia-connecticut-toro',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Liga Exclusiva de Familia Connecticut','Salomon','Figurado','Salomon','USA','Connecticut Shade','Nicaragua',ARRAY['Nicaragua']::text[],3,'Nicaragua','Blanco Cigar Co.',6,54,ARRAY['Wood','Earth','Pepper','Cream']::text[],'En mellomsterk nicaraguansk sigar med Connecticut Shade-dekkblad, med toner av tre, jord, pepper og fløte.',true,'retailer','https://www.neptunecigar.com/cigars/blanco-liga-exclusiva-de-familia-connecticut-toro',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Liga Exclusiva de Familia Connecticut','Toro','Parejo','Toro','USA','Connecticut Shade','Nicaragua',ARRAY['Nicaragua']::text[],3,'Nicaragua','Blanco Cigar Co.',6,54,ARRAY['Wood','Earth','Pepper','Cream']::text[],'En mellomsterk nicaraguansk sigar med Connecticut Shade-dekkblad, med toner av tre, jord, pepper og fløte.',true,'retailer','https://www.neptunecigar.com/cigars/blanco-liga-exclusiva-de-familia-connecticut-toro',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Liga Exclusiva de Familia Maduro','Robusto','Parejo','Robusto','USA','Pennsylvania Maduro','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Blanco Cigar Co.',5,54,ARRAY['Pepper','Wood','Spice','Sweetness']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Pennsylvania Maduro-dekkblad, med toner av pepper, tre, krydder og sødme.',true,'retailer','https://www.neptunecigar.com/cigars/blanco-liga-exclusiva-de-familia-maduro-toro',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Liga Exclusiva de Familia Maduro','Salomon','Figurado','Salomon','USA','Pennsylvania Maduro','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Blanco Cigar Co.',6,54,ARRAY['Pepper','Wood','Spice','Sweetness']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Pennsylvania Maduro-dekkblad, med toner av pepper, tre, krydder og sødme.',true,'retailer','https://www.neptunecigar.com/cigars/blanco-liga-exclusiva-de-familia-maduro-toro',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Liga Exclusiva de Familia Maduro','Toro','Parejo','Toro','USA','Pennsylvania Maduro','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Blanco Cigar Co.',6,54,ARRAY['Pepper','Wood','Spice','Sweetness']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Pennsylvania Maduro-dekkblad, med toner av pepper, tre, krydder og sødme.',true,'retailer','https://www.neptunecigar.com/cigars/blanco-liga-exclusiva-de-familia-maduro-toro',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Nine','Minutos','Parejo','Minutos','Nicaragua','Corojo Oscuro','Nicaragua (Jalapa)',ARRAY['Nicaragua']::text[],5,'Nicaragua','Blanco Cigar Co.',4,38,ARRAY['Coffee','Earth','Spice']::text[],'En fyldig og kraftig nicaraguansk sigar med Corojo Oscuro-dekkblad, med toner av kaffe, jord og krydder.',true,'retailer','https://www.neptunecigar.com/cigars/blanco-nine-oscuro-corojo-robusto',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Nine','Lancero','Parejo','Lancero','Nicaragua','Corojo Oscuro','Nicaragua (Jalapa)',ARRAY['Nicaragua']::text[],5,'Nicaragua','Blanco Cigar Co.',7,38,ARRAY['Coffee','Earth','Spice']::text[],'En fyldig og kraftig nicaraguansk sigar med Corojo Oscuro-dekkblad, med toner av kaffe, jord og krydder.',true,'retailer','https://www.neptunecigar.com/cigars/blanco-nine-oscuro-corojo-robusto',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Nine','Toro','Parejo','Toro','Nicaragua','Corojo Oscuro','Nicaragua (Jalapa)',ARRAY['Nicaragua']::text[],5,'Nicaragua','Blanco Cigar Co.',6,48,ARRAY['Coffee','Earth','Spice']::text[],'En fyldig og kraftig nicaraguansk sigar med Corojo Oscuro-dekkblad, med toner av kaffe, jord og krydder.',true,'retailer','https://www.neptunecigar.com/cigars/blanco-nine-oscuro-corojo-robusto',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Nine','Robusto','Parejo','Robusto','Nicaragua','Corojo Oscuro','Nicaragua (Jalapa)',ARRAY['Nicaragua']::text[],5,'Nicaragua','Blanco Cigar Co.',5,52,ARRAY['Coffee','Earth','Spice']::text[],'En fyldig og kraftig nicaraguansk sigar med Corojo Oscuro-dekkblad, med toner av kaffe, jord og krydder.',true,'retailer','https://www.neptunecigar.com/cigars/blanco-nine-oscuro-corojo-robusto',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Nine','Toro Gordo','Parejo','Toro Gordo','Nicaragua','Corojo Oscuro','Nicaragua (Jalapa)',ARRAY['Nicaragua']::text[],5,'Nicaragua','Blanco Cigar Co.',6,52,ARRAY['Coffee','Earth','Spice']::text[],'En fyldig og kraftig nicaraguansk sigar med Corojo Oscuro-dekkblad, med toner av kaffe, jord og krydder.',true,'retailer','https://www.neptunecigar.com/cigars/blanco-nine-oscuro-corojo-robusto',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Nine JT Limitado','Toro Gordo','Parejo','Toro Gordo','Nicaragua','Habano Ligero','Nicaragua (Ligero)',ARRAY['Nicaragua']::text[],5,'Nicaragua','Blanco Cigar Co.',6.3,58,ARRAY['Cocoa','Leather','Espresso','Coffee','Spice']::text[],'En fyldig og kraftig nicaraguansk sigar med Habano Ligero-dekkblad, med toner av kakao, lær, espresso og kaffe.',true,'retailer','https://cigarandpipes.com/product/blanco-nine-jt-limitado-6-2x58/',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Primos Estate Selection Habano Criollo Maduro','Robusto','Parejo','Robusto','Nicaragua','Habano Maduro','Honduras',ARRAY['Honduras','Nicaragua','Peru']::text[],5,'Nicaragua','Blanco Cigar Co.',5,52,ARRAY['Earth','White Pepper','Cinnamon','Mocha','Oak']::text[],'En fyldig og kraftig nicaraguansk sigar med Habano Maduro-dekkblad, med toner av jord, hvit pepper, kanel og mokka.',true,'retailer','https://www.cigarplace.biz/all-brands/primos-estate-selection-habano-criollo-maduro.html',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Primos Estate Selection Habano Criollo Maduro','Toro','Parejo','Toro','Nicaragua','Habano Maduro','Honduras',ARRAY['Honduras','Nicaragua','Peru']::text[],5,'Nicaragua','Blanco Cigar Co.',6,52,ARRAY['Earth','White Pepper','Cinnamon','Mocha','Oak']::text[],'En fyldig og kraftig nicaraguansk sigar med Habano Maduro-dekkblad, med toner av jord, hvit pepper, kanel og mokka.',true,'retailer','https://www.cigarplace.biz/all-brands/primos-estate-selection-habano-criollo-maduro.html',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Primos Estate Selection Habano Criollo Maduro','Double Corona','Parejo','Double Corona','Nicaragua','Habano Maduro','Honduras',ARRAY['Honduras','Nicaragua','Peru']::text[],5,'Nicaragua','Blanco Cigar Co.',7,52,ARRAY['Earth','White Pepper','Cinnamon','Mocha','Oak']::text[],'En fyldig og kraftig nicaraguansk sigar med Habano Maduro-dekkblad, med toner av jord, hvit pepper, kanel og mokka.',true,'retailer','https://www.cigarplace.biz/all-brands/primos-estate-selection-habano-criollo-maduro.html',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Primos Estate Selection Habano Criollo Maduro','Sesenta','Parejo','Sesenta','Nicaragua','Habano Maduro','Honduras',ARRAY['Honduras','Nicaragua','Peru']::text[],5,'Nicaragua','Blanco Cigar Co.',6,60,ARRAY['Earth','White Pepper','Cinnamon','Mocha','Oak']::text[],'En fyldig og kraftig nicaraguansk sigar med Habano Maduro-dekkblad, med toner av jord, hvit pepper, kanel og mokka.',true,'retailer','https://www.cigarplace.biz/all-brands/primos-estate-selection-habano-criollo-maduro.html',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Primos Estate Selection Habano Criollo Rosado','Robusto','Parejo','Robusto','Nicaragua','Habano Rosado','Honduras',ARRAY['Honduras','Nicaragua','Peru']::text[],5,'Nicaragua','Blanco Cigar Co.',5,52,ARRAY['Pepper','Cinnamon','Cedar','Caramel','Earth']::text[],'En fyldig og kraftig nicaraguansk sigar med Habano Rosado-dekkblad, med toner av pepper, kanel, seder og karamell.',true,'retailer','https://www.cigarplace.biz/all-brands/primos-estate-selection-habano-criollo-rosado.html',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Primos Estate Selection Habano Criollo Rosado','Double Corona','Parejo','Double Corona','Nicaragua','Habano Rosado','Honduras',ARRAY['Honduras','Nicaragua','Peru']::text[],5,'Nicaragua','Blanco Cigar Co.',7,52,ARRAY['Pepper','Cinnamon','Cedar','Caramel','Earth']::text[],'En fyldig og kraftig nicaraguansk sigar med Habano Rosado-dekkblad, med toner av pepper, kanel, seder og karamell.',true,'retailer','https://www.cigarplace.biz/all-brands/primos-estate-selection-habano-criollo-rosado.html',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Primos Estate Selection Habano Criollo Rosado','Sesenta','Parejo','Sesenta','Nicaragua','Habano Rosado','Honduras',ARRAY['Honduras','Nicaragua','Peru']::text[],5,'Nicaragua','Blanco Cigar Co.',6,60,ARRAY['Pepper','Cinnamon','Cedar','Caramel','Earth']::text[],'En fyldig og kraftig nicaraguansk sigar med Habano Rosado-dekkblad, med toner av pepper, kanel, seder og karamell.',true,'retailer','https://www.cigarplace.biz/all-brands/primos-estate-selection-habano-criollo-rosado.html',now(),ARRAY['Blanco']::text[]),
  ('Blanco','Primos Estate Selection Habano Criollo Rosado','Munon','Parejo','Munon','Nicaragua','Habano Rosado','Honduras',ARRAY['Honduras','Nicaragua','Peru']::text[],5,'Nicaragua','Blanco Cigar Co.',5,64,ARRAY['Pepper','Cinnamon','Cedar','Caramel','Earth']::text[],'En fyldig og kraftig nicaraguansk sigar med Habano Rosado-dekkblad, med toner av pepper, kanel, seder og karamell.',true,'retailer','https://www.cigarplace.biz/all-brands/primos-estate-selection-habano-criollo-rosado.html',now(),ARRAY['Blanco']::text[]);

INSERT INTO public.cigars
  (brand,series,vitola,shape,common_format,wrapper_country,wrapper_leaf,binder,filler,strength,country_origin,manufacturer,length_inches,ring_gauge,flavor_notes,description,is_public,source_tier,source_url,verified_at,aliases)
VALUES
  ('Chillin Moose','Bull Moose','Robusto Gordo','Parejo','Robusto Gordo','Nicaragua','Nicaraguan Habano','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Foundry Tobacco Co.',5,60,ARRAY['Earth','Cocoa','Black Pepper','Coffee','Dried Fruit']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Nicaraguan Habano-dekkblad, med toner av jord, kakao, svart pepper og kaffe.',true,'retailer','https://www.cigarplace.biz/all-brands/chillin-moose-cigars/chillin-moose-bull-moose.html',now(),ARRAY['Chillin Moose']::text[]),
  ('Chillin Moose','Bull Moose','Gigante','Parejo','Gigante','Nicaragua','Nicaraguan Habano','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Foundry Tobacco Co.',6,60,ARRAY['Earth','Cocoa','Black Pepper','Coffee','Dried Fruit']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Nicaraguan Habano-dekkblad, med toner av jord, kakao, svart pepper og kaffe.',true,'retailer','https://www.cigarplace.biz/all-brands/chillin-moose-cigars/chillin-moose-bull-moose.html',now(),ARRAY['Chillin Moose']::text[]),
  ('Chillin Moose','Bull Moose','Gigante XXL','Parejo','Gigante XXL','Nicaragua','Nicaraguan Habano','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Foundry Tobacco Co.',7,60,ARRAY['Earth','Cocoa','Black Pepper','Coffee','Dried Fruit']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Nicaraguan Habano-dekkblad, med toner av jord, kakao, svart pepper og kaffe.',true,'retailer','https://www.cigarplace.biz/all-brands/chillin-moose-cigars/chillin-moose-bull-moose.html',now(),ARRAY['Chillin Moose']::text[]),
  ('Chillin Moose','Bull Moose','Gigante XL','Parejo','Gigante XL','Nicaragua','Nicaraguan Habano','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Foundry Tobacco Co.',6,70,ARRAY['Earth','Cocoa','Black Pepper','Coffee','Dried Fruit']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Nicaraguan Habano-dekkblad, med toner av jord, kakao, svart pepper og kaffe.',true,'retailer','https://www.cigarplace.biz/all-brands/chillin-moose-cigars/chillin-moose-bull-moose.html',now(),ARRAY['Chillin Moose']::text[]),
  ('Chillin Moose','Bull Moose Maduro','Robusto Gordo','Parejo','Robusto Gordo','Nicaragua','Nicaraguan Maduro','Nicaragua',ARRAY['Nicaragua']::text[],5,'Nicaragua','Foundry Tobacco Co.',5,60,ARRAY['Earth','Spice','Sweetness']::text[],'En fyldig og kraftig nicaraguansk sigar med Nicaraguan Maduro-dekkblad, med toner av jord, krydder og sødme.',true,'retailer','https://mikescigars.com/cigars/brands/chillinmoose/chillin-moose-bull-moose-maduro',now(),ARRAY['Chillin Moose']::text[]),
  ('Chillin Moose','Bull Moose Maduro','Gigante','Parejo','Gigante','Nicaragua','Nicaraguan Maduro','Nicaragua',ARRAY['Nicaragua']::text[],5,'Nicaragua','Foundry Tobacco Co.',6,60,ARRAY['Earth','Spice','Sweetness']::text[],'En fyldig og kraftig nicaraguansk sigar med Nicaraguan Maduro-dekkblad, med toner av jord, krydder og sødme.',true,'retailer','https://mikescigars.com/cigars/brands/chillinmoose/chillin-moose-bull-moose-maduro',now(),ARRAY['Chillin Moose']::text[]),
  ('Chillin Moose','Bull Moose Maduro','Gigante XXL','Parejo','Gigante XXL','Nicaragua','Nicaraguan Maduro','Nicaragua',ARRAY['Nicaragua']::text[],5,'Nicaragua','Foundry Tobacco Co.',7,60,ARRAY['Earth','Spice','Sweetness']::text[],'En fyldig og kraftig nicaraguansk sigar med Nicaraguan Maduro-dekkblad, med toner av jord, krydder og sødme.',true,'retailer','https://mikescigars.com/cigars/brands/chillinmoose/chillin-moose-bull-moose-maduro',now(),ARRAY['Chillin Moose']::text[]),
  ('Chillin Moose','Bull Moose Maduro','Gigante XL','Parejo','Gigante XL','Nicaragua','Nicaraguan Maduro','Nicaragua',ARRAY['Nicaragua']::text[],5,'Nicaragua','Foundry Tobacco Co.',6,70,ARRAY['Earth','Spice','Sweetness']::text[],'En fyldig og kraftig nicaraguansk sigar med Nicaraguan Maduro-dekkblad, med toner av jord, krydder og sødme.',true,'retailer','https://mikescigars.com/cigars/brands/chillinmoose/chillin-moose-bull-moose-maduro',now(),ARRAY['Chillin Moose']::text[]),
  ('Chillin Moose','Chillin'' Moose','Corona','Parejo','Corona','USA','Connecticut Habano Rosado','Ecuadorian Sumatra',ARRAY['Nicaragua','Dominican Republic','USA Broadleaf','Mexican San Andres']::text[],2,'Nicaragua','Foundry Tobacco Co.',5.3,42,ARRAY['Cedar','Leather','Toasted Nuts','Caramel','Sweetness']::text[],'En mild til mellomsterk nicaraguansk sigar med Connecticut Habano Rosado-dekkblad, med toner av seder, lær, ristede nøtter og karamell.',true,'retailer','https://www.cigarsinternational.com/p/chillin-moose-cigars/1484859/',now(),ARRAY['Chillin Moose']::text[]),
  ('Chillin Moose','Chillin'' Moose','Robusto','Parejo','Robusto','USA','Connecticut Habano Rosado','Ecuadorian Sumatra',ARRAY['Nicaragua','Dominican Republic','USA Broadleaf','Mexican San Andres']::text[],2,'Nicaragua','Foundry Tobacco Co.',5,50,ARRAY['Cedar','Leather','Toasted Nuts','Caramel','Sweetness']::text[],'En mild til mellomsterk nicaraguansk sigar med Connecticut Habano Rosado-dekkblad, med toner av seder, lær, ristede nøtter og karamell.',true,'retailer','https://www.cigarsinternational.com/p/chillin-moose-cigars/1484859/',now(),ARRAY['Chillin Moose']::text[]),
  ('Chillin Moose','Chillin'' Moose','Toro','Parejo','Toro','USA','Connecticut Habano Rosado','Ecuadorian Sumatra',ARRAY['Nicaragua','Dominican Republic','USA Broadleaf','Mexican San Andres']::text[],2,'Nicaragua','Foundry Tobacco Co.',6,52,ARRAY['Cedar','Leather','Toasted Nuts','Caramel','Sweetness']::text[],'En mild til mellomsterk nicaraguansk sigar med Connecticut Habano Rosado-dekkblad, med toner av seder, lær, ristede nøtter og karamell.',true,'retailer','https://www.cigarsinternational.com/p/chillin-moose-cigars/1484859/',now(),ARRAY['Chillin Moose']::text[]),
  ('Chillin Moose','Chillin'' Moose','Gigante','Parejo','Gigante','USA','Connecticut Habano Rosado','Ecuadorian Sumatra',ARRAY['Nicaragua','Dominican Republic','USA Broadleaf','Mexican San Andres']::text[],2,'Nicaragua','Foundry Tobacco Co.',6,60,ARRAY['Cedar','Leather','Toasted Nuts','Caramel','Sweetness']::text[],'En mild til mellomsterk nicaraguansk sigar med Connecticut Habano Rosado-dekkblad, med toner av seder, lær, ristede nøtter og karamell.',true,'retailer','https://www.cigarsinternational.com/p/chillin-moose-cigars/1484859/',now(),ARRAY['Chillin Moose']::text[]),
  ('Chillin Moose','Chillin'' Moose Too','Corona','Parejo','Corona','USA','Connecticut Broadleaf Maduro','Nicaragua',ARRAY['Nicaragua']::text[],3,'Nicaragua','Foundry Tobacco Co.',5.3,45,ARRAY['Cedar','Cocoa','Spice','Vanilla','Sweetness']::text[],'En mellomsterk nicaraguansk sigar med Connecticut Broadleaf Maduro-dekkblad, med toner av seder, kakao, krydder og vanilje.',true,'retailer','https://halfwheel.com/foundry-tobacco-co-s-chillin-moose-too-arriving-at-retailers/115700/',now(),ARRAY['Chillin Moose']::text[]),
  ('Chillin Moose','Chillin'' Moose Too','Robusto','Parejo','Robusto','USA','Connecticut Broadleaf Maduro','Nicaragua',ARRAY['Nicaragua']::text[],3,'Nicaragua','Foundry Tobacco Co.',5.5,50,ARRAY['Cedar','Cocoa','Spice','Vanilla','Sweetness']::text[],'En mellomsterk nicaraguansk sigar med Connecticut Broadleaf Maduro-dekkblad, med toner av seder, kakao, krydder og vanilje.',true,'retailer','https://halfwheel.com/foundry-tobacco-co-s-chillin-moose-too-arriving-at-retailers/115700/',now(),ARRAY['Chillin Moose']::text[]),
  ('Chillin Moose','Chillin'' Moose Too','Toro','Parejo','Toro','USA','Connecticut Broadleaf Maduro','Nicaragua',ARRAY['Nicaragua']::text[],3,'Nicaragua','Foundry Tobacco Co.',6,52,ARRAY['Cedar','Cocoa','Spice','Vanilla','Sweetness']::text[],'En mellomsterk nicaraguansk sigar med Connecticut Broadleaf Maduro-dekkblad, med toner av seder, kakao, krydder og vanilje.',true,'retailer','https://halfwheel.com/foundry-tobacco-co-s-chillin-moose-too-arriving-at-retailers/115700/',now(),ARRAY['Chillin Moose']::text[]),
  ('Chillin Moose','Chillin'' Moose Too','Gigante','Parejo','Gigante','USA','Connecticut Broadleaf Maduro','Nicaragua',ARRAY['Nicaragua']::text[],3,'Nicaragua','Foundry Tobacco Co.',6,60,ARRAY['Cedar','Cocoa','Spice','Vanilla','Sweetness']::text[],'En mellomsterk nicaraguansk sigar med Connecticut Broadleaf Maduro-dekkblad, med toner av seder, kakao, krydder og vanilje.',true,'retailer','https://halfwheel.com/foundry-tobacco-co-s-chillin-moose-too-arriving-at-retailers/115700/',now(),ARRAY['Chillin Moose']::text[]),
  ('Chillin Moose','Shady Moose','Robusto','Parejo','Robusto','Ecuador','Ecuadorian Connecticut Shade','Mexico',ARRAY['Colombia','Dominican Republic','Nicaragua','USA']::text[],2,'Honduras','Foundry Tobacco Co.',5.5,50,ARRAY['White Pepper','Black Pepper','Toast','Cream','Citrus']::text[],'En mild til mellomsterk honduransk sigar med Ecuadorian Connecticut Shade-dekkblad, med toner av hvit pepper, svart pepper, ristet brød og fløte.',true,'retailer','https://halfwheel.com/shady-moose-robusto/423341/',now(),ARRAY['Chillin Moose']::text[]),
  ('Chillin Moose','Shady Moose','Toro','Parejo','Toro','Ecuador','Ecuadorian Connecticut Shade','Mexico',ARRAY['Colombia','Dominican Republic','Nicaragua','USA']::text[],2,'Honduras','Foundry Tobacco Co.',6,52,ARRAY['White Pepper','Black Pepper','Toast','Cream','Citrus']::text[],'En mild til mellomsterk honduransk sigar med Ecuadorian Connecticut Shade-dekkblad, med toner av hvit pepper, svart pepper, ristet brød og fløte.',true,'retailer','https://halfwheel.com/shady-moose-robusto/423341/',now(),ARRAY['Chillin Moose']::text[]),
  ('Chillin Moose','Shady Moose','Gigante','Parejo','Gigante','Ecuador','Ecuadorian Connecticut Shade','Mexico',ARRAY['Colombia','Dominican Republic','Nicaragua','USA']::text[],2,'Honduras','Foundry Tobacco Co.',6,60,ARRAY['White Pepper','Black Pepper','Toast','Cream','Citrus']::text[],'En mild til mellomsterk honduransk sigar med Ecuadorian Connecticut Shade-dekkblad, med toner av hvit pepper, svart pepper, ristet brød og fløte.',true,'retailer','https://halfwheel.com/shady-moose-robusto/423341/',now(),ARRAY['Chillin Moose']::text[]);

INSERT INTO public.cigars
  (brand,series,vitola,shape,common_format,wrapper_country,wrapper_leaf,binder,filler,strength,country_origin,manufacturer,length_inches,ring_gauge,flavor_notes,description,is_public,source_tier,source_url,verified_at,aliases)
VALUES
  ('Esteban Carreras','Cashmere','Boolit','Parejo','Boolit','Ecuador','Connecticut','Nicaragua',ARRAY['Nicaragua']::text[],2,'Nicaragua','Esteban Carreras',4.8,46,ARRAY['Cream','Cedar','Toasted Nuts','Coffee','White Pepper']::text[],'En mild til mellomsterk nicaraguansk sigar med Connecticut-dekkblad, med toner av fløte, seder, ristede nøtter og kaffe.',true,'retailer','https://halfwheel.com/esteban-carreras-cashmere-churchill/381377/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Cashmere','Toro','Parejo','Toro','Ecuador','Connecticut','Nicaragua',ARRAY['Nicaragua']::text[],2,'Nicaragua','Esteban Carreras',6,50,ARRAY['Cream','Cedar','Toasted Nuts','Coffee','White Pepper']::text[],'En mild til mellomsterk nicaraguansk sigar med Connecticut-dekkblad, med toner av fløte, seder, ristede nøtter og kaffe.',true,'retailer','https://halfwheel.com/esteban-carreras-cashmere-churchill/381377/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Cashmere','Churchill','Parejo','Churchill','Ecuador','Connecticut','Nicaragua',ARRAY['Nicaragua']::text[],2,'Nicaragua','Esteban Carreras',7,50,ARRAY['Cream','Cedar','Toasted Nuts','Coffee','White Pepper']::text[],'En mild til mellomsterk nicaraguansk sigar med Connecticut-dekkblad, med toner av fløte, seder, ristede nøtter og kaffe.',true,'retailer','https://halfwheel.com/esteban-carreras-cashmere-churchill/381377/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Cashmere','Sixty','Parejo','Sixty','Ecuador','Connecticut','Nicaragua',ARRAY['Nicaragua']::text[],2,'Nicaragua','Esteban Carreras',6,60,ARRAY['Cream','Cedar','Toasted Nuts','Coffee','White Pepper']::text[],'En mild til mellomsterk nicaraguansk sigar med Connecticut-dekkblad, med toner av fløte, seder, ristede nøtter og kaffe.',true,'retailer','https://halfwheel.com/esteban-carreras-cashmere-churchill/381377/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Chupacabra','Chupitas','Parejo','Chupitas','Nicaragua','Habano Oscuro','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',4,42,ARRAY['Espresso','White Pepper','Leather','Cedar','Cocoa']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Habano Oscuro-dekkblad, med toner av espresso, hvit pepper, lær og seder.',true,'retailer','https://blindmanspuff.com/blind-cigar-review-esteban-carreras-chupacabra/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Chupacabra','Toro','Parejo','Toro','Nicaragua','Habano Oscuro','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',6,50,ARRAY['Espresso','White Pepper','Leather','Cedar','Cocoa']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Habano Oscuro-dekkblad, med toner av espresso, hvit pepper, lær og seder.',true,'retailer','https://blindmanspuff.com/blind-cigar-review-esteban-carreras-chupacabra/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Chupacabra','Robusto','Parejo','Robusto','Nicaragua','Habano Oscuro','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',5,54,ARRAY['Espresso','White Pepper','Leather','Cedar','Cocoa']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Habano Oscuro-dekkblad, med toner av espresso, hvit pepper, lær og seder.',true,'retailer','https://blindmanspuff.com/blind-cigar-review-esteban-carreras-chupacabra/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Chupacabra','Gordito','Parejo','Gordito','Nicaragua','Habano Oscuro','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',5,56,ARRAY['Espresso','White Pepper','Leather','Cedar','Cocoa']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Habano Oscuro-dekkblad, med toner av espresso, hvit pepper, lær og seder.',true,'retailer','https://blindmanspuff.com/blind-cigar-review-esteban-carreras-chupacabra/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Chupacabra','Sixty','Parejo','Sixty','Nicaragua','Habano Oscuro','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',6,60,ARRAY['Espresso','White Pepper','Leather','Cedar','Cocoa']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Habano Oscuro-dekkblad, med toner av espresso, hvit pepper, lær og seder.',true,'retailer','https://blindmanspuff.com/blind-cigar-review-esteban-carreras-chupacabra/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Chupacabra Hellcat','Robusto Grande','Parejo','Robusto Grande','Mexico','San Andrés','Nicaragua',ARRAY['Nicaragua']::text[],3,'Nicaragua','Esteban Carreras',5.5,54,ARRAY['Cocoa','Coffee','Cedar','Black Pepper','Earth']::text[],'En mellomsterk nicaraguansk sigar med San Andrés-dekkblad, med toner av kakao, kaffe, seder og svart pepper.',true,'retailer','https://halfwheel.com/esteban-carreras-chupacabra-hellcat-toro-grande/130336/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Chupacabra Hellcat','Toro Grande','Parejo','Toro Grande','Mexico','San Andrés','Nicaragua',ARRAY['Nicaragua']::text[],3,'Nicaragua','Esteban Carreras',6.5,54,ARRAY['Cocoa','Coffee','Cedar','Black Pepper','Earth']::text[],'En mellomsterk nicaraguansk sigar med San Andrés-dekkblad, med toner av kakao, kaffe, seder og svart pepper.',true,'retailer','https://halfwheel.com/esteban-carreras-chupacabra-hellcat-toro-grande/130336/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Chupacabra Hellcat','Sesenta','Parejo','Sesenta','Mexico','San Andrés','Nicaragua',ARRAY['Nicaragua']::text[],3,'Nicaragua','Esteban Carreras',6,58,ARRAY['Cocoa','Coffee','Cedar','Black Pepper','Earth']::text[],'En mellomsterk nicaraguansk sigar med San Andrés-dekkblad, med toner av kakao, kaffe, seder og svart pepper.',true,'retailer','https://halfwheel.com/esteban-carreras-chupacabra-hellcat-toro-grande/130336/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Chupacabra Maduro','Chupitas','Parejo','Chupitas','Mexico','San Andrés Maduro','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',4,42,ARRAY['Dark Chocolate','Espresso','Black Pepper','Earth','Leather']::text[],'En mellomsterk til fyldig nicaraguansk sigar med San Andrés Maduro-dekkblad, med toner av mørk sjokolade, espresso, svart pepper og jord.',true,'retailer','https://www.neptunecigar.com/esteban-carreras-cigar',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Chupacabra Maduro','Toro','Parejo','Toro','Mexico','San Andrés Maduro','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',6,50,ARRAY['Dark Chocolate','Espresso','Black Pepper','Earth','Leather']::text[],'En mellomsterk til fyldig nicaraguansk sigar med San Andrés Maduro-dekkblad, med toner av mørk sjokolade, espresso, svart pepper og jord.',true,'retailer','https://www.neptunecigar.com/esteban-carreras-cigar',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Chupacabra Maduro','Robusto','Parejo','Robusto','Mexico','San Andrés Maduro','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',5,54,ARRAY['Dark Chocolate','Espresso','Black Pepper','Earth','Leather']::text[],'En mellomsterk til fyldig nicaraguansk sigar med San Andrés Maduro-dekkblad, med toner av mørk sjokolade, espresso, svart pepper og jord.',true,'retailer','https://www.neptunecigar.com/esteban-carreras-cigar',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Chupacabra Maduro','Gordito','Parejo','Gordito','Mexico','San Andrés Maduro','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',5,56,ARRAY['Dark Chocolate','Espresso','Black Pepper','Earth','Leather']::text[],'En mellomsterk til fyldig nicaraguansk sigar med San Andrés Maduro-dekkblad, med toner av mørk sjokolade, espresso, svart pepper og jord.',true,'retailer','https://www.neptunecigar.com/esteban-carreras-cigar',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Chupacabra Maduro','Sixty','Parejo','Sixty','Mexico','San Andrés Maduro','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',6,60,ARRAY['Dark Chocolate','Espresso','Black Pepper','Earth','Leather']::text[],'En mellomsterk til fyldig nicaraguansk sigar med San Andrés Maduro-dekkblad, med toner av mørk sjokolade, espresso, svart pepper og jord.',true,'retailer','https://www.neptunecigar.com/esteban-carreras-cigar',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Mr. Brownstone Habano','Böölit','Parejo','Böölit','Nicaragua','Habano','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',4.8,46,ARRAY['Espresso','Leather','Cedar','Black Pepper','Cocoa']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Habano-dekkblad, med toner av espresso, lær, seder og svart pepper.',true,'retailer','https://www.vitolafinecigars.com/product-category/premium-cigars/esteban-carreras/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Mr. Brownstone Habano','Corona Gorda','Parejo','Corona Gorda','Nicaragua','Habano','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',6,46,ARRAY['Espresso','Leather','Cedar','Black Pepper','Cocoa']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Habano-dekkblad, med toner av espresso, lær, seder og svart pepper.',true,'retailer','https://www.vitolafinecigars.com/product-category/premium-cigars/esteban-carreras/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Mr. Brownstone Habano','Chuchy','Parejo','Chuchy','Nicaragua','Habano','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',7,49,ARRAY['Espresso','Leather','Cedar','Black Pepper','Cocoa']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Habano-dekkblad, med toner av espresso, lær, seder og svart pepper.',true,'retailer','https://www.vitolafinecigars.com/product-category/premium-cigars/esteban-carreras/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Mr. Brownstone Habano','Toro Grande','Parejo','Toro Grande','Nicaragua','Habano','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',6,52,ARRAY['Espresso','Leather','Cedar','Black Pepper','Cocoa']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Habano-dekkblad, med toner av espresso, lær, seder og svart pepper.',true,'retailer','https://www.vitolafinecigars.com/product-category/premium-cigars/esteban-carreras/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Mr. Brownstone Habano','Sesenta','Parejo','Sesenta','Nicaragua','Habano','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',6,60,ARRAY['Espresso','Leather','Cedar','Black Pepper','Cocoa']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Habano-dekkblad, med toner av espresso, lær, seder og svart pepper.',true,'retailer','https://www.vitolafinecigars.com/product-category/premium-cigars/esteban-carreras/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Mr. Brownstone Maduro','Böölit','Parejo','Böölit','United States','Connecticut Broadleaf Maduro','Ecuador',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',4.8,46,ARRAY['Dark Chocolate','Espresso','Black Pepper','Leather','Cedar']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Connecticut Broadleaf Maduro-dekkblad, med toner av mørk sjokolade, espresso, svart pepper og lær.',true,'retailer','https://www.vitolafinecigars.com/product-category/premium-cigars/esteban-carreras/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Taken From the Devil''s Hand Corojo','Boolit','Parejo','Boolit','Nicaragua','Corojo','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',4.8,46,ARRAY['Pepper','Cedar','Leather','Earth','Espresso']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Corojo-dekkblad, med toner av pepper, seder, lær og jord.',true,'retailer','https://halfwheel.com/esteban-carreras-taken-from-the-devils-hand-corojo-maduro-sixty/431401/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Taken From the Devil''s Hand Corojo','Toro','Parejo','Toro','Nicaragua','Corojo','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',6,50,ARRAY['Pepper','Cedar','Leather','Earth','Espresso']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Corojo-dekkblad, med toner av pepper, seder, lær og jord.',true,'retailer','https://halfwheel.com/esteban-carreras-taken-from-the-devils-hand-corojo-maduro-sixty/431401/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Taken From the Devil''s Hand Corojo','Sixty','Parejo','Sixty','Nicaragua','Corojo','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',6,60,ARRAY['Pepper','Cedar','Leather','Earth','Espresso']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Corojo-dekkblad, med toner av pepper, seder, lær og jord.',true,'retailer','https://halfwheel.com/esteban-carreras-taken-from-the-devils-hand-corojo-maduro-sixty/431401/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Taken From the Devil''s Hand Corojo Maduro','Boolit','Parejo','Boolit','Ecuador','Corojo Maduro','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',4.8,46,ARRAY['Dark Chocolate','Black Pepper','Cedar','Leather','Espresso']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Corojo Maduro-dekkblad, med toner av mørk sjokolade, svart pepper, seder og lær.',true,'retailer','https://halfwheel.com/esteban-carreras-taken-from-the-devils-hand-corojo-maduro-sixty/431401/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Taken From the Devil''s Hand Corojo Maduro','Toro','Parejo','Toro','Ecuador','Corojo Maduro','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',6,50,ARRAY['Dark Chocolate','Black Pepper','Cedar','Leather','Espresso']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Corojo Maduro-dekkblad, med toner av mørk sjokolade, svart pepper, seder og lær.',true,'retailer','https://halfwheel.com/esteban-carreras-taken-from-the-devils-hand-corojo-maduro-sixty/431401/',now(),ARRAY['Esteban Carreras']::text[]),
  ('Esteban Carreras','Taken From the Devil''s Hand Corojo Maduro','Sixty','Parejo','Sixty','Ecuador','Corojo Maduro','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Esteban Carreras',6,60,ARRAY['Dark Chocolate','Black Pepper','Cedar','Leather','Espresso']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Corojo Maduro-dekkblad, med toner av mørk sjokolade, svart pepper, seder og lær.',true,'retailer','https://halfwheel.com/esteban-carreras-taken-from-the-devils-hand-corojo-maduro-sixty/431401/',now(),ARRAY['Esteban Carreras']::text[]);

INSERT INTO public.cigars
  (brand,series,vitola,shape,common_format,wrapper_country,wrapper_leaf,binder,filler,strength,country_origin,manufacturer,length_inches,ring_gauge,flavor_notes,description,is_public,source_tier,source_url,verified_at,aliases)
VALUES
  ('Freud Cigar Company','Agape','Robusto Extra','Parejo','Robusto Extra','Dominican Republic','Colorado Maduro','Dominican Republic',ARRAY['Dominican Republic']::text[],3,'Dominican Republic','Freud Cigar Company',5,54,ARRAY['Floral','Cream','Sweetness']::text[],'En mellomsterk dominikansk sigar med Colorado Maduro-dekkblad, med toner av blomster, fløte og sødme.',true,'retailer','https://halfwheel.com/freud-cigars-agape-limited-edition/416570/',now(),ARRAY['Freud Cigar Company']::text[]),
  ('Freud Cigar Company','AlterEgo','Lonsdale','Parejo','Lonsdale','Mexico','San Andres','Sumatra',ARRAY['Dominican Republic']::text[],3,'Dominican Republic','Freud Cigar Company',6.5,43,ARRAY['Earth','Cedar','Leather','Coffee','Cream']::text[],'En mellomsterk dominikansk sigar med San Andres-dekkblad, med toner av jord, seder, lær og kaffe.',true,'retailer','https://halfwheel.com/freud-alterego-toro/423382/',now(),ARRAY['Freud Cigar Company']::text[]),
  ('Freud Cigar Company','AlterEgo','Robusto','Parejo','Robusto','Mexico','San Andres','Sumatra',ARRAY['Dominican Republic']::text[],3,'Dominican Republic','Freud Cigar Company',5,50,ARRAY['Earth','Cedar','Leather','Coffee','Cream']::text[],'En mellomsterk dominikansk sigar med San Andres-dekkblad, med toner av jord, seder, lær og kaffe.',true,'retailer','https://halfwheel.com/freud-alterego-toro/423382/',now(),ARRAY['Freud Cigar Company']::text[]),
  ('Freud Cigar Company','AlterEgo','Toro','Parejo','Toro','Mexico','San Andres','Sumatra',ARRAY['Dominican Republic']::text[],3,'Dominican Republic','Freud Cigar Company',6,52,ARRAY['Earth','Cedar','Leather','Coffee','Cream']::text[],'En mellomsterk dominikansk sigar med San Andres-dekkblad, med toner av jord, seder, lær og kaffe.',true,'retailer','https://halfwheel.com/freud-alterego-toro/423382/',now(),ARRAY['Freud Cigar Company']::text[]),
  ('Freud Cigar Company','First Edition Elvis Panatella','Panatella','Parejo','Panatella','Dominican Republic','Corojo','Dominican Republic',ARRAY['Dominican Republic']::text[],3,'Dominican Republic','Freud Cigar Company',7,40,ARRAY['Oak','Espresso','Dark Chocolate','Leather','Baking Spice']::text[],'En mellomsterk dominikansk sigar med Corojo-dekkblad, med toner av eik, espresso, mørk sjokolade og lær.',true,'retailer','https://halfwheel.com/freud-releases-elvis-themed-cigar/461780/',now(),ARRAY['Freud Cigar Company']::text[]),
  ('Freud Cigar Company','Sigmund: Chapter One - The Disruptor','Double Corona','Parejo','Double Corona',NULL,NULL,NULL,ARRAY[]::text[],2,'Dominican Republic','Freud Cigar Company',7.5,50,ARRAY['Wood','Nuts','Cocoa']::text[],'En mild til mellomsterk dominikansk sigar, med toner av tre, nøtter og kakao.',true,'retailer','https://halfwheel.com/freud-limited-edition-sigmund-chapter-one-the-disruptor/428488/',now(),ARRAY['Freud Cigar Company']::text[]),
  ('Freud Cigar Company','SuperEgo','Lonsdale','Parejo','Lonsdale','Ecuador','Corojo','Sumatra',ARRAY['Nicaragua','Dominican Republic']::text[],3,'Dominican Republic','Freud Cigar Company',6.5,42,ARRAY['Earth','Tobacco','Chocolate','Grass','Pepper']::text[],'En mellomsterk dominikansk sigar med Corojo-dekkblad, med toner av jord, tobakk, sjokolade og gress.',true,'retailer','https://halfwheel.com/freud-superego-robusto-extra/413592/',now(),ARRAY['Freud Cigar Company']::text[]),
  ('Freud Cigar Company','SuperEgo','Belicoso','Figurado','Belicoso','Ecuador','Corojo','Sumatra',ARRAY['Nicaragua','Dominican Republic']::text[],3,'Dominican Republic','Freud Cigar Company',6,52,ARRAY['Earth','Tobacco','Chocolate','Grass','Pepper']::text[],'En mellomsterk dominikansk sigar med Corojo-dekkblad, med toner av jord, tobakk, sjokolade og gress.',true,'retailer','https://halfwheel.com/freud-superego-robusto-extra/413592/',now(),ARRAY['Freud Cigar Company']::text[]),
  ('Freud Cigar Company','SuperEgo','Toro','Parejo','Toro','Ecuador','Corojo','Sumatra',ARRAY['Nicaragua','Dominican Republic']::text[],3,'Dominican Republic','Freud Cigar Company',6,52,ARRAY['Earth','Tobacco','Chocolate','Grass','Pepper']::text[],'En mellomsterk dominikansk sigar med Corojo-dekkblad, med toner av jord, tobakk, sjokolade og gress.',true,'retailer','https://halfwheel.com/freud-superego-robusto-extra/413592/',now(),ARRAY['Freud Cigar Company']::text[]),
  ('Freud Cigar Company','SuperEgo','Robusto Extra','Parejo','Robusto Extra','Ecuador','Corojo','Sumatra',ARRAY['Nicaragua','Dominican Republic']::text[],3,'Dominican Republic','Freud Cigar Company',5,54,ARRAY['Earth','Tobacco','Chocolate','Grass','Pepper']::text[],'En mellomsterk dominikansk sigar med Corojo-dekkblad, med toner av jord, tobakk, sjokolade og gress.',true,'retailer','https://halfwheel.com/freud-superego-robusto-extra/413592/',now(),ARRAY['Freud Cigar Company']::text[]),
  ('Freud Cigar Company','SuperEgo','Magnum','Parejo','Magnum','Ecuador','Corojo','Sumatra',ARRAY['Nicaragua','Dominican Republic']::text[],3,'Dominican Republic','Freud Cigar Company',6,60,ARRAY['Earth','Tobacco','Chocolate','Grass','Pepper']::text[],'En mellomsterk dominikansk sigar med Corojo-dekkblad, med toner av jord, tobakk, sjokolade og gress.',true,'retailer','https://halfwheel.com/freud-superego-robusto-extra/413592/',now(),ARRAY['Freud Cigar Company']::text[]);

INSERT INTO public.cigars
  (brand,series,vitola,shape,common_format,wrapper_country,wrapper_leaf,binder,filler,strength,country_origin,manufacturer,length_inches,ring_gauge,flavor_notes,description,is_public,source_tier,source_url,verified_at,aliases)
VALUES
  ('Gellis Family Cigars','Absolutos','Lonsdale','Parejo','Lonsdale','Nicaragua','Sungrown','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Gellis Family Cigars',6.5,42,ARRAY['White Pepper','Caramel','Leather','Cedar','Spice']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Sungrown-dekkblad, med toner av hvit pepper, karamell, lær og seder.',true,'retailer','https://shop.gelliscigars.com/products/gellis-family-absolutos',now(),ARRAY['Gellis Family Cigars']::text[]),
  ('Gellis Family Cigars','Absolutos','Corona Gorda','Parejo','Corona Gorda','Nicaragua','Sungrown','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Gellis Family Cigars',5.5,48,ARRAY['White Pepper','Caramel','Leather','Cedar','Spice']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Sungrown-dekkblad, med toner av hvit pepper, karamell, lær og seder.',true,'retailer','https://shop.gelliscigars.com/products/gellis-family-absolutos',now(),ARRAY['Gellis Family Cigars']::text[]),
  ('Gellis Family Cigars','Absolutos','Petit Robusto','Parejo','Petit Robusto','Nicaragua','Sungrown','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Gellis Family Cigars',4,50,ARRAY['White Pepper','Caramel','Leather','Cedar','Spice']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Sungrown-dekkblad, med toner av hvit pepper, karamell, lær og seder.',true,'retailer','https://shop.gelliscigars.com/products/gellis-family-absolutos',now(),ARRAY['Gellis Family Cigars']::text[]),
  ('Gellis Family Cigars','Absolutos','Toro','Parejo','Toro','Nicaragua','Sungrown','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Gellis Family Cigars',6,52,ARRAY['White Pepper','Caramel','Leather','Cedar','Spice']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Sungrown-dekkblad, med toner av hvit pepper, karamell, lær og seder.',true,'retailer','https://shop.gelliscigars.com/products/gellis-family-absolutos',now(),ARRAY['Gellis Family Cigars']::text[]),
  ('Gellis Family Cigars','Corona Extra','Corona Extra','Parejo','Corona Extra','Dominican Republic','Corojo','Nicaragua',ARRAY['Nicaragua','Dominican Republic']::text[],4,'Dominican Republic','Gellis Family Cigars',5.6,46,ARRAY['Leather','Cream','Floral','Caramel','Chocolate']::text[],'En mellomsterk til fyldig dominikansk sigar med Corojo-dekkblad, med toner av lær, fløte, blomster og karamell.',true,'retailer','https://dropcigarclub.com/products/gellis-family-domain',now(),ARRAY['Gellis Family Cigars']::text[]),
  ('Gellis Family Cigars','Heritage No. 50','Robusto','Parejo','Robusto','Mexico','San Andres Maduro','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Gellis Family Cigars',5,50,ARRAY['Chocolate','Black Pepper','Oak','Leather','Toasted Nuts']::text[],'En mellomsterk til fyldig nicaraguansk sigar med San Andres Maduro-dekkblad, med toner av sjokolade, svart pepper, eik og lær.',true,'retailer','https://halfwheel.com/gellis-family-cigars-heritage-no-50-arrives-at-stores/475458/',now(),ARRAY['Gellis Family Cigars']::text[]),
  ('Gellis Family Cigars','Marevas','Marevas','Parejo','Marevas','Ecuador','Habano 2000 Rosada','Nicaragua',ARRAY['Dominican Republic','Nicaragua']::text[],3,'Dominican Republic','Gellis Family Cigars',5.1,43,ARRAY['Leather','Cedar','Caramel','Cream','Dried Fruit']::text[],'En mellomsterk dominikansk sigar med Habano 2000 Rosada-dekkblad, med toner av lær, seder, karamell og fløte.',true,'retailer','https://halfwheel.com/gellis-family-cigars-launches-with-marevas-saunter/437412/',now(),ARRAY['Gellis Family Cigars']::text[]),
  ('Gellis Family Cigars','Piece Unique','Toro','Parejo','Toro','Ecuador','Connecticut Shade','Nicaragua',ARRAY['Dominican Republic','Nicaragua']::text[],3,'Dominican Republic','Gellis Family Cigars',6,52,ARRAY['Cream','Dried Fruit','Vanilla']::text[],'En mellomsterk dominikansk sigar med Connecticut Shade-dekkblad, med toner av fløte, tørket frukt og vanilje.',true,'retailer','https://halfwheel.com/gellis-family-cigars-announces-piece-unique-2026/466555/',now(),ARRAY['Gellis Family Cigars']::text[]),
  ('Gellis Family Cigars','Saunter','Saunter','Parejo','Saunter','Ecuador','Connecticut Desflorada','Ecuador',ARRAY['Nicaragua','Dominican Republic']::text[],3,'Dominican Republic','Gellis Family Cigars',5.3,48,ARRAY['Cream','Honey','White Pepper','Caramel']::text[],'En mellomsterk dominikansk sigar med Connecticut Desflorada-dekkblad, med toner av fløte, honning, hvit pepper og karamell.',true,'retailer','https://halfwheel.com/gellis-family-cigars-saunter/447327/',now(),ARRAY['Gellis Family Cigars']::text[]);

INSERT INTO public.cigars
  (brand,series,vitola,shape,common_format,wrapper_country,wrapper_leaf,binder,filler,strength,country_origin,manufacturer,length_inches,ring_gauge,flavor_notes,description,is_public,source_tier,source_url,verified_at,aliases)
VALUES
  ('Ilegal','Ilegal Connecticut','Toro','Parejo','Toro','Ecuador','Connecticut',NULL,ARRAY[]::text[],2,'Nicaragua','HR Cigars',6,50,ARRAY['Cream','Cedar','Nuts','Hay','Pepper']::text[],'En mild til mellomsterk nicaraguansk sigar med Connecticut-dekkblad, med toner av fløte, seder, nøtter og høy.',true,'retailer',NULL,now(),ARRAY['Ilegal']::text[]),
  ('Ilegal','Ilegal Connecticut','Robusto','Parejo','Robusto','Ecuador','Connecticut',NULL,ARRAY[]::text[],2,'Nicaragua','HR Cigars',5.5,54,ARRAY['Cream','Cedar','Nuts','Hay','Pepper']::text[],'En mild til mellomsterk nicaraguansk sigar med Connecticut-dekkblad, med toner av fløte, seder, nøtter og høy.',true,'retailer',NULL,now(),ARRAY['Ilegal']::text[]),
  ('Ilegal','Ilegal Connecticut','Gordo','Parejo','Gordo','Ecuador','Connecticut',NULL,ARRAY[]::text[],2,'Nicaragua','HR Cigars',6,60,ARRAY['Cream','Cedar','Nuts','Hay','Pepper']::text[],'En mild til mellomsterk nicaraguansk sigar med Connecticut-dekkblad, med toner av fløte, seder, nøtter og høy.',true,'retailer',NULL,now(),ARRAY['Ilegal']::text[]),
  ('Ilegal','Ilegal Habano','Toro','Parejo','Toro','Ecuador','Habano',NULL,ARRAY[]::text[],3,'Nicaragua','HR Cigars',6,50,ARRAY['Pepper','Cream','Almonds','Citrus','Baking Spice']::text[],'En mellomsterk nicaraguansk sigar med Habano-dekkblad, med toner av pepper, fløte, mandler og sitrus.',true,'retailer',NULL,now(),ARRAY['Ilegal']::text[]),
  ('Ilegal','Ilegal Habano','Robusto','Parejo','Robusto','Ecuador','Habano',NULL,ARRAY[]::text[],3,'Nicaragua','HR Cigars',5.5,54,ARRAY['Pepper','Cream','Almonds','Citrus','Baking Spice']::text[],'En mellomsterk nicaraguansk sigar med Habano-dekkblad, med toner av pepper, fløte, mandler og sitrus.',true,'retailer',NULL,now(),ARRAY['Ilegal']::text[]),
  ('Ilegal','Ilegal Habano','Gordo','Parejo','Gordo','Ecuador','Habano',NULL,ARRAY[]::text[],3,'Nicaragua','HR Cigars',6,60,ARRAY['Pepper','Cream','Almonds','Citrus','Baking Spice']::text[],'En mellomsterk nicaraguansk sigar med Habano-dekkblad, med toner av pepper, fløte, mandler og sitrus.',true,'retailer',NULL,now(),ARRAY['Ilegal']::text[]),
  ('Ilegal','Ilegal San Andres','Toro','Parejo','Toro','Mexico','San Andres',NULL,ARRAY[]::text[],4,'Nicaragua','HR Cigars',6,50,ARRAY['Dark Chocolate','Coffee','Black Pepper','Earth','Sweetness']::text[],'En mellomsterk til fyldig nicaraguansk sigar med San Andres-dekkblad, med toner av mørk sjokolade, kaffe, svart pepper og jord.',true,'retailer',NULL,now(),ARRAY['Ilegal']::text[]),
  ('Ilegal','Ilegal San Andres','Robusto','Parejo','Robusto','Mexico','San Andres',NULL,ARRAY[]::text[],4,'Nicaragua','HR Cigars',5.5,54,ARRAY['Dark Chocolate','Coffee','Black Pepper','Earth','Sweetness']::text[],'En mellomsterk til fyldig nicaraguansk sigar med San Andres-dekkblad, med toner av mørk sjokolade, kaffe, svart pepper og jord.',true,'retailer',NULL,now(),ARRAY['Ilegal']::text[]),
  ('Ilegal','Ilegal San Andres','Gordo','Parejo','Gordo','Mexico','San Andres',NULL,ARRAY[]::text[],4,'Nicaragua','HR Cigars',6,60,ARRAY['Dark Chocolate','Coffee','Black Pepper','Earth','Sweetness']::text[],'En mellomsterk til fyldig nicaraguansk sigar med San Andres-dekkblad, med toner av mørk sjokolade, kaffe, svart pepper og jord.',true,'retailer',NULL,now(),ARRAY['Ilegal']::text[]);

INSERT INTO public.cigars
  (brand,series,vitola,shape,common_format,wrapper_country,wrapper_leaf,binder,filler,strength,country_origin,manufacturer,length_inches,ring_gauge,flavor_notes,description,is_public,source_tier,source_url,verified_at,aliases)
VALUES
  ('Latitude Zero','Latitude Zero (Original)','Toro','Parejo','Toro','Ecuador','Habano','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Forged Cigar Company',6,52,ARRAY['Nuts','Oak','Black Pepper','Cream','Caramel']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Habano-dekkblad, med toner av nøtter, eik, svart pepper og fløte.',true,'retailer',NULL,now(),ARRAY['Latitude Zero']::text[]),
  ('Latitude Zero','Latitude Zero (Original)','Robusto','Parejo','Robusto','Ecuador','Habano','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Forged Cigar Company',5,54,ARRAY['Nuts','Oak','Black Pepper','Cream','Caramel']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Habano-dekkblad, med toner av nøtter, eik, svart pepper og fløte.',true,'retailer',NULL,now(),ARRAY['Latitude Zero']::text[]),
  ('Latitude Zero','Latitude Zero (Original)','Double Corona','Parejo','Double Corona','Ecuador','Habano','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Forged Cigar Company',7,54,ARRAY['Nuts','Oak','Black Pepper','Cream','Caramel']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Habano-dekkblad, med toner av nøtter, eik, svart pepper og fløte.',true,'retailer',NULL,now(),ARRAY['Latitude Zero']::text[]),
  ('Latitude Zero','Latitude Zero (Original)','Gordo','Parejo','Gordo','Ecuador','Habano','Nicaragua',ARRAY['Nicaragua']::text[],4,'Nicaragua','Forged Cigar Company',6,60,ARRAY['Nuts','Oak','Black Pepper','Cream','Caramel']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Habano-dekkblad, med toner av nøtter, eik, svart pepper og fløte.',true,'retailer',NULL,now(),ARRAY['Latitude Zero']::text[]),
  ('Latitude Zero','Latitude Zero El Valle','Toro','Parejo','Toro','USA','Connecticut Broadleaf','Nicaragua',ARRAY['Nicaragua','Dominican Republic']::text[],4,'Nicaragua','Forged Cigar Company',6,52,ARRAY['Dark Chocolate','Coffee','Pepper','Earth']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Connecticut Broadleaf-dekkblad, med toner av mørk sjokolade, kaffe, pepper og jord.',true,'retailer',NULL,now(),ARRAY['Latitude Zero']::text[]),
  ('Latitude Zero','Latitude Zero El Valle','Robusto','Parejo','Robusto','USA','Connecticut Broadleaf','Nicaragua',ARRAY['Nicaragua','Dominican Republic']::text[],4,'Nicaragua','Forged Cigar Company',5,54,ARRAY['Dark Chocolate','Coffee','Pepper','Earth']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Connecticut Broadleaf-dekkblad, med toner av mørk sjokolade, kaffe, pepper og jord.',true,'retailer',NULL,now(),ARRAY['Latitude Zero']::text[]),
  ('Latitude Zero','Latitude Zero El Valle','Gordo','Parejo','Gordo','USA','Connecticut Broadleaf','Nicaragua',ARRAY['Nicaragua','Dominican Republic']::text[],4,'Nicaragua','Forged Cigar Company',6,60,ARRAY['Dark Chocolate','Coffee','Pepper','Earth']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Connecticut Broadleaf-dekkblad, med toner av mørk sjokolade, kaffe, pepper og jord.',true,'retailer',NULL,now(),ARRAY['Latitude Zero']::text[]),
  ('Latitude Zero','Latitude Zero Los Rios','Churchill','Parejo','Churchill','Ecuador','Connecticut','Nicaragua',ARRAY['Nicaragua','Dominican Republic']::text[],3,'Nicaragua','Forged Cigar Company',7,50,ARRAY['Cream','Hay','Herbal','Spice']::text[],'En mellomsterk nicaraguansk sigar med Connecticut-dekkblad, med toner av fløte, høy, urter og krydder.',true,'retailer',NULL,now(),ARRAY['Latitude Zero']::text[]),
  ('Latitude Zero','Latitude Zero Los Rios','Toro','Parejo','Toro','Ecuador','Connecticut','Nicaragua',ARRAY['Nicaragua','Dominican Republic']::text[],3,'Nicaragua','Forged Cigar Company',6,52,ARRAY['Cream','Hay','Herbal','Spice']::text[],'En mellomsterk nicaraguansk sigar med Connecticut-dekkblad, med toner av fløte, høy, urter og krydder.',true,'retailer',NULL,now(),ARRAY['Latitude Zero']::text[]),
  ('Latitude Zero','Latitude Zero Los Rios','Robusto','Parejo','Robusto','Ecuador','Connecticut','Nicaragua',ARRAY['Nicaragua','Dominican Republic']::text[],3,'Nicaragua','Forged Cigar Company',5,54,ARRAY['Cream','Hay','Herbal','Spice']::text[],'En mellomsterk nicaraguansk sigar med Connecticut-dekkblad, med toner av fløte, høy, urter og krydder.',true,'retailer',NULL,now(),ARRAY['Latitude Zero']::text[]),
  ('Latitude Zero','Latitude Zero Los Rios','Gordo','Parejo','Gordo','Ecuador','Connecticut','Nicaragua',ARRAY['Nicaragua','Dominican Republic']::text[],3,'Nicaragua','Forged Cigar Company',6,60,ARRAY['Cream','Hay','Herbal','Spice']::text[],'En mellomsterk nicaraguansk sigar med Connecticut-dekkblad, med toner av fløte, høy, urter og krydder.',true,'retailer',NULL,now(),ARRAY['Latitude Zero']::text[]),
  ('Latitude Zero','Latitude Zero Signature','Toro','Parejo','Toro','Ecuador','Sumatra','Nicaragua',ARRAY['Nicaragua','Dominican Republic','USA (Connecticut Broadleaf)']::text[],4,'Nicaragua','Forged Cigar Company',6,52,ARRAY['Pepper','Leather','Cream','Spice']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Sumatra-dekkblad, med toner av pepper, lær, fløte og krydder.',true,'retailer',NULL,now(),ARRAY['Latitude Zero']::text[]),
  ('Latitude Zero','Latitude Zero Signature','Robusto','Parejo','Robusto','Ecuador','Sumatra','Nicaragua',ARRAY['Nicaragua','Dominican Republic','USA (Connecticut Broadleaf)']::text[],4,'Nicaragua','Forged Cigar Company',5,54,ARRAY['Pepper','Leather','Cream','Spice']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Sumatra-dekkblad, med toner av pepper, lær, fløte og krydder.',true,'retailer',NULL,now(),ARRAY['Latitude Zero']::text[]),
  ('Latitude Zero','Latitude Zero Signature','Gordo','Parejo','Gordo','Ecuador','Sumatra','Nicaragua',ARRAY['Nicaragua','Dominican Republic','USA (Connecticut Broadleaf)']::text[],4,'Nicaragua','Forged Cigar Company',6,60,ARRAY['Pepper','Leather','Cream','Spice']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Sumatra-dekkblad, med toner av pepper, lær, fløte og krydder.',true,'retailer',NULL,now(),ARRAY['Latitude Zero']::text[]);

INSERT INTO public.cigars
  (brand,series,vitola,shape,common_format,wrapper_country,wrapper_leaf,binder,filler,strength,country_origin,manufacturer,length_inches,ring_gauge,flavor_notes,description,is_public,source_tier,source_url,verified_at,aliases)
VALUES
  ('Los Statos','Los Statos Deluxe','Churchill','Parejo','Churchill','Ecuador','Sumatra','Nicaragua',ARRAY['Nicaragua','Dominican Republic']::text[],3,'Honduras','Altadis USA',7,49,ARRAY['Black Pepper','Coffee','Earth','Dark Chocolate','Caramel']::text[],'En mellomsterk honduransk sigar med Sumatra-dekkblad, med toner av svart pepper, kaffe, jord og mørk sjokolade.',true,'retailer','https://www.cigaraficionado.com/article/matt-booth-and-stg-revamp-los-statos-deluxe',now(),ARRAY['Los Statos']::text[]),
  ('Los Statos','Los Statos Deluxe','Robusto','Parejo','Robusto','Ecuador','Sumatra','Nicaragua',ARRAY['Nicaragua','Dominican Republic']::text[],3,'Honduras','Altadis USA',5,50,ARRAY['Black Pepper','Coffee','Earth','Dark Chocolate','Caramel']::text[],'En mellomsterk honduransk sigar med Sumatra-dekkblad, med toner av svart pepper, kaffe, jord og mørk sjokolade.',true,'retailer','https://www.cigaraficionado.com/article/matt-booth-and-stg-revamp-los-statos-deluxe',now(),ARRAY['Los Statos']::text[]),
  ('Los Statos','Los Statos Deluxe','Toro','Parejo','Toro','Ecuador','Sumatra','Nicaragua',ARRAY['Nicaragua','Dominican Republic']::text[],3,'Honduras','Altadis USA',6,52,ARRAY['Black Pepper','Coffee','Earth','Dark Chocolate','Caramel']::text[],'En mellomsterk honduransk sigar med Sumatra-dekkblad, med toner av svart pepper, kaffe, jord og mørk sjokolade.',true,'retailer','https://www.cigaraficionado.com/article/matt-booth-and-stg-revamp-los-statos-deluxe',now(),ARRAY['Los Statos']::text[]),
  ('Los Statos','Los Statos Deluxe','Gigante','Parejo','Gigante','Ecuador','Sumatra','Nicaragua',ARRAY['Nicaragua','Dominican Republic']::text[],3,'Honduras','Altadis USA',6,60,ARRAY['Black Pepper','Coffee','Earth','Dark Chocolate','Caramel']::text[],'En mellomsterk honduransk sigar med Sumatra-dekkblad, med toner av svart pepper, kaffe, jord og mørk sjokolade.',true,'retailer','https://www.cigaraficionado.com/article/matt-booth-and-stg-revamp-los-statos-deluxe',now(),ARRAY['Los Statos']::text[]),
  ('Los Statos','Los Statos Deluxe Connecticut','Churchill','Parejo','Churchill','Ecuador','Connecticut','Nicaragua (Habano)',ARRAY['Nicaragua','United States']::text[],2,'Nicaragua','Altadis USA',7,48,ARRAY['Cream','White Pepper','Toasted Nuts','Butter','Sweetness']::text[],'En mild til mellomsterk nicaraguansk sigar med Connecticut-dekkblad, med toner av fløte, hvit pepper, ristede nøtter og smør.',true,'retailer','https://halfwheel.com/los-statos-deluxe-connecticut-robusto/443875/',now(),ARRAY['Los Statos']::text[]),
  ('Los Statos','Los Statos Deluxe Connecticut','Robusto','Parejo','Robusto','Ecuador','Connecticut','Nicaragua (Habano)',ARRAY['Nicaragua','United States']::text[],2,'Nicaragua','Altadis USA',5,50,ARRAY['Cream','White Pepper','Toasted Nuts','Butter','Sweetness']::text[],'En mild til mellomsterk nicaraguansk sigar med Connecticut-dekkblad, med toner av fløte, hvit pepper, ristede nøtter og smør.',true,'retailer','https://halfwheel.com/los-statos-deluxe-connecticut-robusto/443875/',now(),ARRAY['Los Statos']::text[]),
  ('Los Statos','Los Statos Deluxe Connecticut','Toro','Parejo','Toro','Ecuador','Connecticut','Nicaragua (Habano)',ARRAY['Nicaragua','United States']::text[],2,'Nicaragua','Altadis USA',6,52,ARRAY['Cream','White Pepper','Toasted Nuts','Butter','Sweetness']::text[],'En mild til mellomsterk nicaraguansk sigar med Connecticut-dekkblad, med toner av fløte, hvit pepper, ristede nøtter og smør.',true,'retailer','https://halfwheel.com/los-statos-deluxe-connecticut-robusto/443875/',now(),ARRAY['Los Statos']::text[]),
  ('Los Statos','Los Statos Deluxe Connecticut','Gigante','Parejo','Gigante','Ecuador','Connecticut','Nicaragua (Habano)',ARRAY['Nicaragua','United States']::text[],2,'Nicaragua','Altadis USA',6,60,ARRAY['Cream','White Pepper','Toasted Nuts','Butter','Sweetness']::text[],'En mild til mellomsterk nicaraguansk sigar med Connecticut-dekkblad, med toner av fløte, hvit pepper, ristede nøtter og smør.',true,'retailer','https://halfwheel.com/los-statos-deluxe-connecticut-robusto/443875/',now(),ARRAY['Los Statos']::text[]),
  ('Los Statos','Los Statos Deluxe Maduro','Churchill','Parejo','Churchill','United States','Connecticut Broadleaf','Nicaragua (Estelí)',ARRAY['Honduras','Dominican Republic']::text[],3,'Honduras','Altadis USA',7,49,ARRAY['Mocha','Leather','Cedar','Espresso','Chocolate']::text[],'En mellomsterk honduransk sigar med Connecticut Broadleaf-dekkblad, med toner av mokka, lær, seder og espresso.',true,'retailer','https://cigar-coop.com/2024/07/los-statos-deluxe-maduro-robusto-cigar-review.html',now(),ARRAY['Los Statos']::text[]),
  ('Los Statos','Los Statos Deluxe Maduro','Robusto','Parejo','Robusto','United States','Connecticut Broadleaf','Nicaragua (Estelí)',ARRAY['Honduras','Dominican Republic']::text[],3,'Honduras','Altadis USA',5,50,ARRAY['Mocha','Leather','Cedar','Espresso','Chocolate']::text[],'En mellomsterk honduransk sigar med Connecticut Broadleaf-dekkblad, med toner av mokka, lær, seder og espresso.',true,'retailer','https://cigar-coop.com/2024/07/los-statos-deluxe-maduro-robusto-cigar-review.html',now(),ARRAY['Los Statos']::text[]),
  ('Los Statos','Los Statos Deluxe Maduro','Toro','Parejo','Toro','United States','Connecticut Broadleaf','Nicaragua (Estelí)',ARRAY['Honduras','Dominican Republic']::text[],3,'Honduras','Altadis USA',6,52,ARRAY['Mocha','Leather','Cedar','Espresso','Chocolate']::text[],'En mellomsterk honduransk sigar med Connecticut Broadleaf-dekkblad, med toner av mokka, lær, seder og espresso.',true,'retailer','https://cigar-coop.com/2024/07/los-statos-deluxe-maduro-robusto-cigar-review.html',now(),ARRAY['Los Statos']::text[]),
  ('Los Statos','Los Statos Deluxe Maduro','Gigante','Parejo','Gigante','United States','Connecticut Broadleaf','Nicaragua (Estelí)',ARRAY['Honduras','Dominican Republic']::text[],3,'Honduras','Altadis USA',6,60,ARRAY['Mocha','Leather','Cedar','Espresso','Chocolate']::text[],'En mellomsterk honduransk sigar med Connecticut Broadleaf-dekkblad, med toner av mokka, lær, seder og espresso.',true,'retailer','https://cigar-coop.com/2024/07/los-statos-deluxe-maduro-robusto-cigar-review.html',now(),ARRAY['Los Statos']::text[]);

INSERT INTO public.cigars
  (brand,series,vitola,shape,common_format,wrapper_country,wrapper_leaf,binder,filler,strength,country_origin,manufacturer,length_inches,ring_gauge,flavor_notes,description,is_public,source_tier,source_url,verified_at,aliases)
VALUES
  ('Titan de Bronze','Gold','Corona','Parejo','Corona','Ecuador','Connecticut','Ecuador',ARRAY['Nicaragua','Dominican Republic']::text[],2,'United States','El Titan de Bronze',5.8,48,ARRAY['Cream','Cedar','Toasted Nuts','Hay','Sweetness']::text[],'En mild til mellomsterk amerikansk sigar med Connecticut-dekkblad, med toner av fløte, seder, ristede nøtter og høy.',true,'retailer','https://eltitancigars.com/products/titan-de-bronze-gold',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Gold','Robusto','Parejo','Robusto','Ecuador','Connecticut','Ecuador',ARRAY['Nicaragua','Dominican Republic']::text[],2,'United States','El Titan de Bronze',5,50,ARRAY['Cream','Cedar','Toasted Nuts','Hay','Sweetness']::text[],'En mild til mellomsterk amerikansk sigar med Connecticut-dekkblad, med toner av fløte, seder, ristede nøtter og høy.',true,'retailer','https://eltitancigars.com/products/titan-de-bronze-gold',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Gold','Churchill','Parejo','Churchill','Ecuador','Connecticut','Ecuador',ARRAY['Nicaragua','Dominican Republic']::text[],2,'United States','El Titan de Bronze',7.5,50,ARRAY['Cream','Cedar','Toasted Nuts','Hay','Sweetness']::text[],'En mild til mellomsterk amerikansk sigar med Connecticut-dekkblad, med toner av fløte, seder, ristede nøtter og høy.',true,'retailer','https://eltitancigars.com/products/titan-de-bronze-gold',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Gold','Toro','Parejo','Toro','Ecuador','Connecticut','Ecuador',ARRAY['Nicaragua','Dominican Republic']::text[],2,'United States','El Titan de Bronze',6,52,ARRAY['Cream','Cedar','Toasted Nuts','Hay','Sweetness']::text[],'En mild til mellomsterk amerikansk sigar med Connecticut-dekkblad, med toner av fløte, seder, ristede nøtter og høy.',true,'retailer','https://eltitancigars.com/products/titan-de-bronze-gold',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Gold','Torpedo','Figurado','Torpedo','Ecuador','Connecticut','Ecuador',ARRAY['Nicaragua','Dominican Republic']::text[],2,'United States','El Titan de Bronze',6,52,ARRAY['Cream','Cedar','Toasted Nuts','Hay','Sweetness']::text[],'En mild til mellomsterk amerikansk sigar med Connecticut-dekkblad, med toner av fløte, seder, ristede nøtter og høy.',true,'retailer','https://eltitancigars.com/products/titan-de-bronze-gold',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Gold','Belicoso','Figurado','Belicoso','Ecuador','Connecticut','Ecuador',ARRAY['Nicaragua','Dominican Republic']::text[],2,'United States','El Titan de Bronze',4.5,54,ARRAY['Cream','Cedar','Toasted Nuts','Hay','Sweetness']::text[],'En mild til mellomsterk amerikansk sigar med Connecticut-dekkblad, med toner av fløte, seder, ristede nøtter og høy.',true,'retailer','https://eltitancigars.com/products/titan-de-bronze-gold',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Grande Reserve Maduro','Corona','Parejo','Corona','Brazil','Arapiraca','Ecuador',ARRAY['Dominican Republic','Nicaragua']::text[],5,'United States','El Titan de Bronze',5.5,48,ARRAY['Dark Chocolate','Molasses','Espresso','Earth','Black Pepper']::text[],'En fyldig og kraftig amerikansk sigar med Arapiraca-dekkblad, med toner av mørk sjokolade, melasse, espresso og jord.',true,'retailer','https://eltitancigars.com/products/el-titan-de-bronze-grande-reserve-maduro-cigar',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Grande Reserve Maduro','Robusto','Parejo','Robusto','Brazil','Arapiraca','Ecuador',ARRAY['Dominican Republic','Nicaragua']::text[],5,'United States','El Titan de Bronze',5,50,ARRAY['Dark Chocolate','Molasses','Espresso','Earth','Black Pepper']::text[],'En fyldig og kraftig amerikansk sigar med Arapiraca-dekkblad, med toner av mørk sjokolade, melasse, espresso og jord.',true,'retailer','https://eltitancigars.com/products/el-titan-de-bronze-grande-reserve-maduro-cigar',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Grande Reserve Maduro','Churchill','Parejo','Churchill','Brazil','Arapiraca','Ecuador',ARRAY['Dominican Republic','Nicaragua']::text[],5,'United States','El Titan de Bronze',7,50,ARRAY['Dark Chocolate','Molasses','Espresso','Earth','Black Pepper']::text[],'En fyldig og kraftig amerikansk sigar med Arapiraca-dekkblad, med toner av mørk sjokolade, melasse, espresso og jord.',true,'retailer','https://eltitancigars.com/products/el-titan-de-bronze-grande-reserve-maduro-cigar',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Grande Reserve Maduro','Toro','Parejo','Toro','Brazil','Arapiraca','Ecuador',ARRAY['Dominican Republic','Nicaragua']::text[],5,'United States','El Titan de Bronze',6,52,ARRAY['Dark Chocolate','Molasses','Espresso','Earth','Black Pepper']::text[],'En fyldig og kraftig amerikansk sigar med Arapiraca-dekkblad, med toner av mørk sjokolade, melasse, espresso og jord.',true,'retailer','https://eltitancigars.com/products/el-titan-de-bronze-grande-reserve-maduro-cigar',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Grande Reserve Maduro','Belicoso','Figurado','Belicoso','Brazil','Arapiraca','Ecuador',ARRAY['Dominican Republic','Nicaragua']::text[],5,'United States','El Titan de Bronze',4.5,54,ARRAY['Dark Chocolate','Molasses','Espresso','Earth','Black Pepper']::text[],'En fyldig og kraftig amerikansk sigar med Arapiraca-dekkblad, med toner av mørk sjokolade, melasse, espresso og jord.',true,'retailer','https://eltitancigars.com/products/el-titan-de-bronze-grande-reserve-maduro-cigar',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Grande Reserve Maduro','Torpedo','Figurado','Torpedo','Brazil','Arapiraca','Ecuador',ARRAY['Dominican Republic','Nicaragua']::text[],5,'United States','El Titan de Bronze',6,54,ARRAY['Dark Chocolate','Molasses','Espresso','Earth','Black Pepper']::text[],'En fyldig og kraftig amerikansk sigar med Arapiraca-dekkblad, med toner av mørk sjokolade, melasse, espresso og jord.',true,'retailer','https://eltitancigars.com/products/el-titan-de-bronze-grande-reserve-maduro-cigar',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','My Way – Dark Habano','Lancero','Parejo','Lancero','Ecuador','Habano Oscuro','Nicaragua',ARRAY['Nicaragua']::text[],3,'United States','El Titan de Bronze',7,38,ARRAY['Earth','Espresso','Black Pepper','Cocoa','Oak']::text[],'En mellomsterk amerikansk sigar med Habano Oscuro-dekkblad, med toner av jord, espresso, svart pepper og kakao.',true,'retailer','https://eltitancigars.com/products/titan-de-bronze-redempti0n-dark-habano',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','My Way – Dark Habano','Corona','Parejo','Corona','Ecuador','Habano Oscuro','Nicaragua',ARRAY['Nicaragua']::text[],3,'United States','El Titan de Bronze',5.5,48,ARRAY['Earth','Espresso','Black Pepper','Cocoa','Oak']::text[],'En mellomsterk amerikansk sigar med Habano Oscuro-dekkblad, med toner av jord, espresso, svart pepper og kakao.',true,'retailer','https://eltitancigars.com/products/titan-de-bronze-redempti0n-dark-habano',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','My Way – Dark Habano','Robusto','Parejo','Robusto','Ecuador','Habano Oscuro','Nicaragua',ARRAY['Nicaragua']::text[],3,'United States','El Titan de Bronze',5,50,ARRAY['Earth','Espresso','Black Pepper','Cocoa','Oak']::text[],'En mellomsterk amerikansk sigar med Habano Oscuro-dekkblad, med toner av jord, espresso, svart pepper og kakao.',true,'retailer','https://eltitancigars.com/products/titan-de-bronze-redempti0n-dark-habano',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','My Way – Dark Habano','Churchill','Parejo','Churchill','Ecuador','Habano Oscuro','Nicaragua',ARRAY['Nicaragua']::text[],3,'United States','El Titan de Bronze',7,50,ARRAY['Earth','Espresso','Black Pepper','Cocoa','Oak']::text[],'En mellomsterk amerikansk sigar med Habano Oscuro-dekkblad, med toner av jord, espresso, svart pepper og kakao.',true,'retailer','https://eltitancigars.com/products/titan-de-bronze-redempti0n-dark-habano',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','My Way – Dark Habano','Toro','Parejo','Toro','Ecuador','Habano Oscuro','Nicaragua',ARRAY['Nicaragua']::text[],3,'United States','El Titan de Bronze',6,52,ARRAY['Earth','Espresso','Black Pepper','Cocoa','Oak']::text[],'En mellomsterk amerikansk sigar med Habano Oscuro-dekkblad, med toner av jord, espresso, svart pepper og kakao.',true,'retailer','https://eltitancigars.com/products/titan-de-bronze-redempti0n-dark-habano',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Nicaragua','Corona','Parejo','Corona',NULL,'Broadleaf','Mexico',ARRAY['Nicaragua']::text[],4,'Nicaragua','El Titan de Bronze',6.3,48,ARRAY['Dark Chocolate','Espresso','Earth','Spice']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Broadleaf-dekkblad, med toner av mørk sjokolade, espresso, jord og krydder.',true,'retailer','https://eltitancigars.com/products/el-titan-de-bronze-nicaragua-cigar',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Nicaragua','Toro','Parejo','Toro',NULL,'Broadleaf','Mexico',ARRAY['Nicaragua']::text[],4,'Nicaragua','El Titan de Bronze',6,52,ARRAY['Dark Chocolate','Espresso','Earth','Spice']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Broadleaf-dekkblad, med toner av mørk sjokolade, espresso, jord og krydder.',true,'retailer','https://eltitancigars.com/products/el-titan-de-bronze-nicaragua-cigar',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Nicaragua','Robusto','Parejo','Robusto',NULL,'Broadleaf','Mexico',ARRAY['Nicaragua']::text[],4,'Nicaragua','El Titan de Bronze',5,54,ARRAY['Dark Chocolate','Espresso','Earth','Spice']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Broadleaf-dekkblad, med toner av mørk sjokolade, espresso, jord og krydder.',true,'retailer','https://eltitancigars.com/products/el-titan-de-bronze-nicaragua-cigar',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Nicaragua','Gigante','Parejo','Gigante',NULL,'Broadleaf','Mexico',ARRAY['Nicaragua']::text[],4,'Nicaragua','El Titan de Bronze',6,60,ARRAY['Dark Chocolate','Espresso','Earth','Spice']::text[],'En mellomsterk til fyldig nicaraguansk sigar med Broadleaf-dekkblad, med toner av mørk sjokolade, espresso, jord og krydder.',true,'retailer','https://eltitancigars.com/products/el-titan-de-bronze-nicaragua-cigar',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Redemption','Corona','Parejo','Corona','Ecuador','Sun Grown Habano Claro','Nicaragua',ARRAY['Nicaragua']::text[],3,'United States','El Titan de Bronze',5.6,46,ARRAY['Cedar','Toast','Spice','Earth','Pepper']::text[],'En mellomsterk amerikansk sigar med Sun Grown Habano Claro-dekkblad, med toner av seder, ristet brød, krydder og jord.',true,'retailer','https://eltitancigars.com/products/el-titan-de-bronze-redemption-cigar',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Redemption','Robusto','Parejo','Robusto','Ecuador','Sun Grown Habano Claro','Nicaragua',ARRAY['Nicaragua']::text[],3,'United States','El Titan de Bronze',5,50,ARRAY['Cedar','Toast','Spice','Earth','Pepper']::text[],'En mellomsterk amerikansk sigar med Sun Grown Habano Claro-dekkblad, med toner av seder, ristet brød, krydder og jord.',true,'retailer','https://eltitancigars.com/products/el-titan-de-bronze-redemption-cigar',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Redemption','Toro','Parejo','Toro','Ecuador','Sun Grown Habano Claro','Nicaragua',ARRAY['Nicaragua']::text[],3,'United States','El Titan de Bronze',6,52,ARRAY['Cedar','Toast','Spice','Earth','Pepper']::text[],'En mellomsterk amerikansk sigar med Sun Grown Habano Claro-dekkblad, med toner av seder, ristet brød, krydder og jord.',true,'retailer','https://eltitancigars.com/products/el-titan-de-bronze-redemption-cigar',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Redemption Maduro','Corona','Parejo','Corona','Mexico','San Andrés Maduro','Nicaragua',ARRAY['Dominican Republic','Nicaragua']::text[],4,'United States','El Titan de Bronze',5.5,48,ARRAY['Cocoa','Espresso','Black Pepper','Leather','Earth']::text[],'En mellomsterk til fyldig amerikansk sigar med San Andrés Maduro-dekkblad, med toner av kakao, espresso, svart pepper og lær.',true,'retailer','https://eltitancigars.com/products/titan-redemption-maduro',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Redemption Maduro','Robusto','Parejo','Robusto','Mexico','San Andrés Maduro','Nicaragua',ARRAY['Dominican Republic','Nicaragua']::text[],4,'United States','El Titan de Bronze',5,50,ARRAY['Cocoa','Espresso','Black Pepper','Leather','Earth']::text[],'En mellomsterk til fyldig amerikansk sigar med San Andrés Maduro-dekkblad, med toner av kakao, espresso, svart pepper og lær.',true,'retailer','https://eltitancigars.com/products/titan-redemption-maduro',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Redemption Maduro','Churchill','Parejo','Churchill','Mexico','San Andrés Maduro','Nicaragua',ARRAY['Dominican Republic','Nicaragua']::text[],4,'United States','El Titan de Bronze',7,50,ARRAY['Cocoa','Espresso','Black Pepper','Leather','Earth']::text[],'En mellomsterk til fyldig amerikansk sigar med San Andrés Maduro-dekkblad, med toner av kakao, espresso, svart pepper og lær.',true,'retailer','https://eltitancigars.com/products/titan-redemption-maduro',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Redemption Maduro','Toro','Parejo','Toro','Mexico','San Andrés Maduro','Nicaragua',ARRAY['Dominican Republic','Nicaragua']::text[],4,'United States','El Titan de Bronze',6,52,ARRAY['Cocoa','Espresso','Black Pepper','Leather','Earth']::text[],'En mellomsterk til fyldig amerikansk sigar med San Andrés Maduro-dekkblad, med toner av kakao, espresso, svart pepper og lær.',true,'retailer','https://eltitancigars.com/products/titan-redemption-maduro',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Redemption Maduro','Belicoso','Figurado','Belicoso','Mexico','San Andrés Maduro','Nicaragua',ARRAY['Dominican Republic','Nicaragua']::text[],4,'United States','El Titan de Bronze',4.5,54,ARRAY['Cocoa','Espresso','Black Pepper','Leather','Earth']::text[],'En mellomsterk til fyldig amerikansk sigar med San Andrés Maduro-dekkblad, med toner av kakao, espresso, svart pepper og lær.',true,'retailer','https://eltitancigars.com/products/titan-redemption-maduro',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Redemption Maduro','Torpedo','Figurado','Torpedo','Mexico','San Andrés Maduro','Nicaragua',ARRAY['Dominican Republic','Nicaragua']::text[],4,'United States','El Titan de Bronze',6,54,ARRAY['Cocoa','Espresso','Black Pepper','Leather','Earth']::text[],'En mellomsterk til fyldig amerikansk sigar med San Andrés Maduro-dekkblad, med toner av kakao, espresso, svart pepper og lær.',true,'retailer','https://eltitancigars.com/products/titan-redemption-maduro',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Redemption Sun Grown','Lancero','Parejo','Lancero','Ecuador','Habano Sun Grown','Nicaragua',ARRAY['Dominican Republic','Nicaragua']::text[],3,'United States','El Titan de Bronze',6.8,38,ARRAY['Cedar','Toasted Nuts','Baking Spice','White Pepper','Sweetness']::text[],'En mellomsterk amerikansk sigar med Habano Sun Grown-dekkblad, med toner av seder, ristede nøtter, bakekrydder og hvit pepper.',true,'retailer','https://eltitancigars.com/products/titan-redemption-sun-grown',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Redemption Sun Grown','Corona','Parejo','Corona','Ecuador','Habano Sun Grown','Nicaragua',ARRAY['Dominican Republic','Nicaragua']::text[],3,'United States','El Titan de Bronze',5.5,48,ARRAY['Cedar','Toasted Nuts','Baking Spice','White Pepper','Sweetness']::text[],'En mellomsterk amerikansk sigar med Habano Sun Grown-dekkblad, med toner av seder, ristede nøtter, bakekrydder og hvit pepper.',true,'retailer','https://eltitancigars.com/products/titan-redemption-sun-grown',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Redemption Sun Grown','Robusto','Parejo','Robusto','Ecuador','Habano Sun Grown','Nicaragua',ARRAY['Dominican Republic','Nicaragua']::text[],3,'United States','El Titan de Bronze',5,50,ARRAY['Cedar','Toasted Nuts','Baking Spice','White Pepper','Sweetness']::text[],'En mellomsterk amerikansk sigar med Habano Sun Grown-dekkblad, med toner av seder, ristede nøtter, bakekrydder og hvit pepper.',true,'retailer','https://eltitancigars.com/products/titan-redemption-sun-grown',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Redemption Sun Grown','Churchill','Parejo','Churchill','Ecuador','Habano Sun Grown','Nicaragua',ARRAY['Dominican Republic','Nicaragua']::text[],3,'United States','El Titan de Bronze',7,50,ARRAY['Cedar','Toasted Nuts','Baking Spice','White Pepper','Sweetness']::text[],'En mellomsterk amerikansk sigar med Habano Sun Grown-dekkblad, med toner av seder, ristede nøtter, bakekrydder og hvit pepper.',true,'retailer','https://eltitancigars.com/products/titan-redemption-sun-grown',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Redemption Sun Grown','Toro','Parejo','Toro','Ecuador','Habano Sun Grown','Nicaragua',ARRAY['Dominican Republic','Nicaragua']::text[],3,'United States','El Titan de Bronze',6,52,ARRAY['Cedar','Toasted Nuts','Baking Spice','White Pepper','Sweetness']::text[],'En mellomsterk amerikansk sigar med Habano Sun Grown-dekkblad, med toner av seder, ristede nøtter, bakekrydder og hvit pepper.',true,'retailer','https://eltitancigars.com/products/titan-redemption-sun-grown',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Redemption Sun Grown','Belicoso','Figurado','Belicoso','Ecuador','Habano Sun Grown','Nicaragua',ARRAY['Dominican Republic','Nicaragua']::text[],3,'United States','El Titan de Bronze',4.5,54,ARRAY['Cedar','Toasted Nuts','Baking Spice','White Pepper','Sweetness']::text[],'En mellomsterk amerikansk sigar med Habano Sun Grown-dekkblad, med toner av seder, ristede nøtter, bakekrydder og hvit pepper.',true,'retailer','https://eltitancigars.com/products/titan-redemption-sun-grown',now(),ARRAY['Titan de Bronze']::text[]),
  ('Titan de Bronze','Redemption Sun Grown','Torpedo','Figurado','Torpedo','Ecuador','Habano Sun Grown','Nicaragua',ARRAY['Dominican Republic','Nicaragua']::text[],3,'United States','El Titan de Bronze',6,54,ARRAY['Cedar','Toasted Nuts','Baking Spice','White Pepper','Sweetness']::text[],'En mellomsterk amerikansk sigar med Habano Sun Grown-dekkblad, med toner av seder, ristede nøtter, bakekrydder og hvit pepper.',true,'retailer','https://eltitancigars.com/products/titan-redemption-sun-grown',now(),ARRAY['Titan de Bronze']::text[]);
