-- 151: Macanudo — fyll manglende opphav, beskrivelser (og smak for Ecuadorian Shade).
-- Opphav er produksjonsland (fabrikk). Inspirado-linjen er delt: Orange=Honduras, Red/Sumatra/Ecuadorian Shade=Nicaragua, resten Den dominikanske republikk.
-- Beskrivelse settes bare der den mangler (description IS NULL).
UPDATE public.cigars SET country_origin = COALESCE(country_origin, 'Dominican Republic'), description = COALESCE(description, 'En mellomsterk til fyldig dominikansk sigar med Honduran Olancho San Agustin-dekkblad, med toner av lær, kakao, kaffe og krydder.') WHERE brand='Macanudo' AND series='1968';
UPDATE public.cigars SET country_origin = COALESCE(country_origin, 'Dominican Republic'), description = COALESCE(description, 'En mild dominikansk sigar med Connecticut Shade-dekkblad, med toner av fløte, seder, nøtter og sødme.') WHERE brand='Macanudo' AND series='Café';
UPDATE public.cigars SET country_origin = COALESCE(country_origin, 'Dominican Republic'), description = COALESCE(description, 'En mellomsterk dominikansk sigar med Ecuadorian Habano-dekkblad, med toner av nøtter, kakao, krydder og jord.') WHERE brand='Macanudo' AND series='Cru Royale';
UPDATE public.cigars SET country_origin = COALESCE(country_origin, 'Nicaragua'), flavor_notes = CASE WHEN flavor_notes IS NULL OR cardinality(flavor_notes)=0 THEN ARRAY['Cream','Toasted Nuts','Sweetness','White Pepper','Butter']::text[] ELSE flavor_notes END, description = COALESCE(description, 'En mild til mellomsterk nicaraguansk sigar med Ecuadorian Shade-dekkblad, med toner av fløte, ristede nøtter, sødme og hvit pepper.') WHERE brand='Macanudo' AND series='Ecuadorian Shade';
UPDATE public.cigars SET country_origin = COALESCE(country_origin, 'Dominican Republic'), description = COALESCE(description, 'En mellomsterk dominikansk sigar med Ecuadorian Connecticut Shade-dekkblad, med toner av eik, kanel, vanilje og fløte.') WHERE brand='Macanudo' AND series='Estate Reserve No. 1';
UPDATE public.cigars SET country_origin = COALESCE(country_origin, 'Dominican Republic'), description = COALESCE(description, 'En mellomsterk dominikansk sigar med Ecuadorian Connecticut Shade-dekkblad, med toner av vanilje, fløte, mandler og mørk frukt.') WHERE brand='Macanudo' AND series='Estate Reserve No. 2';
UPDATE public.cigars SET country_origin = COALESCE(country_origin, 'Dominican Republic'), description = COALESCE(description, 'En mellomsterk dominikansk sigar med Ecuadorian Connecticut Shade-dekkblad, med toner av vanilje, kirsebær, fløte og tre.') WHERE brand='Macanudo' AND series='Estate Reserve No. 3';
UPDATE public.cigars SET country_origin = COALESCE(country_origin, 'Dominican Republic'), description = COALESCE(description, 'En mild dominikansk sigar med Connecticut Golden Shade-dekkblad, med toner av fløte, sødme og mandler.') WHERE brand='Macanudo' AND series='Gold Label';
UPDATE public.cigars SET country_origin = COALESCE(country_origin, 'Dominican Republic'), description = COALESCE(description, 'En mellomsterk dominikansk sigar med Connecticut Broadleaf-dekkblad, med toner av mokka, ristede nøtter, sjokolade og krydder.') WHERE brand='Macanudo' AND series='Inspirado Black';
UPDATE public.cigars SET country_origin = COALESCE(country_origin, 'Dominican Republic'), description = COALESCE(description, 'En mellomsterk dominikansk sigar med Connecticut Shade-dekkblad, med toner av høy, seder, fløte og lær.') WHERE brand='Macanudo' AND series='Inspirado Brazilian Shade';
UPDATE public.cigars SET country_origin = COALESCE(country_origin, 'Dominican Republic'), description = COALESCE(description, 'En mellomsterk dominikansk sigar med Brazilian Arapiraca-dekkblad, med toner av kaffe, hvit pepper, sitrus og jord.') WHERE brand='Macanudo' AND series='Inspirado Green';
UPDATE public.cigars SET country_origin = COALESCE(country_origin, 'Dominican Republic'), description = COALESCE(description, 'En mellomsterk dominikansk sigar med Jamao Dominican-dekkblad, med toner av tre, seder, jord og svart pepper.') WHERE brand='Macanudo' AND series='Inspirado Jamao';
UPDATE public.cigars SET country_origin = COALESCE(country_origin, 'Honduras'), description = COALESCE(description, 'En mellomsterk honduransk sigar med Honduran-dekkblad, med toner av tre, krydder, seder og jord.') WHERE brand='Macanudo' AND series='Inspirado Orange';
UPDATE public.cigars SET country_origin = COALESCE(country_origin, 'Nicaragua'), description = COALESCE(description, 'En mellomsterk til fyldig nicaraguansk sigar med Ecuadorian Habano-dekkblad, med toner av mørk frukt, svart pepper, lær og seder.') WHERE brand='Macanudo' AND series='Inspirado Red';
UPDATE public.cigars SET country_origin = COALESCE(country_origin, 'Dominican Republic'), description = COALESCE(description, 'En mellomsterk dominikansk sigar med Mexican San Andrés-dekkblad, med toner av sjokolade, kaffe, pepper og jord.') WHERE brand='Macanudo' AND series='Inspirado Tercio Aged';
UPDATE public.cigars SET country_origin = COALESCE(country_origin, 'Dominican Republic'), description = COALESCE(description, 'En mild til mellomsterk dominikansk sigar med Ecuadorian Connecticut-dekkblad, med toner av fløte, krydder og seder.') WHERE brand='Macanudo' AND series='Inspirado White';
UPDATE public.cigars SET country_origin = COALESCE(country_origin, 'Dominican Republic'), description = COALESCE(description, 'En mild til mellomsterk dominikansk sigar med Connecticut Broadleaf-dekkblad, med toner av kanel, sjokolade, kaffe og seder.') WHERE brand='Macanudo' AND series='Maduro';
UPDATE public.cigars SET country_origin = COALESCE(country_origin, 'Nicaragua'), description = COALESCE(description, 'En mellomsterk nicaraguansk sigar med Ecuadorian Sumatra-dekkblad, med toner av eik, kaffe, kakao og tørket frukt.') WHERE brand='Macanudo' AND series='Sumatra';
UPDATE public.cigars SET country_origin = COALESCE(country_origin, 'Dominican Republic'), description = COALESCE(description, 'En mild til mellomsterk dominikansk sigar med Connecticut Shade Vintage 2010-dekkblad, med toner av seder, fløte og vanilje.') WHERE brand='Macanudo' AND series='Vintage 2010';
UPDATE public.cigars SET country_origin = COALESCE(country_origin, 'Dominican Republic'), description = COALESCE(description, 'En mellomsterk dominikansk sigar med Connecticut Broadleaf Maduro-dekkblad, med toner av kaffe, mørk frukt, krydder og jord.') WHERE brand='Macanudo' AND series='Vintage Maduro 2013';
