-- 155: Fyll smak/styrke/dekkblad + komponerte norske beskrivelser for restmerker.
-- Idempotent (CASE/COALESCE). Beskrivelse komponeres kun der description IS NULL.
UPDATE public.cigars SET description = COALESCE(description, 'En mellomsterk honduransk sigar med Habano 2000-dekkblad, med toner av fløte, jord, urter og krydder.') WHERE brand='Camacho' AND series='Ecuador';
UPDATE public.cigars SET description = COALESCE(description, 'En mellomsterk til fyldig honduransk sigar med Habano 2000-dekkblad, med toner av fløte, pepper og krydder.') WHERE brand='Camacho' AND series='Ecuador BXP';
UPDATE public.cigars SET description = COALESCE(description, 'En mellomsterk til fyldig nicaraguansk sigar med San Andres Maduro-dekkblad, med toner av svart pepper, kakao, jord og nøtter.') WHERE brand='Augusto Cigars' AND series='El Rey de la Caída';
UPDATE public.cigars SET flavor_notes = CASE WHEN flavor_notes IS NULL OR cardinality(flavor_notes)=0 THEN ARRAY['Cream','Cedar','Almonds','Hay']::text[] ELSE flavor_notes END, strength = COALESCE(strength, 2), description = COALESCE(description, 'En mild til mellomsterk dominikansk sigar med Connecticut Shade-dekkblad, med toner av fløte, seder, mandler og høy.') WHERE brand='Cuesta-Rey' AND series='Cabinet Selection' AND wrapper_leaf='Connecticut Shade';
UPDATE public.cigars SET flavor_notes = CASE WHEN flavor_notes IS NULL OR cardinality(flavor_notes)=0 THEN ARRAY['Nuts','Pepper','Cedar','Coffee','Sweetness']::text[] ELSE flavor_notes END, strength = COALESCE(strength, 3), description = COALESCE(description, 'En mellomsterk dominikansk sigar med African Cameroon-dekkblad, med toner av nøtter, pepper, seder og kaffe.') WHERE brand='Cuesta-Rey' AND series='Cabinet Selection' AND wrapper_leaf='African Cameroon';
UPDATE public.cigars SET flavor_notes = CASE WHEN flavor_notes IS NULL OR cardinality(flavor_notes)=0 THEN ARRAY['Cream','Cedar','Almonds','Hay']::text[] ELSE flavor_notes END, strength = COALESCE(strength, 2), description = COALESCE(description, 'En mild til mellomsterk dominikansk sigar med Connecticut Shade-dekkblad, med toner av fløte, seder, mandler og høy.') WHERE brand='Cuesta-Rey' AND series='Centenario';
UPDATE public.cigars SET flavor_notes = CASE WHEN flavor_notes IS NULL OR cardinality(flavor_notes)=0 THEN ARRAY['Leather','Cocoa','Coffee','Wood','Baking Spice']::text[] ELSE flavor_notes END, strength = COALESCE(strength, 3), description = COALESCE(description, 'En mellomsterk dominikansk sigar med Sungrown-dekkblad, med toner av lær, kakao, kaffe og tre.') WHERE brand='Cuesta-Rey' AND series='Centro Fino';
UPDATE public.cigars SET flavor_notes = CASE WHEN flavor_notes IS NULL OR cardinality(flavor_notes)=0 THEN ARRAY['Cedar','Pepper','Coffee','Cream','Baking Spice']::text[] ELSE flavor_notes END, strength = COALESCE(strength, 3), description = COALESCE(description, 'En mellomsterk amerikansk sigar med Havana Rosado-dekkblad, med toner av seder, pepper, kaffe og fløte.') WHERE brand='Angel Cuesta' AND series='Rosado';
UPDATE public.cigars SET flavor_notes = CASE WHEN flavor_notes IS NULL OR cardinality(flavor_notes)=0 THEN ARRAY['Cream','Cedar','Nuts','Hay','Sweetness']::text[] ELSE flavor_notes END, strength = COALESCE(strength, 2), description = COALESCE(description, 'En mild til mellomsterk amerikansk sigar med Shade-dekkblad, med toner av fløte, seder, nøtter og høy.') WHERE brand='Angel Cuesta' AND series='Shade';
UPDATE public.cigars SET flavor_notes = CASE WHEN flavor_notes IS NULL OR cardinality(flavor_notes)=0 THEN ARRAY['Cedar','Coffee','Nuts','Pepper','Sweetness']::text[] ELSE flavor_notes END, strength = COALESCE(strength, 3), description = COALESCE(description, 'En mellomsterk nicaraguansk sigar med Havana-dekkblad, med toner av seder, kaffe, nøtter og pepper.') WHERE brand='Brick House' AND series='Classic';
UPDATE public.cigars SET flavor_notes = CASE WHEN flavor_notes IS NULL OR cardinality(flavor_notes)=0 THEN ARRAY['Cedar','Coffee','Leather','Pepper']::text[] ELSE flavor_notes END, strength = COALESCE(strength, 3), wrapper_leaf = COALESCE(wrapper_leaf, 'Ecuador'), wrapper_country = COALESCE(wrapper_country, 'Ecuador'), description = COALESCE(description, 'En mellomsterk honduransk sigar med Ecuador-dekkblad, med toner av seder, kaffe, lær og pepper.') WHERE brand='Cuba Aliados' AND series='Original Blend';
UPDATE public.cigars SET flavor_notes = CASE WHEN flavor_notes IS NULL OR cardinality(flavor_notes)=0 THEN ARRAY['Cream','Cedar','Nuts','Coffee','Sweetness']::text[] ELSE flavor_notes END, strength = COALESCE(strength, 2), description = COALESCE(description, 'En mild til mellomsterk dominikansk sigar med Connecticut Shade-dekkblad, med toner av fløte, seder, nøtter og kaffe.') WHERE brand='Diamond Crown' AND series='Classic';
UPDATE public.cigars SET flavor_notes = CASE WHEN flavor_notes IS NULL OR cardinality(flavor_notes)=0 THEN ARRAY['Cream','Cedar','Almonds','Hay','Sweetness']::text[] ELSE flavor_notes END, strength = COALESCE(strength, 2), description = COALESCE(description, 'En mild til mellomsterk nicaraguansk sigar med Connecticut Shade-dekkblad, med toner av fløte, seder, mandler og høy.') WHERE brand='Perla del Mar' AND series='Shade';
UPDATE public.cigars SET flavor_notes = CASE WHEN flavor_notes IS NULL OR cardinality(flavor_notes)=0 THEN ARRAY['Cedar','Pepper','Leather','Coffee','Earth']::text[] ELSE flavor_notes END, strength = COALESCE(strength, 4), description = COALESCE(description, 'En mellomsterk til fyldig nicaraguansk sigar med Havana-dekkblad, med toner av seder, pepper, lær og kaffe.') WHERE brand='El Baton' AND series IS NULL;
UPDATE public.cigars SET flavor_notes = CASE WHEN flavor_notes IS NULL OR cardinality(flavor_notes)=0 THEN ARRAY['Earth','Black Pepper','Cocoa','Leather','Espresso']::text[] ELSE flavor_notes END WHERE brand='Black Works Studio' AND series='NBK';
UPDATE public.cigars SET flavor_notes = CASE WHEN flavor_notes IS NULL OR cardinality(flavor_notes)=0 THEN ARRAY['Cedar','Cream','Coffee','Nuts','Sweetness']::text[] ELSE flavor_notes END WHERE brand='Warfighter Tobacco' AND series='10th Anniversary';
UPDATE public.cigars SET flavor_notes = CASE WHEN flavor_notes IS NULL OR cardinality(flavor_notes)=0 THEN ARRAY['Earth','Dark Chocolate','Pepper','Coffee','Leather']::text[] ELSE flavor_notes END WHERE brand='Warfighter Tobacco' AND series='San Andres';
UPDATE public.cigars SET flavor_notes = CASE WHEN flavor_notes IS NULL OR cardinality(flavor_notes)=0 THEN ARRAY['Cedar','Floral','Honey','Cream','Baking Spice']::text[] ELSE flavor_notes END WHERE brand='Romeo y Julieta' AND series='Churchills';
